namespace DexiWin;

interface

{$HIDE H7}

uses
  System.Drawing,
  System.Collections,
  System.Windows.Forms,
  System.ComponentModel;

type
  CtrlFormCharts = public partial class
  {$REGION Windows Control Designer generated fields}
  private
    ItemPopResetAltOrder: System.Windows.Forms.ToolStripMenuItem;
    AlternativesMenu: System.Windows.Forms.ContextMenuStrip;
    ItemPopMoveUp: System.Windows.Forms.ToolStripMenuItem;
    ItemPopMoveDown: System.Windows.Forms.ToolStripMenuItem;
    
    ItemMenuEditAddReport: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator4: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator3: System.Windows.Forms.ToolStripSeparator;
    MenuSelectAllAttributes: System.Windows.Forms.ToolStripMenuItem;
    MenuSelectBasicAttributes: System.Windows.Forms.ToolStripMenuItem;
    MenuSelectRoots: System.Windows.Forms.ToolStripMenuItem;
    MenuSelectLevel1: System.Windows.Forms.ToolStripMenuItem;
    MenuSelectLevel2: System.Windows.Forms.ToolStripMenuItem;
    MenuSelectLevel3: System.Windows.Forms.ToolStripMenuItem;
    MenuAttSelect: System.Windows.Forms.ToolStripMenuItem;
    MenuSelectAtt: System.Windows.Forms.MenuStrip;
    EditTransparency: System.Windows.Forms.NumericUpDown;
    EditLinearPoint: System.Windows.Forms.NumericUpDown;
    EditRadarPoint: System.Windows.Forms.NumericUpDown;
    EditScatterPoint: System.Windows.Forms.NumericUpDown;
    GrpColors: System.Windows.Forms.GroupBox;
    BtnAreaColor: System.Windows.Forms.Button;
    LblLinear: System.Windows.Forms.Label;
    LblRadar: System.Windows.Forms.Label;
    LblScatter: System.Windows.Forms.Label;
    LblPointSizes: System.Windows.Forms.Label;
    LblTransparency: System.Windows.Forms.Label;
    EditBarWidth: System.Windows.Forms.NumericUpDown;
    LblBarWidth: System.Windows.Forms.Label;
    EditLineWidth: System.Windows.Forms.NumericUpDown;
    LblLineWidth: System.Windows.Forms.Label;
    EditTextGaps: System.Windows.Forms.NumericUpDown;
    LblTextGaps: System.Windows.Forms.Label;
    GrpSizes: System.Windows.Forms.GroupBox;
    EditChartType: System.Windows.Forms.ComboBox;
    EditGridY: System.Windows.Forms.NumericUpDown;
    LblTimes: System.Windows.Forms.Label;
    EditGridX: System.Windows.Forms.NumericUpDown;
    LblGrid: System.Windows.Forms.Label;
    GrpChartType: System.Windows.Forms.GroupBox;
    GrpFonts: System.Windows.Forms.GroupBox;
    BtnValFont: System.Windows.Forms.Button;
    BtnAttFont: System.Windows.Forms.Button;
    BtnAltFont: System.Windows.Forms.Button;
    BtnUnselectAllAtt: System.Windows.Forms.Button;
    BtnUnselectAllAlt: System.Windows.Forms.Button;
    BtnSelectAllAlt: System.Windows.Forms.Button;
    ChartSplitter: System.Windows.Forms.Splitter;
    AltList: BrightIdeasSoftware.ObjectListView;
    ColAlternative: BrightIdeasSoftware.OLVColumn;
    AttList: BrightIdeasSoftware.TreeListView;
    ColAttribute: BrightIdeasSoftware.OLVColumn;
    PanelAltCtrl: System.Windows.Forms.TabPage;
    panel1: System.Windows.Forms.Panel;
    PanelAttCtrl: System.Windows.Forms.Panel;
    LblMessage: System.Windows.Forms.Label;
    TabChart: System.Windows.Forms.TabPage;
    TabAttributes: System.Windows.Forms.TabPage;
    ChartPicture: System.Windows.Forms.PictureBox;
    ChartMenu: System.Windows.Forms.ContextMenuStrip;
    ChartPanel: DexiWin.ZoomablePanel;
    SaveChartDialog: System.Windows.Forms.SaveFileDialog;
    ItemPopCopyMetafile: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuCopyMetafile: System.Windows.Forms.ToolStripMenuItem;
    ItemPopCopyBitmap: System.Windows.Forms.ToolStripMenuItem;
    DlgFont: System.Windows.Forms.FontDialog;
    DlgColor: System.Windows.Forms.ColorDialog;
    EditBorderRight: System.Windows.Forms.NumericUpDown;
    EditBorderBottom: System.Windows.Forms.NumericUpDown;
    EditBorderTop: System.Windows.Forms.NumericUpDown;
    EditBorderLeft: System.Windows.Forms.NumericUpDown;
    PicBorders: System.Windows.Forms.PictureBox;
    TabFormat: System.Windows.Forms.TabControl;
    BtnBackgroundColor: System.Windows.Forms.Button;
    GrpBorders: System.Windows.Forms.GroupBox;
    CtrlPanel: System.Windows.Forms.Panel;
    FormTool: System.Windows.Forms.ToolStrip;
    _separator: System.Windows.Forms.ToolStripSeparator;
    ItemToolCopy: System.Windows.Forms.ToolStripButton;
    ItemToolSave: System.Windows.Forms.ToolStripButton;
    FormMenu: System.Windows.Forms.MenuStrip;
    ItemMenuFile: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuSave: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator5: System.Windows.Forms.ToolStripSeparator;
    ItemMenuEdit: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuCopyBitmap: System.Windows.Forms.ToolStripMenuItem;
    components: System.ComponentModel.Container := nil;
    method InitializeComponent;
  {$ENDREGION}
  end;

implementation

{$REGION Windows Control Designer generated code}
method CtrlFormCharts.InitializeComponent;
begin
  self.components := new System.ComponentModel.Container();
  var resources: System.ComponentModel.ComponentResourceManager := new System.ComponentModel.ComponentResourceManager(typeOf(CtrlFormCharts));
  self.FormTool := new System.Windows.Forms.ToolStrip();
  self._separator := new System.Windows.Forms.ToolStripSeparator();
  self.ItemToolCopy := new System.Windows.Forms.ToolStripButton();
  self.ItemToolSave := new System.Windows.Forms.ToolStripButton();
  self.FormMenu := new System.Windows.Forms.MenuStrip();
  self.ItemMenuFile := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator5 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuSave := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuEdit := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator3 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuEditAddReport := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator4 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuCopyMetafile := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuCopyBitmap := new System.Windows.Forms.ToolStripMenuItem();
  self.CtrlPanel := new System.Windows.Forms.Panel();
  self.TabFormat := new System.Windows.Forms.TabControl();
  self.TabAttributes := new System.Windows.Forms.TabPage();
  self.AttList := new BrightIdeasSoftware.TreeListView();
  self.ColAttribute := (new BrightIdeasSoftware.OLVColumn() as BrightIdeasSoftware.OLVColumn);
  self.PanelAttCtrl := new System.Windows.Forms.Panel();
  self.BtnUnselectAllAtt := new System.Windows.Forms.Button();
  self.MenuSelectAtt := new System.Windows.Forms.MenuStrip();
  self.MenuAttSelect := new System.Windows.Forms.ToolStripMenuItem();
  self.MenuSelectAllAttributes := new System.Windows.Forms.ToolStripMenuItem();
  self.MenuSelectBasicAttributes := new System.Windows.Forms.ToolStripMenuItem();
  self.MenuSelectRoots := new System.Windows.Forms.ToolStripMenuItem();
  self.MenuSelectLevel1 := new System.Windows.Forms.ToolStripMenuItem();
  self.MenuSelectLevel2 := new System.Windows.Forms.ToolStripMenuItem();
  self.MenuSelectLevel3 := new System.Windows.Forms.ToolStripMenuItem();
  self.PanelAltCtrl := new System.Windows.Forms.TabPage();
  self.AltList := new BrightIdeasSoftware.ObjectListView();
  self.ColAlternative := (new BrightIdeasSoftware.OLVColumn() as BrightIdeasSoftware.OLVColumn);
  self.AlternativesMenu := new System.Windows.Forms.ContextMenuStrip(self.components);
  self.ItemPopMoveUp := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopMoveDown := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopResetAltOrder := new System.Windows.Forms.ToolStripMenuItem();
  self.panel1 := new System.Windows.Forms.Panel();
  self.BtnUnselectAllAlt := new System.Windows.Forms.Button();
  self.BtnSelectAllAlt := new System.Windows.Forms.Button();
  self.TabChart := new System.Windows.Forms.TabPage();
  self.GrpFonts := new System.Windows.Forms.GroupBox();
  self.BtnValFont := new System.Windows.Forms.Button();
  self.BtnAttFont := new System.Windows.Forms.Button();
  self.BtnAltFont := new System.Windows.Forms.Button();
  self.GrpColors := new System.Windows.Forms.GroupBox();
  self.BtnAreaColor := new System.Windows.Forms.Button();
  self.EditTransparency := new System.Windows.Forms.NumericUpDown();
  self.LblTransparency := new System.Windows.Forms.Label();
  self.BtnBackgroundColor := new System.Windows.Forms.Button();
  self.GrpSizes := new System.Windows.Forms.GroupBox();
  self.LblLinear := new System.Windows.Forms.Label();
  self.EditLinearPoint := new System.Windows.Forms.NumericUpDown();
  self.LblRadar := new System.Windows.Forms.Label();
  self.EditRadarPoint := new System.Windows.Forms.NumericUpDown();
  self.LblScatter := new System.Windows.Forms.Label();
  self.EditScatterPoint := new System.Windows.Forms.NumericUpDown();
  self.LblPointSizes := new System.Windows.Forms.Label();
  self.EditBarWidth := new System.Windows.Forms.NumericUpDown();
  self.LblBarWidth := new System.Windows.Forms.Label();
  self.EditLineWidth := new System.Windows.Forms.NumericUpDown();
  self.LblLineWidth := new System.Windows.Forms.Label();
  self.EditTextGaps := new System.Windows.Forms.NumericUpDown();
  self.LblTextGaps := new System.Windows.Forms.Label();
  self.GrpBorders := new System.Windows.Forms.GroupBox();
  self.EditBorderRight := new System.Windows.Forms.NumericUpDown();
  self.EditBorderBottom := new System.Windows.Forms.NumericUpDown();
  self.EditBorderTop := new System.Windows.Forms.NumericUpDown();
  self.EditBorderLeft := new System.Windows.Forms.NumericUpDown();
  self.PicBorders := new System.Windows.Forms.PictureBox();
  self.GrpChartType := new System.Windows.Forms.GroupBox();
  self.EditGridY := new System.Windows.Forms.NumericUpDown();
  self.LblTimes := new System.Windows.Forms.Label();
  self.EditGridX := new System.Windows.Forms.NumericUpDown();
  self.LblGrid := new System.Windows.Forms.Label();
  self.EditChartType := new System.Windows.Forms.ComboBox();
  self.ChartPicture := new System.Windows.Forms.PictureBox();
  self.DlgColor := new System.Windows.Forms.ColorDialog();
  self.DlgFont := new System.Windows.Forms.FontDialog();
  self.ChartMenu := new System.Windows.Forms.ContextMenuStrip(self.components);
  self.ItemPopCopyMetafile := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopCopyBitmap := new System.Windows.Forms.ToolStripMenuItem();
  self.ChartPanel := new DexiWin.ZoomablePanel();
  self.LblMessage := new System.Windows.Forms.Label();
  self.SaveChartDialog := new System.Windows.Forms.SaveFileDialog();
  self.ChartSplitter := new System.Windows.Forms.Splitter();
  self.FormTool.SuspendLayout();
  self.FormMenu.SuspendLayout();
  self.CtrlPanel.SuspendLayout();
  self.TabFormat.SuspendLayout();
  self.TabAttributes.SuspendLayout();
  (self.AttList as System.ComponentModel.ISupportInitialize).BeginInit();
  self.PanelAttCtrl.SuspendLayout();
  self.MenuSelectAtt.SuspendLayout();
  self.PanelAltCtrl.SuspendLayout();
  (self.AltList as System.ComponentModel.ISupportInitialize).BeginInit();
  self.AlternativesMenu.SuspendLayout();
  self.panel1.SuspendLayout();
  self.TabChart.SuspendLayout();
  self.GrpFonts.SuspendLayout();
  self.GrpColors.SuspendLayout();
  (self.EditTransparency as System.ComponentModel.ISupportInitialize).BeginInit();
  self.GrpSizes.SuspendLayout();
  (self.EditLinearPoint as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditRadarPoint as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditScatterPoint as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditBarWidth as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditLineWidth as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditTextGaps as System.ComponentModel.ISupportInitialize).BeginInit();
  self.GrpBorders.SuspendLayout();
  (self.EditBorderRight as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditBorderBottom as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditBorderTop as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditBorderLeft as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.PicBorders as System.ComponentModel.ISupportInitialize).BeginInit();
  self.GrpChartType.SuspendLayout();
  (self.EditGridY as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditGridX as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.ChartPicture as System.ComponentModel.ISupportInitialize).BeginInit();
  self.ChartMenu.SuspendLayout();
  self.ChartPanel.SuspendLayout();
  self.SuspendLayout();
  self.FormTool.ImeMode := System.Windows.Forms.ImeMode.Off;
  self.FormTool.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self._separator, self.ItemToolCopy, self.ItemToolSave]));
  self.FormTool.Location := new System.Drawing.Point(0, 24);
  self.FormTool.Name := 'FormTool';
  self.FormTool.Size := new System.Drawing.Size(1208, 25);
  self.FormTool.TabIndex := 3;
  self.FormTool.Text := 'toolStrip1';
  self._separator.Name := '_separator';
  self._separator.Size := new System.Drawing.Size(6, 25);
  self._separator.Visible := false;
  self.ItemToolCopy.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolCopy.Image := DEXiWin.Properties.Resources.PrevCopyMetafile;
  self.ItemToolCopy.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolCopy.Name := 'ItemToolCopy';
  self.ItemToolCopy.Size := new System.Drawing.Size(23, 22);
  self.ItemToolCopy.Text := '&Copy';
  self.ItemToolCopy.ToolTipText := 'Copy chart';
  self.ItemToolCopy.Click += new System.EventHandler(self.ItemMenuCopyMetafile_Click);
  self.ItemToolSave.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolSave.Image := DEXiWin.Properties.Resources.PrevSave;
  self.ItemToolSave.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolSave.Name := 'ItemToolSave';
  self.ItemToolSave.Size := new System.Drawing.Size(23, 22);
  self.ItemToolSave.Text := 'Save';
  self.ItemToolSave.ToolTipText := 'Save chart...';
  self.ItemToolSave.Click += new System.EventHandler(self.ItemToolSave_Click);
  self.FormMenu.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemMenuFile, self.ItemMenuEdit]));
  self.FormMenu.Location := new System.Drawing.Point(0, 0);
  self.FormMenu.Name := 'FormMenu';
  self.FormMenu.Size := new System.Drawing.Size(1208, 24);
  self.FormMenu.TabIndex := 2;
  self.FormMenu.Text := 'menuStrip1';
  self.ItemMenuFile.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.toolStripSeparator5, self.ItemMenuSave]));
  self.ItemMenuFile.MergeAction := System.Windows.Forms.MergeAction.MatchOnly;
  self.ItemMenuFile.Name := 'ItemMenuFile';
  self.ItemMenuFile.Size := new System.Drawing.Size(37, 20);
  self.ItemMenuFile.Text := '&File';
  self.toolStripSeparator5.MergeAction := System.Windows.Forms.MergeAction.Insert;
  self.toolStripSeparator5.MergeIndex := 7;
  self.toolStripSeparator5.Name := 'toolStripSeparator5';
  self.toolStripSeparator5.Size := new System.Drawing.Size(134, 6);
  self.ItemMenuSave.MergeAction := System.Windows.Forms.MergeAction.Insert;
  self.ItemMenuSave.MergeIndex := 8;
  self.ItemMenuSave.Name := 'ItemMenuSave';
  self.ItemMenuSave.Size := new System.Drawing.Size(137, 22);
  self.ItemMenuSave.Text := 'Save &chart...';
  self.ItemMenuSave.Click += new System.EventHandler(self.ItemToolSave_Click);
  self.ItemMenuEdit.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.toolStripSeparator3, self.ItemMenuEditAddReport, self.toolStripSeparator4, self.ItemMenuCopyMetafile, self.ItemMenuCopyBitmap]));
  self.ItemMenuEdit.MergeAction := System.Windows.Forms.MergeAction.MatchOnly;
  self.ItemMenuEdit.Name := 'ItemMenuEdit';
  self.ItemMenuEdit.Size := new System.Drawing.Size(39, 20);
  self.ItemMenuEdit.Text := '&Edit';
  self.toolStripSeparator3.Name := 'toolStripSeparator3';
  self.toolStripSeparator3.Size := new System.Drawing.Size(228, 6);
  self.ItemMenuEditAddReport.Name := 'ItemMenuEditAddReport';
  self.ItemMenuEditAddReport.Size := new System.Drawing.Size(231, 22);
  self.ItemMenuEditAddReport.Text := '&Add to Report';
  self.ItemMenuEditAddReport.ToolTipText := 'Add this graphic to the main Report tab';
  self.ItemMenuEditAddReport.Click += new System.EventHandler(self.ItemMenuEditAddReport_Click);
  self.toolStripSeparator4.Name := 'toolStripSeparator4';
  self.toolStripSeparator4.Size := new System.Drawing.Size(228, 6);
  self.ItemMenuCopyMetafile.Image := DEXiWin.Properties.Resources.PrevCopyMetafile;
  self.ItemMenuCopyMetafile.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemMenuCopyMetafile.Name := 'ItemMenuCopyMetafile';
  self.ItemMenuCopyMetafile.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.C as System.Windows.Forms.Keys);
  self.ItemMenuCopyMetafile.Size := new System.Drawing.Size(231, 22);
  self.ItemMenuCopyMetafile.Text := '&Copy as metafile';
  self.ItemMenuCopyMetafile.ToolTipText := 'Copy report page as a metafile';
  self.ItemMenuCopyMetafile.Click += new System.EventHandler(self.ItemMenuCopyMetafile_Click);
  self.ItemMenuCopyBitmap.Image := DEXiWin.Properties.Resources.PrevCopyBitmap;
  self.ItemMenuCopyBitmap.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemMenuCopyBitmap.Name := 'ItemMenuCopyBitmap';
  self.ItemMenuCopyBitmap.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Shift or System.Windows.Forms.Keys.C as System.Windows.Forms.Keys);
  self.ItemMenuCopyBitmap.Size := new System.Drawing.Size(231, 22);
  self.ItemMenuCopyBitmap.Text := 'Copy as &bitmap';
  self.ItemMenuCopyBitmap.ToolTipText := 'Copy report page as a bitmap';
  self.ItemMenuCopyBitmap.Click += new System.EventHandler(self.ItemMenuCopyBitmap_Click);
  self.CtrlPanel.Controls.Add(self.TabFormat);
  self.CtrlPanel.Dock := System.Windows.Forms.DockStyle.Right;
  self.CtrlPanel.Location := new System.Drawing.Point(1000, 49);
  self.CtrlPanel.Name := 'CtrlPanel';
  self.CtrlPanel.Size := new System.Drawing.Size(208, 695);
  self.CtrlPanel.TabIndex := 4;
  self.TabFormat.Controls.Add(self.TabAttributes);
  self.TabFormat.Controls.Add(self.PanelAltCtrl);
  self.TabFormat.Controls.Add(self.TabChart);
  self.TabFormat.Dock := System.Windows.Forms.DockStyle.Fill;
  self.TabFormat.Location := new System.Drawing.Point(0, 0);
  self.TabFormat.Name := 'TabFormat';
  self.TabFormat.SelectedIndex := 0;
  self.TabFormat.Size := new System.Drawing.Size(208, 695);
  self.TabFormat.TabIndex := 0;
  self.TabAttributes.Controls.Add(self.AttList);
  self.TabAttributes.Controls.Add(self.PanelAttCtrl);
  self.TabAttributes.Location := new System.Drawing.Point(4, 22);
  self.TabAttributes.Name := 'TabAttributes';
  self.TabAttributes.Padding := new System.Windows.Forms.Padding(3);
  self.TabAttributes.Size := new System.Drawing.Size(200, 669);
  self.TabAttributes.TabIndex := 0;
  self.TabAttributes.Text := 'Attributes';
  self.TabAttributes.UseVisualStyleBackColor := true;
  self.AttList.AllColumns.Add(self.ColAttribute);
  self.AttList.CellEditUseWholeCell := false;
  self.AttList.CheckBoxes := true;
  self.AttList.Columns.AddRange(array of System.Windows.Forms.ColumnHeader([self.ColAttribute]));
  self.AttList.Dock := System.Windows.Forms.DockStyle.Fill;
  self.AttList.HeaderStyle := System.Windows.Forms.ColumnHeaderStyle.None;
  self.AttList.HideSelection := false;
  self.AttList.Location := new System.Drawing.Point(3, 3);
  self.AttList.MultiSelect := false;
  self.AttList.Name := 'AttList';
  self.AttList.ShowGroups := false;
  self.AttList.ShowImagesOnSubItems := true;
  self.AttList.ShowItemToolTips := true;
  self.AttList.Size := new System.Drawing.Size(194, 621);
  self.AttList.TabIndex := 1;
  self.AttList.UseCompatibleStateImageBehavior := false;
  self.AttList.View := System.Windows.Forms.View.Details;
  self.AttList.VirtualMode := true;
  self.AttList.ItemChecked += new System.Windows.Forms.ItemCheckedEventHandler(self.AttList_ItemChecked);
  self.ColAttribute.AspectName := 'Name';
  self.ColAttribute.FillsFreeSpace := true;
  self.ColAttribute.Groupable := false;
  self.ColAttribute.Hideable := false;
  self.ColAttribute.IsEditable := false;
  self.ColAttribute.Searchable := false;
  self.ColAttribute.Sortable := false;
  self.ColAttribute.UseFiltering := false;
  self.PanelAttCtrl.Controls.Add(self.BtnUnselectAllAtt);
  self.PanelAttCtrl.Controls.Add(self.MenuSelectAtt);
  self.PanelAttCtrl.Dock := System.Windows.Forms.DockStyle.Bottom;
  self.PanelAttCtrl.Location := new System.Drawing.Point(3, 624);
  self.PanelAttCtrl.Name := 'PanelAttCtrl';
  self.PanelAttCtrl.Size := new System.Drawing.Size(194, 42);
  self.PanelAttCtrl.TabIndex := 2;
  self.BtnUnselectAllAtt.Location := new System.Drawing.Point(100, 10);
  self.BtnUnselectAllAtt.Name := 'BtnUnselectAllAtt';
  self.BtnUnselectAllAtt.Size := new System.Drawing.Size(82, 23);
  self.BtnUnselectAllAtt.TabIndex := 11;
  self.BtnUnselectAllAtt.Text := 'Unselect all';
  self.BtnUnselectAllAtt.UseVisualStyleBackColor := true;
  self.BtnUnselectAllAtt.Click += new System.EventHandler(self.BtnUnselectAllAtt_Click);
  self.MenuSelectAtt.AutoSize := false;
  self.MenuSelectAtt.BackColor := System.Drawing.SystemColors.ControlLight;
  self.MenuSelectAtt.Dock := System.Windows.Forms.DockStyle.None;
  self.MenuSelectAtt.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.MenuAttSelect]));
  self.MenuSelectAtt.Location := new System.Drawing.Point(12, 10);
  self.MenuSelectAtt.Name := 'MenuSelectAtt';
  self.MenuSelectAtt.Size := new System.Drawing.Size(82, 24);
  self.MenuSelectAtt.TabIndex := 10;
  self.MenuSelectAtt.TabStop := true;
  self.MenuSelectAtt.Text := 'Select';
  self.MenuAttSelect.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.MenuSelectAllAttributes, self.MenuSelectBasicAttributes, self.MenuSelectRoots, self.MenuSelectLevel1, self.MenuSelectLevel2, self.MenuSelectLevel3]));
  self.MenuAttSelect.Name := 'MenuAttSelect';
  self.MenuAttSelect.Size := new System.Drawing.Size(62, 20);
  self.MenuAttSelect.Text := 'Select ...';
  self.MenuSelectAllAttributes.Name := 'MenuSelectAllAttributes';
  self.MenuSelectAllAttributes.Size := new System.Drawing.Size(175, 22);
  self.MenuSelectAllAttributes.Text := '&All attributes';
  self.MenuSelectAllAttributes.Click += new System.EventHandler(self.MenuSelectAllAttributes_Click);
  self.MenuSelectBasicAttributes.Name := 'MenuSelectBasicAttributes';
  self.MenuSelectBasicAttributes.Size := new System.Drawing.Size(175, 22);
  self.MenuSelectBasicAttributes.Text := '&Basic attributes';
  self.MenuSelectBasicAttributes.Click += new System.EventHandler(self.MenuSelectBasicAttributes_Click);
  self.MenuSelectRoots.Name := 'MenuSelectRoots';
  self.MenuSelectRoots.Size := new System.Drawing.Size(175, 22);
  self.MenuSelectRoots.Text := '&Root(s)';
  self.MenuSelectRoots.Click += new System.EventHandler(self.MenuSelectRoots_Click);
  self.MenuSelectLevel1.Name := 'MenuSelectLevel1';
  self.MenuSelectLevel1.Size := new System.Drawing.Size(175, 22);
  self.MenuSelectLevel1.Text := 'Level &1 intersection';
  self.MenuSelectLevel1.Click += new System.EventHandler(self.MenuSelectLevel1_Click);
  self.MenuSelectLevel2.Name := 'MenuSelectLevel2';
  self.MenuSelectLevel2.Size := new System.Drawing.Size(175, 22);
  self.MenuSelectLevel2.Text := 'Level &2 intersection';
  self.MenuSelectLevel2.Click += new System.EventHandler(self.MenuSelectLevel2_Click);
  self.MenuSelectLevel3.Name := 'MenuSelectLevel3';
  self.MenuSelectLevel3.Size := new System.Drawing.Size(175, 22);
  self.MenuSelectLevel3.Text := 'Level &3 intersection';
  self.MenuSelectLevel3.Click += new System.EventHandler(self.MenuSelectLevel3_Click);
  self.PanelAltCtrl.Controls.Add(self.AltList);
  self.PanelAltCtrl.Controls.Add(self.panel1);
  self.PanelAltCtrl.Location := new System.Drawing.Point(4, 22);
  self.PanelAltCtrl.Name := 'PanelAltCtrl';
  self.PanelAltCtrl.Padding := new System.Windows.Forms.Padding(3);
  self.PanelAltCtrl.Size := new System.Drawing.Size(200, 669);
  self.PanelAltCtrl.TabIndex := 1;
  self.PanelAltCtrl.Text := 'Alternatives';
  self.PanelAltCtrl.UseVisualStyleBackColor := true;
  self.AltList.AllColumns.Add(self.ColAlternative);
  self.AltList.CellEditUseWholeCell := false;
  self.AltList.CheckBoxes := true;
  self.AltList.Columns.AddRange(array of System.Windows.Forms.ColumnHeader([self.ColAlternative]));
  self.AltList.ContextMenuStrip := self.AlternativesMenu;
  self.AltList.Cursor := System.Windows.Forms.Cursors.Default;
  self.AltList.Dock := System.Windows.Forms.DockStyle.Fill;
  self.AltList.FullRowSelect := true;
  self.AltList.HeaderStyle := System.Windows.Forms.ColumnHeaderStyle.None;
  self.AltList.HideSelection := false;
  self.AltList.Location := new System.Drawing.Point(3, 3);
  self.AltList.MultiSelect := false;
  self.AltList.Name := 'AltList';
  self.AltList.ShowGroups := false;
  self.AltList.ShowItemToolTips := true;
  self.AltList.Size := new System.Drawing.Size(194, 621);
  self.AltList.TabIndex := 4;
  self.AltList.UseCompatibleStateImageBehavior := false;
  self.AltList.View := System.Windows.Forms.View.Details;
  self.AltList.CellToolTipShowing += new System.EventHandler<BrightIdeasSoftware.ToolTipShowingEventArgs>(self.AltList_CellToolTipShowing);
  self.AltList.ItemChecked += new System.Windows.Forms.ItemCheckedEventHandler(self.AltList_ItemChecked);
  self.AltList.SelectedIndexChanged += new System.EventHandler(self.AltList_SelectedIndexChanged);
  self.ColAlternative.AspectName := 'Name';
  self.ColAlternative.ToolTipText := 'Description';
  self.AlternativesMenu.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemPopMoveUp, self.ItemPopMoveDown, self.ItemPopResetAltOrder]));
  self.AlternativesMenu.Name := 'AlternativesMenu';
  self.AlternativesMenu.Size := new System.Drawing.Size(203, 70);
  self.ItemPopMoveUp.Image := DEXiWin.Properties.Resources.ImgMoveUp;
  self.ItemPopMoveUp.Name := 'ItemPopMoveUp';
  self.ItemPopMoveUp.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Up as System.Windows.Forms.Keys);
  self.ItemPopMoveUp.Size := new System.Drawing.Size(202, 22);
  self.ItemPopMoveUp.Text := 'Move up';
  self.ItemPopMoveUp.ToolTipText := 'Move alternative up';
  self.ItemPopMoveUp.Click += new System.EventHandler(self.ItemPopMoveUp_Click);
  self.ItemPopMoveDown.Image := DEXiWin.Properties.Resources.ImgMoveDown;
  self.ItemPopMoveDown.Name := 'ItemPopMoveDown';
  self.ItemPopMoveDown.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Down as System.Windows.Forms.Keys);
  self.ItemPopMoveDown.Size := new System.Drawing.Size(202, 22);
  self.ItemPopMoveDown.Text := 'Move down';
  self.ItemPopMoveDown.ToolTipText := 'Move alternative down';
  self.ItemPopMoveDown.Click += new System.EventHandler(self.ItemPopMoveDown_Click);
  self.ItemPopResetAltOrder.Image := DEXiWin.Properties.Resources.ImgVertReset;
  self.ItemPopResetAltOrder.Name := 'ItemPopResetAltOrder';
  self.ItemPopResetAltOrder.Size := new System.Drawing.Size(202, 22);
  self.ItemPopResetAltOrder.Text := "Reset alternatives' order";
  self.ItemPopResetAltOrder.Click += new System.EventHandler(self.ItemPopResetAltOrder_Click);
  self.panel1.Controls.Add(self.BtnUnselectAllAlt);
  self.panel1.Controls.Add(self.BtnSelectAllAlt);
  self.panel1.Dock := System.Windows.Forms.DockStyle.Bottom;
  self.panel1.Location := new System.Drawing.Point(3, 624);
  self.panel1.Name := 'panel1';
  self.panel1.Size := new System.Drawing.Size(194, 42);
  self.panel1.TabIndex := 3;
  self.BtnUnselectAllAlt.Location := new System.Drawing.Point(100, 10);
  self.BtnUnselectAllAlt.Name := 'BtnUnselectAllAlt';
  self.BtnUnselectAllAlt.Size := new System.Drawing.Size(82, 23);
  self.BtnUnselectAllAlt.TabIndex := 11;
  self.BtnUnselectAllAlt.Text := 'Unselect all';
  self.BtnUnselectAllAlt.UseVisualStyleBackColor := true;
  self.BtnUnselectAllAlt.Click += new System.EventHandler(self.BtnUnselectAllAlt_Click);
  self.BtnSelectAllAlt.Location := new System.Drawing.Point(12, 10);
  self.BtnSelectAllAlt.Name := 'BtnSelectAllAlt';
  self.BtnSelectAllAlt.Size := new System.Drawing.Size(82, 23);
  self.BtnSelectAllAlt.TabIndex := 10;
  self.BtnSelectAllAlt.Text := 'Select all';
  self.BtnSelectAllAlt.UseVisualStyleBackColor := true;
  self.BtnSelectAllAlt.Click += new System.EventHandler(self.BtnSelectAllAlt_Click);
  self.TabChart.Controls.Add(self.GrpFonts);
  self.TabChart.Controls.Add(self.GrpColors);
  self.TabChart.Controls.Add(self.GrpSizes);
  self.TabChart.Controls.Add(self.GrpBorders);
  self.TabChart.Controls.Add(self.GrpChartType);
  self.TabChart.Location := new System.Drawing.Point(4, 22);
  self.TabChart.Name := 'TabChart';
  self.TabChart.Size := new System.Drawing.Size(200, 669);
  self.TabChart.TabIndex := 2;
  self.TabChart.Text := 'Chart';
  self.TabChart.UseVisualStyleBackColor := true;
  self.GrpFonts.Controls.Add(self.BtnValFont);
  self.GrpFonts.Controls.Add(self.BtnAttFont);
  self.GrpFonts.Controls.Add(self.BtnAltFont);
  self.GrpFonts.Dock := System.Windows.Forms.DockStyle.Top;
  self.GrpFonts.Location := new System.Drawing.Point(0, 439);
  self.GrpFonts.Name := 'GrpFonts';
  self.GrpFonts.Size := new System.Drawing.Size(200, 100);
  self.GrpFonts.TabIndex := 50;
  self.GrpFonts.TabStop := false;
  self.GrpFonts.Text := 'Fonts';
  self.BtnValFont.Location := new System.Drawing.Point(8, 70);
  self.BtnValFont.Name := 'BtnValFont';
  self.BtnValFont.Size := new System.Drawing.Size(162, 23);
  self.BtnValFont.TabIndex := 53;
  self.BtnValFont.Text := 'Values...';
  self.BtnValFont.UseVisualStyleBackColor := true;
  self.BtnValFont.Click += new System.EventHandler(self.BtnValFont_Click);
  self.BtnAttFont.Location := new System.Drawing.Point(8, 45);
  self.BtnAttFont.Name := 'BtnAttFont';
  self.BtnAttFont.Size := new System.Drawing.Size(162, 23);
  self.BtnAttFont.TabIndex := 52;
  self.BtnAttFont.Text := 'Attributes...';
  self.BtnAttFont.UseVisualStyleBackColor := true;
  self.BtnAttFont.Click += new System.EventHandler(self.BtnAttFont_Click);
  self.BtnAltFont.Location := new System.Drawing.Point(8, 20);
  self.BtnAltFont.Name := 'BtnAltFont';
  self.BtnAltFont.Size := new System.Drawing.Size(162, 23);
  self.BtnAltFont.TabIndex := 51;
  self.BtnAltFont.Text := 'Alternatives...';
  self.BtnAltFont.UseVisualStyleBackColor := true;
  self.BtnAltFont.Click += new System.EventHandler(self.BtnAltFont_Click);
  self.GrpColors.Controls.Add(self.BtnAreaColor);
  self.GrpColors.Controls.Add(self.EditTransparency);
  self.GrpColors.Controls.Add(self.LblTransparency);
  self.GrpColors.Controls.Add(self.BtnBackgroundColor);
  self.GrpColors.Dock := System.Windows.Forms.DockStyle.Top;
  self.GrpColors.Location := new System.Drawing.Point(0, 339);
  self.GrpColors.Name := 'GrpColors';
  self.GrpColors.Size := new System.Drawing.Size(200, 100);
  self.GrpColors.TabIndex := 40;
  self.GrpColors.TabStop := false;
  self.GrpColors.Text := '&Colors';
  self.BtnAreaColor.Location := new System.Drawing.Point(8, 71);
  self.BtnAreaColor.Name := 'BtnAreaColor';
  self.BtnAreaColor.Size := new System.Drawing.Size(162, 23);
  self.BtnAreaColor.TabIndex := 43;
  self.BtnAreaColor.Text := 'Chart area ...';
  self.BtnAreaColor.UseVisualStyleBackColor := true;
  self.BtnAreaColor.Click += new System.EventHandler(self.BtnAreaColor_Click);
  self.EditTransparency.Location := new System.Drawing.Point(120, 20);
  self.EditTransparency.Name := 'EditTransparency';
  self.EditTransparency.Size := new System.Drawing.Size(50, 20);
  self.EditTransparency.TabIndex := 41;
  self.EditTransparency.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditTransparency.ValueChanged += new System.EventHandler(self.EditChart_ValueChanged);
  self.LblTransparency.AutoSize := true;
  self.LblTransparency.Location := new System.Drawing.Point(8, 24);
  self.LblTransparency.Name := 'LblTransparency';
  self.LblTransparency.Size := new System.Drawing.Size(89, 13);
  self.LblTransparency.TabIndex := 13;
  self.LblTransparency.Text := '&Transparency [%]';
  self.BtnBackgroundColor.Location := new System.Drawing.Point(8, 46);
  self.BtnBackgroundColor.Name := 'BtnBackgroundColor';
  self.BtnBackgroundColor.Size := new System.Drawing.Size(162, 23);
  self.BtnBackgroundColor.TabIndex := 42;
  self.BtnBackgroundColor.Text := 'Background ...';
  self.BtnBackgroundColor.UseVisualStyleBackColor := true;
  self.BtnBackgroundColor.Click += new System.EventHandler(self.BtnBackgroundColor_Click);
  self.GrpSizes.Controls.Add(self.LblLinear);
  self.GrpSizes.Controls.Add(self.EditLinearPoint);
  self.GrpSizes.Controls.Add(self.LblRadar);
  self.GrpSizes.Controls.Add(self.EditRadarPoint);
  self.GrpSizes.Controls.Add(self.LblScatter);
  self.GrpSizes.Controls.Add(self.EditScatterPoint);
  self.GrpSizes.Controls.Add(self.LblPointSizes);
  self.GrpSizes.Controls.Add(self.EditBarWidth);
  self.GrpSizes.Controls.Add(self.LblBarWidth);
  self.GrpSizes.Controls.Add(self.EditLineWidth);
  self.GrpSizes.Controls.Add(self.LblLineWidth);
  self.GrpSizes.Controls.Add(self.EditTextGaps);
  self.GrpSizes.Controls.Add(self.LblTextGaps);
  self.GrpSizes.Dock := System.Windows.Forms.DockStyle.Top;
  self.GrpSizes.Location := new System.Drawing.Point(0, 179);
  self.GrpSizes.Name := 'GrpSizes';
  self.GrpSizes.Size := new System.Drawing.Size(200, 160);
  self.GrpSizes.TabIndex := 30;
  self.GrpSizes.TabStop := false;
  self.GrpSizes.Text := '&Sizes';
  self.LblLinear.AutoSize := true;
  self.LblLinear.Location := new System.Drawing.Point(127, 112);
  self.LblLinear.Name := 'LblLinear';
  self.LblLinear.Size := new System.Drawing.Size(36, 13);
  self.LblLinear.TabIndex := 17;
  self.LblLinear.Text := 'Linear';
  self.EditLinearPoint.Location := new System.Drawing.Point(120, 128);
  self.EditLinearPoint.Maximum := new System.Decimal(array of System.Int32([20, 0, 0, 0]));
  self.EditLinearPoint.Minimum := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditLinearPoint.Name := 'EditLinearPoint';
  self.EditLinearPoint.Size := new System.Drawing.Size(50, 20);
  self.EditLinearPoint.TabIndex := 38;
  self.EditLinearPoint.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditLinearPoint.ValueChanged += new System.EventHandler(self.EditChart_ValueChanged);
  self.LblRadar.AutoSize := true;
  self.LblRadar.Location := new System.Drawing.Point(71, 112);
  self.LblRadar.Name := 'LblRadar';
  self.LblRadar.Size := new System.Drawing.Size(36, 13);
  self.LblRadar.TabIndex := 15;
  self.LblRadar.Text := 'Radar';
  self.EditRadarPoint.Location := new System.Drawing.Point(64, 128);
  self.EditRadarPoint.Maximum := new System.Decimal(array of System.Int32([20, 0, 0, 0]));
  self.EditRadarPoint.Minimum := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditRadarPoint.Name := 'EditRadarPoint';
  self.EditRadarPoint.Size := new System.Drawing.Size(50, 20);
  self.EditRadarPoint.TabIndex := 37;
  self.EditRadarPoint.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditRadarPoint.ValueChanged += new System.EventHandler(self.EditChart_ValueChanged);
  self.LblScatter.AutoSize := true;
  self.LblScatter.Location := new System.Drawing.Point(13, 112);
  self.LblScatter.Name := 'LblScatter';
  self.LblScatter.Size := new System.Drawing.Size(41, 13);
  self.LblScatter.TabIndex := 13;
  self.LblScatter.Text := 'Scatter';
  self.EditScatterPoint.Location := new System.Drawing.Point(8, 128);
  self.EditScatterPoint.Maximum := new System.Decimal(array of System.Int32([20, 0, 0, 0]));
  self.EditScatterPoint.Minimum := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditScatterPoint.Name := 'EditScatterPoint';
  self.EditScatterPoint.Size := new System.Drawing.Size(50, 20);
  self.EditScatterPoint.TabIndex := 36;
  self.EditScatterPoint.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditScatterPoint.ValueChanged += new System.EventHandler(self.EditChart_ValueChanged);
  self.LblPointSizes.AutoSize := true;
  self.LblPointSizes.Location := new System.Drawing.Point(9, 95);
  self.LblPointSizes.Name := 'LblPointSizes';
  self.LblPointSizes.Size := new System.Drawing.Size(60, 13);
  self.LblPointSizes.TabIndex := 11;
  self.LblPointSizes.Text := 'Po&int sizes:';
  self.EditBarWidth.Location := new System.Drawing.Point(120, 68);
  self.EditBarWidth.Maximum := new System.Decimal(array of System.Int32([99, 0, 0, 0]));
  self.EditBarWidth.Minimum := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditBarWidth.Name := 'EditBarWidth';
  self.EditBarWidth.Size := new System.Drawing.Size(50, 20);
  self.EditBarWidth.TabIndex := 33;
  self.EditBarWidth.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditBarWidth.ValueChanged += new System.EventHandler(self.EditChart_ValueChanged);
  self.LblBarWidth.AutoSize := true;
  self.LblBarWidth.Location := new System.Drawing.Point(8, 72);
  self.LblBarWidth.Name := 'LblBarWidth';
  self.LblBarWidth.Size := new System.Drawing.Size(68, 13);
  self.LblBarWidth.TabIndex := 9;
  self.LblBarWidth.Text := '&Bar width [%]';
  self.EditLineWidth.Location := new System.Drawing.Point(120, 44);
  self.EditLineWidth.Maximum := new System.Decimal(array of System.Int32([5, 0, 0, 0]));
  self.EditLineWidth.Minimum := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditLineWidth.Name := 'EditLineWidth';
  self.EditLineWidth.Size := new System.Drawing.Size(50, 20);
  self.EditLineWidth.TabIndex := 32;
  self.EditLineWidth.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditLineWidth.ValueChanged += new System.EventHandler(self.EditChart_ValueChanged);
  self.LblLineWidth.AutoSize := true;
  self.LblLineWidth.Location := new System.Drawing.Point(8, 48);
  self.LblLineWidth.Name := 'LblLineWidth';
  self.LblLineWidth.Size := new System.Drawing.Size(55, 13);
  self.LblLineWidth.TabIndex := 7;
  self.LblLineWidth.Text := 'Line &width';
  self.EditTextGaps.Location := new System.Drawing.Point(120, 20);
  self.EditTextGaps.Maximum := new System.Decimal(array of System.Int32([30, 0, 0, 0]));
  self.EditTextGaps.Minimum := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditTextGaps.Name := 'EditTextGaps';
  self.EditTextGaps.Size := new System.Drawing.Size(50, 20);
  self.EditTextGaps.TabIndex := 31;
  self.EditTextGaps.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditTextGaps.ValueChanged += new System.EventHandler(self.EditChart_ValueChanged);
  self.LblTextGaps.AutoSize := true;
  self.LblTextGaps.Location := new System.Drawing.Point(8, 24);
  self.LblTextGaps.Name := 'LblTextGaps';
  self.LblTextGaps.Size := new System.Drawing.Size(54, 13);
  self.LblTextGaps.TabIndex := 5;
  self.LblTextGaps.Text := 'Text &gaps';
  self.GrpBorders.Controls.Add(self.EditBorderRight);
  self.GrpBorders.Controls.Add(self.EditBorderBottom);
  self.GrpBorders.Controls.Add(self.EditBorderTop);
  self.GrpBorders.Controls.Add(self.EditBorderLeft);
  self.GrpBorders.Controls.Add(self.PicBorders);
  self.GrpBorders.Dock := System.Windows.Forms.DockStyle.Top;
  self.GrpBorders.Location := new System.Drawing.Point(0, 79);
  self.GrpBorders.Name := 'GrpBorders';
  self.GrpBorders.Size := new System.Drawing.Size(200, 100);
  self.GrpBorders.TabIndex := 20;
  self.GrpBorders.TabStop := false;
  self.GrpBorders.Text := 'Chart &borders';
  self.EditBorderRight.Location := new System.Drawing.Point(120, 45);
  self.EditBorderRight.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditBorderRight.Name := 'EditBorderRight';
  self.EditBorderRight.Size := new System.Drawing.Size(50, 20);
  self.EditBorderRight.TabIndex := 5;
  self.EditBorderRight.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditBorderRight.ValueChanged += new System.EventHandler(self.EditChart_ValueChanged);
  self.EditBorderBottom.Location := new System.Drawing.Point(64, 70);
  self.EditBorderBottom.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditBorderBottom.Name := 'EditBorderBottom';
  self.EditBorderBottom.Size := new System.Drawing.Size(50, 20);
  self.EditBorderBottom.TabIndex := 4;
  self.EditBorderBottom.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditBorderBottom.ValueChanged += new System.EventHandler(self.EditChart_ValueChanged);
  self.EditBorderTop.Location := new System.Drawing.Point(64, 20);
  self.EditBorderTop.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditBorderTop.Name := 'EditBorderTop';
  self.EditBorderTop.Size := new System.Drawing.Size(50, 20);
  self.EditBorderTop.TabIndex := 3;
  self.EditBorderTop.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditBorderTop.ValueChanged += new System.EventHandler(self.EditChart_ValueChanged);
  self.EditBorderLeft.Location := new System.Drawing.Point(8, 45);
  self.EditBorderLeft.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditBorderLeft.Name := 'EditBorderLeft';
  self.EditBorderLeft.Size := new System.Drawing.Size(50, 20);
  self.EditBorderLeft.TabIndex := 2;
  self.EditBorderLeft.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditBorderLeft.ValueChanged += new System.EventHandler(self.EditChart_ValueChanged);
  self.PicBorders.Image := DEXiWin.Properties.Resources.TextBorder;
  self.PicBorders.Location := new System.Drawing.Point(64, 44);
  self.PicBorders.Name := 'PicBorders';
  self.PicBorders.Size := new System.Drawing.Size(50, 22);
  self.PicBorders.SizeMode := System.Windows.Forms.PictureBoxSizeMode.AutoSize;
  self.PicBorders.TabIndex := 0;
  self.PicBorders.TabStop := false;
  self.GrpChartType.Controls.Add(self.EditGridY);
  self.GrpChartType.Controls.Add(self.LblTimes);
  self.GrpChartType.Controls.Add(self.EditGridX);
  self.GrpChartType.Controls.Add(self.LblGrid);
  self.GrpChartType.Controls.Add(self.EditChartType);
  self.GrpChartType.Dock := System.Windows.Forms.DockStyle.Top;
  self.GrpChartType.Location := new System.Drawing.Point(0, 0);
  self.GrpChartType.Name := 'GrpChartType';
  self.GrpChartType.Size := new System.Drawing.Size(200, 79);
  self.GrpChartType.TabIndex := 10;
  self.GrpChartType.TabStop := false;
  self.GrpChartType.Text := 'Chart type for >2 attributes';
  self.EditGridY.Location := new System.Drawing.Point(120, 49);
  self.EditGridY.Maximum := new System.Decimal(array of System.Int32([5, 0, 0, 0]));
  self.EditGridY.Minimum := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditGridY.Name := 'EditGridY';
  self.EditGridY.Size := new System.Drawing.Size(50, 20);
  self.EditGridY.TabIndex := 13;
  self.EditGridY.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditGridY.ValueChanged += new System.EventHandler(self.EditChart_ValueChanged);
  self.LblTimes.AutoSize := true;
  self.LblTimes.Location := new System.Drawing.Point(103, 51);
  self.LblTimes.Name := 'LblTimes';
  self.LblTimes.Size := new System.Drawing.Size(13, 13);
  self.LblTimes.TabIndex := 5;
  self.LblTimes.Text := ""#215;
  self.EditGridX.Location := new System.Drawing.Point(49, 49);
  self.EditGridX.Maximum := new System.Decimal(array of System.Int32([5, 0, 0, 0]));
  self.EditGridX.Minimum := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditGridX.Name := 'EditGridX';
  self.EditGridX.Size := new System.Drawing.Size(50, 20);
  self.EditGridX.TabIndex := 12;
  self.EditGridX.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditGridX.ValueChanged += new System.EventHandler(self.EditChart_ValueChanged);
  self.LblGrid.AutoSize := true;
  self.LblGrid.Location := new System.Drawing.Point(8, 51);
  self.LblGrid.Name := 'LblGrid';
  self.LblGrid.Size := new System.Drawing.Size(26, 13);
  self.LblGrid.TabIndex := 1;
  self.LblGrid.Text := 'Grid';
  self.EditChartType.DropDownStyle := System.Windows.Forms.ComboBoxStyle.DropDownList;
  self.EditChartType.FormattingEnabled := true;
  self.EditChartType.Items.AddRange(array of System.Object(['Radar', 'Radar Grid', 'Linear']));
  self.EditChartType.Location := new System.Drawing.Point(8, 20);
  self.EditChartType.Name := 'EditChartType';
  self.EditChartType.Size := new System.Drawing.Size(162, 21);
  self.EditChartType.TabIndex := 11;
  self.EditChartType.SelectedIndexChanged += new System.EventHandler(self.EditChart_ValueChanged);
  self.ChartPicture.Location := new System.Drawing.Point(0, 0);
  self.ChartPicture.MinimumSize := new System.Drawing.Size(200, 200);
  self.ChartPicture.Name := 'ChartPicture';
  self.ChartPicture.Size := new System.Drawing.Size(200, 200);
  self.ChartPicture.SizeMode := System.Windows.Forms.PictureBoxSizeMode.StretchImage;
  self.ChartPicture.TabIndex := 0;
  self.ChartPicture.TabStop := false;
  self.DlgColor.AnyColor := true;
  self.ChartMenu.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemPopCopyMetafile, self.ItemPopCopyBitmap]));
  self.ChartMenu.Name := 'ReportMenu';
  self.ChartMenu.Size := new System.Drawing.Size(163, 48);
  self.ItemPopCopyMetafile.Image := (resources.GetObject('ItemPopCopyMetafile.Image') as System.Drawing.Image);
  self.ItemPopCopyMetafile.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemPopCopyMetafile.Name := 'ItemPopCopyMetafile';
  self.ItemPopCopyMetafile.Size := new System.Drawing.Size(162, 22);
  self.ItemPopCopyMetafile.Text := '&Copy as Metafile';
  self.ItemPopCopyMetafile.ToolTipText := 'Copy report page as a Metafile';
  self.ItemPopCopyMetafile.Click += new System.EventHandler(self.ItemMenuCopyMetafile_Click);
  self.ItemPopCopyBitmap.Image := (resources.GetObject('ItemPopCopyBitmap.Image') as System.Drawing.Image);
  self.ItemPopCopyBitmap.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemPopCopyBitmap.Name := 'ItemPopCopyBitmap';
  self.ItemPopCopyBitmap.Size := new System.Drawing.Size(162, 22);
  self.ItemPopCopyBitmap.Text := 'Copy as &Bitmap';
  self.ItemPopCopyBitmap.ToolTipText := 'Copy report page as a Bitmap';
  self.ItemPopCopyBitmap.Click += new System.EventHandler(self.ItemMenuCopyBitmap_Click);
  self.ChartPanel.AutoScroll := true;
  self.ChartPanel.Controls.Add(self.LblMessage);
  self.ChartPanel.Controls.Add(self.ChartPicture);
  self.ChartPanel.Dock := System.Windows.Forms.DockStyle.Fill;
  self.ChartPanel.Location := new System.Drawing.Point(0, 49);
  self.ChartPanel.Name := 'ChartPanel';
  self.ChartPanel.Size := new System.Drawing.Size(1000, 695);
  self.ChartPanel.TabIndex := 5;
  self.LblMessage.BackColor := System.Drawing.SystemColors.AppWorkspace;
  self.LblMessage.Dock := System.Windows.Forms.DockStyle.Bottom;
  self.LblMessage.Font := new System.Drawing.Font('Microsoft Sans Serif', 8.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (238 as System.Byte));
  self.LblMessage.Location := new System.Drawing.Point(0, 542);
  self.LblMessage.Name := 'LblMessage';
  self.LblMessage.Size := new System.Drawing.Size(1000, 153);
  self.LblMessage.TabIndex := 1;
  self.LblMessage.Text := 'Charts: Select attributes and alternatives';
  self.LblMessage.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
  self.SaveChartDialog.Filter := 'Metafile|*.emf|Bitmap|*.png';
  self.SaveChartDialog.Title := 'Save chart as';
  self.ChartSplitter.Dock := System.Windows.Forms.DockStyle.Right;
  self.ChartSplitter.Location := new System.Drawing.Point(997, 49);
  self.ChartSplitter.Name := 'ChartSplitter';
  self.ChartSplitter.Size := new System.Drawing.Size(3, 695);
  self.ChartSplitter.TabIndex := 6;
  self.ChartSplitter.TabStop := false;
  self.AutoScroll := true;
  self.ContextMenuStrip := self.ChartMenu;
  self.Controls.Add(self.ChartSplitter);
  self.Controls.Add(self.ChartPanel);
  self.Controls.Add(self.CtrlPanel);
  self.Controls.Add(self.FormTool);
  self.Controls.Add(self.FormMenu);
  self.Name := 'CtrlFormCharts';
  self.Size := new System.Drawing.Size(1208, 744);
  self.VisibleChanged += new System.EventHandler(self.CtrlFormCharts_VisibleChanged);
  self.Resize += new System.EventHandler(self.CtrlFormCharts_Resize);
  self.FormTool.ResumeLayout(false);
  self.FormTool.PerformLayout();
  self.FormMenu.ResumeLayout(false);
  self.FormMenu.PerformLayout();
  self.CtrlPanel.ResumeLayout(false);
  self.TabFormat.ResumeLayout(false);
  self.TabAttributes.ResumeLayout(false);
  (self.AttList as System.ComponentModel.ISupportInitialize).EndInit();
  self.PanelAttCtrl.ResumeLayout(false);
  self.MenuSelectAtt.ResumeLayout(false);
  self.MenuSelectAtt.PerformLayout();
  self.PanelAltCtrl.ResumeLayout(false);
  (self.AltList as System.ComponentModel.ISupportInitialize).EndInit();
  self.AlternativesMenu.ResumeLayout(false);
  self.panel1.ResumeLayout(false);
  self.TabChart.ResumeLayout(false);
  self.GrpFonts.ResumeLayout(false);
  self.GrpColors.ResumeLayout(false);
  self.GrpColors.PerformLayout();
  (self.EditTransparency as System.ComponentModel.ISupportInitialize).EndInit();
  self.GrpSizes.ResumeLayout(false);
  self.GrpSizes.PerformLayout();
  (self.EditLinearPoint as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditRadarPoint as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditScatterPoint as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditBarWidth as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditLineWidth as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditTextGaps as System.ComponentModel.ISupportInitialize).EndInit();
  self.GrpBorders.ResumeLayout(false);
  self.GrpBorders.PerformLayout();
  (self.EditBorderRight as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditBorderBottom as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditBorderTop as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditBorderLeft as System.ComponentModel.ISupportInitialize).EndInit();
  (self.PicBorders as System.ComponentModel.ISupportInitialize).EndInit();
  self.GrpChartType.ResumeLayout(false);
  self.GrpChartType.PerformLayout();
  (self.EditGridY as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditGridX as System.ComponentModel.ISupportInitialize).EndInit();
  (self.ChartPicture as System.ComponentModel.ISupportInitialize).EndInit();
  self.ChartMenu.ResumeLayout(false);
  self.ChartPanel.ResumeLayout(false);
  self.ResumeLayout(false);
  self.PerformLayout();
end;
{$ENDREGION}

end.