namespace DexiWin;

interface

{$HIDE H7}

uses
  System.Drawing,
  System.Collections,
  System.Windows.Forms,
  System.ComponentModel;

type
  CtrlFormFunctChart = public partial class
  {$REGION Windows Control Designer generated fields}
  private
    ChkQQ2: System.Windows.Forms.CheckBox;
    
    TabAdvanced: System.Windows.Forms.TabPage;
    GrpLevels: System.Windows.Forms.GroupBox;
    
    ChkQQ: System.Windows.Forms.CheckBox;
    ChkMultilinear: System.Windows.Forms.CheckBox;
    ChkLinear: System.Windows.Forms.CheckBox;
    
    ItemMenuAddReport: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator2: System.Windows.Forms.ToolStripSeparator;
    GrpFonts: System.Windows.Forms.GroupBox;
    BtnValFont: System.Windows.Forms.Button;
    BtnAttFont: System.Windows.Forms.Button;
    ItemMenuViewResetRotation: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator7: System.Windows.Forms.ToolStripSeparator;
    GrpRotation: System.Windows.Forms.GroupBox;
    BtnResetRotation: System.Windows.Forms.Button;
    EditVertical: System.Windows.Forms.NumericUpDown;
    LblVertical: System.Windows.Forms.Label;
    EditHorizontal: System.Windows.Forms.NumericUpDown;
    LblHorizontal: System.Windows.Forms.Label;
    ItemMenuToolFirst: System.Windows.Forms.ToolStripButton;
    ItemMenuToolPrev: System.Windows.Forms.ToolStripButton;
    ItemMenuToolNext: System.Windows.Forms.ToolStripButton;
    toolStripSeparator6: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator3: System.Windows.Forms.ToolStripSeparator;
    ItemMenuViewPrev: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuViewNext: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuViewFirst: System.Windows.Forms.ToolStripMenuItem;
    LblMessage: System.Windows.Forms.Label;
    PanelDimControl: System.Windows.Forms.Panel;
    TabDimensions: System.Windows.Forms.TabPage;
    PanelChartCtrl: System.Windows.Forms.Panel;
    TabChart: System.Windows.Forms.TabPage;
    ChartPicture: System.Windows.Forms.PictureBox;
    ChartMenu: System.Windows.Forms.ContextMenuStrip;
    ChartPanel: DexiWin.ZoomablePanel;
    SaveChartDialog: System.Windows.Forms.SaveFileDialog;
    ItemPopCopyMetafile: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuCopyMetafile: System.Windows.Forms.ToolStripMenuItem;
    ItemPopCopyBitmap: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator4: System.Windows.Forms.ToolStripSeparator;
    ItemPopSettings: System.Windows.Forms.ToolStripMenuItem;
    DlgFont: System.Windows.Forms.FontDialog;
    DlgColor: System.Windows.Forms.ColorDialog;
    EditBorderRight: System.Windows.Forms.NumericUpDown;
    EditBorderBottom: System.Windows.Forms.NumericUpDown;
    EditBorderTop: System.Windows.Forms.NumericUpDown;
    EditBorderLeft: System.Windows.Forms.NumericUpDown;
    PicBorders: System.Windows.Forms.PictureBox;
    TabFormat: System.Windows.Forms.TabControl;
    GrpBorders: System.Windows.Forms.GroupBox;
    CtrlPanel: System.Windows.Forms.Panel;
    FormTool: System.Windows.Forms.ToolStrip;
    _separator: System.Windows.Forms.ToolStripSeparator;
    ItemToolCopy: System.Windows.Forms.ToolStripButton;
    ItemToolSave: System.Windows.Forms.ToolStripButton;
    FormMenu: System.Windows.Forms.MenuStrip;
    ItemMenuFile: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuSave: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator5: System.Windows.Forms.ToolStripSeparator;
    ItemMenuEdit: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuCopyBitmap: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuView: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator1: System.Windows.Forms.ToolStripSeparator;
    ItemMenuViewReports: System.Windows.Forms.ToolStripMenuItem;
    components: System.ComponentModel.Container := nil;
    method InitializeComponent;
  {$ENDREGION}
  end;

implementation

{$REGION Windows Control Designer generated code}
method CtrlFormFunctChart.InitializeComponent;
begin
  self.components := new System.ComponentModel.Container();
  var resources: System.ComponentModel.ComponentResourceManager := new System.ComponentModel.ComponentResourceManager(typeOf(CtrlFormFunctChart));
  self.FormTool := new System.Windows.Forms.ToolStrip();
  self._separator := new System.Windows.Forms.ToolStripSeparator();
  self.ItemToolCopy := new System.Windows.Forms.ToolStripButton();
  self.ItemToolSave := new System.Windows.Forms.ToolStripButton();
  self.toolStripSeparator1 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuToolFirst := new System.Windows.Forms.ToolStripButton();
  self.ItemMenuToolPrev := new System.Windows.Forms.ToolStripButton();
  self.ItemMenuToolNext := new System.Windows.Forms.ToolStripButton();
  self.toolStripSeparator6 := new System.Windows.Forms.ToolStripSeparator();
  self.FormMenu := new System.Windows.Forms.MenuStrip();
  self.ItemMenuFile := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuSave := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator5 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuEdit := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuAddReport := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator2 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuCopyMetafile := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuCopyBitmap := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuView := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuViewFirst := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuViewPrev := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuViewNext := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator3 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuViewResetRotation := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator7 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuViewReports := new System.Windows.Forms.ToolStripMenuItem();
  self.CtrlPanel := new System.Windows.Forms.Panel();
  self.TabFormat := new System.Windows.Forms.TabControl();
  self.TabDimensions := new System.Windows.Forms.TabPage();
  self.PanelDimControl := new System.Windows.Forms.Panel();
  self.PanelChartCtrl := new System.Windows.Forms.Panel();
  self.TabChart := new System.Windows.Forms.TabPage();
  self.GrpFonts := new System.Windows.Forms.GroupBox();
  self.BtnValFont := new System.Windows.Forms.Button();
  self.BtnAttFont := new System.Windows.Forms.Button();
  self.GrpRotation := new System.Windows.Forms.GroupBox();
  self.BtnResetRotation := new System.Windows.Forms.Button();
  self.EditVertical := new System.Windows.Forms.NumericUpDown();
  self.LblVertical := new System.Windows.Forms.Label();
  self.EditHorizontal := new System.Windows.Forms.NumericUpDown();
  self.LblHorizontal := new System.Windows.Forms.Label();
  self.GrpBorders := new System.Windows.Forms.GroupBox();
  self.EditBorderRight := new System.Windows.Forms.NumericUpDown();
  self.EditBorderBottom := new System.Windows.Forms.NumericUpDown();
  self.EditBorderTop := new System.Windows.Forms.NumericUpDown();
  self.EditBorderLeft := new System.Windows.Forms.NumericUpDown();
  self.PicBorders := new System.Windows.Forms.PictureBox();
  self.TabAdvanced := new System.Windows.Forms.TabPage();
  self.GrpLevels := new System.Windows.Forms.GroupBox();
  self.ChkQQ2 := new System.Windows.Forms.CheckBox();
  self.ChkQQ := new System.Windows.Forms.CheckBox();
  self.ChkMultilinear := new System.Windows.Forms.CheckBox();
  self.ChkLinear := new System.Windows.Forms.CheckBox();
  self.ChartPicture := new System.Windows.Forms.PictureBox();
  self.DlgColor := new System.Windows.Forms.ColorDialog();
  self.DlgFont := new System.Windows.Forms.FontDialog();
  self.ChartMenu := new System.Windows.Forms.ContextMenuStrip(self.components);
  self.ItemPopCopyMetafile := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopCopyBitmap := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator4 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopSettings := new System.Windows.Forms.ToolStripMenuItem();
  self.ChartPanel := new DexiWin.ZoomablePanel();
  self.LblMessage := new System.Windows.Forms.Label();
  self.SaveChartDialog := new System.Windows.Forms.SaveFileDialog();
  self.FormTool.SuspendLayout();
  self.FormMenu.SuspendLayout();
  self.CtrlPanel.SuspendLayout();
  self.TabFormat.SuspendLayout();
  self.TabDimensions.SuspendLayout();
  self.TabChart.SuspendLayout();
  self.GrpFonts.SuspendLayout();
  self.GrpRotation.SuspendLayout();
  (self.EditVertical as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditHorizontal as System.ComponentModel.ISupportInitialize).BeginInit();
  self.GrpBorders.SuspendLayout();
  (self.EditBorderRight as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditBorderBottom as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditBorderTop as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditBorderLeft as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.PicBorders as System.ComponentModel.ISupportInitialize).BeginInit();
  self.TabAdvanced.SuspendLayout();
  self.GrpLevels.SuspendLayout();
  (self.ChartPicture as System.ComponentModel.ISupportInitialize).BeginInit();
  self.ChartMenu.SuspendLayout();
  self.ChartPanel.SuspendLayout();
  self.SuspendLayout();
  self.FormTool.ImeMode := System.Windows.Forms.ImeMode.Off;
  self.FormTool.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self._separator, self.ItemToolCopy, self.ItemToolSave, self.toolStripSeparator1, self.ItemMenuToolFirst, self.ItemMenuToolPrev, self.ItemMenuToolNext, self.toolStripSeparator6]));
  self.FormTool.Location := new System.Drawing.Point(0, 24);
  self.FormTool.Name := 'FormTool';
  self.FormTool.Size := new System.Drawing.Size(1286, 25);
  self.FormTool.TabIndex := 3;
  self.FormTool.Text := 'toolStrip1';
  self._separator.Name := '_separator';
  self._separator.Size := new System.Drawing.Size(6, 25);
  self._separator.Visible := false;
  self.ItemToolCopy.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolCopy.Image := DEXiWin.Properties.Resources.PrevCopyMetafile;
  self.ItemToolCopy.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolCopy.Name := 'ItemToolCopy';
  self.ItemToolCopy.Size := new System.Drawing.Size(23, 22);
  self.ItemToolCopy.Text := '&Copy';
  self.ItemToolCopy.ToolTipText := 'Copy tree graphic';
  self.ItemToolCopy.Click += new System.EventHandler(self.ItemMenuCopyMetafile_Click);
  self.ItemToolSave.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolSave.Image := DEXiWin.Properties.Resources.PrevSave;
  self.ItemToolSave.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolSave.Name := 'ItemToolSave';
  self.ItemToolSave.Size := new System.Drawing.Size(23, 22);
  self.ItemToolSave.Text := 'Save';
  self.ItemToolSave.ToolTipText := 'Save tree graphic';
  self.ItemToolSave.Click += new System.EventHandler(self.ItemToolSave_Click);
  self.toolStripSeparator1.Name := 'toolStripSeparator1';
  self.toolStripSeparator1.Size := new System.Drawing.Size(6, 25);
  self.ItemMenuToolFirst.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemMenuToolFirst.Image := DEXiWin.Properties.Resources.ImgFirstChart;
  self.ItemMenuToolFirst.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemMenuToolFirst.Name := 'ItemMenuToolFirst';
  self.ItemMenuToolFirst.Size := new System.Drawing.Size(23, 22);
  self.ItemMenuToolFirst.Text := 'First chart';
  self.ItemMenuToolFirst.Click += new System.EventHandler(self.ItemMenuViewFirst_Click);
  self.ItemMenuToolPrev.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemMenuToolPrev.Image := DEXiWin.Properties.Resources.ImgMoveLeft;
  self.ItemMenuToolPrev.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemMenuToolPrev.Name := 'ItemMenuToolPrev';
  self.ItemMenuToolPrev.Size := new System.Drawing.Size(23, 22);
  self.ItemMenuToolPrev.Text := 'Previous chart';
  self.ItemMenuToolPrev.Click += new System.EventHandler(self.ItemMenuViewPrev_Click);
  self.ItemMenuToolNext.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemMenuToolNext.Image := DEXiWin.Properties.Resources.ImgMoveRight;
  self.ItemMenuToolNext.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemMenuToolNext.Name := 'ItemMenuToolNext';
  self.ItemMenuToolNext.Size := new System.Drawing.Size(23, 22);
  self.ItemMenuToolNext.Text := 'Next chart';
  self.ItemMenuToolNext.Click += new System.EventHandler(self.ItemMenuViewNext_Click);
  self.toolStripSeparator6.Name := 'toolStripSeparator6';
  self.toolStripSeparator6.Size := new System.Drawing.Size(6, 25);
  self.FormMenu.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemMenuFile, self.ItemMenuEdit, self.ItemMenuView]));
  self.FormMenu.Location := new System.Drawing.Point(0, 0);
  self.FormMenu.Name := 'FormMenu';
  self.FormMenu.Size := new System.Drawing.Size(1286, 24);
  self.FormMenu.TabIndex := 2;
  self.FormMenu.Text := 'menuStrip1';
  self.ItemMenuFile.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemMenuSave, self.toolStripSeparator5]));
  self.ItemMenuFile.MergeAction := System.Windows.Forms.MergeAction.MatchOnly;
  self.ItemMenuFile.Name := 'ItemMenuFile';
  self.ItemMenuFile.Size := new System.Drawing.Size(37, 20);
  self.ItemMenuFile.Text := '&File';
  self.ItemMenuSave.MergeAction := System.Windows.Forms.MergeAction.Insert;
  self.ItemMenuSave.MergeIndex := 5;
  self.ItemMenuSave.Name := 'ItemMenuSave';
  self.ItemMenuSave.Size := new System.Drawing.Size(137, 22);
  self.ItemMenuSave.Text := 'Save &chart...';
  self.ItemMenuSave.Click += new System.EventHandler(self.ItemToolSave_Click);
  self.toolStripSeparator5.MergeAction := System.Windows.Forms.MergeAction.Insert;
  self.toolStripSeparator5.MergeIndex := 10;
  self.toolStripSeparator5.Name := 'toolStripSeparator5';
  self.toolStripSeparator5.Size := new System.Drawing.Size(134, 6);
  self.ItemMenuEdit.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemMenuAddReport, self.toolStripSeparator2, self.ItemMenuCopyMetafile, self.ItemMenuCopyBitmap]));
  self.ItemMenuEdit.MergeAction := System.Windows.Forms.MergeAction.MatchOnly;
  self.ItemMenuEdit.Name := 'ItemMenuEdit';
  self.ItemMenuEdit.Size := new System.Drawing.Size(39, 20);
  self.ItemMenuEdit.Text := '&Edit';
  self.ItemMenuAddReport.Name := 'ItemMenuAddReport';
  self.ItemMenuAddReport.Size := new System.Drawing.Size(231, 22);
  self.ItemMenuAddReport.Text := '&Add to Report';
  self.ItemMenuAddReport.ToolTipText := 'Add this graphic to the main Report tab';
  self.ItemMenuAddReport.Visible := false;
  self.ItemMenuAddReport.Click += new System.EventHandler(self.ItemMenuAddReport_Click);
  self.toolStripSeparator2.Name := 'toolStripSeparator2';
  self.toolStripSeparator2.Size := new System.Drawing.Size(228, 6);
  self.toolStripSeparator2.Visible := false;
  self.ItemMenuCopyMetafile.Image := DEXiWin.Properties.Resources.PrevCopyMetafile;
  self.ItemMenuCopyMetafile.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemMenuCopyMetafile.Name := 'ItemMenuCopyMetafile';
  self.ItemMenuCopyMetafile.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.C as System.Windows.Forms.Keys);
  self.ItemMenuCopyMetafile.Size := new System.Drawing.Size(231, 22);
  self.ItemMenuCopyMetafile.Text := '&Copy as metafile';
  self.ItemMenuCopyMetafile.ToolTipText := 'Copy report page as a metafile';
  self.ItemMenuCopyMetafile.Click += new System.EventHandler(self.ItemMenuCopyMetafile_Click);
  self.ItemMenuCopyBitmap.Image := DEXiWin.Properties.Resources.PrevCopyBitmap;
  self.ItemMenuCopyBitmap.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemMenuCopyBitmap.Name := 'ItemMenuCopyBitmap';
  self.ItemMenuCopyBitmap.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Shift or System.Windows.Forms.Keys.C as System.Windows.Forms.Keys);
  self.ItemMenuCopyBitmap.Size := new System.Drawing.Size(231, 22);
  self.ItemMenuCopyBitmap.Text := 'Copy as &bitmap';
  self.ItemMenuCopyBitmap.ToolTipText := 'Copy report page as a bitmap';
  self.ItemMenuCopyBitmap.Click += new System.EventHandler(self.ItemMenuCopyBitmap_Click);
  self.ItemMenuView.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemMenuViewFirst, self.ItemMenuViewPrev, self.ItemMenuViewNext, self.toolStripSeparator3, self.ItemMenuViewResetRotation, self.toolStripSeparator7, self.ItemMenuViewReports]));
  self.ItemMenuView.MergeAction := System.Windows.Forms.MergeAction.Insert;
  self.ItemMenuView.MergeIndex := 2;
  self.ItemMenuView.Name := 'ItemMenuView';
  self.ItemMenuView.Size := new System.Drawing.Size(44, 20);
  self.ItemMenuView.Text := '&View';
  self.ItemMenuViewFirst.Image := DEXiWin.Properties.Resources.ImgFirstChart;
  self.ItemMenuViewFirst.Name := 'ItemMenuViewFirst';
  self.ItemMenuViewFirst.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Up as System.Windows.Forms.Keys);
  self.ItemMenuViewFirst.Size := new System.Drawing.Size(203, 22);
  self.ItemMenuViewFirst.Text := '&First chart';
  self.ItemMenuViewFirst.Click += new System.EventHandler(self.ItemMenuViewFirst_Click);
  self.ItemMenuViewPrev.Image := DEXiWin.Properties.Resources.ImgMoveLeft;
  self.ItemMenuViewPrev.Name := 'ItemMenuViewPrev';
  self.ItemMenuViewPrev.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Left as System.Windows.Forms.Keys);
  self.ItemMenuViewPrev.Size := new System.Drawing.Size(203, 22);
  self.ItemMenuViewPrev.Text := '&Previous chart';
  self.ItemMenuViewPrev.Click += new System.EventHandler(self.ItemMenuViewPrev_Click);
  self.ItemMenuViewNext.Image := DEXiWin.Properties.Resources.ImgMoveRight;
  self.ItemMenuViewNext.Name := 'ItemMenuViewNext';
  self.ItemMenuViewNext.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Right as System.Windows.Forms.Keys);
  self.ItemMenuViewNext.Size := new System.Drawing.Size(203, 22);
  self.ItemMenuViewNext.Text := '&Next chart';
  self.ItemMenuViewNext.Click += new System.EventHandler(self.ItemMenuViewNext_Click);
  self.toolStripSeparator3.Name := 'toolStripSeparator3';
  self.toolStripSeparator3.Size := new System.Drawing.Size(200, 6);
  self.ItemMenuViewResetRotation.Name := 'ItemMenuViewResetRotation';
  self.ItemMenuViewResetRotation.Size := new System.Drawing.Size(203, 22);
  self.ItemMenuViewResetRotation.Text := 'Reset &rotation';
  self.ItemMenuViewResetRotation.Click += new System.EventHandler(self.ItemMenuViewResetRotation_Click);
  self.toolStripSeparator7.Name := 'toolStripSeparator7';
  self.toolStripSeparator7.Size := new System.Drawing.Size(200, 6);
  self.toolStripSeparator7.Visible := false;
  self.ItemMenuViewReports.Name := 'ItemMenuViewReports';
  self.ItemMenuViewReports.Size := new System.Drawing.Size(203, 22);
  self.ItemMenuViewReports.Text := '&Add to Report';
  self.ItemMenuViewReports.ToolTipText := 'Add this graphic to the main Report tab';
  self.ItemMenuViewReports.Visible := false;
  self.CtrlPanel.Controls.Add(self.TabFormat);
  self.CtrlPanel.Dock := System.Windows.Forms.DockStyle.Right;
  self.CtrlPanel.Location := new System.Drawing.Point(1078, 49);
  self.CtrlPanel.Name := 'CtrlPanel';
  self.CtrlPanel.Size := new System.Drawing.Size(208, 716);
  self.CtrlPanel.TabIndex := 4;
  self.TabFormat.Controls.Add(self.TabDimensions);
  self.TabFormat.Controls.Add(self.TabChart);
  self.TabFormat.Controls.Add(self.TabAdvanced);
  self.TabFormat.Dock := System.Windows.Forms.DockStyle.Fill;
  self.TabFormat.Location := new System.Drawing.Point(0, 0);
  self.TabFormat.Name := 'TabFormat';
  self.TabFormat.SelectedIndex := 0;
  self.TabFormat.Size := new System.Drawing.Size(208, 716);
  self.TabFormat.TabIndex := 0;
  self.TabDimensions.Controls.Add(self.PanelDimControl);
  self.TabDimensions.Controls.Add(self.PanelChartCtrl);
  self.TabDimensions.Location := new System.Drawing.Point(4, 22);
  self.TabDimensions.Name := 'TabDimensions';
  self.TabDimensions.Padding := new System.Windows.Forms.Padding(3);
  self.TabDimensions.Size := new System.Drawing.Size(200, 690);
  self.TabDimensions.TabIndex := 0;
  self.TabDimensions.Text := 'Dimensions';
  self.TabDimensions.UseVisualStyleBackColor := true;
  self.PanelDimControl.AutoScroll := true;
  self.PanelDimControl.Dock := System.Windows.Forms.DockStyle.Fill;
  self.PanelDimControl.Location := new System.Drawing.Point(3, 3);
  self.PanelDimControl.Name := 'PanelDimControl';
  self.PanelDimControl.Size := new System.Drawing.Size(194, 549);
  self.PanelDimControl.TabIndex := 1;
  self.PanelChartCtrl.Dock := System.Windows.Forms.DockStyle.Bottom;
  self.PanelChartCtrl.Location := new System.Drawing.Point(3, 552);
  self.PanelChartCtrl.Name := 'PanelChartCtrl';
  self.PanelChartCtrl.Size := new System.Drawing.Size(194, 135);
  self.PanelChartCtrl.TabIndex := 0;
  self.TabChart.Controls.Add(self.GrpFonts);
  self.TabChart.Controls.Add(self.GrpRotation);
  self.TabChart.Controls.Add(self.GrpBorders);
  self.TabChart.Location := new System.Drawing.Point(4, 22);
  self.TabChart.Name := 'TabChart';
  self.TabChart.Size := new System.Drawing.Size(200, 691);
  self.TabChart.TabIndex := 2;
  self.TabChart.Text := 'Chart';
  self.TabChart.UseVisualStyleBackColor := true;
  self.GrpFonts.Controls.Add(self.BtnValFont);
  self.GrpFonts.Controls.Add(self.BtnAttFont);
  self.GrpFonts.Dock := System.Windows.Forms.DockStyle.Top;
  self.GrpFonts.Location := new System.Drawing.Point(0, 210);
  self.GrpFonts.Name := 'GrpFonts';
  self.GrpFonts.Size := new System.Drawing.Size(200, 79);
  self.GrpFonts.TabIndex := 6;
  self.GrpFonts.TabStop := false;
  self.GrpFonts.Text := 'Fonts';
  self.BtnValFont.Location := new System.Drawing.Point(11, 44);
  self.BtnValFont.Name := 'BtnValFont';
  self.BtnValFont.Size := new System.Drawing.Size(162, 23);
  self.BtnValFont.TabIndex := 20;
  self.BtnValFont.Text := 'Values...';
  self.BtnValFont.UseVisualStyleBackColor := true;
  self.BtnValFont.Click += new System.EventHandler(self.BtnValFont_Click);
  self.BtnAttFont.Location := new System.Drawing.Point(11, 19);
  self.BtnAttFont.Name := 'BtnAttFont';
  self.BtnAttFont.Size := new System.Drawing.Size(162, 23);
  self.BtnAttFont.TabIndex := 19;
  self.BtnAttFont.Text := 'Attributes...';
  self.BtnAttFont.UseVisualStyleBackColor := true;
  self.BtnAttFont.Click += new System.EventHandler(self.BtnAttFont_Click);
  self.GrpRotation.Controls.Add(self.BtnResetRotation);
  self.GrpRotation.Controls.Add(self.EditVertical);
  self.GrpRotation.Controls.Add(self.LblVertical);
  self.GrpRotation.Controls.Add(self.EditHorizontal);
  self.GrpRotation.Controls.Add(self.LblHorizontal);
  self.GrpRotation.Dock := System.Windows.Forms.DockStyle.Top;
  self.GrpRotation.Location := new System.Drawing.Point(0, 100);
  self.GrpRotation.Name := 'GrpRotation';
  self.GrpRotation.Size := new System.Drawing.Size(200, 110);
  self.GrpRotation.TabIndex := 4;
  self.GrpRotation.TabStop := false;
  self.GrpRotation.Text := '&Rotation';
  self.BtnResetRotation.Location := new System.Drawing.Point(11, 73);
  self.BtnResetRotation.Name := 'BtnResetRotation';
  self.BtnResetRotation.Size := new System.Drawing.Size(159, 23);
  self.BtnResetRotation.TabIndex := 9;
  self.BtnResetRotation.Text := 'Reset rotation';
  self.BtnResetRotation.UseVisualStyleBackColor := true;
  self.BtnResetRotation.Click += new System.EventHandler(self.ItemMenuViewResetRotation_Click);
  self.EditVertical.Location := new System.Drawing.Point(120, 44);
  self.EditVertical.Maximum := new System.Decimal(array of System.Int32([90, 0, 0, 0]));
  self.EditVertical.Name := 'EditVertical';
  self.EditVertical.Size := new System.Drawing.Size(50, 20);
  self.EditVertical.TabIndex := 8;
  self.EditVertical.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditVertical.ValueChanged += new System.EventHandler(self.EditChart_ValueChanged);
  self.LblVertical.AutoSize := true;
  self.LblVertical.Location := new System.Drawing.Point(8, 48);
  self.LblVertical.Name := 'LblVertical';
  self.LblVertical.Size := new System.Drawing.Size(42, 13);
  self.LblVertical.TabIndex := 7;
  self.LblVertical.Text := '&Vertical';
  self.EditHorizontal.Location := new System.Drawing.Point(120, 20);
  self.EditHorizontal.Maximum := new System.Decimal(array of System.Int32([359, 0, 0, 0]));
  self.EditHorizontal.Name := 'EditHorizontal';
  self.EditHorizontal.Size := new System.Drawing.Size(50, 20);
  self.EditHorizontal.TabIndex := 6;
  self.EditHorizontal.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditHorizontal.ValueChanged += new System.EventHandler(self.EditChart_ValueChanged);
  self.LblHorizontal.AutoSize := true;
  self.LblHorizontal.Location := new System.Drawing.Point(8, 24);
  self.LblHorizontal.Name := 'LblHorizontal';
  self.LblHorizontal.Size := new System.Drawing.Size(54, 13);
  self.LblHorizontal.TabIndex := 5;
  self.LblHorizontal.Text := '&Horizontal';
  self.GrpBorders.Controls.Add(self.EditBorderRight);
  self.GrpBorders.Controls.Add(self.EditBorderBottom);
  self.GrpBorders.Controls.Add(self.EditBorderTop);
  self.GrpBorders.Controls.Add(self.EditBorderLeft);
  self.GrpBorders.Controls.Add(self.PicBorders);
  self.GrpBorders.Dock := System.Windows.Forms.DockStyle.Top;
  self.GrpBorders.Location := new System.Drawing.Point(0, 0);
  self.GrpBorders.Name := 'GrpBorders';
  self.GrpBorders.Size := new System.Drawing.Size(200, 100);
  self.GrpBorders.TabIndex := 2;
  self.GrpBorders.TabStop := false;
  self.GrpBorders.Text := 'Picture &borders';
  self.EditBorderRight.Location := new System.Drawing.Point(120, 45);
  self.EditBorderRight.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditBorderRight.Name := 'EditBorderRight';
  self.EditBorderRight.Size := new System.Drawing.Size(50, 20);
  self.EditBorderRight.TabIndex := 5;
  self.EditBorderRight.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditBorderRight.ValueChanged += new System.EventHandler(self.EditChart_ValueChanged);
  self.EditBorderBottom.Location := new System.Drawing.Point(64, 70);
  self.EditBorderBottom.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditBorderBottom.Name := 'EditBorderBottom';
  self.EditBorderBottom.Size := new System.Drawing.Size(50, 20);
  self.EditBorderBottom.TabIndex := 4;
  self.EditBorderBottom.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditBorderBottom.ValueChanged += new System.EventHandler(self.EditChart_ValueChanged);
  self.EditBorderTop.Location := new System.Drawing.Point(64, 20);
  self.EditBorderTop.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditBorderTop.Name := 'EditBorderTop';
  self.EditBorderTop.Size := new System.Drawing.Size(50, 20);
  self.EditBorderTop.TabIndex := 3;
  self.EditBorderTop.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditBorderTop.ValueChanged += new System.EventHandler(self.EditChart_ValueChanged);
  self.EditBorderLeft.Location := new System.Drawing.Point(8, 45);
  self.EditBorderLeft.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditBorderLeft.Name := 'EditBorderLeft';
  self.EditBorderLeft.Size := new System.Drawing.Size(50, 20);
  self.EditBorderLeft.TabIndex := 2;
  self.EditBorderLeft.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditBorderLeft.ValueChanged += new System.EventHandler(self.EditChart_ValueChanged);
  self.PicBorders.Image := DEXiWin.Properties.Resources.TextBorder;
  self.PicBorders.Location := new System.Drawing.Point(64, 44);
  self.PicBorders.Name := 'PicBorders';
  self.PicBorders.Size := new System.Drawing.Size(50, 22);
  self.PicBorders.SizeMode := System.Windows.Forms.PictureBoxSizeMode.AutoSize;
  self.PicBorders.TabIndex := 0;
  self.PicBorders.TabStop := false;
  self.TabAdvanced.Controls.Add(self.GrpLevels);
  self.TabAdvanced.Location := new System.Drawing.Point(4, 22);
  self.TabAdvanced.Name := 'TabAdvanced';
  self.TabAdvanced.Padding := new System.Windows.Forms.Padding(3);
  self.TabAdvanced.Size := new System.Drawing.Size(200, 690);
  self.TabAdvanced.TabIndex := 3;
  self.TabAdvanced.Text := 'Advanced';
  self.TabAdvanced.UseVisualStyleBackColor := true;
  self.GrpLevels.Controls.Add(self.ChkQQ2);
  self.GrpLevels.Controls.Add(self.ChkQQ);
  self.GrpLevels.Controls.Add(self.ChkMultilinear);
  self.GrpLevels.Controls.Add(self.ChkLinear);
  self.GrpLevels.Dock := System.Windows.Forms.DockStyle.Top;
  self.GrpLevels.Location := new System.Drawing.Point(3, 3);
  self.GrpLevels.Name := 'GrpLevels';
  self.GrpLevels.Size := new System.Drawing.Size(194, 101);
  self.GrpLevels.TabIndex := 1;
  self.GrpLevels.TabStop := false;
  self.GrpLevels.Text := 'Overlays';
  self.ChkQQ2.AutoSize := true;
  self.ChkQQ2.Location := new System.Drawing.Point(8, 80);
  self.ChkQQ2.Name := 'ChkQQ2';
  self.ChkQQ2.Size := new System.Drawing.Size(157, 17);
  self.ChkQQ2.TabIndex := 3;
  self.ChkQQ2.Text := 'QQ&2: QQ Quadratic-Optimal';
  self.ChkQQ2.UseVisualStyleBackColor := true;
  self.ChkQQ2.CheckedChanged += new System.EventHandler(self.ChkLinear_CheckedChanged);
  self.ChkQQ.AutoSize := true;
  self.ChkQQ.Location := new System.Drawing.Point(8, 60);
  self.ChkQQ.Name := 'ChkQQ';
  self.ChkQQ.Size := new System.Drawing.Size(164, 17);
  self.ChkQQ.TabIndex := 2;
  self.ChkQQ.Text := 'QQ&1: Qualitative-Quantitative';
  self.ChkQQ.UseVisualStyleBackColor := true;
  self.ChkQQ.CheckedChanged += new System.EventHandler(self.ChkLinear_CheckedChanged);
  self.ChkMultilinear.AutoSize := true;
  self.ChkMultilinear.Location := new System.Drawing.Point(8, 40);
  self.ChkMultilinear.Name := 'ChkMultilinear';
  self.ChkMultilinear.Size := new System.Drawing.Size(133, 17);
  self.ChkMultilinear.TabIndex := 1;
  self.ChkMultilinear.Text := 'Multilinear &interpolation';
  self.ChkMultilinear.UseVisualStyleBackColor := true;
  self.ChkMultilinear.CheckedChanged += new System.EventHandler(self.ChkLinear_CheckedChanged);
  self.ChkLinear.AutoSize := true;
  self.ChkLinear.Location := new System.Drawing.Point(8, 20);
  self.ChkLinear.Name := 'ChkLinear';
  self.ChkLinear.Size := new System.Drawing.Size(123, 17);
  self.ChkLinear.TabIndex := 0;
  self.ChkLinear.Text := 'Linear &approximation';
  self.ChkLinear.UseVisualStyleBackColor := true;
  self.ChkLinear.CheckedChanged += new System.EventHandler(self.ChkLinear_CheckedChanged);
  self.ChartPicture.Location := new System.Drawing.Point(0, 0);
  self.ChartPicture.Name := 'ChartPicture';
  self.ChartPicture.Size := new System.Drawing.Size(100, 50);
  self.ChartPicture.SizeMode := System.Windows.Forms.PictureBoxSizeMode.StretchImage;
  self.ChartPicture.TabIndex := 0;
  self.ChartPicture.TabStop := false;
  self.ChartPicture.MouseDown += new System.Windows.Forms.MouseEventHandler(self.ChartPicture_MouseDown);
  self.ChartPicture.MouseUp += new System.Windows.Forms.MouseEventHandler(self.ChartPicture_MouseUp);
  self.DlgColor.AnyColor := true;
  self.ChartMenu.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemPopCopyMetafile, self.ItemPopCopyBitmap, self.toolStripSeparator4, self.ItemPopSettings]));
  self.ChartMenu.Name := 'ReportMenu';
  self.ChartMenu.Size := new System.Drawing.Size(163, 76);
  self.ItemPopCopyMetafile.Image := (resources.GetObject('ItemPopCopyMetafile.Image') as System.Drawing.Image);
  self.ItemPopCopyMetafile.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemPopCopyMetafile.Name := 'ItemPopCopyMetafile';
  self.ItemPopCopyMetafile.Size := new System.Drawing.Size(162, 22);
  self.ItemPopCopyMetafile.Text := '&Copy as Metafile';
  self.ItemPopCopyMetafile.ToolTipText := 'Copy report page as a Metafile';
  self.ItemPopCopyMetafile.Click += new System.EventHandler(self.ItemMenuCopyMetafile_Click);
  self.ItemPopCopyBitmap.Image := (resources.GetObject('ItemPopCopyBitmap.Image') as System.Drawing.Image);
  self.ItemPopCopyBitmap.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemPopCopyBitmap.Name := 'ItemPopCopyBitmap';
  self.ItemPopCopyBitmap.Size := new System.Drawing.Size(162, 22);
  self.ItemPopCopyBitmap.Text := 'Copy as &Bitmap';
  self.ItemPopCopyBitmap.ToolTipText := 'Copy report page as a Bitmap';
  self.ItemPopCopyBitmap.Click += new System.EventHandler(self.ItemMenuCopyBitmap_Click);
  self.toolStripSeparator4.Name := 'toolStripSeparator4';
  self.toolStripSeparator4.Size := new System.Drawing.Size(159, 6);
  self.ItemPopSettings.Image := DEXiWin.Properties.Resources.ImgSettings;
  self.ItemPopSettings.Name := 'ItemPopSettings';
  self.ItemPopSettings.Size := new System.Drawing.Size(162, 22);
  self.ItemPopSettings.Text := 'Report settings...';
  self.ChartPanel.AutoScroll := true;
  self.ChartPanel.Controls.Add(self.LblMessage);
  self.ChartPanel.Controls.Add(self.ChartPicture);
  self.ChartPanel.Dock := System.Windows.Forms.DockStyle.Fill;
  self.ChartPanel.Location := new System.Drawing.Point(0, 49);
  self.ChartPanel.Name := 'ChartPanel';
  self.ChartPanel.Size := new System.Drawing.Size(1078, 716);
  self.ChartPanel.TabIndex := 5;
  self.LblMessage.BackColor := System.Drawing.SystemColors.AppWorkspace;
  self.LblMessage.Dock := System.Windows.Forms.DockStyle.Bottom;
  self.LblMessage.Font := new System.Drawing.Font('Microsoft Sans Serif', 8.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (238 as System.Byte));
  self.LblMessage.Location := new System.Drawing.Point(0, 563);
  self.LblMessage.Name := 'LblMessage';
  self.LblMessage.Size := new System.Drawing.Size(1078, 153);
  self.LblMessage.TabIndex := 2;
  self.LblMessage.Text := 'Function chart: Select two dimensions';
  self.LblMessage.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
  self.SaveChartDialog.Filter := 'Metafile|*.emf|Bitmap|*.png';
  self.SaveChartDialog.Title := 'Save chart as';
  self.AutoScroll := true;
  self.ContextMenuStrip := self.ChartMenu;
  self.Controls.Add(self.ChartPanel);
  self.Controls.Add(self.CtrlPanel);
  self.Controls.Add(self.FormTool);
  self.Controls.Add(self.FormMenu);
  self.Name := 'CtrlFormFunctChart';
  self.Size := new System.Drawing.Size(1286, 765);
  self.VisibleChanged += new System.EventHandler(self.CtrlFormFunct_VisibleChanged);
  self.Resize += new System.EventHandler(self.CtrlFormFunct_Resize);
  self.FormTool.ResumeLayout(false);
  self.FormTool.PerformLayout();
  self.FormMenu.ResumeLayout(false);
  self.FormMenu.PerformLayout();
  self.CtrlPanel.ResumeLayout(false);
  self.TabFormat.ResumeLayout(false);
  self.TabDimensions.ResumeLayout(false);
  self.TabChart.ResumeLayout(false);
  self.GrpFonts.ResumeLayout(false);
  self.GrpRotation.ResumeLayout(false);
  self.GrpRotation.PerformLayout();
  (self.EditVertical as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditHorizontal as System.ComponentModel.ISupportInitialize).EndInit();
  self.GrpBorders.ResumeLayout(false);
  self.GrpBorders.PerformLayout();
  (self.EditBorderRight as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditBorderBottom as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditBorderTop as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditBorderLeft as System.ComponentModel.ISupportInitialize).EndInit();
  (self.PicBorders as System.ComponentModel.ISupportInitialize).EndInit();
  self.TabAdvanced.ResumeLayout(false);
  self.GrpLevels.ResumeLayout(false);
  self.GrpLevels.PerformLayout();
  (self.ChartPicture as System.ComponentModel.ISupportInitialize).EndInit();
  self.ChartMenu.ResumeLayout(false);
  self.ChartPanel.ResumeLayout(false);
  self.ResumeLayout(false);
  self.PerformLayout();
end;
{$ENDREGION}

end.