namespace DexiWin;

interface

{$HIDE H7}

uses
  System.Drawing,
  System.Collections,
  System.Windows.Forms,
  System.ComponentModel;

type
  CtrlFormAlternatives = public partial class
  {$REGION Windows Control Designer generated fields}
  private
    ItemPopResetVertical: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuResetVertical: System.Windows.Forms.ToolStripMenuItem;
    ItemPopMoveDown: System.Windows.Forms.ToolStripMenuItem;
    ItemPopMoveUp: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuMoveDown: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuMoveUp: System.Windows.Forms.ToolStripMenuItem;
    ItemToolMoveUp: System.Windows.Forms.ToolStripButton;
    ItemToolMoveDown: System.Windows.Forms.ToolStripButton;
    ItemMenuResizeColumns: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator4: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator8: System.Windows.Forms.ToolStripSeparator;
    AlternativesMenu: System.Windows.Forms.ContextMenuStrip;
    ViewAlternatives: BrightIdeasSoftware.ObjectListView;
    ItemPopEditSeparator1: System.Windows.Forms.ToolStripSeparator;
    ItemPopEditSeparator2: System.Windows.Forms.ToolStripSeparator;
    ItemPopFullRange: System.Windows.Forms.ToolStripMenuItem;
    ItemPopUndefinedValue: System.Windows.Forms.ToolStripMenuItem;
    ItemPopValueEditor: System.Windows.Forms.ToolStripMenuItem;
    ItemPopEditValue: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuValueEditor: System.Windows.Forms.ToolStripMenuItem;
    ItemToolValueEditor: System.Windows.Forms.ToolStripButton;
    ItemMenuEditValue: System.Windows.Forms.ToolStripMenuItem;
    ItemToolEditValue: System.Windows.Forms.ToolStripButton;
    ItemPopDuplicateAlternative: System.Windows.Forms.ToolStripMenuItem;
    ItemPopDeleteAlternative: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuDeleteAlternative: System.Windows.Forms.ToolStripMenuItem;
    ItemPopAddAlternativeLeft: System.Windows.Forms.ToolStripMenuItem;
    ItemPopAddAlternativeRight: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuDuplicateAlternative: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuAddAlternativeLeft: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuAddAlternativeRight: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator18: System.Windows.Forms.ToolStripSeparator;
    ItemPopAltDescr: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuAltDescr: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuMoveRight: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuMoveLeft: System.Windows.Forms.ToolStripMenuItem;
    ItemPopMoveRight: System.Windows.Forms.ToolStripMenuItem;
    ItemPopMoveLeft: System.Windows.Forms.ToolStripMenuItem;
    ItemToolAltDescr: System.Windows.Forms.ToolStripButton;
    ItemToolMoveLeft: System.Windows.Forms.ToolStripButton;
    ItemToolMoveRight: System.Windows.Forms.ToolStripButton;
    ItemToolDuplicateAlternative: System.Windows.Forms.ToolStripButton;
    ItemToolAddAlternativeLeft: System.Windows.Forms.ToolStripButton;
    ItemToolAddAlternativeRight: System.Windows.Forms.ToolStripButton;
    ItemToolDeleteAlternative: System.Windows.Forms.ToolStripButton;
    ItemMenuViewAlternatives: System.Windows.Forms.ToolStripMenuItem;
    ItemViewAltShowAll: System.Windows.Forms.ToolStripMenuItem;
    ItemViewAltHideAll: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator16: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator15: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator11: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator12: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator10: System.Windows.Forms.ToolStripSeparator;
    ItemMenuPaste: System.Windows.Forms.ToolStripMenuItem;
    ItemToolPaste: System.Windows.Forms.ToolStripButton;
    ItemToolCopy: System.Windows.Forms.ToolStripButton;
    ItemMenuCopy: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator7: System.Windows.Forms.ToolStripSeparator;
    ToolTips: System.Windows.Forms.ToolTip;
    ItemMenuViewDescription: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuViewScale: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator2: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator3: System.Windows.Forms.ToolStripSeparator;
    ItemMenuEdit: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator1: System.Windows.Forms.ToolStripSeparator;
    ItemMenuView: System.Windows.Forms.ToolStripMenuItem;
    ItemPopCopy: System.Windows.Forms.ToolStripMenuItem;
    ItemPopPaste: System.Windows.Forms.ToolStripMenuItem;
    ColDescription: BrightIdeasSoftware.OLVColumn;
    ColScale: BrightIdeasSoftware.OLVColumn;
    ColName: BrightIdeasSoftware.OLVColumn;
    FormMenu: System.Windows.Forms.MenuStrip;
    FormTool: System.Windows.Forms.ToolStrip;
    components: System.ComponentModel.Container := nil;
    method InitializeComponent;
  {$ENDREGION}
  end;

implementation

{$REGION Windows Control Designer generated code}
method CtrlFormAlternatives.InitializeComponent;
begin
  self.components := new System.ComponentModel.Container();
  var resources: System.ComponentModel.ComponentResourceManager := new System.ComponentModel.ComponentResourceManager(typeOf(CtrlFormAlternatives));
  self.FormMenu := new System.Windows.Forms.MenuStrip();
  self.ItemMenuEdit := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator8 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuAltDescr := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuEditValue := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuValueEditor := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator18 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuAddAlternativeLeft := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuAddAlternativeRight := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuDeleteAlternative := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuDuplicateAlternative := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator10 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuMoveLeft := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuMoveRight := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuMoveUp := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuMoveDown := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuResetVertical := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator1 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuCopy := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuPaste := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuView := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuResizeColumns := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator4 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuViewDescription := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuViewScale := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuViewAlternatives := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemViewAltShowAll := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemViewAltHideAll := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator16 := new System.Windows.Forms.ToolStripSeparator();
  self.FormTool := new System.Windows.Forms.ToolStrip();
  self.ItemToolAltDescr := new System.Windows.Forms.ToolStripButton();
  self.ItemToolEditValue := new System.Windows.Forms.ToolStripButton();
  self.ItemToolValueEditor := new System.Windows.Forms.ToolStripButton();
  self.toolStripSeparator2 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemToolAddAlternativeLeft := new System.Windows.Forms.ToolStripButton();
  self.ItemToolAddAlternativeRight := new System.Windows.Forms.ToolStripButton();
  self.ItemToolDeleteAlternative := new System.Windows.Forms.ToolStripButton();
  self.ItemToolDuplicateAlternative := new System.Windows.Forms.ToolStripButton();
  self.toolStripSeparator3 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemToolMoveLeft := new System.Windows.Forms.ToolStripButton();
  self.ItemToolMoveRight := new System.Windows.Forms.ToolStripButton();
  self.ItemToolMoveDown := new System.Windows.Forms.ToolStripButton();
  self.ItemToolMoveUp := new System.Windows.Forms.ToolStripButton();
  self.toolStripSeparator7 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemToolCopy := new System.Windows.Forms.ToolStripButton();
  self.ItemToolPaste := new System.Windows.Forms.ToolStripButton();
  self.ViewAlternatives := new BrightIdeasSoftware.ObjectListView();
  self.ColName := (new BrightIdeasSoftware.OLVColumn() as BrightIdeasSoftware.OLVColumn);
  self.ColDescription := (new BrightIdeasSoftware.OLVColumn() as BrightIdeasSoftware.OLVColumn);
  self.ColScale := (new BrightIdeasSoftware.OLVColumn() as BrightIdeasSoftware.OLVColumn);
  self.AlternativesMenu := new System.Windows.Forms.ContextMenuStrip(self.components);
  self.ItemPopEditSeparator1 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopFullRange := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopUndefinedValue := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopEditSeparator2 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopAltDescr := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopEditValue := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopValueEditor := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator12 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopAddAlternativeLeft := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopAddAlternativeRight := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopDeleteAlternative := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopDuplicateAlternative := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator15 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopMoveLeft := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopMoveRight := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopMoveUp := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopMoveDown := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopResetVertical := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator11 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopCopy := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopPaste := new System.Windows.Forms.ToolStripMenuItem();
  self.ToolTips := new System.Windows.Forms.ToolTip(self.components);
  self.FormMenu.SuspendLayout();
  self.FormTool.SuspendLayout();
  (self.ViewAlternatives as System.ComponentModel.ISupportInitialize).BeginInit();
  self.AlternativesMenu.SuspendLayout();
  self.SuspendLayout();
  self.FormMenu.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemMenuEdit, self.ItemMenuView]));
  self.FormMenu.Location := new System.Drawing.Point(0, 0);
  self.FormMenu.Name := 'FormMenu';
  self.FormMenu.Size := new System.Drawing.Size(1332, 24);
  self.FormMenu.TabIndex := 0;
  self.FormMenu.Text := 'menuStrip1';
  self.ItemMenuEdit.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.toolStripSeparator8, self.ItemMenuAltDescr, self.ItemMenuEditValue, self.ItemMenuValueEditor, self.toolStripSeparator18, self.ItemMenuAddAlternativeLeft, self.ItemMenuAddAlternativeRight, self.ItemMenuDeleteAlternative, self.ItemMenuDuplicateAlternative, self.toolStripSeparator10, self.ItemMenuMoveLeft, self.ItemMenuMoveRight, self.ItemMenuMoveUp, self.ItemMenuMoveDown, self.ItemMenuResetVertical, self.toolStripSeparator1, self.ItemMenuCopy, self.ItemMenuPaste]));
  self.ItemMenuEdit.MergeAction := System.Windows.Forms.MergeAction.MatchOnly;
  self.ItemMenuEdit.Name := 'ItemMenuEdit';
  self.ItemMenuEdit.Size := new System.Drawing.Size(39, 20);
  self.ItemMenuEdit.Text := '&Edit';
  self.toolStripSeparator8.Name := 'toolStripSeparator8';
  self.toolStripSeparator8.Size := new System.Drawing.Size(260, 6);
  self.ItemMenuAltDescr.Image := DEXiWin.Properties.Resources.ImgAlternativeDescr;
  self.ItemMenuAltDescr.Name := 'ItemMenuAltDescr';
  self.ItemMenuAltDescr.Size := new System.Drawing.Size(263, 22);
  self.ItemMenuAltDescr.Text := 'Alternative description...';
  self.ItemMenuAltDescr.ToolTipText := 'Edit alternative name and description';
  self.ItemMenuAltDescr.Click += new System.EventHandler(self.ItemToolAltDescr_Click);
  self.ItemMenuEditValue.Image := DEXiWin.Properties.Resources.ImgValueEdit;
  self.ItemMenuEditValue.Name := 'ItemMenuEditValue';
  self.ItemMenuEditValue.ShortcutKeys := System.Windows.Forms.Keys.F2;
  self.ItemMenuEditValue.Size := new System.Drawing.Size(263, 22);
  self.ItemMenuEditValue.Text := 'Edit value';
  self.ItemMenuEditValue.ToolTipText := 'Edit selected value cell';
  self.ItemMenuEditValue.Click += new System.EventHandler(self.ItemToolEditValue_Click);
  self.ItemMenuValueEditor.Image := DEXiWin.Properties.Resources.ImgValueEditMulti;
  self.ItemMenuValueEditor.Name := 'ItemMenuValueEditor';
  self.ItemMenuValueEditor.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.F2 as System.Windows.Forms.Keys);
  self.ItemMenuValueEditor.Size := new System.Drawing.Size(263, 22);
  self.ItemMenuValueEditor.Text := 'Value editor...';
  self.ItemMenuValueEditor.ToolTipText := 'Open value editor';
  self.ItemMenuValueEditor.Click += new System.EventHandler(self.ItemToolValueEditor_Click);
  self.toolStripSeparator18.Name := 'toolStripSeparator18';
  self.toolStripSeparator18.Size := new System.Drawing.Size(260, 6);
  self.ItemMenuAddAlternativeLeft.Image := DEXiWin.Properties.Resources.ImgAlternativeAddLeft;
  self.ItemMenuAddAlternativeLeft.Name := 'ItemMenuAddAlternativeLeft';
  self.ItemMenuAddAlternativeLeft.Size := new System.Drawing.Size(263, 22);
  self.ItemMenuAddAlternativeLeft.Text := 'Add alternative &left';
  self.ItemMenuAddAlternativeLeft.ToolTipText := 'Add  alternative to the left';
  self.ItemMenuAddAlternativeLeft.Click += new System.EventHandler(self.ItemToolAddAlternativeLeft_Click);
  self.ItemMenuAddAlternativeRight.Image := DEXiWin.Properties.Resources.ImgAlternativeAddRight;
  self.ItemMenuAddAlternativeRight.Name := 'ItemMenuAddAlternativeRight';
  self.ItemMenuAddAlternativeRight.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Shift or System.Windows.Forms.Keys.Insert as System.Windows.Forms.Keys);
  self.ItemMenuAddAlternativeRight.Size := new System.Drawing.Size(263, 22);
  self.ItemMenuAddAlternativeRight.Text := 'Add alternative &right';
  self.ItemMenuAddAlternativeRight.ToolTipText := 'Add  alternative to the right';
  self.ItemMenuAddAlternativeRight.Click += new System.EventHandler(self.ItemToolAddAlternativeRight_Click);
  self.ItemMenuDeleteAlternative.Image := DEXiWin.Properties.Resources.ImgAlternativeDelete;
  self.ItemMenuDeleteAlternative.Name := 'ItemMenuDeleteAlternative';
  self.ItemMenuDeleteAlternative.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Shift or System.Windows.Forms.Keys.Delete as System.Windows.Forms.Keys);
  self.ItemMenuDeleteAlternative.Size := new System.Drawing.Size(263, 22);
  self.ItemMenuDeleteAlternative.Text := '&Delete alternative';
  self.ItemMenuDeleteAlternative.ToolTipText := 'Delete selected alternative';
  self.ItemMenuDeleteAlternative.Click += new System.EventHandler(self.ItemToolDeleteAlternative_Click);
  self.ItemMenuDuplicateAlternative.Image := DEXiWin.Properties.Resources.ImgAlternativeDuplicate;
  self.ItemMenuDuplicateAlternative.Name := 'ItemMenuDuplicateAlternative';
  self.ItemMenuDuplicateAlternative.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Shift or System.Windows.Forms.Keys.D as System.Windows.Forms.Keys);
  self.ItemMenuDuplicateAlternative.Size := new System.Drawing.Size(263, 22);
  self.ItemMenuDuplicateAlternative.Text := 'D&uplicate alternative';
  self.ItemMenuDuplicateAlternative.ToolTipText := 'Duplicate selected alternative';
  self.ItemMenuDuplicateAlternative.Click += new System.EventHandler(self.ItemToolDuplicateAlternative_Click);
  self.toolStripSeparator10.Name := 'toolStripSeparator10';
  self.toolStripSeparator10.Size := new System.Drawing.Size(260, 6);
  self.ItemMenuMoveLeft.Image := DEXiWin.Properties.Resources.ImgMoveLeft;
  self.ItemMenuMoveLeft.Name := 'ItemMenuMoveLeft';
  self.ItemMenuMoveLeft.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Shift or System.Windows.Forms.Keys.Left as System.Windows.Forms.Keys);
  self.ItemMenuMoveLeft.Size := new System.Drawing.Size(263, 22);
  self.ItemMenuMoveLeft.Text := 'Move left';
  self.ItemMenuMoveLeft.ToolTipText := 'Move alternative left';
  self.ItemMenuMoveLeft.Click += new System.EventHandler(self.ItemToolMoveLeft_Click);
  self.ItemMenuMoveRight.Image := DEXiWin.Properties.Resources.ImgMoveRight;
  self.ItemMenuMoveRight.Name := 'ItemMenuMoveRight';
  self.ItemMenuMoveRight.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Shift or System.Windows.Forms.Keys.Right as System.Windows.Forms.Keys);
  self.ItemMenuMoveRight.Size := new System.Drawing.Size(263, 22);
  self.ItemMenuMoveRight.Text := 'Move right';
  self.ItemMenuMoveRight.ToolTipText := 'Move alternative right';
  self.ItemMenuMoveRight.Click += new System.EventHandler(self.ItemToolMoveRight_Click);
  self.ItemMenuMoveUp.Image := DEXiWin.Properties.Resources.ImgMoveUp;
  self.ItemMenuMoveUp.Name := 'ItemMenuMoveUp';
  self.ItemMenuMoveUp.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Up as System.Windows.Forms.Keys);
  self.ItemMenuMoveUp.Size := new System.Drawing.Size(263, 22);
  self.ItemMenuMoveUp.Text := 'Move up';
  self.ItemMenuMoveUp.ToolTipText := 'Move input attribute up';
  self.ItemMenuMoveUp.Click += new System.EventHandler(self.ItemToolMoveUp_Click);
  self.ItemMenuMoveDown.Image := DEXiWin.Properties.Resources.ImgMoveDown;
  self.ItemMenuMoveDown.Name := 'ItemMenuMoveDown';
  self.ItemMenuMoveDown.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Down as System.Windows.Forms.Keys);
  self.ItemMenuMoveDown.Size := new System.Drawing.Size(263, 22);
  self.ItemMenuMoveDown.Text := 'Move down';
  self.ItemMenuMoveDown.ToolTipText := 'Move input attribute down';
  self.ItemMenuMoveDown.Click += new System.EventHandler(self.ItemToolMoveDown_Click);
  self.ItemMenuResetVertical.Image := DEXiWin.Properties.Resources.ImgVertReset;
  self.ItemMenuResetVertical.Name := 'ItemMenuResetVertical';
  self.ItemMenuResetVertical.Size := new System.Drawing.Size(263, 22);
  self.ItemMenuResetVertical.Text := 'Reset vertical attribute order';
  self.ItemMenuResetVertical.Click += new System.EventHandler(self.ItemMenuResetVertical_Click);
  self.toolStripSeparator1.Name := 'toolStripSeparator1';
  self.toolStripSeparator1.Size := new System.Drawing.Size(260, 6);
  self.ItemMenuCopy.Image := (resources.GetObject('ItemMenuCopy.Image') as System.Drawing.Image);
  self.ItemMenuCopy.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemMenuCopy.Name := 'ItemMenuCopy';
  self.ItemMenuCopy.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.C as System.Windows.Forms.Keys);
  self.ItemMenuCopy.Size := new System.Drawing.Size(263, 22);
  self.ItemMenuCopy.Text := '&Copy';
  self.ItemMenuCopy.ToolTipText := 'Copy attribute and subtree';
  self.ItemMenuCopy.Click += new System.EventHandler(self.ItemToolCopy_Click);
  self.ItemMenuPaste.Image := (resources.GetObject('ItemMenuPaste.Image') as System.Drawing.Image);
  self.ItemMenuPaste.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemMenuPaste.Name := 'ItemMenuPaste';
  self.ItemMenuPaste.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.V as System.Windows.Forms.Keys);
  self.ItemMenuPaste.Size := new System.Drawing.Size(263, 22);
  self.ItemMenuPaste.Text := '&Paste';
  self.ItemMenuPaste.ToolTipText := 'Paste subtree';
  self.ItemMenuPaste.Click += new System.EventHandler(self.ItemToolPaste_Click);
  self.ItemMenuView.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemMenuResizeColumns, self.toolStripSeparator4, self.ItemMenuViewDescription, self.ItemMenuViewScale, self.ItemMenuViewAlternatives]));
  self.ItemMenuView.MergeAction := System.Windows.Forms.MergeAction.Insert;
  self.ItemMenuView.MergeIndex := 2;
  self.ItemMenuView.Name := 'ItemMenuView';
  self.ItemMenuView.Size := new System.Drawing.Size(44, 20);
  self.ItemMenuView.Text := '&View';
  self.ItemMenuResizeColumns.Name := 'ItemMenuResizeColumns';
  self.ItemMenuResizeColumns.ShortcutKeyDisplayString := 'F8';
  self.ItemMenuResizeColumns.Size := new System.Drawing.Size(174, 22);
  self.ItemMenuResizeColumns.Text := '&Resize columns';
  self.ItemMenuResizeColumns.ToolTipText := 'Resize columns';
  self.ItemMenuResizeColumns.Click += new System.EventHandler(self.ItemMenuResizeColumns_Click);
  self.toolStripSeparator4.Name := 'toolStripSeparator4';
  self.toolStripSeparator4.Size := new System.Drawing.Size(171, 6);
  self.ItemMenuViewDescription.Name := 'ItemMenuViewDescription';
  self.ItemMenuViewDescription.Size := new System.Drawing.Size(174, 22);
  self.ItemMenuViewDescription.Text := '&Description';
  self.ItemMenuViewDescription.Click += new System.EventHandler(self.ItemMenuViewDescription_Click);
  self.ItemMenuViewScale.Name := 'ItemMenuViewScale';
  self.ItemMenuViewScale.Size := new System.Drawing.Size(174, 22);
  self.ItemMenuViewScale.Text := '&Scale';
  self.ItemMenuViewScale.Click += new System.EventHandler(self.ItemMenuViewScale_Click);
  self.ItemMenuViewAlternatives.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemViewAltShowAll, self.ItemViewAltHideAll, self.toolStripSeparator16]));
  self.ItemMenuViewAlternatives.Name := 'ItemMenuViewAlternatives';
  self.ItemMenuViewAlternatives.Size := new System.Drawing.Size(174, 22);
  self.ItemMenuViewAlternatives.Text := '&Alternatives';
  self.ItemViewAltShowAll.Name := 'ItemViewAltShowAll';
  self.ItemViewAltShowAll.Size := new System.Drawing.Size(118, 22);
  self.ItemViewAltShowAll.Text := '&Show all';
  self.ItemViewAltShowAll.Click += new System.EventHandler(self.ItemViewAltShowAll_Click);
  self.ItemViewAltHideAll.Name := 'ItemViewAltHideAll';
  self.ItemViewAltHideAll.Size := new System.Drawing.Size(118, 22);
  self.ItemViewAltHideAll.Text := '&Hide all';
  self.ItemViewAltHideAll.Click += new System.EventHandler(self.ItemViewAltHideAll_Click);
  self.toolStripSeparator16.Name := 'toolStripSeparator16';
  self.toolStripSeparator16.Size := new System.Drawing.Size(115, 6);
  self.FormTool.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemToolAltDescr, self.ItemToolEditValue, self.ItemToolValueEditor, self.toolStripSeparator2, self.ItemToolAddAlternativeLeft, self.ItemToolAddAlternativeRight, self.ItemToolDeleteAlternative, self.ItemToolDuplicateAlternative, self.toolStripSeparator3, self.ItemToolMoveLeft, self.ItemToolMoveRight, self.ItemToolMoveDown, self.ItemToolMoveUp, self.toolStripSeparator7, self.ItemToolCopy, self.ItemToolPaste]));
  self.FormTool.Location := new System.Drawing.Point(0, 24);
  self.FormTool.Name := 'FormTool';
  self.FormTool.Size := new System.Drawing.Size(1332, 25);
  self.FormTool.TabIndex := 1;
  self.FormTool.Text := 'toolStrip1';
  self.ItemToolAltDescr.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolAltDescr.Image := DEXiWin.Properties.Resources.ImgAlternativeDescr;
  self.ItemToolAltDescr.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolAltDescr.Name := 'ItemToolAltDescr';
  self.ItemToolAltDescr.Size := new System.Drawing.Size(23, 22);
  self.ItemToolAltDescr.Text := 'Alternative description ...';
  self.ItemToolAltDescr.ToolTipText := 'Edit alternative name and description';
  self.ItemToolAltDescr.Click += new System.EventHandler(self.ItemToolAltDescr_Click);
  self.ItemToolEditValue.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolEditValue.Image := DEXiWin.Properties.Resources.ImgValueEdit;
  self.ItemToolEditValue.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolEditValue.Name := 'ItemToolEditValue';
  self.ItemToolEditValue.Size := new System.Drawing.Size(23, 22);
  self.ItemToolEditValue.Text := 'Edit value (F2)';
  self.ItemToolEditValue.ToolTipText := 'Edit selected value';
  self.ItemToolEditValue.Click += new System.EventHandler(self.ItemToolEditValue_Click);
  self.ItemToolValueEditor.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolValueEditor.Image := DEXiWin.Properties.Resources.ImgValueEditMulti;
  self.ItemToolValueEditor.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolValueEditor.Name := 'ItemToolValueEditor';
  self.ItemToolValueEditor.Size := new System.Drawing.Size(23, 22);
  self.ItemToolValueEditor.Text := 'Edit value ... (Ctrl-F2)';
  self.ItemToolValueEditor.ToolTipText := 'Open value editor';
  self.ItemToolValueEditor.Click += new System.EventHandler(self.ItemToolValueEditor_Click);
  self.toolStripSeparator2.Name := 'toolStripSeparator2';
  self.toolStripSeparator2.Size := new System.Drawing.Size(6, 25);
  self.ItemToolAddAlternativeLeft.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolAddAlternativeLeft.Image := DEXiWin.Properties.Resources.ImgAlternativeAddLeft;
  self.ItemToolAddAlternativeLeft.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolAddAlternativeLeft.Name := 'ItemToolAddAlternativeLeft';
  self.ItemToolAddAlternativeLeft.Size := new System.Drawing.Size(23, 22);
  self.ItemToolAddAlternativeLeft.Text := 'Add alternative left';
  self.ItemToolAddAlternativeLeft.ToolTipText := 'Add alternative to the left of the selected alternative';
  self.ItemToolAddAlternativeLeft.Click += new System.EventHandler(self.ItemToolAddAlternativeLeft_Click);
  self.ItemToolAddAlternativeRight.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolAddAlternativeRight.Image := DEXiWin.Properties.Resources.ImgAlternativeAddRight;
  self.ItemToolAddAlternativeRight.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolAddAlternativeRight.Name := 'ItemToolAddAlternativeRight';
  self.ItemToolAddAlternativeRight.Size := new System.Drawing.Size(23, 22);
  self.ItemToolAddAlternativeRight.Text := 'Add alternative right';
  self.ItemToolAddAlternativeRight.ToolTipText := 'Add alternative to the right of the selected alternative';
  self.ItemToolAddAlternativeRight.Click += new System.EventHandler(self.ItemToolAddAlternativeRight_Click);
  self.ItemToolDeleteAlternative.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolDeleteAlternative.Image := DEXiWin.Properties.Resources.ImgAlternativeDelete;
  self.ItemToolDeleteAlternative.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolDeleteAlternative.Name := 'ItemToolDeleteAlternative';
  self.ItemToolDeleteAlternative.Size := new System.Drawing.Size(23, 22);
  self.ItemToolDeleteAlternative.Text := 'Delete alternative';
  self.ItemToolDeleteAlternative.ToolTipText := 'Delete selected alternative';
  self.ItemToolDeleteAlternative.Click += new System.EventHandler(self.ItemToolDeleteAlternative_Click);
  self.ItemToolDuplicateAlternative.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolDuplicateAlternative.Image := DEXiWin.Properties.Resources.ImgAlternativeDuplicate;
  self.ItemToolDuplicateAlternative.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolDuplicateAlternative.Name := 'ItemToolDuplicateAlternative';
  self.ItemToolDuplicateAlternative.Size := new System.Drawing.Size(23, 22);
  self.ItemToolDuplicateAlternative.Text := 'Duplicate alternative';
  self.ItemToolDuplicateAlternative.ToolTipText := 'Duplicate selected alternative';
  self.ItemToolDuplicateAlternative.Click += new System.EventHandler(self.ItemToolDuplicateAlternative_Click);
  self.toolStripSeparator3.Name := 'toolStripSeparator3';
  self.toolStripSeparator3.Size := new System.Drawing.Size(6, 25);
  self.ItemToolMoveLeft.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolMoveLeft.Image := DEXiWin.Properties.Resources.ImgMoveLeft;
  self.ItemToolMoveLeft.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolMoveLeft.Name := 'ItemToolMoveLeft';
  self.ItemToolMoveLeft.Size := new System.Drawing.Size(23, 22);
  self.ItemToolMoveLeft.Text := 'Move down';
  self.ItemToolMoveLeft.ToolTipText := 'Move attribute down';
  self.ItemToolMoveLeft.Click += new System.EventHandler(self.ItemToolMoveLeft_Click);
  self.ItemToolMoveRight.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolMoveRight.Image := DEXiWin.Properties.Resources.ImgMoveRight;
  self.ItemToolMoveRight.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolMoveRight.Name := 'ItemToolMoveRight';
  self.ItemToolMoveRight.Size := new System.Drawing.Size(23, 22);
  self.ItemToolMoveRight.Text := 'Move up';
  self.ItemToolMoveRight.ToolTipText := 'Move attribute up';
  self.ItemToolMoveRight.Click += new System.EventHandler(self.ItemToolMoveRight_Click);
  self.ItemToolMoveDown.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolMoveDown.Image := DEXiWin.Properties.Resources.ImgMoveDown;
  self.ItemToolMoveDown.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolMoveDown.Name := 'ItemToolMoveDown';
  self.ItemToolMoveDown.Size := new System.Drawing.Size(23, 22);
  self.ItemToolMoveDown.Text := 'Move down';
  self.ItemToolMoveDown.ToolTipText := 'Move input attribute down';
  self.ItemToolMoveDown.Click += new System.EventHandler(self.ItemToolMoveDown_Click);
  self.ItemToolMoveUp.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolMoveUp.Image := DEXiWin.Properties.Resources.ImgMoveUp;
  self.ItemToolMoveUp.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolMoveUp.Name := 'ItemToolMoveUp';
  self.ItemToolMoveUp.Size := new System.Drawing.Size(23, 22);
  self.ItemToolMoveUp.Text := 'Move up';
  self.ItemToolMoveUp.ToolTipText := 'Move input attribute up';
  self.ItemToolMoveUp.Click += new System.EventHandler(self.ItemToolMoveUp_Click);
  self.toolStripSeparator7.Name := 'toolStripSeparator7';
  self.toolStripSeparator7.Size := new System.Drawing.Size(6, 25);
  self.ItemToolCopy.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolCopy.Image := (resources.GetObject('ItemToolCopy.Image') as System.Drawing.Image);
  self.ItemToolCopy.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolCopy.Name := 'ItemToolCopy';
  self.ItemToolCopy.Size := new System.Drawing.Size(23, 22);
  self.ItemToolCopy.Text := '&Copy';
  self.ItemToolCopy.ToolTipText := 'Copy alternatives';
  self.ItemToolCopy.Click += new System.EventHandler(self.ItemToolCopy_Click);
  self.ItemToolPaste.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolPaste.Image := (resources.GetObject('ItemToolPaste.Image') as System.Drawing.Image);
  self.ItemToolPaste.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolPaste.Name := 'ItemToolPaste';
  self.ItemToolPaste.Size := new System.Drawing.Size(23, 22);
  self.ItemToolPaste.Text := '&Paste';
  self.ItemToolPaste.ToolTipText := 'Paste alternatives';
  self.ItemToolPaste.Click += new System.EventHandler(self.ItemToolPaste_Click);
  self.ViewAlternatives.AllColumns.Add(self.ColName);
  self.ViewAlternatives.AllColumns.Add(self.ColDescription);
  self.ViewAlternatives.AllColumns.Add(self.ColScale);
  self.ViewAlternatives.CellEditActivation := BrightIdeasSoftware.ObjectListView.CellEditActivateMode.DoubleClick;
  self.ViewAlternatives.CellEditUseWholeCell := false;
  self.ViewAlternatives.Columns.AddRange(array of System.Windows.Forms.ColumnHeader([self.ColName]));
  self.ViewAlternatives.ContextMenuStrip := self.AlternativesMenu;
  self.ViewAlternatives.Cursor := System.Windows.Forms.Cursors.Default;
  self.ViewAlternatives.Dock := System.Windows.Forms.DockStyle.Fill;
  self.ViewAlternatives.FullRowSelect := true;
  self.ViewAlternatives.HasCollapsibleGroups := false;
  self.ViewAlternatives.HideSelection := false;
  self.ViewAlternatives.IsSearchOnSortColumn := false;
  self.ViewAlternatives.Location := new System.Drawing.Point(0, 49);
  self.ViewAlternatives.MultiSelect := false;
  self.ViewAlternatives.Name := 'ViewAlternatives';
  self.ViewAlternatives.SelectAllOnControlA := false;
  self.ViewAlternatives.SelectColumnsOnRightClick := false;
  self.ViewAlternatives.SelectColumnsOnRightClickBehaviour := BrightIdeasSoftware.ObjectListView.ColumnSelectBehaviour.None;
  self.ViewAlternatives.ShowGroups := false;
  self.ViewAlternatives.ShowItemToolTips := true;
  self.ViewAlternatives.Size := new System.Drawing.Size(1332, 717);
  self.ViewAlternatives.TabIndex := 2;
  self.ViewAlternatives.UseCellFormatEvents := true;
  self.ViewAlternatives.UseCompatibleStateImageBehavior := false;
  self.ViewAlternatives.View := System.Windows.Forms.View.Details;
  self.ViewAlternatives.CellEditFinished += new BrightIdeasSoftware.CellEditEventHandler(self.ViewAlternatives_CellEditFinished);
  self.ViewAlternatives.CellEditFinishing += new BrightIdeasSoftware.CellEditEventHandler(self.ViewAlternatives_CellEditFinishing);
  self.ViewAlternatives.CellEditStarting += new BrightIdeasSoftware.CellEditEventHandler(self.ViewAlternatives_CellEditStarting);
  self.ViewAlternatives.CellEditValidating += new BrightIdeasSoftware.CellEditEventHandler(self.ViewAlternatives_CellEditValidating);
  self.ViewAlternatives.CellToolTipShowing += new System.EventHandler<BrightIdeasSoftware.ToolTipShowingEventArgs>(self.ViewAlternatives_CellToolTipShowing);
  self.ViewAlternatives.FormatCell += new System.EventHandler<BrightIdeasSoftware.FormatCellEventArgs>(self.ViewAlternatives_FormatCell);
  self.ViewAlternatives.SelectionChanged += new System.EventHandler(self.ViewAlternatives_SelectionChanged);
  self.ViewAlternatives.ColumnClick += new System.Windows.Forms.ColumnClickEventHandler(self.ViewAlternatives_ColumnClick);
  self.ViewAlternatives.Click += new System.EventHandler(self.ViewAlternatives_Click);
  self.ViewAlternatives.KeyDown += new System.Windows.Forms.KeyEventHandler(self.ViewAlternatives_KeyDown);
  self.ViewAlternatives.KeyPress += new System.Windows.Forms.KeyPressEventHandler(self.ViewAlternatives_KeyPress);
  self.ViewAlternatives.MouseClick += new System.Windows.Forms.MouseEventHandler(self.ViewAlternatives_MouseClick);
  self.ViewAlternatives.MouseDoubleClick += new System.Windows.Forms.MouseEventHandler(self.ViewAlternatives_MouseDoubleClick);
  self.ViewAlternatives.MouseDown += new System.Windows.Forms.MouseEventHandler(self.ViewAlternatives_MouseDown);
  self.ColName.AspectName := 'Name';
  self.ColName.AspectToStringFormat := '';
  self.ColName.CellPadding := new System.Drawing.Rectangle(0, 0, -12, 0);
  self.ColName.Groupable := false;
  self.ColName.IsEditable := false;
  self.ColName.MinimumWidth := 100;
  self.ColName.Sortable := false;
  self.ColName.Text := 'Attribute';
  self.ColName.Width := 200;
  self.ColDescription.AspectName := 'Description';
  self.ColDescription.DisplayIndex := 1;
  self.ColDescription.Groupable := false;
  self.ColDescription.IsEditable := false;
  self.ColDescription.IsVisible := false;
  self.ColDescription.MinimumWidth := 100;
  self.ColDescription.Searchable := false;
  self.ColDescription.Sortable := false;
  self.ColDescription.Text := 'Description';
  self.ColDescription.Width := 200;
  self.ColScale.AspectName := 'ScaleComposite';
  self.ColScale.DisplayIndex := 2;
  self.ColScale.Groupable := false;
  self.ColScale.IsEditable := false;
  self.ColScale.IsVisible := false;
  self.ColScale.MinimumWidth := 100;
  self.ColScale.Searchable := false;
  self.ColScale.Sortable := false;
  self.ColScale.Text := 'Scale';
  self.ColScale.Width := 200;
  self.AlternativesMenu.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemPopEditSeparator1, self.ItemPopFullRange, self.ItemPopUndefinedValue, self.ItemPopEditSeparator2, self.ItemPopAltDescr, self.ItemPopEditValue, self.ItemPopValueEditor, self.toolStripSeparator12, self.ItemPopAddAlternativeLeft, self.ItemPopAddAlternativeRight, self.ItemPopDeleteAlternative, self.ItemPopDuplicateAlternative, self.toolStripSeparator15, self.ItemPopMoveLeft, self.ItemPopMoveRight, self.ItemPopMoveUp, self.ItemPopMoveDown, self.ItemPopResetVertical, self.toolStripSeparator11, self.ItemPopCopy, self.ItemPopPaste]));
  self.AlternativesMenu.Name := 'ModelMenu';
  self.AlternativesMenu.Size := new System.Drawing.Size(223, 386);
  self.AlternativesMenu.Opening += new System.ComponentModel.CancelEventHandler(self.AlternativesMenu_Opening);
  self.ItemPopEditSeparator1.Name := 'ItemPopEditSeparator1';
  self.ItemPopEditSeparator1.Size := new System.Drawing.Size(219, 6);
  self.ItemPopFullRange.Name := 'ItemPopFullRange';
  self.ItemPopFullRange.Size := new System.Drawing.Size(222, 22);
  self.ItemPopFullRange.Tag := #48;
  self.ItemPopFullRange.Text := 'Full range (*)';
  self.ItemPopFullRange.ToolTipText := 'Assing full range set to this value';
  self.ItemPopFullRange.Click += new System.EventHandler(self.ItemPopFullRange_Click);
  self.ItemPopUndefinedValue.Name := 'ItemPopUndefinedValue';
  self.ItemPopUndefinedValue.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Delete as System.Windows.Forms.Keys);
  self.ItemPopUndefinedValue.Size := new System.Drawing.Size(222, 22);
  self.ItemPopUndefinedValue.Tag := #48;
  self.ItemPopUndefinedValue.Text := 'Undefined';
  self.ItemPopUndefinedValue.ToolTipText := 'Declare rule value as undefined';
  self.ItemPopUndefinedValue.Click += new System.EventHandler(self.ItemPopUndefinedValue_Click);
  self.ItemPopEditSeparator2.Name := 'ItemPopEditSeparator2';
  self.ItemPopEditSeparator2.Size := new System.Drawing.Size(219, 6);
  self.ItemPopAltDescr.Image := DEXiWin.Properties.Resources.ImgAlternativeDescr;
  self.ItemPopAltDescr.Name := 'ItemPopAltDescr';
  self.ItemPopAltDescr.Size := new System.Drawing.Size(222, 22);
  self.ItemPopAltDescr.Text := 'Alternative description...';
  self.ItemPopAltDescr.ToolTipText := 'Edit alternative name and description';
  self.ItemPopAltDescr.Click += new System.EventHandler(self.ItemToolAltDescr_Click);
  self.ItemPopEditValue.Image := DEXiWin.Properties.Resources.ImgValueEdit;
  self.ItemPopEditValue.Name := 'ItemPopEditValue';
  self.ItemPopEditValue.Size := new System.Drawing.Size(222, 22);
  self.ItemPopEditValue.Text := 'Edit value';
  self.ItemPopEditValue.ToolTipText := 'Edit selected value cell';
  self.ItemPopEditValue.Click += new System.EventHandler(self.ItemToolEditValue_Click);
  self.ItemPopValueEditor.Image := DEXiWin.Properties.Resources.ImgValueEditMulti;
  self.ItemPopValueEditor.Name := 'ItemPopValueEditor';
  self.ItemPopValueEditor.Size := new System.Drawing.Size(222, 22);
  self.ItemPopValueEditor.Text := 'Value editor...';
  self.ItemPopValueEditor.ToolTipText := 'Open value editor';
  self.ItemPopValueEditor.Click += new System.EventHandler(self.ItemToolValueEditor_Click);
  self.toolStripSeparator12.Name := 'toolStripSeparator12';
  self.toolStripSeparator12.Size := new System.Drawing.Size(219, 6);
  self.ItemPopAddAlternativeLeft.Image := DEXiWin.Properties.Resources.ImgAlternativeAddLeft;
  self.ItemPopAddAlternativeLeft.Name := 'ItemPopAddAlternativeLeft';
  self.ItemPopAddAlternativeLeft.Size := new System.Drawing.Size(222, 22);
  self.ItemPopAddAlternativeLeft.Text := 'Add alternative &left';
  self.ItemPopAddAlternativeLeft.ToolTipText := 'Add  alternative to the left';
  self.ItemPopAddAlternativeLeft.Click += new System.EventHandler(self.ItemToolAddAlternativeLeft_Click);
  self.ItemPopAddAlternativeRight.Image := DEXiWin.Properties.Resources.ImgAlternativeAddRight;
  self.ItemPopAddAlternativeRight.Name := 'ItemPopAddAlternativeRight';
  self.ItemPopAddAlternativeRight.Size := new System.Drawing.Size(222, 22);
  self.ItemPopAddAlternativeRight.Text := 'Add alternative &right';
  self.ItemPopAddAlternativeRight.ToolTipText := 'Add  alternative to the right';
  self.ItemPopAddAlternativeRight.Click += new System.EventHandler(self.ItemToolAddAlternativeRight_Click);
  self.ItemPopDeleteAlternative.Image := DEXiWin.Properties.Resources.ImgAlternativeDelete;
  self.ItemPopDeleteAlternative.Name := 'ItemPopDeleteAlternative';
  self.ItemPopDeleteAlternative.Size := new System.Drawing.Size(222, 22);
  self.ItemPopDeleteAlternative.Text := '&Delete alternative';
  self.ItemPopDeleteAlternative.ToolTipText := 'Delete selected alternative';
  self.ItemPopDeleteAlternative.Click += new System.EventHandler(self.ItemToolDeleteAlternative_Click);
  self.ItemPopDuplicateAlternative.Image := DEXiWin.Properties.Resources.ImgAlternativeDuplicate;
  self.ItemPopDuplicateAlternative.Name := 'ItemPopDuplicateAlternative';
  self.ItemPopDuplicateAlternative.Size := new System.Drawing.Size(222, 22);
  self.ItemPopDuplicateAlternative.Text := 'D&uplicate alternative';
  self.ItemPopDuplicateAlternative.ToolTipText := 'Duplicate selected alternative';
  self.ItemPopDuplicateAlternative.Click += new System.EventHandler(self.ItemToolDuplicateAlternative_Click);
  self.toolStripSeparator15.Name := 'toolStripSeparator15';
  self.toolStripSeparator15.Size := new System.Drawing.Size(219, 6);
  self.ItemPopMoveLeft.Image := DEXiWin.Properties.Resources.ImgMoveLeft;
  self.ItemPopMoveLeft.Name := 'ItemPopMoveLeft';
  self.ItemPopMoveLeft.Size := new System.Drawing.Size(222, 22);
  self.ItemPopMoveLeft.Text := 'Move left';
  self.ItemPopMoveLeft.ToolTipText := 'Move alternative left';
  self.ItemPopMoveLeft.Click += new System.EventHandler(self.ItemToolMoveLeft_Click);
  self.ItemPopMoveRight.Image := DEXiWin.Properties.Resources.ImgMoveRight;
  self.ItemPopMoveRight.Name := 'ItemPopMoveRight';
  self.ItemPopMoveRight.Size := new System.Drawing.Size(222, 22);
  self.ItemPopMoveRight.Text := 'Move right';
  self.ItemPopMoveRight.ToolTipText := 'Move alternative right';
  self.ItemPopMoveRight.Click += new System.EventHandler(self.ItemToolMoveRight_Click);
  self.ItemPopMoveUp.Image := DEXiWin.Properties.Resources.ImgMoveUp;
  self.ItemPopMoveUp.Name := 'ItemPopMoveUp';
  self.ItemPopMoveUp.Size := new System.Drawing.Size(222, 22);
  self.ItemPopMoveUp.Text := 'Move up';
  self.ItemPopMoveUp.ToolTipText := 'Move input attribute up';
  self.ItemPopMoveUp.Click += new System.EventHandler(self.ItemToolMoveUp_Click);
  self.ItemPopMoveDown.Image := DEXiWin.Properties.Resources.ImgMoveDown;
  self.ItemPopMoveDown.Name := 'ItemPopMoveDown';
  self.ItemPopMoveDown.Size := new System.Drawing.Size(222, 22);
  self.ItemPopMoveDown.Text := 'Move down';
  self.ItemPopMoveDown.ToolTipText := 'Move input attribute down';
  self.ItemPopMoveDown.Click += new System.EventHandler(self.ItemToolMoveDown_Click);
  self.ItemPopResetVertical.Image := DEXiWin.Properties.Resources.ImgVertReset;
  self.ItemPopResetVertical.Name := 'ItemPopResetVertical';
  self.ItemPopResetVertical.Size := new System.Drawing.Size(222, 22);
  self.ItemPopResetVertical.Text := 'Reset vertical attribute order';
  self.ItemPopResetVertical.Click += new System.EventHandler(self.ItemMenuResetVertical_Click);
  self.toolStripSeparator11.Name := 'toolStripSeparator11';
  self.toolStripSeparator11.Size := new System.Drawing.Size(219, 6);
  self.ItemPopCopy.Image := (resources.GetObject('ItemPopCopy.Image') as System.Drawing.Image);
  self.ItemPopCopy.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemPopCopy.Name := 'ItemPopCopy';
  self.ItemPopCopy.Size := new System.Drawing.Size(222, 22);
  self.ItemPopCopy.Text := '&Copy';
  self.ItemPopCopy.ToolTipText := 'Copy attribute and subtree';
  self.ItemPopCopy.Click += new System.EventHandler(self.ItemToolCopy_Click);
  self.ItemPopPaste.Image := (resources.GetObject('ItemPopPaste.Image') as System.Drawing.Image);
  self.ItemPopPaste.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemPopPaste.Name := 'ItemPopPaste';
  self.ItemPopPaste.Size := new System.Drawing.Size(222, 22);
  self.ItemPopPaste.Text := '&Paste';
  self.ItemPopPaste.ToolTipText := 'Paste subtree';
  self.ItemPopPaste.Click += new System.EventHandler(self.ItemToolPaste_Click);
  self.Controls.Add(self.ViewAlternatives);
  self.Controls.Add(self.FormTool);
  self.Controls.Add(self.FormMenu);
  self.Name := 'CtrlFormAlternatives';
  self.Size := new System.Drawing.Size(1332, 766);
  self.VisibleChanged += new System.EventHandler(self.CtrlFormAlternatives_VisibleChanged);
  self.FormMenu.ResumeLayout(false);
  self.FormMenu.PerformLayout();
  self.FormTool.ResumeLayout(false);
  self.FormTool.PerformLayout();
  (self.ViewAlternatives as System.ComponentModel.ISupportInitialize).EndInit();
  self.AlternativesMenu.ResumeLayout(false);
  self.ResumeLayout(false);
  self.PerformLayout();
end;

{$ENDREGION}

end.