namespace DexiWin;

interface

{$HIDE H7}

uses
  System.Drawing,
  System.Collections,
  System.Windows.Forms,
  System.ComponentModel;

type
  CtrlFormReport = public partial class
  {$REGION Windows Control Designer generated fields}
  private
    ItemPopCropImage: System.Windows.Forms.ToolStripMenuItem;
    ItemPopCropMetafile: System.Windows.Forms.ToolStripMenuItem;
    ItemPopCropBitmap: System.Windows.Forms.ToolStripMenuItem;
    
    
    
    
    
    
    
    
    
    ItemMenuCopyImage: System.Windows.Forms.ToolStripMenuItem;
    
    ItemMenuCropMetafile: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuCropBitmap: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuBrowse: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuEditAddReport: System.Windows.Forms.ToolStripMenuItem;
    FirstFileSeparator: System.Windows.Forms.ToolStripSeparator;
    FirstEditSeparator: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator7: System.Windows.Forms.ToolStripSeparator;
    ItemMenuSave: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuSettings: System.Windows.Forms.ToolStripMenuItem;
    ItemPopSettings: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuPrint: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuPageSetup: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator4: System.Windows.Forms.ToolStripSeparator;
    ItemMenuFile: System.Windows.Forms.ToolStripMenuItem;
    ItemToolSettings: System.Windows.Forms.ToolStripButton;
    toolStripSeparator3: System.Windows.Forms.ToolStripSeparator;
    FontDlg: System.Windows.Forms.FontDialog;
    ItemPopActualSize: System.Windows.Forms.ToolStripMenuItem;
    ItemPopFullPage: System.Windows.Forms.ToolStripMenuItem;
    ItemPopPageWidth: System.Windows.Forms.ToolStripMenuItem;
    ItemPopTwoPages: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator2: System.Windows.Forms.ToolStripSeparator;
    ItemPopCopyBitmap: System.Windows.Forms.ToolStripMenuItem;
    ReportMenu: System.Windows.Forms.ContextMenuStrip;
    ItemMenuZoom10: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuZoomActualSize: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuZoomFullPage: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuZoomPageWidth: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuZoomTwoPages: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator1: System.Windows.Forms.ToolStripSeparator;
    ItemMenuZoom500: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuZoom200: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuZoom150: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuZoom100: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuZoom75: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuZoom50: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuZoom25: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuCopyBitmap: System.Windows.Forms.ToolStripMenuItem;
    PrintDlg: System.Windows.Forms.PrintDialog;
    SaveReportDialog: System.Windows.Forms.SaveFileDialog;
    PanelMessage: System.Windows.Forms.Panel;
    LblMessage: System.Windows.Forms.Label;
    Viewer: DexiWin.CtrlPreview;
    PageSetupDlg: System.Windows.Forms.PageSetupDialog;
    ItemToolBrowse: System.Windows.Forms.ToolStripButton;
    ItemToolFirst: System.Windows.Forms.ToolStripButton;
    ItemToolPrev: System.Windows.Forms.ToolStripButton;
    ItemToolStartPageEdit: System.Windows.Forms.ToolStripTextBox;
    ItemToolPageCountLabel: System.Windows.Forms.ToolStripLabel;
    ItemToolNext: System.Windows.Forms.ToolStripButton;
    ItemToolLast: System.Windows.Forms.ToolStripButton;
    ItemToolSave: System.Windows.Forms.ToolStripButton;
    ItemToolZoom500: System.Windows.Forms.ToolStripMenuItem;
    ItemToolZoom200: System.Windows.Forms.ToolStripMenuItem;
    ItemToolZoom150: System.Windows.Forms.ToolStripMenuItem;
    ItemToolZoom100: System.Windows.Forms.ToolStripMenuItem;
    ItemToolZoom75: System.Windows.Forms.ToolStripMenuItem;
    ItemToolZoom50: System.Windows.Forms.ToolStripMenuItem;
    ItemToolZoom25: System.Windows.Forms.ToolStripMenuItem;
    ItemToolZoom10: System.Windows.Forms.ToolStripMenuItem;
    _separator: System.Windows.Forms.ToolStripSeparator;
    ItemToolZoomActualSize: System.Windows.Forms.ToolStripMenuItem;
    ItemToolZoomFullPage: System.Windows.Forms.ToolStripMenuItem;
    ItemToolZoomPageWidth: System.Windows.Forms.ToolStripMenuItem;
    ItemToolZoomTwoPages: System.Windows.Forms.ToolStripMenuItem;
    ItemToolPageSetup: System.Windows.Forms.ToolStripButton;
    ItemToolZoom: System.Windows.Forms.ToolStripSplitButton;
    ItemToolPrint: System.Windows.Forms.ToolStripButton;
    ItemMenuViewZoom: System.Windows.Forms.ToolStripMenuItem;
    ItemToolCopy: System.Windows.Forms.ToolStripButton;
    ItemMenuCopy: System.Windows.Forms.ToolStripMenuItem;
    ToolTips: System.Windows.Forms.ToolTip;
    ItemMenuEdit: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuView: System.Windows.Forms.ToolStripMenuItem;
    ItemPopCopy: System.Windows.Forms.ToolStripMenuItem;
    FormMenu: System.Windows.Forms.MenuStrip;
    FormTool: System.Windows.Forms.ToolStrip;
    components: System.ComponentModel.Container := nil;
    method InitializeComponent;
  {$ENDREGION}
  end;

implementation

{$REGION Windows Control Designer generated code}
method CtrlFormReport.InitializeComponent;
begin
  self.components := new System.ComponentModel.Container();
  var resources: System.ComponentModel.ComponentResourceManager := new System.ComponentModel.ComponentResourceManager(typeOf(CtrlFormReport));
  self.FormMenu := new System.Windows.Forms.MenuStrip();
  self.ItemMenuFile := new System.Windows.Forms.ToolStripMenuItem();
  self.FirstFileSeparator := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuSave := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuPrint := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuPageSetup := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuEdit := new System.Windows.Forms.ToolStripMenuItem();
  self.FirstEditSeparator := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuSettings := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuEditAddReport := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator7 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuCopyImage := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuCopy := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuCopyBitmap := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuCropMetafile := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuCropBitmap := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuView := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuViewZoom := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuZoomActualSize := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuZoomFullPage := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuZoomPageWidth := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuZoomTwoPages := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator1 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuZoom500 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuZoom200 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuZoom150 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuZoom100 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuZoom75 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuZoom50 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuZoom25 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuZoom10 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuBrowse := new System.Windows.Forms.ToolStripMenuItem();
  self.FormTool := new System.Windows.Forms.ToolStrip();
  self.ItemToolSettings := new System.Windows.Forms.ToolStripButton();
  self.ItemToolPrint := new System.Windows.Forms.ToolStripButton();
  self.ItemToolPageSetup := new System.Windows.Forms.ToolStripButton();
  self.ItemToolZoom := new System.Windows.Forms.ToolStripSplitButton();
  self.ItemToolZoomActualSize := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolZoomFullPage := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolZoomPageWidth := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolZoomTwoPages := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator3 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemToolZoom500 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolZoom200 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolZoom150 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolZoom100 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolZoom75 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolZoom50 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolZoom25 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolZoom10 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolFirst := new System.Windows.Forms.ToolStripButton();
  self.ItemToolPrev := new System.Windows.Forms.ToolStripButton();
  self.ItemToolStartPageEdit := new System.Windows.Forms.ToolStripTextBox();
  self.ItemToolPageCountLabel := new System.Windows.Forms.ToolStripLabel();
  self.ItemToolNext := new System.Windows.Forms.ToolStripButton();
  self.ItemToolLast := new System.Windows.Forms.ToolStripButton();
  self._separator := new System.Windows.Forms.ToolStripSeparator();
  self.ItemToolCopy := new System.Windows.Forms.ToolStripButton();
  self.ItemToolSave := new System.Windows.Forms.ToolStripButton();
  self.ItemToolBrowse := new System.Windows.Forms.ToolStripButton();
  self.ToolTips := new System.Windows.Forms.ToolTip(self.components);
  self.PageSetupDlg := new System.Windows.Forms.PageSetupDialog();
  self.Viewer := new DexiWin.CtrlPreview();
  self.ReportMenu := new System.Windows.Forms.ContextMenuStrip(self.components);
  self.ItemPopActualSize := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopFullPage := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopPageWidth := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopTwoPages := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator2 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopCropImage := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopCopy := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopCopyBitmap := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopCropMetafile := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopCropBitmap := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator4 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopSettings := new System.Windows.Forms.ToolStripMenuItem();
  self.PanelMessage := new System.Windows.Forms.Panel();
  self.LblMessage := new System.Windows.Forms.Label();
  self.SaveReportDialog := new System.Windows.Forms.SaveFileDialog();
  self.PrintDlg := new System.Windows.Forms.PrintDialog();
  self.FontDlg := new System.Windows.Forms.FontDialog();
  self.FormMenu.SuspendLayout();
  self.FormTool.SuspendLayout();
  self.ReportMenu.SuspendLayout();
  self.PanelMessage.SuspendLayout();
  self.SuspendLayout();
  self.FormMenu.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemMenuFile, self.ItemMenuEdit, self.ItemMenuView]));
  self.FormMenu.Location := new System.Drawing.Point(0, 0);
  self.FormMenu.Name := 'FormMenu';
  self.FormMenu.Size := new System.Drawing.Size(1502, 24);
  self.FormMenu.TabIndex := 0;
  self.FormMenu.Text := 'menuStrip1';
  self.FormMenu.ItemClicked += new System.Windows.Forms.ToolStripItemClickedEventHandler(self.FormMenu_ItemClicked);
  self.ItemMenuFile.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.FirstFileSeparator, self.ItemMenuSave, self.ItemMenuPrint, self.ItemMenuPageSetup]));
  self.ItemMenuFile.MergeAction := System.Windows.Forms.MergeAction.MatchOnly;
  self.ItemMenuFile.Name := 'ItemMenuFile';
  self.ItemMenuFile.Size := new System.Drawing.Size(37, 20);
  self.ItemMenuFile.Text := '&File';
  self.FirstFileSeparator.MergeAction := System.Windows.Forms.MergeAction.Insert;
  self.FirstFileSeparator.MergeIndex := 7;
  self.FirstFileSeparator.Name := 'FirstFileSeparator';
  self.FirstFileSeparator.Size := new System.Drawing.Size(139, 6);
  self.ItemMenuSave.Image := DEXiWin.Properties.Resources.PrevSave;
  self.ItemMenuSave.MergeAction := System.Windows.Forms.MergeAction.Insert;
  self.ItemMenuSave.MergeIndex := 8;
  self.ItemMenuSave.Name := 'ItemMenuSave';
  self.ItemMenuSave.Size := new System.Drawing.Size(142, 22);
  self.ItemMenuSave.Text := 'Save &report...';
  self.ItemMenuSave.Click += new System.EventHandler(self.ItemToolSave_Click);
  self.ItemMenuPrint.Image := (resources.GetObject('ItemMenuPrint.Image') as System.Drawing.Image);
  self.ItemMenuPrint.MergeAction := System.Windows.Forms.MergeAction.Insert;
  self.ItemMenuPrint.MergeIndex := 9;
  self.ItemMenuPrint.Name := 'ItemMenuPrint';
  self.ItemMenuPrint.Size := new System.Drawing.Size(142, 22);
  self.ItemMenuPrint.Text := '&Print...';
  self.ItemMenuPrint.Click += new System.EventHandler(self.ItemToolPrint_Click);
  self.ItemMenuPageSetup.Image := (resources.GetObject('ItemMenuPageSetup.Image') as System.Drawing.Image);
  self.ItemMenuPageSetup.MergeAction := System.Windows.Forms.MergeAction.Insert;
  self.ItemMenuPageSetup.MergeIndex := 10;
  self.ItemMenuPageSetup.Name := 'ItemMenuPageSetup';
  self.ItemMenuPageSetup.Size := new System.Drawing.Size(142, 22);
  self.ItemMenuPageSetup.Text := 'Page &setup...';
  self.ItemMenuPageSetup.Click += new System.EventHandler(self.ItemToolPageSetup_Click);
  self.ItemMenuEdit.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.FirstEditSeparator, self.ItemMenuSettings, self.ItemMenuEditAddReport, self.toolStripSeparator7, self.ItemMenuCopyImage]));
  self.ItemMenuEdit.MergeAction := System.Windows.Forms.MergeAction.MatchOnly;
  self.ItemMenuEdit.Name := 'ItemMenuEdit';
  self.ItemMenuEdit.Size := new System.Drawing.Size(39, 20);
  self.ItemMenuEdit.Text := '&Edit';
  self.FirstEditSeparator.Name := 'FirstEditSeparator';
  self.FirstEditSeparator.Size := new System.Drawing.Size(177, 6);
  self.ItemMenuSettings.Image := (resources.GetObject('ItemMenuSettings.Image') as System.Drawing.Image);
  self.ItemMenuSettings.MergeAction := System.Windows.Forms.MergeAction.Insert;
  self.ItemMenuSettings.MergeIndex := 7;
  self.ItemMenuSettings.Name := 'ItemMenuSettings';
  self.ItemMenuSettings.Size := new System.Drawing.Size(180, 22);
  self.ItemMenuSettings.Text := '&Report parameters...';
  self.ItemMenuSettings.Click += new System.EventHandler(self.ItemToolSettings_Click);
  self.ItemMenuEditAddReport.Name := 'ItemMenuEditAddReport';
  self.ItemMenuEditAddReport.Size := new System.Drawing.Size(180, 22);
  self.ItemMenuEditAddReport.Text := '&Add to Report';
  self.ItemMenuEditAddReport.ToolTipText := 'Add this report as a section to the main Report tab';
  self.ItemMenuEditAddReport.Click += new System.EventHandler(self.ItemMenuEditAddReport_Click);
  self.toolStripSeparator7.Name := 'toolStripSeparator7';
  self.toolStripSeparator7.Size := new System.Drawing.Size(177, 6);
  self.ItemMenuCopyImage.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemMenuCopy, self.ItemMenuCopyBitmap, self.ItemMenuCropMetafile, self.ItemMenuCropBitmap]));
  self.ItemMenuCopyImage.Image := DEXiWin.Properties.Resources.PrevCopy;
  self.ItemMenuCopyImage.Name := 'ItemMenuCopyImage';
  self.ItemMenuCopyImage.Size := new System.Drawing.Size(180, 22);
  self.ItemMenuCopyImage.Text := 'Copy report page...';
  self.ItemMenuCopyImage.ToolTipText := 'Copy current report page to an image';
  self.ItemMenuCopy.Image := DEXiWin.Properties.Resources.PrevCopyMetafile;
  self.ItemMenuCopy.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemMenuCopy.Name := 'ItemMenuCopy';
  self.ItemMenuCopy.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.C as System.Windows.Forms.Keys);
  self.ItemMenuCopy.Size := new System.Drawing.Size(252, 22);
  self.ItemMenuCopy.Text := '&Copy as metafile';
  self.ItemMenuCopy.ToolTipText := 'Copy report page as a metafile';
  self.ItemMenuCopy.Click += new System.EventHandler(self.ItemToolCopy_Click);
  self.ItemMenuCopyBitmap.Image := DEXiWin.Properties.Resources.PrevCopyBitmap;
  self.ItemMenuCopyBitmap.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemMenuCopyBitmap.Name := 'ItemMenuCopyBitmap';
  self.ItemMenuCopyBitmap.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Shift or System.Windows.Forms.Keys.C as System.Windows.Forms.Keys);
  self.ItemMenuCopyBitmap.Size := new System.Drawing.Size(252, 22);
  self.ItemMenuCopyBitmap.Text := 'Copy as &bitmap';
  self.ItemMenuCopyBitmap.ToolTipText := 'Copy report page as a bitmap';
  self.ItemMenuCopyBitmap.Click += new System.EventHandler(self.ItemMenuCopyBitmap_Click);
  self.ItemMenuCropMetafile.Name := 'ItemMenuCropMetafile';
  self.ItemMenuCropMetafile.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Alt or System.Windows.Forms.Keys.C as System.Windows.Forms.Keys);
  self.ItemMenuCropMetafile.Size := new System.Drawing.Size(252, 22);
  self.ItemMenuCropMetafile.Text := 'Cro&p to metafile';
  self.ItemMenuCropMetafile.ToolTipText := 'Copy report page as a metafile and crop it to useful contents';
  self.ItemMenuCropMetafile.Click += new System.EventHandler(self.ItemMenuCropMetafile_Click);
  self.ItemMenuCropBitmap.Name := 'ItemMenuCropBitmap';
  self.ItemMenuCropBitmap.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Alt or System.Windows.Forms.Keys.Shift or System.Windows.Forms.Keys.C as System.Windows.Forms.Keys);
  self.ItemMenuCropBitmap.Size := new System.Drawing.Size(252, 22);
  self.ItemMenuCropBitmap.Text := 'Crop to bitmap';
  self.ItemMenuCropBitmap.ToolTipText := 'Copy report page as a bitmap and crop it to useful contents';
  self.ItemMenuCropBitmap.Click += new System.EventHandler(self.ItemMenuCropBitmap_Click);
  self.ItemMenuView.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemMenuViewZoom, self.ItemMenuBrowse]));
  self.ItemMenuView.MergeAction := System.Windows.Forms.MergeAction.Insert;
  self.ItemMenuView.MergeIndex := 2;
  self.ItemMenuView.Name := 'ItemMenuView';
  self.ItemMenuView.Size := new System.Drawing.Size(44, 20);
  self.ItemMenuView.Text := '&View';
  self.ItemMenuViewZoom.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemMenuZoomActualSize, self.ItemMenuZoomFullPage, self.ItemMenuZoomPageWidth, self.ItemMenuZoomTwoPages, self.toolStripSeparator1, self.ItemMenuZoom500, self.ItemMenuZoom200, self.ItemMenuZoom150, self.ItemMenuZoom100, self.ItemMenuZoom75, self.ItemMenuZoom50, self.ItemMenuZoom25, self.ItemMenuZoom10]));
  self.ItemMenuViewZoom.Image := DEXiWin.Properties.Resources.PrevZoom;
  self.ItemMenuViewZoom.Name := 'ItemMenuViewZoom';
  self.ItemMenuViewZoom.Size := new System.Drawing.Size(170, 22);
  self.ItemMenuViewZoom.Text := '&Zoom';
  self.ItemMenuViewZoom.DropDownItemClicked += new System.Windows.Forms.ToolStripItemClickedEventHandler(self.ItemToolZoom_DropDownItemClicked);
  self.ItemMenuZoomActualSize.Image := (resources.GetObject('ItemMenuZoomActualSize.Image') as System.Drawing.Image);
  self.ItemMenuZoomActualSize.Name := 'ItemMenuZoomActualSize';
  self.ItemMenuZoomActualSize.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.D0 as System.Windows.Forms.Keys);
  self.ItemMenuZoomActualSize.Size := new System.Drawing.Size(171, 22);
  self.ItemMenuZoomActualSize.Text := 'Actual Size';
  self.ItemMenuZoomFullPage.Image := (resources.GetObject('ItemMenuZoomFullPage.Image') as System.Drawing.Image);
  self.ItemMenuZoomFullPage.Name := 'ItemMenuZoomFullPage';
  self.ItemMenuZoomFullPage.Size := new System.Drawing.Size(171, 22);
  self.ItemMenuZoomFullPage.Text := 'Full Page';
  self.ItemMenuZoomPageWidth.Image := (resources.GetObject('ItemMenuZoomPageWidth.Image') as System.Drawing.Image);
  self.ItemMenuZoomPageWidth.Name := 'ItemMenuZoomPageWidth';
  self.ItemMenuZoomPageWidth.Size := new System.Drawing.Size(171, 22);
  self.ItemMenuZoomPageWidth.Text := 'Page Width';
  self.ItemMenuZoomTwoPages.Image := (resources.GetObject('ItemMenuZoomTwoPages.Image') as System.Drawing.Image);
  self.ItemMenuZoomTwoPages.Name := 'ItemMenuZoomTwoPages';
  self.ItemMenuZoomTwoPages.Size := new System.Drawing.Size(171, 22);
  self.ItemMenuZoomTwoPages.Text := 'Two Pages';
  self.toolStripSeparator1.Name := 'toolStripSeparator1';
  self.toolStripSeparator1.Size := new System.Drawing.Size(168, 6);
  self.ItemMenuZoom500.Name := 'ItemMenuZoom500';
  self.ItemMenuZoom500.Size := new System.Drawing.Size(171, 22);
  self.ItemMenuZoom500.Text := '500%';
  self.ItemMenuZoom200.Name := 'ItemMenuZoom200';
  self.ItemMenuZoom200.Size := new System.Drawing.Size(171, 22);
  self.ItemMenuZoom200.Text := '200%';
  self.ItemMenuZoom150.Name := 'ItemMenuZoom150';
  self.ItemMenuZoom150.Size := new System.Drawing.Size(171, 22);
  self.ItemMenuZoom150.Text := '150%';
  self.ItemMenuZoom100.Name := 'ItemMenuZoom100';
  self.ItemMenuZoom100.Size := new System.Drawing.Size(171, 22);
  self.ItemMenuZoom100.Text := '100%';
  self.ItemMenuZoom75.Name := 'ItemMenuZoom75';
  self.ItemMenuZoom75.Size := new System.Drawing.Size(171, 22);
  self.ItemMenuZoom75.Text := '75%';
  self.ItemMenuZoom50.Name := 'ItemMenuZoom50';
  self.ItemMenuZoom50.Size := new System.Drawing.Size(171, 22);
  self.ItemMenuZoom50.Text := '50%';
  self.ItemMenuZoom25.Name := 'ItemMenuZoom25';
  self.ItemMenuZoom25.Size := new System.Drawing.Size(171, 22);
  self.ItemMenuZoom25.Text := '25%';
  self.ItemMenuZoom10.Name := 'ItemMenuZoom10';
  self.ItemMenuZoom10.Size := new System.Drawing.Size(171, 22);
  self.ItemMenuZoom10.Text := '10%';
  self.ItemMenuBrowse.Image := DEXiWin.Properties.Resources.PrevBrowse;
  self.ItemMenuBrowse.Name := 'ItemMenuBrowse';
  self.ItemMenuBrowse.Size := new System.Drawing.Size(170, 22);
  self.ItemMenuBrowse.Text := 'Open in browser...';
  self.ItemMenuBrowse.Click += new System.EventHandler(self.ItemToolBrowse_Click);
  self.FormTool.ImeMode := System.Windows.Forms.ImeMode.Off;
  self.FormTool.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemToolSettings, self.ItemToolPrint, self.ItemToolPageSetup, self.ItemToolZoom, self.ItemToolFirst, self.ItemToolPrev, self.ItemToolStartPageEdit, self.ItemToolPageCountLabel, self.ItemToolNext, self.ItemToolLast, self._separator, self.ItemToolCopy, self.ItemToolSave, self.ItemToolBrowse]));
  self.FormTool.Location := new System.Drawing.Point(0, 24);
  self.FormTool.Name := 'FormTool';
  self.FormTool.Size := new System.Drawing.Size(1502, 25);
  self.FormTool.TabIndex := 1;
  self.FormTool.Text := 'toolStrip1';
  self.ItemToolSettings.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolSettings.Image := (resources.GetObject('ItemToolSettings.Image') as System.Drawing.Image);
  self.ItemToolSettings.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolSettings.Name := 'ItemToolSettings';
  self.ItemToolSettings.Size := new System.Drawing.Size(23, 22);
  self.ItemToolSettings.Text := 'Report parameters';
  self.ItemToolSettings.Click += new System.EventHandler(self.ItemToolSettings_Click);
  self.ItemToolPrint.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolPrint.Image := (resources.GetObject('ItemToolPrint.Image') as System.Drawing.Image);
  self.ItemToolPrint.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolPrint.Name := 'ItemToolPrint';
  self.ItemToolPrint.Size := new System.Drawing.Size(23, 22);
  self.ItemToolPrint.Text := 'Print';
  self.ItemToolPrint.ToolTipText := 'Print report';
  self.ItemToolPrint.Click += new System.EventHandler(self.ItemToolPrint_Click);
  self.ItemToolPageSetup.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolPageSetup.Image := (resources.GetObject('ItemToolPageSetup.Image') as System.Drawing.Image);
  self.ItemToolPageSetup.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolPageSetup.Name := 'ItemToolPageSetup';
  self.ItemToolPageSetup.Size := new System.Drawing.Size(23, 22);
  self.ItemToolPageSetup.Text := 'Page setup';
  self.ItemToolPageSetup.ToolTipText := 'Set page dimensions';
  self.ItemToolPageSetup.Click += new System.EventHandler(self.ItemToolPageSetup_Click);
  self.ItemToolZoom.AutoToolTip := false;
  self.ItemToolZoom.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemToolZoomActualSize, self.ItemToolZoomFullPage, self.ItemToolZoomPageWidth, self.ItemToolZoomTwoPages, self.toolStripSeparator3, self.ItemToolZoom500, self.ItemToolZoom200, self.ItemToolZoom150, self.ItemToolZoom100, self.ItemToolZoom75, self.ItemToolZoom50, self.ItemToolZoom25, self.ItemToolZoom10]));
  self.ItemToolZoom.Image := (resources.GetObject('ItemToolZoom.Image') as System.Drawing.Image);
  self.ItemToolZoom.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolZoom.Name := 'ItemToolZoom';
  self.ItemToolZoom.Size := new System.Drawing.Size(71, 22);
  self.ItemToolZoom.Text := '&Zoom';
  self.ItemToolZoom.ToolTipText := 'Zoom';
  self.ItemToolZoom.ButtonClick += new System.EventHandler(self.ItemToolZoom_ButtonClick);
  self.ItemToolZoom.DropDownItemClicked += new System.Windows.Forms.ToolStripItemClickedEventHandler(self.ItemToolZoom_DropDownItemClicked);
  self.ItemToolZoomActualSize.Image := (resources.GetObject('ItemToolZoomActualSize.Image') as System.Drawing.Image);
  self.ItemToolZoomActualSize.Name := 'ItemToolZoomActualSize';
  self.ItemToolZoomActualSize.Size := new System.Drawing.Size(135, 22);
  self.ItemToolZoomActualSize.Text := 'Actual Size';
  self.ItemToolZoomFullPage.Image := (resources.GetObject('ItemToolZoomFullPage.Image') as System.Drawing.Image);
  self.ItemToolZoomFullPage.Name := 'ItemToolZoomFullPage';
  self.ItemToolZoomFullPage.Size := new System.Drawing.Size(135, 22);
  self.ItemToolZoomFullPage.Text := 'Full Page';
  self.ItemToolZoomPageWidth.Image := (resources.GetObject('ItemToolZoomPageWidth.Image') as System.Drawing.Image);
  self.ItemToolZoomPageWidth.Name := 'ItemToolZoomPageWidth';
  self.ItemToolZoomPageWidth.Size := new System.Drawing.Size(135, 22);
  self.ItemToolZoomPageWidth.Text := 'Page Width';
  self.ItemToolZoomTwoPages.Image := (resources.GetObject('ItemToolZoomTwoPages.Image') as System.Drawing.Image);
  self.ItemToolZoomTwoPages.Name := 'ItemToolZoomTwoPages';
  self.ItemToolZoomTwoPages.Size := new System.Drawing.Size(135, 22);
  self.ItemToolZoomTwoPages.Text := 'Two Pages';
  self.toolStripSeparator3.Name := 'toolStripSeparator3';
  self.toolStripSeparator3.Size := new System.Drawing.Size(132, 6);
  self.ItemToolZoom500.Name := 'ItemToolZoom500';
  self.ItemToolZoom500.Size := new System.Drawing.Size(135, 22);
  self.ItemToolZoom500.Text := '500%';
  self.ItemToolZoom200.Name := 'ItemToolZoom200';
  self.ItemToolZoom200.Size := new System.Drawing.Size(135, 22);
  self.ItemToolZoom200.Text := '200%';
  self.ItemToolZoom150.Name := 'ItemToolZoom150';
  self.ItemToolZoom150.Size := new System.Drawing.Size(135, 22);
  self.ItemToolZoom150.Text := '150%';
  self.ItemToolZoom100.Name := 'ItemToolZoom100';
  self.ItemToolZoom100.Size := new System.Drawing.Size(135, 22);
  self.ItemToolZoom100.Text := '100%';
  self.ItemToolZoom75.Name := 'ItemToolZoom75';
  self.ItemToolZoom75.Size := new System.Drawing.Size(135, 22);
  self.ItemToolZoom75.Text := '75%';
  self.ItemToolZoom50.Name := 'ItemToolZoom50';
  self.ItemToolZoom50.Size := new System.Drawing.Size(135, 22);
  self.ItemToolZoom50.Text := '50%';
  self.ItemToolZoom25.Name := 'ItemToolZoom25';
  self.ItemToolZoom25.Size := new System.Drawing.Size(135, 22);
  self.ItemToolZoom25.Text := '25%';
  self.ItemToolZoom10.Name := 'ItemToolZoom10';
  self.ItemToolZoom10.Size := new System.Drawing.Size(135, 22);
  self.ItemToolZoom10.Text := '10%';
  self.ItemToolFirst.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolFirst.Image := (resources.GetObject('ItemToolFirst.Image') as System.Drawing.Image);
  self.ItemToolFirst.ImageTransparentColor := System.Drawing.Color.Red;
  self.ItemToolFirst.Name := 'ItemToolFirst';
  self.ItemToolFirst.Size := new System.Drawing.Size(23, 22);
  self.ItemToolFirst.Text := 'First Page';
  self.ItemToolFirst.Click += new System.EventHandler(self.ItemToolFirst_Click);
  self.ItemToolPrev.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolPrev.Image := (resources.GetObject('ItemToolPrev.Image') as System.Drawing.Image);
  self.ItemToolPrev.ImageTransparentColor := System.Drawing.Color.Red;
  self.ItemToolPrev.Name := 'ItemToolPrev';
  self.ItemToolPrev.Size := new System.Drawing.Size(23, 22);
  self.ItemToolPrev.Text := 'Previous Page';
  self.ItemToolPrev.Click += new System.EventHandler(self.ItemToolPrev_Click);
  self.ItemToolStartPageEdit.AutoSize := false;
  self.ItemToolStartPageEdit.Name := 'ItemToolStartPageEdit';
  self.ItemToolStartPageEdit.Size := new System.Drawing.Size(32, 23);
  self.ItemToolStartPageEdit.TextBoxTextAlign := System.Windows.Forms.HorizontalAlignment.Center;
  self.ItemToolStartPageEdit.Enter += new System.EventHandler(self.ItemToolStartPageEdit_Enter);
  self.ItemToolStartPageEdit.Leave += new System.EventHandler(self.ItemToolStartPageEdit_Leave);
  self.ItemToolStartPageEdit.KeyPress += new System.Windows.Forms.KeyPressEventHandler(self.ItemToolStartPageEdit_KeyPress);
  self.ItemToolStartPageEdit.Validating += new System.ComponentModel.CancelEventHandler(self.ItemToolStartPageEdit_Validating);
  self.ItemToolStartPageEdit.Validated += new System.EventHandler(self.ItemToolStartPageEdit_Validated);
  self.ItemToolPageCountLabel.Name := 'ItemToolPageCountLabel';
  self.ItemToolPageCountLabel.Size := new System.Drawing.Size(10, 22);
  self.ItemToolPageCountLabel.Text := ' ';
  self.ItemToolNext.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolNext.Image := (resources.GetObject('ItemToolNext.Image') as System.Drawing.Image);
  self.ItemToolNext.ImageTransparentColor := System.Drawing.Color.Red;
  self.ItemToolNext.Name := 'ItemToolNext';
  self.ItemToolNext.Size := new System.Drawing.Size(23, 22);
  self.ItemToolNext.Text := 'Next Page';
  self.ItemToolNext.Click += new System.EventHandler(self.ItemToolNext_Click);
  self.ItemToolLast.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolLast.Image := (resources.GetObject('ItemToolLast.Image') as System.Drawing.Image);
  self.ItemToolLast.ImageTransparentColor := System.Drawing.Color.Red;
  self.ItemToolLast.Name := 'ItemToolLast';
  self.ItemToolLast.Size := new System.Drawing.Size(23, 22);
  self.ItemToolLast.Text := 'Last Page';
  self.ItemToolLast.Click += new System.EventHandler(self.ItemToolLast_Click);
  self._separator.Name := '_separator';
  self._separator.Size := new System.Drawing.Size(6, 25);
  self._separator.Visible := false;
  self.ItemToolCopy.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolCopy.Image := DEXiWin.Properties.Resources.PrevCopyMetafile;
  self.ItemToolCopy.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolCopy.Name := 'ItemToolCopy';
  self.ItemToolCopy.Size := new System.Drawing.Size(23, 22);
  self.ItemToolCopy.Text := '&Copy';
  self.ItemToolCopy.ToolTipText := 'Copy report page';
  self.ItemToolCopy.Click += new System.EventHandler(self.ItemToolCopy_Click);
  self.ItemToolSave.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolSave.Image := (resources.GetObject('ItemToolSave.Image') as System.Drawing.Image);
  self.ItemToolSave.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolSave.Name := 'ItemToolSave';
  self.ItemToolSave.Size := new System.Drawing.Size(23, 22);
  self.ItemToolSave.Text := 'Save';
  self.ItemToolSave.ToolTipText := 'Save report';
  self.ItemToolSave.Click += new System.EventHandler(self.ItemToolSave_Click);
  self.ItemToolBrowse.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolBrowse.Image := (resources.GetObject('ItemToolBrowse.Image') as System.Drawing.Image);
  self.ItemToolBrowse.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolBrowse.Name := 'ItemToolBrowse';
  self.ItemToolBrowse.Size := new System.Drawing.Size(23, 22);
  self.ItemToolBrowse.Text := 'Browse';
  self.ItemToolBrowse.ToolTipText := 'Open report in browser';
  self.ItemToolBrowse.Click += new System.EventHandler(self.ItemToolBrowse_Click);
  self.PageSetupDlg.EnableMetric := true;
  self.Viewer.AutoScroll := true;
  self.Viewer.AutoScrollMinSize := new System.Drawing.Size(0, 8);
  self.Viewer.ContextMenuStrip := self.ReportMenu;
  self.Viewer.Dock := System.Windows.Forms.DockStyle.Fill;
  self.Viewer.Document := nil;
  self.Viewer.Location := new System.Drawing.Point(0, 49);
  self.Viewer.Name := 'Viewer';
  self.Viewer.Size := new System.Drawing.Size(1502, 717);
  self.Viewer.TabIndex := 2;
  self.Viewer.StartPageChanged += new System.EventHandler(self.Viewer_StartPageChanged);
  self.ReportMenu.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemPopActualSize, self.ItemPopFullPage, self.ItemPopPageWidth, self.ItemPopTwoPages, self.toolStripSeparator2, self.ItemPopCropImage, self.toolStripSeparator4, self.ItemPopSettings]));
  self.ReportMenu.Name := 'ReportMenu';
  self.ReportMenu.Size := new System.Drawing.Size(181, 148);
  self.ItemPopActualSize.Image := (resources.GetObject('ItemPopActualSize.Image') as System.Drawing.Image);
  self.ItemPopActualSize.Name := 'ItemPopActualSize';
  self.ItemPopActualSize.Size := new System.Drawing.Size(180, 22);
  self.ItemPopActualSize.Text := 'Actual Size';
  self.ItemPopActualSize.Click += new System.EventHandler(self.ItemPopActualSize_Click);
  self.ItemPopFullPage.Image := (resources.GetObject('ItemPopFullPage.Image') as System.Drawing.Image);
  self.ItemPopFullPage.Name := 'ItemPopFullPage';
  self.ItemPopFullPage.Size := new System.Drawing.Size(180, 22);
  self.ItemPopFullPage.Text := 'Full Page';
  self.ItemPopFullPage.Click += new System.EventHandler(self.ItemPopFullPage_Click);
  self.ItemPopPageWidth.Image := (resources.GetObject('ItemPopPageWidth.Image') as System.Drawing.Image);
  self.ItemPopPageWidth.Name := 'ItemPopPageWidth';
  self.ItemPopPageWidth.Size := new System.Drawing.Size(180, 22);
  self.ItemPopPageWidth.Text := 'Page Width';
  self.ItemPopPageWidth.Click += new System.EventHandler(self.ItemPopPageWidth_Click);
  self.ItemPopTwoPages.Image := (resources.GetObject('ItemPopTwoPages.Image') as System.Drawing.Image);
  self.ItemPopTwoPages.Name := 'ItemPopTwoPages';
  self.ItemPopTwoPages.Size := new System.Drawing.Size(180, 22);
  self.ItemPopTwoPages.Text := 'Two Pages';
  self.ItemPopTwoPages.Click += new System.EventHandler(self.ItemPopTwoPages_Click);
  self.toolStripSeparator2.Name := 'toolStripSeparator2';
  self.toolStripSeparator2.Size := new System.Drawing.Size(177, 6);
  self.ItemPopCropImage.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemPopCopy, self.ItemPopCopyBitmap, self.ItemPopCropMetafile, self.ItemPopCropBitmap]));
  self.ItemPopCropImage.Image := DEXiWin.Properties.Resources.PrevCopy;
  self.ItemPopCropImage.Name := 'ItemPopCropImage';
  self.ItemPopCropImage.Size := new System.Drawing.Size(180, 22);
  self.ItemPopCropImage.Text := 'Copy report page...';
  self.ItemPopCropImage.ToolTipText := 'Copy current report page to an image';
  self.ItemPopCopy.Image := DEXiWin.Properties.Resources.PrevCopyMetafile;
  self.ItemPopCopy.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemPopCopy.Name := 'ItemPopCopy';
  self.ItemPopCopy.Size := new System.Drawing.Size(162, 22);
  self.ItemPopCopy.Text := '&Copy as metafile';
  self.ItemPopCopy.ToolTipText := 'Copy report page as a metafile';
  self.ItemPopCopy.Click += new System.EventHandler(self.ItemToolCopy_Click);
  self.ItemPopCopyBitmap.Image := DEXiWin.Properties.Resources.PrevCopyBitmap;
  self.ItemPopCopyBitmap.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemPopCopyBitmap.Name := 'ItemPopCopyBitmap';
  self.ItemPopCopyBitmap.Size := new System.Drawing.Size(162, 22);
  self.ItemPopCopyBitmap.Text := 'Copy as &bitmap';
  self.ItemPopCopyBitmap.ToolTipText := 'Copy report page as a bitmap';
  self.ItemPopCopyBitmap.Click += new System.EventHandler(self.ItemMenuCopyBitmap_Click);
  self.ItemPopCropMetafile.Name := 'ItemPopCropMetafile';
  self.ItemPopCropMetafile.Size := new System.Drawing.Size(162, 22);
  self.ItemPopCropMetafile.Text := 'Cro&p to metafile';
  self.ItemPopCropMetafile.ToolTipText := 'Copy report page as a metafile and crop it to useful contents';
  self.ItemPopCropMetafile.Click += new System.EventHandler(self.ItemMenuCropMetafile_Click);
  self.ItemPopCropBitmap.Name := 'ItemPopCropBitmap';
  self.ItemPopCropBitmap.Size := new System.Drawing.Size(162, 22);
  self.ItemPopCropBitmap.Text := 'Crop to bitmap';
  self.ItemPopCropBitmap.ToolTipText := 'Copy report page as a bitmap and crop it to useful contents';
  self.ItemPopCropBitmap.Click += new System.EventHandler(self.ItemMenuCropBitmap_Click);
  self.toolStripSeparator4.Name := 'toolStripSeparator4';
  self.toolStripSeparator4.Size := new System.Drawing.Size(177, 6);
  self.ItemPopSettings.Image := (resources.GetObject('ItemPopSettings.Image') as System.Drawing.Image);
  self.ItemPopSettings.Name := 'ItemPopSettings';
  self.ItemPopSettings.Size := new System.Drawing.Size(180, 22);
  self.ItemPopSettings.Text := 'Report parameters...';
  self.ItemPopSettings.Click += new System.EventHandler(self.ItemToolSettings_Click);
  self.PanelMessage.Controls.Add(self.LblMessage);
  self.PanelMessage.Dock := System.Windows.Forms.DockStyle.Top;
  self.PanelMessage.Location := new System.Drawing.Point(0, 49);
  self.PanelMessage.Name := 'PanelMessage';
  self.PanelMessage.Size := new System.Drawing.Size(1502, 40);
  self.PanelMessage.TabIndex := 3;
  self.LblMessage.BackColor := System.Drawing.SystemColors.AppWorkspace;
  self.LblMessage.Dock := System.Windows.Forms.DockStyle.Fill;
  self.LblMessage.Font := new System.Drawing.Font('Microsoft Sans Serif', 8.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (238 as System.Byte));
  self.LblMessage.Location := new System.Drawing.Point(0, 0);
  self.LblMessage.Name := 'LblMessage';
  self.LblMessage.Size := new System.Drawing.Size(1502, 40);
  self.LblMessage.TabIndex := 0;
  self.LblMessage.Text := 'Making report ...';
  self.LblMessage.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
  self.SaveReportDialog.Filter := 'HTML File|*.html|Text File|*.txt|Bitmaps|*_#.png|Metafiles|*_#.emf';
  self.SaveReportDialog.Title := 'Save report as';
  self.PrintDlg.AllowCurrentPage := true;
  self.PrintDlg.AllowSelection := true;
  self.PrintDlg.AllowSomePages := true;
  self.PrintDlg.UseEXDialog := true;
  self.Controls.Add(self.PanelMessage);
  self.Controls.Add(self.Viewer);
  self.Controls.Add(self.FormTool);
  self.Controls.Add(self.FormMenu);
  self.Name := 'CtrlFormReport';
  self.Size := new System.Drawing.Size(1502, 766);
  self.VisibleChanged += new System.EventHandler(self.CtrlFormReport_VisibleChanged);
  self.Leave += new System.EventHandler(self.CtrlFormReport_Leave);
  self.FormMenu.ResumeLayout(false);
  self.FormMenu.PerformLayout();
  self.FormTool.ResumeLayout(false);
  self.FormTool.PerformLayout();
  self.ReportMenu.ResumeLayout(false);
  self.PanelMessage.ResumeLayout(false);
  self.ResumeLayout(false);
  self.PerformLayout();
end;

{$ENDREGION}

end.