namespace DexiWin;

interface

{$HIDE H7}

uses
  System.Drawing,
  System.Collections,
  System.Windows.Forms,
  System.ComponentModel;

type
  CtrlFormBrowse = public partial class
  {$REGION Windows Control Designer generated fields}
  private
    ItemMenuBrowse: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuEditAddReport: System.Windows.Forms.ToolStripMenuItem;
    FirstFileSeparator: System.Windows.Forms.ToolStripSeparator;
    FirstEditSeparator: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator5: System.Windows.Forms.ToolStripSeparator;
    ItemMenuSave: System.Windows.Forms.ToolStripMenuItem;
    ItemToolPrintPreview: System.Windows.Forms.ToolStripButton;
    ItemMenuPrintPreview: System.Windows.Forms.ToolStripMenuItem;
    ItemPopSettings: System.Windows.Forms.ToolStripMenuItem;
    ItemToolSettings: System.Windows.Forms.ToolStripButton;
    ItemMenuFile: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuSettings: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuPrint: System.Windows.Forms.ToolStripMenuItem;
    SaveHtmlDialog: System.Windows.Forms.SaveFileDialog;
    toolStripSeparator3: System.Windows.Forms.ToolStripSeparator;
    ItemPopPrint: System.Windows.Forms.ToolStripMenuItem;
    ItemPopPrintPreview: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuZoomIn: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuZoomOut: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuZoomReset: System.Windows.Forms.ToolStripMenuItem;
    ItemPopZoomIn: System.Windows.Forms.ToolStripMenuItem;
    ItemPopZoomOut: System.Windows.Forms.ToolStripMenuItem;
    ItemPopZoomReset: System.Windows.Forms.ToolStripMenuItem;
    ItemToolZoomIn: System.Windows.Forms.ToolStripMenuItem;
    ItemToolZoomOut: System.Windows.Forms.ToolStripMenuItem;
    ItemToolZoomReset: System.Windows.Forms.ToolStripMenuItem;
    Browser: System.Windows.Forms.WebBrowser;
    BrowseMenu: System.Windows.Forms.ContextMenuStrip;
    FontDlg: System.Windows.Forms.FontDialog;
    toolStripSeparator2: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator1: System.Windows.Forms.ToolStripSeparator;
    PrintDlg: System.Windows.Forms.PrintDialog;
    PageSetupDlg: System.Windows.Forms.PageSetupDialog;
    ItemToolBrowse: System.Windows.Forms.ToolStripButton;
    ItemToolSave: System.Windows.Forms.ToolStripButton;
    _separator: System.Windows.Forms.ToolStripSeparator;
    ItemToolZoom: System.Windows.Forms.ToolStripSplitButton;
    ItemMenuViewZoom: System.Windows.Forms.ToolStripMenuItem;
    ItemToolCopy: System.Windows.Forms.ToolStripButton;
    ItemMenuCopy: System.Windows.Forms.ToolStripMenuItem;
    ToolTips: System.Windows.Forms.ToolTip;
    ItemMenuEdit: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuView: System.Windows.Forms.ToolStripMenuItem;
    FormMenu: System.Windows.Forms.MenuStrip;
    FormTool: System.Windows.Forms.ToolStrip;
    components: System.ComponentModel.Container := nil;
    method InitializeComponent;
  {$ENDREGION}
  end;

implementation

{$REGION Windows Control Designer generated code}
method CtrlFormBrowse.InitializeComponent;
begin
  self.components := new System.ComponentModel.Container();
  var resources: System.ComponentModel.ComponentResourceManager := new System.ComponentModel.ComponentResourceManager(typeOf(CtrlFormBrowse));
  self.FormMenu := new System.Windows.Forms.MenuStrip();
  self.ItemMenuFile := new System.Windows.Forms.ToolStripMenuItem();
  self.FirstFileSeparator := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuSave := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuPrintPreview := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuPrint := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuEdit := new System.Windows.Forms.ToolStripMenuItem();
  self.FirstEditSeparator := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuSettings := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuEditAddReport := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator5 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuCopy := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuView := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuViewZoom := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuZoomIn := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuZoomOut := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuZoomReset := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator1 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuBrowse := new System.Windows.Forms.ToolStripMenuItem();
  self.FormTool := new System.Windows.Forms.ToolStrip();
  self.ItemToolSettings := new System.Windows.Forms.ToolStripButton();
  self.ItemToolPrintPreview := new System.Windows.Forms.ToolStripButton();
  self.ItemToolZoom := new System.Windows.Forms.ToolStripSplitButton();
  self.ItemToolZoomIn := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolZoomOut := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolZoomReset := new System.Windows.Forms.ToolStripMenuItem();
  self._separator := new System.Windows.Forms.ToolStripSeparator();
  self.ItemToolCopy := new System.Windows.Forms.ToolStripButton();
  self.ItemToolSave := new System.Windows.Forms.ToolStripButton();
  self.ItemToolBrowse := new System.Windows.Forms.ToolStripButton();
  self.ToolTips := new System.Windows.Forms.ToolTip(self.components);
  self.PageSetupDlg := new System.Windows.Forms.PageSetupDialog();
  self.BrowseMenu := new System.Windows.Forms.ContextMenuStrip(self.components);
  self.ItemPopZoomIn := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopZoomOut := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopZoomReset := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator3 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopSettings := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopPrintPreview := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopPrint := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator2 := new System.Windows.Forms.ToolStripSeparator();
  self.SaveHtmlDialog := new System.Windows.Forms.SaveFileDialog();
  self.PrintDlg := new System.Windows.Forms.PrintDialog();
  self.FontDlg := new System.Windows.Forms.FontDialog();
  self.Browser := new System.Windows.Forms.WebBrowser();
  self.FormMenu.SuspendLayout();
  self.FormTool.SuspendLayout();
  self.BrowseMenu.SuspendLayout();
  self.SuspendLayout();
  self.FormMenu.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemMenuFile, self.ItemMenuEdit, self.ItemMenuView]));
  self.FormMenu.Location := new System.Drawing.Point(0, 0);
  self.FormMenu.Name := 'FormMenu';
  self.FormMenu.Size := new System.Drawing.Size(1502, 24);
  self.FormMenu.TabIndex := 0;
  self.FormMenu.Text := 'menuStrip1';
  self.ItemMenuFile.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.FirstFileSeparator, self.ItemMenuSave, self.ItemMenuPrintPreview, self.ItemMenuPrint]));
  self.ItemMenuFile.MergeAction := System.Windows.Forms.MergeAction.MatchOnly;
  self.ItemMenuFile.Name := 'ItemMenuFile';
  self.ItemMenuFile.Size := new System.Drawing.Size(37, 20);
  self.ItemMenuFile.Text := '&File';
  self.FirstFileSeparator.MergeAction := System.Windows.Forms.MergeAction.Insert;
  self.FirstFileSeparator.MergeIndex := 7;
  self.FirstFileSeparator.Name := 'FirstFileSeparator';
  self.FirstFileSeparator.Size := new System.Drawing.Size(149, 6);
  self.ItemMenuSave.MergeAction := System.Windows.Forms.MergeAction.Insert;
  self.ItemMenuSave.MergeIndex := 8;
  self.ItemMenuSave.Name := 'ItemMenuSave';
  self.ItemMenuSave.Size := new System.Drawing.Size(152, 22);
  self.ItemMenuSave.Text := 'Save &report...';
  self.ItemMenuSave.Click += new System.EventHandler(self.ItemToolSave_Click);
  self.ItemMenuPrintPreview.Image := DEXiWin.Properties.Resources.PrevPrint;
  self.ItemMenuPrintPreview.MergeAction := System.Windows.Forms.MergeAction.Insert;
  self.ItemMenuPrintPreview.MergeIndex := 9;
  self.ItemMenuPrintPreview.Name := 'ItemMenuPrintPreview';
  self.ItemMenuPrintPreview.Size := new System.Drawing.Size(152, 22);
  self.ItemMenuPrintPreview.Text := '&Print preview...';
  self.ItemMenuPrintPreview.Click += new System.EventHandler(self.ItemToolPrintPreview_Click);
  self.ItemMenuPrint.MergeAction := System.Windows.Forms.MergeAction.Insert;
  self.ItemMenuPrint.MergeIndex := 10;
  self.ItemMenuPrint.Name := 'ItemMenuPrint';
  self.ItemMenuPrint.Size := new System.Drawing.Size(152, 22);
  self.ItemMenuPrint.Text := 'Print...';
  self.ItemMenuPrint.ToolTipText := 'Print HTML document';
  self.ItemMenuPrint.Click += new System.EventHandler(self.ItemPopPrint_Click);
  self.ItemMenuEdit.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.FirstEditSeparator, self.ItemMenuSettings, self.ItemMenuEditAddReport, self.toolStripSeparator5, self.ItemMenuCopy]));
  self.ItemMenuEdit.MergeAction := System.Windows.Forms.MergeAction.MatchOnly;
  self.ItemMenuEdit.Name := 'ItemMenuEdit';
  self.ItemMenuEdit.Size := new System.Drawing.Size(39, 20);
  self.ItemMenuEdit.Text := '&Edit';
  self.FirstEditSeparator.Name := 'FirstEditSeparator';
  self.FirstEditSeparator.Size := new System.Drawing.Size(177, 6);
  self.ItemMenuSettings.Image := DEXiWin.Properties.Resources.ImgSettings;
  self.ItemMenuSettings.MergeAction := System.Windows.Forms.MergeAction.Insert;
  self.ItemMenuSettings.MergeIndex := 7;
  self.ItemMenuSettings.Name := 'ItemMenuSettings';
  self.ItemMenuSettings.Size := new System.Drawing.Size(180, 22);
  self.ItemMenuSettings.Text := '&Report parameters...';
  self.ItemMenuSettings.Click += new System.EventHandler(self.ItemToolSettings_Click);
  self.ItemMenuEditAddReport.Name := 'ItemMenuEditAddReport';
  self.ItemMenuEditAddReport.Size := new System.Drawing.Size(180, 22);
  self.ItemMenuEditAddReport.Text := '&Add to Report';
  self.ItemMenuEditAddReport.ToolTipText := 'Add this report as a section to the main Report tab';
  self.ItemMenuEditAddReport.Click += new System.EventHandler(self.ItemMenuEditAddReport_Click);
  self.toolStripSeparator5.Name := 'toolStripSeparator5';
  self.toolStripSeparator5.Size := new System.Drawing.Size(177, 6);
  self.ItemMenuCopy.Image := (resources.GetObject('ItemMenuCopy.Image') as System.Drawing.Image);
  self.ItemMenuCopy.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemMenuCopy.Name := 'ItemMenuCopy';
  self.ItemMenuCopy.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.C as System.Windows.Forms.Keys);
  self.ItemMenuCopy.Size := new System.Drawing.Size(180, 22);
  self.ItemMenuCopy.Text := '&Copy';
  self.ItemMenuCopy.ToolTipText := 'Copy HTML page';
  self.ItemMenuCopy.Click += new System.EventHandler(self.ItemToolCopy_Click);
  self.ItemMenuView.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemMenuViewZoom, self.ItemMenuBrowse]));
  self.ItemMenuView.MergeAction := System.Windows.Forms.MergeAction.Insert;
  self.ItemMenuView.MergeIndex := 2;
  self.ItemMenuView.Name := 'ItemMenuView';
  self.ItemMenuView.Size := new System.Drawing.Size(44, 20);
  self.ItemMenuView.Text := '&View';
  self.ItemMenuViewZoom.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemMenuZoomIn, self.ItemMenuZoomOut, self.ItemMenuZoomReset, self.toolStripSeparator1]));
  self.ItemMenuViewZoom.Image := DEXiWin.Properties.Resources.PrevZoom;
  self.ItemMenuViewZoom.Name := 'ItemMenuViewZoom';
  self.ItemMenuViewZoom.Size := new System.Drawing.Size(210, 22);
  self.ItemMenuViewZoom.Text := '&Zoom';
  self.ItemMenuZoomIn.Name := 'ItemMenuZoomIn';
  self.ItemMenuZoomIn.Size := new System.Drawing.Size(127, 22);
  self.ItemMenuZoomIn.Text := 'Zoom in';
  self.ItemMenuZoomIn.ToolTipText := 'Zoom in';
  self.ItemMenuZoomIn.Click += new System.EventHandler(self.ItemToolZoomIn_Click);
  self.ItemMenuZoomOut.Name := 'ItemMenuZoomOut';
  self.ItemMenuZoomOut.Size := new System.Drawing.Size(127, 22);
  self.ItemMenuZoomOut.Text := 'Zoom out';
  self.ItemMenuZoomOut.ToolTipText := 'Zoom out';
  self.ItemMenuZoomOut.Click += new System.EventHandler(self.ItemToolZoomOut_Click);
  self.ItemMenuZoomReset.Name := 'ItemMenuZoomReset';
  self.ItemMenuZoomReset.Size := new System.Drawing.Size(127, 22);
  self.ItemMenuZoomReset.Text := 'Reset';
  self.ItemMenuZoomReset.ToolTipText := 'Reset zoom';
  self.ItemMenuZoomReset.Click += new System.EventHandler(self.ItemToolZoomReset_Click);
  self.toolStripSeparator1.Name := 'toolStripSeparator1';
  self.toolStripSeparator1.Size := new System.Drawing.Size(124, 6);
  self.ItemMenuBrowse.Image := DEXiWin.Properties.Resources.PrevBrowse;
  self.ItemMenuBrowse.Name := 'ItemMenuBrowse';
  self.ItemMenuBrowse.Size := new System.Drawing.Size(210, 22);
  self.ItemMenuBrowse.Text := 'Open in system &browser...';
  self.ItemMenuBrowse.Click += new System.EventHandler(self.ItemToolBrowse_Click);
  self.FormTool.ImeMode := System.Windows.Forms.ImeMode.Off;
  self.FormTool.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemToolSettings, self.ItemToolPrintPreview, self.ItemToolZoom, self._separator, self.ItemToolCopy, self.ItemToolSave, self.ItemToolBrowse]));
  self.FormTool.Location := new System.Drawing.Point(0, 24);
  self.FormTool.Name := 'FormTool';
  self.FormTool.Size := new System.Drawing.Size(1502, 25);
  self.FormTool.TabIndex := 1;
  self.FormTool.Text := 'toolStrip1';
  self.ItemToolSettings.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolSettings.Image := DEXiWin.Properties.Resources.ImgSettings;
  self.ItemToolSettings.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolSettings.Name := 'ItemToolSettings';
  self.ItemToolSettings.Size := new System.Drawing.Size(23, 22);
  self.ItemToolSettings.Text := 'Report parameters';
  self.ItemToolSettings.Click += new System.EventHandler(self.ItemToolSettings_Click);
  self.ItemToolPrintPreview.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolPrintPreview.Image := DEXiWin.Properties.Resources.PrevPrint;
  self.ItemToolPrintPreview.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolPrintPreview.Name := 'ItemToolPrintPreview';
  self.ItemToolPrintPreview.Size := new System.Drawing.Size(23, 22);
  self.ItemToolPrintPreview.Text := 'Print preview';
  self.ItemToolPrintPreview.Click += new System.EventHandler(self.ItemToolPrintPreview_Click);
  self.ItemToolZoom.AutoToolTip := false;
  self.ItemToolZoom.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemToolZoomIn, self.ItemToolZoomOut, self.ItemToolZoomReset]));
  self.ItemToolZoom.Image := DEXiWin.Properties.Resources.PrevZoom;
  self.ItemToolZoom.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolZoom.Name := 'ItemToolZoom';
  self.ItemToolZoom.Size := new System.Drawing.Size(71, 22);
  self.ItemToolZoom.Text := '&Zoom';
  self.ItemToolZoom.ToolTipText := 'Zoom';
  self.ItemToolZoomIn.Name := 'ItemToolZoomIn';
  self.ItemToolZoomIn.Size := new System.Drawing.Size(127, 22);
  self.ItemToolZoomIn.Text := 'Zoom in';
  self.ItemToolZoomIn.ToolTipText := 'Zoom in';
  self.ItemToolZoomIn.Click += new System.EventHandler(self.ItemToolZoomIn_Click);
  self.ItemToolZoomOut.Name := 'ItemToolZoomOut';
  self.ItemToolZoomOut.Size := new System.Drawing.Size(127, 22);
  self.ItemToolZoomOut.Text := 'Zoom out';
  self.ItemToolZoomOut.ToolTipText := 'Zoom out';
  self.ItemToolZoomOut.Click += new System.EventHandler(self.ItemToolZoomOut_Click);
  self.ItemToolZoomReset.Name := 'ItemToolZoomReset';
  self.ItemToolZoomReset.Size := new System.Drawing.Size(127, 22);
  self.ItemToolZoomReset.Text := 'Reset';
  self.ItemToolZoomReset.ToolTipText := 'Reset zoom';
  self.ItemToolZoomReset.Click += new System.EventHandler(self.ItemToolZoomReset_Click);
  self._separator.Name := '_separator';
  self._separator.Size := new System.Drawing.Size(6, 25);
  self._separator.Visible := false;
  self.ItemToolCopy.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolCopy.Image := (resources.GetObject('ItemToolCopy.Image') as System.Drawing.Image);
  self.ItemToolCopy.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolCopy.Name := 'ItemToolCopy';
  self.ItemToolCopy.Size := new System.Drawing.Size(23, 22);
  self.ItemToolCopy.Text := '&Copy';
  self.ItemToolCopy.ToolTipText := 'Copy HTML document to clipboard';
  self.ItemToolCopy.Click += new System.EventHandler(self.ItemToolCopy_Click);
  self.ItemToolSave.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolSave.Image := DEXiWin.Properties.Resources.PrevSave;
  self.ItemToolSave.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolSave.Name := 'ItemToolSave';
  self.ItemToolSave.Size := new System.Drawing.Size(23, 22);
  self.ItemToolSave.Text := 'Save';
  self.ItemToolSave.ToolTipText := 'Save report';
  self.ItemToolSave.Click += new System.EventHandler(self.ItemToolSave_Click);
  self.ItemToolBrowse.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolBrowse.Image := DEXiWin.Properties.Resources.PrevBrowse;
  self.ItemToolBrowse.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolBrowse.Name := 'ItemToolBrowse';
  self.ItemToolBrowse.Size := new System.Drawing.Size(23, 22);
  self.ItemToolBrowse.Text := 'Browse';
  self.ItemToolBrowse.ToolTipText := 'Open report in system browser';
  self.ItemToolBrowse.Click += new System.EventHandler(self.ItemToolBrowse_Click);
  self.PageSetupDlg.EnableMetric := true;
  self.BrowseMenu.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemPopZoomIn, self.ItemPopZoomOut, self.ItemPopZoomReset, self.toolStripSeparator3, self.ItemPopSettings, self.ItemPopPrintPreview, self.ItemPopPrint]));
  self.BrowseMenu.Name := 'ReportMenu';
  self.BrowseMenu.Size := new System.Drawing.Size(181, 142);
  self.ItemPopZoomIn.Name := 'ItemPopZoomIn';
  self.ItemPopZoomIn.Size := new System.Drawing.Size(180, 22);
  self.ItemPopZoomIn.Text := 'Zoom in';
  self.ItemPopZoomIn.ToolTipText := 'Zoom in';
  self.ItemPopZoomIn.Click += new System.EventHandler(self.ItemToolZoomIn_Click);
  self.ItemPopZoomOut.Name := 'ItemPopZoomOut';
  self.ItemPopZoomOut.Size := new System.Drawing.Size(180, 22);
  self.ItemPopZoomOut.Text := 'Zoom out';
  self.ItemPopZoomOut.ToolTipText := 'Zoom out';
  self.ItemPopZoomOut.Click += new System.EventHandler(self.ItemToolZoomOut_Click);
  self.ItemPopZoomReset.Name := 'ItemPopZoomReset';
  self.ItemPopZoomReset.Size := new System.Drawing.Size(180, 22);
  self.ItemPopZoomReset.Text := 'Reset';
  self.ItemPopZoomReset.ToolTipText := 'Reset zoom';
  self.ItemPopZoomReset.Click += new System.EventHandler(self.ItemToolZoomReset_Click);
  self.toolStripSeparator3.Name := 'toolStripSeparator3';
  self.toolStripSeparator3.Size := new System.Drawing.Size(177, 6);
  self.ItemPopSettings.Image := DEXiWin.Properties.Resources.ImgSettings;
  self.ItemPopSettings.Name := 'ItemPopSettings';
  self.ItemPopSettings.Size := new System.Drawing.Size(180, 22);
  self.ItemPopSettings.Text := 'Report parameters...';
  self.ItemPopSettings.Click += new System.EventHandler(self.ItemToolSettings_Click);
  self.ItemPopPrintPreview.Image := DEXiWin.Properties.Resources.PrevPrint;
  self.ItemPopPrintPreview.Name := 'ItemPopPrintPreview';
  self.ItemPopPrintPreview.Size := new System.Drawing.Size(180, 22);
  self.ItemPopPrintPreview.Text := 'Print preview...';
  self.ItemPopPrintPreview.ToolTipText := 'Preview print document';
  self.ItemPopPrintPreview.Click += new System.EventHandler(self.ItemToolPrintPreview_Click);
  self.ItemPopPrint.Name := 'ItemPopPrint';
  self.ItemPopPrint.Size := new System.Drawing.Size(180, 22);
  self.ItemPopPrint.Text := 'Print...';
  self.ItemPopPrint.ToolTipText := 'Print HTML document';
  self.ItemPopPrint.Click += new System.EventHandler(self.ItemPopPrint_Click);
  self.toolStripSeparator2.Name := 'toolStripSeparator2';
  self.toolStripSeparator2.Size := new System.Drawing.Size(159, 6);
  self.SaveHtmlDialog.Filter := 'HTML File|*.html';
  self.PrintDlg.AllowCurrentPage := true;
  self.PrintDlg.AllowSelection := true;
  self.PrintDlg.AllowSomePages := true;
  self.PrintDlg.UseEXDialog := true;
  self.Browser.AllowNavigation := false;
  self.Browser.AllowWebBrowserDrop := false;
  self.Browser.ContextMenuStrip := self.BrowseMenu;
  self.Browser.Dock := System.Windows.Forms.DockStyle.Fill;
  self.Browser.IsWebBrowserContextMenuEnabled := false;
  self.Browser.Location := new System.Drawing.Point(0, 49);
  self.Browser.MinimumSize := new System.Drawing.Size(20, 20);
  self.Browser.Name := 'Browser';
  self.Browser.ScriptErrorsSuppressed := true;
  self.Browser.Size := new System.Drawing.Size(1502, 717);
  self.Browser.TabIndex := 2;
  self.Controls.Add(self.Browser);
  self.Controls.Add(self.FormTool);
  self.Controls.Add(self.FormMenu);
  self.Name := 'CtrlFormBrowse';
  self.Size := new System.Drawing.Size(1502, 766);
  self.VisibleChanged += new System.EventHandler(self.CtrlFormBrowse_VisibleChanged);
  self.FormMenu.ResumeLayout(false);
  self.FormMenu.PerformLayout();
  self.FormTool.ResumeLayout(false);
  self.FormTool.PerformLayout();
  self.BrowseMenu.ResumeLayout(false);
  self.ResumeLayout(false);
  self.PerformLayout();
end;

{$ENDREGION}

end.