namespace DexiWin;

interface

{$HIDE H7}

uses
  System.Drawing,
  System.Collections,
  System.Windows.Forms,
  System.ComponentModel;

type
  CtrlFormTree = public partial class
  {$REGION Windows Control Designer generated fields}
  private
    ItemMenuAddReport: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator7: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator6: System.Windows.Forms.ToolStripSeparator;
    SaveTreeDialog: System.Windows.Forms.SaveFileDialog;
    ItemPopCopyMetafile: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuCopyMetafile: System.Windows.Forms.ToolStripMenuItem;
    TreeMenu: System.Windows.Forms.ContextMenuStrip;
    ItemPopActualSize: System.Windows.Forms.ToolStripMenuItem;
    ItemPopFullPage: System.Windows.Forms.ToolStripMenuItem;
    ItemPopPageWidth: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator2: System.Windows.Forms.ToolStripSeparator;
    ItemPopCopyBitmap: System.Windows.Forms.ToolStripMenuItem;
    DlgFont: System.Windows.Forms.FontDialog;
    DlgColor: System.Windows.Forms.ColorDialog;
    BtnFontColor: System.Windows.Forms.Button;
    BtnTextFont: System.Windows.Forms.Button;
    GrpTextPosition: System.Windows.Forms.GroupBox;
    LblMR: System.Windows.Forms.Label;
    LblBR: System.Windows.Forms.Label;
    LblTR: System.Windows.Forms.Label;
    LblMC: System.Windows.Forms.Label;
    LblBC: System.Windows.Forms.Label;
    LblTC: System.Windows.Forms.Label;
    LblML: System.Windows.Forms.Label;
    LblBL: System.Windows.Forms.Label;
    LblTL: System.Windows.Forms.Label;
    GrpTextFormat: System.Windows.Forms.GroupBox;
    LblLineSpace: System.Windows.Forms.Label;
    LblPercent: System.Windows.Forms.Label;
    EditLineSpace: System.Windows.Forms.NumericUpDown;
    LblCharacters: System.Windows.Forms.Label;
    EditTrim: System.Windows.Forms.NumericUpDown;
    ChkTrim: System.Windows.Forms.CheckBox;
    ChkClip: System.Windows.Forms.CheckBox;
    ChkWrap: System.Windows.Forms.CheckBox;
    GtgpTextBorders: System.Windows.Forms.GroupBox;
    EditTextBorderRight: System.Windows.Forms.NumericUpDown;
    EditTextBorderBottom: System.Windows.Forms.NumericUpDown;
    EditTextBorderTop: System.Windows.Forms.NumericUpDown;
    EditTextBorderLeft: System.Windows.Forms.NumericUpDown;
    pictureBox1: System.Windows.Forms.PictureBox;
    TabNodeFormat: System.Windows.Forms.TabControl;
    TabNodeGraphic: System.Windows.Forms.TabPage;
    GrpBottomAnchor: System.Windows.Forms.GroupBox;
    EditBottomAnchorUnitsVertical: System.Windows.Forms.ComboBox;
    EditBottomAnchorUnitsHorizontal: System.Windows.Forms.ComboBox;
    EditBottomAnchorVertical: System.Windows.Forms.NumericUpDown;
    EditBottomAnchorHorizontal: System.Windows.Forms.NumericUpDown;
    label3: System.Windows.Forms.Label;
    label4: System.Windows.Forms.Label;
    GrpTopAnchor: System.Windows.Forms.GroupBox;
    EditTopAnchorUnitsVertical: System.Windows.Forms.ComboBox;
    EditTopAnchorUnitsHorizontal: System.Windows.Forms.ComboBox;
    EditTopAnchorVertical: System.Windows.Forms.NumericUpDown;
    EditTopAnchorHorizontal: System.Windows.Forms.NumericUpDown;
    label1: System.Windows.Forms.Label;
    label2: System.Windows.Forms.Label;
    GrpNodeAlignment: System.Windows.Forms.GroupBox;
    RadBottom: System.Windows.Forms.RadioButton;
    RadMiddle: System.Windows.Forms.RadioButton;
    RadTop: System.Windows.Forms.RadioButton;
    GrpNodeGraphic: System.Windows.Forms.GroupBox;
    BtnShape: System.Windows.Forms.Button;
    PicNode: System.Windows.Forms.PictureBox;
    GrpDimensions: System.Windows.Forms.GroupBox;
    EditMaxHeight: System.Windows.Forms.NumericUpDown;
    EditMinHeight: System.Windows.Forms.NumericUpDown;
    EditMaxWidth: System.Windows.Forms.NumericUpDown;
    EditMinWidth: System.Windows.Forms.NumericUpDown;
    LblDimHeight: System.Windows.Forms.Label;
    LblDimWidth: System.Windows.Forms.Label;
    LblMaxDim: System.Windows.Forms.Label;
    LblMinDim: System.Windows.Forms.Label;
    TabNodeText: System.Windows.Forms.TabPage;
    PanelNodeFormat: System.Windows.Forms.Panel;
    BtnResetFormat: System.Windows.Forms.Button;
    EditNodeFormat: System.Windows.Forms.ComboBox;
    LblNodeFormat: System.Windows.Forms.Label;
    GrpPrune: System.Windows.Forms.GroupBox;
    BtnExpand: System.Windows.Forms.Button;
    BtnCollapse: System.Windows.Forms.Button;
    ChkMirror: System.Windows.Forms.CheckBox;
    ChkAlignParents: System.Windows.Forms.CheckBox;
    PicSeparation: System.Windows.Forms.PictureBox;
    ChkAlignLevels: System.Windows.Forms.CheckBox;
    EditMinLevelSep: System.Windows.Forms.NumericUpDown;
    EditLevelSep: System.Windows.Forms.NumericUpDown;
    EditNodeSep: System.Windows.Forms.NumericUpDown;
    LblMinLevel: System.Windows.Forms.Label;
    LblLevel: System.Windows.Forms.Label;
    LblNode: System.Windows.Forms.Label;
    EditBorderRight: System.Windows.Forms.NumericUpDown;
    EditBorderBottom: System.Windows.Forms.NumericUpDown;
    EditBorderTop: System.Windows.Forms.NumericUpDown;
    EditBorderLeft: System.Windows.Forms.NumericUpDown;
    PicBorders: System.Windows.Forms.PictureBox;
    PicStretch: System.Windows.Forms.PictureBox;
    EditStretchY: System.Windows.Forms.NumericUpDown;
    EditStretchX: System.Windows.Forms.NumericUpDown;
    TabFormat: System.Windows.Forms.TabControl;
    TabTree: System.Windows.Forms.TabPage;
    BtnBackgroundColor: System.Windows.Forms.Button;
    GrpPlacement: System.Windows.Forms.GroupBox;
    GrpSeparation: System.Windows.Forms.GroupBox;
    GrpBorders: System.Windows.Forms.GroupBox;
    GrpStretch: System.Windows.Forms.GroupBox;
    TabNode: System.Windows.Forms.TabPage;
    ItemToolAlgWalker: System.Windows.Forms.ToolStripMenuItem;
    ItemToolDirection: System.Windows.Forms.ToolStripDropDownButton;
    ItemToolDirTopDown: System.Windows.Forms.ToolStripMenuItem;
    ItemToolDirLeftRight: System.Windows.Forms.ToolStripMenuItem;
    ItemToolDirBottomUp: System.Windows.Forms.ToolStripMenuItem;
    ItemToolDirRightLeft: System.Windows.Forms.ToolStripMenuItem;
    ItemToolAlgorithm: System.Windows.Forms.ToolStripDropDownButton;
    ItemToolAlgDistribute: System.Windows.Forms.ToolStripMenuItem;
    ItemToolAlgAlign: System.Windows.Forms.ToolStripMenuItem;
    ItemToolAlgQP: System.Windows.Forms.ToolStripMenuItem;
    TreePicture: System.Windows.Forms.PictureBox;
    CtrlPanel: System.Windows.Forms.Panel;
    TreePanel: System.Windows.Forms.Panel;
    FormTool: System.Windows.Forms.ToolStrip;
    ItemToolZoom: System.Windows.Forms.ToolStripSplitButton;
    ItemToolZoomActualSize: System.Windows.Forms.ToolStripMenuItem;
    ItemToolZoomFullPage: System.Windows.Forms.ToolStripMenuItem;
    ItemToolZoomPageWidth: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator3: System.Windows.Forms.ToolStripSeparator;
    ItemToolZoom500: System.Windows.Forms.ToolStripMenuItem;
    ItemToolZoom200: System.Windows.Forms.ToolStripMenuItem;
    ItemToolZoom150: System.Windows.Forms.ToolStripMenuItem;
    ItemToolZoom100: System.Windows.Forms.ToolStripMenuItem;
    ItemToolZoom75: System.Windows.Forms.ToolStripMenuItem;
    ItemToolZoom50: System.Windows.Forms.ToolStripMenuItem;
    ItemToolZoom25: System.Windows.Forms.ToolStripMenuItem;
    ItemToolZoom10: System.Windows.Forms.ToolStripMenuItem;
    _separator: System.Windows.Forms.ToolStripSeparator;
    ItemToolCopy: System.Windows.Forms.ToolStripButton;
    ItemToolSave: System.Windows.Forms.ToolStripButton;
    FormMenu: System.Windows.Forms.MenuStrip;
    ItemMenuFile: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuSave: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator5: System.Windows.Forms.ToolStripSeparator;
    ItemMenuEdit: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuCopyBitmap: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuView: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuViewZoom: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuZoomActualSize: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuZoomFullPage: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuZoomPageWidth: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator1: System.Windows.Forms.ToolStripSeparator;
    ItemMenuZoom500: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuZoom200: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuZoom150: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuZoom100: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuZoom75: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuZoom50: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuZoom25: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuZoom10: System.Windows.Forms.ToolStripMenuItem;
    
    components: System.ComponentModel.Container := nil;
    method InitializeComponent;
  {$ENDREGION}
  end;

implementation

{$REGION Windows Control Designer generated code}
method CtrlFormTree.InitializeComponent;
begin
  self.components := new System.ComponentModel.Container();
  var resources: System.ComponentModel.ComponentResourceManager := new System.ComponentModel.ComponentResourceManager(typeOf(CtrlFormTree));
  self.FormTool := new System.Windows.Forms.ToolStrip();
  self.ItemToolZoom := new System.Windows.Forms.ToolStripSplitButton();
  self.ItemToolZoomActualSize := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolZoomFullPage := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolZoomPageWidth := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator3 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemToolZoom500 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolZoom200 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolZoom150 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolZoom100 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolZoom75 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolZoom50 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolZoom25 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolZoom10 := new System.Windows.Forms.ToolStripMenuItem();
  self._separator := new System.Windows.Forms.ToolStripSeparator();
  self.ItemToolCopy := new System.Windows.Forms.ToolStripButton();
  self.ItemToolSave := new System.Windows.Forms.ToolStripButton();
  self.ItemToolDirection := new System.Windows.Forms.ToolStripDropDownButton();
  self.ItemToolDirTopDown := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolDirLeftRight := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolDirBottomUp := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolDirRightLeft := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolAlgorithm := new System.Windows.Forms.ToolStripDropDownButton();
  self.ItemToolAlgDistribute := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolAlgAlign := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolAlgWalker := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolAlgQP := new System.Windows.Forms.ToolStripMenuItem();
  self.FormMenu := new System.Windows.Forms.MenuStrip();
  self.ItemMenuFile := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator5 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuSave := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuEdit := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator7 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuAddReport := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator6 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuCopyMetafile := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuCopyBitmap := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuView := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuViewZoom := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuZoomActualSize := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuZoomFullPage := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuZoomPageWidth := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator1 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuZoom500 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuZoom200 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuZoom150 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuZoom100 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuZoom75 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuZoom50 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuZoom25 := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuZoom10 := new System.Windows.Forms.ToolStripMenuItem();
  self.CtrlPanel := new System.Windows.Forms.Panel();
  self.TabFormat := new System.Windows.Forms.TabControl();
  self.TabTree := new System.Windows.Forms.TabPage();
  self.GrpPrune := new System.Windows.Forms.GroupBox();
  self.BtnExpand := new System.Windows.Forms.Button();
  self.BtnCollapse := new System.Windows.Forms.Button();
  self.BtnBackgroundColor := new System.Windows.Forms.Button();
  self.GrpPlacement := new System.Windows.Forms.GroupBox();
  self.ChkMirror := new System.Windows.Forms.CheckBox();
  self.ChkAlignParents := new System.Windows.Forms.CheckBox();
  self.GrpSeparation := new System.Windows.Forms.GroupBox();
  self.PicSeparation := new System.Windows.Forms.PictureBox();
  self.ChkAlignLevels := new System.Windows.Forms.CheckBox();
  self.EditMinLevelSep := new System.Windows.Forms.NumericUpDown();
  self.EditLevelSep := new System.Windows.Forms.NumericUpDown();
  self.EditNodeSep := new System.Windows.Forms.NumericUpDown();
  self.LblMinLevel := new System.Windows.Forms.Label();
  self.LblLevel := new System.Windows.Forms.Label();
  self.LblNode := new System.Windows.Forms.Label();
  self.GrpBorders := new System.Windows.Forms.GroupBox();
  self.EditBorderRight := new System.Windows.Forms.NumericUpDown();
  self.EditBorderBottom := new System.Windows.Forms.NumericUpDown();
  self.EditBorderTop := new System.Windows.Forms.NumericUpDown();
  self.EditBorderLeft := new System.Windows.Forms.NumericUpDown();
  self.PicBorders := new System.Windows.Forms.PictureBox();
  self.GrpStretch := new System.Windows.Forms.GroupBox();
  self.PicStretch := new System.Windows.Forms.PictureBox();
  self.EditStretchY := new System.Windows.Forms.NumericUpDown();
  self.EditStretchX := new System.Windows.Forms.NumericUpDown();
  self.TabNode := new System.Windows.Forms.TabPage();
  self.TabNodeFormat := new System.Windows.Forms.TabControl();
  self.TabNodeGraphic := new System.Windows.Forms.TabPage();
  self.GrpBottomAnchor := new System.Windows.Forms.GroupBox();
  self.EditBottomAnchorUnitsVertical := new System.Windows.Forms.ComboBox();
  self.EditBottomAnchorUnitsHorizontal := new System.Windows.Forms.ComboBox();
  self.EditBottomAnchorVertical := new System.Windows.Forms.NumericUpDown();
  self.EditBottomAnchorHorizontal := new System.Windows.Forms.NumericUpDown();
  self.label3 := new System.Windows.Forms.Label();
  self.label4 := new System.Windows.Forms.Label();
  self.GrpTopAnchor := new System.Windows.Forms.GroupBox();
  self.EditTopAnchorUnitsVertical := new System.Windows.Forms.ComboBox();
  self.EditTopAnchorUnitsHorizontal := new System.Windows.Forms.ComboBox();
  self.EditTopAnchorVertical := new System.Windows.Forms.NumericUpDown();
  self.EditTopAnchorHorizontal := new System.Windows.Forms.NumericUpDown();
  self.label1 := new System.Windows.Forms.Label();
  self.label2 := new System.Windows.Forms.Label();
  self.GrpNodeAlignment := new System.Windows.Forms.GroupBox();
  self.RadBottom := new System.Windows.Forms.RadioButton();
  self.RadMiddle := new System.Windows.Forms.RadioButton();
  self.RadTop := new System.Windows.Forms.RadioButton();
  self.GrpNodeGraphic := new System.Windows.Forms.GroupBox();
  self.BtnShape := new System.Windows.Forms.Button();
  self.PicNode := new System.Windows.Forms.PictureBox();
  self.GrpDimensions := new System.Windows.Forms.GroupBox();
  self.EditMaxHeight := new System.Windows.Forms.NumericUpDown();
  self.EditMinHeight := new System.Windows.Forms.NumericUpDown();
  self.EditMaxWidth := new System.Windows.Forms.NumericUpDown();
  self.EditMinWidth := new System.Windows.Forms.NumericUpDown();
  self.LblDimHeight := new System.Windows.Forms.Label();
  self.LblDimWidth := new System.Windows.Forms.Label();
  self.LblMaxDim := new System.Windows.Forms.Label();
  self.LblMinDim := new System.Windows.Forms.Label();
  self.TabNodeText := new System.Windows.Forms.TabPage();
  self.BtnFontColor := new System.Windows.Forms.Button();
  self.BtnTextFont := new System.Windows.Forms.Button();
  self.GrpTextPosition := new System.Windows.Forms.GroupBox();
  self.LblMR := new System.Windows.Forms.Label();
  self.LblBR := new System.Windows.Forms.Label();
  self.LblTR := new System.Windows.Forms.Label();
  self.LblMC := new System.Windows.Forms.Label();
  self.LblBC := new System.Windows.Forms.Label();
  self.LblTC := new System.Windows.Forms.Label();
  self.LblML := new System.Windows.Forms.Label();
  self.LblBL := new System.Windows.Forms.Label();
  self.LblTL := new System.Windows.Forms.Label();
  self.GrpTextFormat := new System.Windows.Forms.GroupBox();
  self.LblLineSpace := new System.Windows.Forms.Label();
  self.LblPercent := new System.Windows.Forms.Label();
  self.EditLineSpace := new System.Windows.Forms.NumericUpDown();
  self.LblCharacters := new System.Windows.Forms.Label();
  self.EditTrim := new System.Windows.Forms.NumericUpDown();
  self.ChkTrim := new System.Windows.Forms.CheckBox();
  self.ChkClip := new System.Windows.Forms.CheckBox();
  self.ChkWrap := new System.Windows.Forms.CheckBox();
  self.GtgpTextBorders := new System.Windows.Forms.GroupBox();
  self.EditTextBorderRight := new System.Windows.Forms.NumericUpDown();
  self.EditTextBorderBottom := new System.Windows.Forms.NumericUpDown();
  self.EditTextBorderTop := new System.Windows.Forms.NumericUpDown();
  self.EditTextBorderLeft := new System.Windows.Forms.NumericUpDown();
  self.pictureBox1 := new System.Windows.Forms.PictureBox();
  self.PanelNodeFormat := new System.Windows.Forms.Panel();
  self.BtnResetFormat := new System.Windows.Forms.Button();
  self.LblNodeFormat := new System.Windows.Forms.Label();
  self.EditNodeFormat := new System.Windows.Forms.ComboBox();
  self.TreePicture := new System.Windows.Forms.PictureBox();
  self.DlgColor := new System.Windows.Forms.ColorDialog();
  self.DlgFont := new System.Windows.Forms.FontDialog();
  self.TreeMenu := new System.Windows.Forms.ContextMenuStrip(self.components);
  self.ItemPopActualSize := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopFullPage := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopPageWidth := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator2 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopCopyMetafile := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopCopyBitmap := new System.Windows.Forms.ToolStripMenuItem();
  self.TreePanel := new DexiWin.ZoomablePanel();
  self.SaveTreeDialog := new System.Windows.Forms.SaveFileDialog();
  self.FormTool.SuspendLayout();
  self.FormMenu.SuspendLayout();
  self.CtrlPanel.SuspendLayout();
  self.TabFormat.SuspendLayout();
  self.TabTree.SuspendLayout();
  self.GrpPrune.SuspendLayout();
  self.GrpPlacement.SuspendLayout();
  self.GrpSeparation.SuspendLayout();
  (self.PicSeparation as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditMinLevelSep as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditLevelSep as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditNodeSep as System.ComponentModel.ISupportInitialize).BeginInit();
  self.GrpBorders.SuspendLayout();
  (self.EditBorderRight as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditBorderBottom as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditBorderTop as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditBorderLeft as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.PicBorders as System.ComponentModel.ISupportInitialize).BeginInit();
  self.GrpStretch.SuspendLayout();
  (self.PicStretch as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditStretchY as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditStretchX as System.ComponentModel.ISupportInitialize).BeginInit();
  self.TabNode.SuspendLayout();
  self.TabNodeFormat.SuspendLayout();
  self.TabNodeGraphic.SuspendLayout();
  self.GrpBottomAnchor.SuspendLayout();
  (self.EditBottomAnchorVertical as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditBottomAnchorHorizontal as System.ComponentModel.ISupportInitialize).BeginInit();
  self.GrpTopAnchor.SuspendLayout();
  (self.EditTopAnchorVertical as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditTopAnchorHorizontal as System.ComponentModel.ISupportInitialize).BeginInit();
  self.GrpNodeAlignment.SuspendLayout();
  self.GrpNodeGraphic.SuspendLayout();
  (self.PicNode as System.ComponentModel.ISupportInitialize).BeginInit();
  self.GrpDimensions.SuspendLayout();
  (self.EditMaxHeight as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditMinHeight as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditMaxWidth as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditMinWidth as System.ComponentModel.ISupportInitialize).BeginInit();
  self.TabNodeText.SuspendLayout();
  self.GrpTextPosition.SuspendLayout();
  self.GrpTextFormat.SuspendLayout();
  (self.EditLineSpace as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditTrim as System.ComponentModel.ISupportInitialize).BeginInit();
  self.GtgpTextBorders.SuspendLayout();
  (self.EditTextBorderRight as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditTextBorderBottom as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditTextBorderTop as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditTextBorderLeft as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.pictureBox1 as System.ComponentModel.ISupportInitialize).BeginInit();
  self.PanelNodeFormat.SuspendLayout();
  (self.TreePicture as System.ComponentModel.ISupportInitialize).BeginInit();
  self.TreeMenu.SuspendLayout();
  self.TreePanel.SuspendLayout();
  self.SuspendLayout();
  self.FormTool.ImeMode := System.Windows.Forms.ImeMode.Off;
  self.FormTool.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemToolZoom, self._separator, self.ItemToolCopy, self.ItemToolSave, self.ItemToolDirection, self.ItemToolAlgorithm]));
  self.FormTool.Location := new System.Drawing.Point(0, 24);
  self.FormTool.Name := 'FormTool';
  self.FormTool.Size := new System.Drawing.Size(1286, 25);
  self.FormTool.TabIndex := 3;
  self.FormTool.Text := 'toolStrip1';
  self.ItemToolZoom.AutoToolTip := false;
  self.ItemToolZoom.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemToolZoomActualSize, self.ItemToolZoomFullPage, self.ItemToolZoomPageWidth, self.toolStripSeparator3, self.ItemToolZoom500, self.ItemToolZoom200, self.ItemToolZoom150, self.ItemToolZoom100, self.ItemToolZoom75, self.ItemToolZoom50, self.ItemToolZoom25, self.ItemToolZoom10]));
  self.ItemToolZoom.Image := DEXiWin.Properties.Resources.PrevZoom;
  self.ItemToolZoom.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolZoom.Name := 'ItemToolZoom';
  self.ItemToolZoom.Size := new System.Drawing.Size(71, 22);
  self.ItemToolZoom.Text := '&Zoom';
  self.ItemToolZoom.ToolTipText := 'Zoom';
  self.ItemToolZoom.DropDownItemClicked += new System.Windows.Forms.ToolStripItemClickedEventHandler(self.ItemToolZoom_DropDownItemClicked);
  self.ItemToolZoomActualSize.Image := DEXiWin.Properties.Resources.PrevZoom100;
  self.ItemToolZoomActualSize.Name := 'ItemToolZoomActualSize';
  self.ItemToolZoomActualSize.Size := new System.Drawing.Size(135, 22);
  self.ItemToolZoomActualSize.Text := 'Actual Size';
  self.ItemToolZoomFullPage.Image := DEXiWin.Properties.Resources.PrevZoomFullPage;
  self.ItemToolZoomFullPage.Name := 'ItemToolZoomFullPage';
  self.ItemToolZoomFullPage.Size := new System.Drawing.Size(135, 22);
  self.ItemToolZoomFullPage.Text := 'Full Page';
  self.ItemToolZoomPageWidth.Image := DEXiWin.Properties.Resources.PrevZoomPageWidth;
  self.ItemToolZoomPageWidth.Name := 'ItemToolZoomPageWidth';
  self.ItemToolZoomPageWidth.Size := new System.Drawing.Size(135, 22);
  self.ItemToolZoomPageWidth.Text := 'Page Width';
  self.toolStripSeparator3.Name := 'toolStripSeparator3';
  self.toolStripSeparator3.Size := new System.Drawing.Size(132, 6);
  self.ItemToolZoom500.Name := 'ItemToolZoom500';
  self.ItemToolZoom500.Size := new System.Drawing.Size(135, 22);
  self.ItemToolZoom500.Text := '500%';
  self.ItemToolZoom200.Name := 'ItemToolZoom200';
  self.ItemToolZoom200.Size := new System.Drawing.Size(135, 22);
  self.ItemToolZoom200.Text := '200%';
  self.ItemToolZoom150.Name := 'ItemToolZoom150';
  self.ItemToolZoom150.Size := new System.Drawing.Size(135, 22);
  self.ItemToolZoom150.Text := '150%';
  self.ItemToolZoom100.Name := 'ItemToolZoom100';
  self.ItemToolZoom100.Size := new System.Drawing.Size(135, 22);
  self.ItemToolZoom100.Text := '100%';
  self.ItemToolZoom75.Name := 'ItemToolZoom75';
  self.ItemToolZoom75.Size := new System.Drawing.Size(135, 22);
  self.ItemToolZoom75.Text := '75%';
  self.ItemToolZoom50.Name := 'ItemToolZoom50';
  self.ItemToolZoom50.Size := new System.Drawing.Size(135, 22);
  self.ItemToolZoom50.Text := '50%';
  self.ItemToolZoom25.Name := 'ItemToolZoom25';
  self.ItemToolZoom25.Size := new System.Drawing.Size(135, 22);
  self.ItemToolZoom25.Text := '25%';
  self.ItemToolZoom10.Name := 'ItemToolZoom10';
  self.ItemToolZoom10.Size := new System.Drawing.Size(135, 22);
  self.ItemToolZoom10.Text := '10%';
  self._separator.Name := '_separator';
  self._separator.Size := new System.Drawing.Size(6, 25);
  self._separator.Visible := false;
  self.ItemToolCopy.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolCopy.Image := DEXiWin.Properties.Resources.PrevCopyMetafile;
  self.ItemToolCopy.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolCopy.Name := 'ItemToolCopy';
  self.ItemToolCopy.Size := new System.Drawing.Size(23, 22);
  self.ItemToolCopy.Text := '&Copy';
  self.ItemToolCopy.ToolTipText := 'Copy tree graphic';
  self.ItemToolCopy.Click += new System.EventHandler(self.ItemMenuCopyMetafile_Click);
  self.ItemToolSave.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolSave.Image := DEXiWin.Properties.Resources.PrevSave;
  self.ItemToolSave.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolSave.Name := 'ItemToolSave';
  self.ItemToolSave.Size := new System.Drawing.Size(23, 22);
  self.ItemToolSave.Text := 'Save';
  self.ItemToolSave.ToolTipText := 'Save tree graphic';
  self.ItemToolSave.Click += new System.EventHandler(self.ItemToolSave_Click);
  self.ItemToolDirection.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemToolDirTopDown, self.ItemToolDirLeftRight, self.ItemToolDirBottomUp, self.ItemToolDirRightLeft]));
  self.ItemToolDirection.Image := (resources.GetObject('ItemToolDirection.Image') as System.Drawing.Image);
  self.ItemToolDirection.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolDirection.Name := 'ItemToolDirection';
  self.ItemToolDirection.Size := new System.Drawing.Size(84, 22);
  self.ItemToolDirection.Text := 'Direction';
  self.ItemToolDirection.DropDownItemClicked += new System.Windows.Forms.ToolStripItemClickedEventHandler(self.ItemToolDirection_DropDownItemClicked);
  self.ItemToolDirTopDown.Image := DEXiWin.Properties.Resources.DirTopDown;
  self.ItemToolDirTopDown.Name := 'ItemToolDirTopDown';
  self.ItemToolDirTopDown.Size := new System.Drawing.Size(134, 22);
  self.ItemToolDirTopDown.Text := '&Top-Down';
  self.ItemToolDirLeftRight.Image := DEXiWin.Properties.Resources.DirLeftRight;
  self.ItemToolDirLeftRight.Name := 'ItemToolDirLeftRight';
  self.ItemToolDirLeftRight.Size := new System.Drawing.Size(134, 22);
  self.ItemToolDirLeftRight.Text := '&Left-Right';
  self.ItemToolDirBottomUp.Image := DEXiWin.Properties.Resources.DirBottomUp;
  self.ItemToolDirBottomUp.Name := 'ItemToolDirBottomUp';
  self.ItemToolDirBottomUp.Size := new System.Drawing.Size(134, 22);
  self.ItemToolDirBottomUp.Text := '&Bottom-Up';
  self.ItemToolDirRightLeft.Image := DEXiWin.Properties.Resources.DirRightLeft;
  self.ItemToolDirRightLeft.Name := 'ItemToolDirRightLeft';
  self.ItemToolDirRightLeft.Size := new System.Drawing.Size(134, 22);
  self.ItemToolDirRightLeft.Text := '&Right-Left';
  self.ItemToolAlgorithm.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemToolAlgDistribute, self.ItemToolAlgAlign, self.ItemToolAlgWalker, self.ItemToolAlgQP]));
  self.ItemToolAlgorithm.Image := (resources.GetObject('ItemToolAlgorithm.Image') as System.Drawing.Image);
  self.ItemToolAlgorithm.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolAlgorithm.Name := 'ItemToolAlgorithm';
  self.ItemToolAlgorithm.Size := new System.Drawing.Size(90, 22);
  self.ItemToolAlgorithm.Text := 'Algorithm';
  self.ItemToolAlgorithm.DropDownItemClicked += new System.Windows.Forms.ToolStripItemClickedEventHandler(self.ItemToolAlgorithm_DropDownItemClicked);
  self.ItemToolAlgDistribute.Image := DEXiWin.Properties.Resources.AlgDistribute;
  self.ItemToolAlgDistribute.Name := 'ItemToolAlgDistribute';
  self.ItemToolAlgDistribute.Size := new System.Drawing.Size(125, 22);
  self.ItemToolAlgDistribute.Text := '&Distribute';
  self.ItemToolAlgDistribute.ToolTipText := 'Distribute input nodes';
  self.ItemToolAlgAlign.Image := DEXiWin.Properties.Resources.AlgAlign;
  self.ItemToolAlgAlign.Name := 'ItemToolAlgAlign';
  self.ItemToolAlgAlign.Size := new System.Drawing.Size(125, 22);
  self.ItemToolAlgAlign.Text := '&Align';
  self.ItemToolAlgAlign.ToolTipText := 'Align input nodes at the same level';
  self.ItemToolAlgWalker.Image := DEXiWin.Properties.Resources.AlgWalker;
  self.ItemToolAlgWalker.Name := 'ItemToolAlgWalker';
  self.ItemToolAlgWalker.Size := new System.Drawing.Size(125, 22);
  self.ItemToolAlgWalker.Text := '&Walker';
  self.ItemToolAlgWalker.ToolTipText := "Use Walker's space preserving algorithm";
  self.ItemToolAlgQP.Image := DEXiWin.Properties.Resources.AlgQP;
  self.ItemToolAlgQP.Name := 'ItemToolAlgQP';
  self.ItemToolAlgQP.Size := new System.Drawing.Size(125, 22);
  self.ItemToolAlgQP.Text := '&QP';
  self.ItemToolAlgQP.ToolTipText := 'Use algorithm based on quadratic optimization';
  self.FormMenu.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemMenuFile, self.ItemMenuEdit, self.ItemMenuView]));
  self.FormMenu.Location := new System.Drawing.Point(0, 0);
  self.FormMenu.Name := 'FormMenu';
  self.FormMenu.Size := new System.Drawing.Size(1286, 24);
  self.FormMenu.TabIndex := 2;
  self.FormMenu.Text := 'menuStrip1';
  self.ItemMenuFile.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.toolStripSeparator5, self.ItemMenuSave]));
  self.ItemMenuFile.MergeAction := System.Windows.Forms.MergeAction.MatchOnly;
  self.ItemMenuFile.Name := 'ItemMenuFile';
  self.ItemMenuFile.Size := new System.Drawing.Size(37, 20);
  self.ItemMenuFile.Text := '&File';
  self.toolStripSeparator5.MergeAction := System.Windows.Forms.MergeAction.Insert;
  self.toolStripSeparator5.MergeIndex := 7;
  self.toolStripSeparator5.Name := 'toolStripSeparator5';
  self.toolStripSeparator5.Size := new System.Drawing.Size(127, 6);
  self.ItemMenuSave.MergeAction := System.Windows.Forms.MergeAction.Insert;
  self.ItemMenuSave.MergeIndex := 8;
  self.ItemMenuSave.Name := 'ItemMenuSave';
  self.ItemMenuSave.Size := new System.Drawing.Size(130, 22);
  self.ItemMenuSave.Text := 'Save &tree...';
  self.ItemMenuSave.ToolTipText := 'Save tree';
  self.ItemMenuSave.Click += new System.EventHandler(self.ItemToolSave_Click);
  self.ItemMenuEdit.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.toolStripSeparator7, self.ItemMenuAddReport, self.toolStripSeparator6, self.ItemMenuCopyMetafile, self.ItemMenuCopyBitmap]));
  self.ItemMenuEdit.MergeAction := System.Windows.Forms.MergeAction.MatchOnly;
  self.ItemMenuEdit.Name := 'ItemMenuEdit';
  self.ItemMenuEdit.Size := new System.Drawing.Size(39, 20);
  self.ItemMenuEdit.Text := '&Edit';
  self.toolStripSeparator7.Name := 'toolStripSeparator7';
  self.toolStripSeparator7.Size := new System.Drawing.Size(228, 6);
  self.toolStripSeparator7.Visible := false;
  self.ItemMenuAddReport.Name := 'ItemMenuAddReport';
  self.ItemMenuAddReport.Size := new System.Drawing.Size(231, 22);
  self.ItemMenuAddReport.Text := '&Add to Report';
  self.ItemMenuAddReport.ToolTipText := 'Add this graphic to the main Report tab';
  self.ItemMenuAddReport.Visible := false;
  self.ItemMenuAddReport.Click += new System.EventHandler(self.ItemMenuAddReport_Click);
  self.toolStripSeparator6.Name := 'toolStripSeparator6';
  self.toolStripSeparator6.Size := new System.Drawing.Size(228, 6);
  self.ItemMenuCopyMetafile.Image := DEXiWin.Properties.Resources.PrevCopyMetafile;
  self.ItemMenuCopyMetafile.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemMenuCopyMetafile.Name := 'ItemMenuCopyMetafile';
  self.ItemMenuCopyMetafile.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.C as System.Windows.Forms.Keys);
  self.ItemMenuCopyMetafile.Size := new System.Drawing.Size(231, 22);
  self.ItemMenuCopyMetafile.Text := '&Copy as metafile';
  self.ItemMenuCopyMetafile.ToolTipText := 'Copy report page as a metafile';
  self.ItemMenuCopyMetafile.Click += new System.EventHandler(self.ItemMenuCopyMetafile_Click);
  self.ItemMenuCopyBitmap.Image := DEXiWin.Properties.Resources.PrevCopyBitmap;
  self.ItemMenuCopyBitmap.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemMenuCopyBitmap.Name := 'ItemMenuCopyBitmap';
  self.ItemMenuCopyBitmap.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Shift or System.Windows.Forms.Keys.C as System.Windows.Forms.Keys);
  self.ItemMenuCopyBitmap.Size := new System.Drawing.Size(231, 22);
  self.ItemMenuCopyBitmap.Text := 'Copy as &bitmap';
  self.ItemMenuCopyBitmap.ToolTipText := 'Copy report page as a bitmap';
  self.ItemMenuCopyBitmap.Click += new System.EventHandler(self.ItemMenuCopyBitmap_Click);
  self.ItemMenuView.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemMenuViewZoom]));
  self.ItemMenuView.MergeAction := System.Windows.Forms.MergeAction.Insert;
  self.ItemMenuView.MergeIndex := 2;
  self.ItemMenuView.Name := 'ItemMenuView';
  self.ItemMenuView.Size := new System.Drawing.Size(44, 20);
  self.ItemMenuView.Text := '&View';
  self.ItemMenuViewZoom.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemMenuZoomActualSize, self.ItemMenuZoomFullPage, self.ItemMenuZoomPageWidth, self.toolStripSeparator1, self.ItemMenuZoom500, self.ItemMenuZoom200, self.ItemMenuZoom150, self.ItemMenuZoom100, self.ItemMenuZoom75, self.ItemMenuZoom50, self.ItemMenuZoom25, self.ItemMenuZoom10]));
  self.ItemMenuViewZoom.Image := DEXiWin.Properties.Resources.PrevZoom;
  self.ItemMenuViewZoom.Name := 'ItemMenuViewZoom';
  self.ItemMenuViewZoom.Size := new System.Drawing.Size(106, 22);
  self.ItemMenuViewZoom.Text := '&Zoom';
  self.ItemMenuViewZoom.DropDownItemClicked += new System.Windows.Forms.ToolStripItemClickedEventHandler(self.ItemToolZoom_DropDownItemClicked);
  self.ItemMenuZoomActualSize.Image := DEXiWin.Properties.Resources.PrevZoom100;
  self.ItemMenuZoomActualSize.Name := 'ItemMenuZoomActualSize';
  self.ItemMenuZoomActualSize.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.D0 as System.Windows.Forms.Keys);
  self.ItemMenuZoomActualSize.Size := new System.Drawing.Size(171, 22);
  self.ItemMenuZoomActualSize.Text := 'Actual Size';
  self.ItemMenuZoomFullPage.Image := DEXiWin.Properties.Resources.PrevZoomFullPage;
  self.ItemMenuZoomFullPage.Name := 'ItemMenuZoomFullPage';
  self.ItemMenuZoomFullPage.Size := new System.Drawing.Size(171, 22);
  self.ItemMenuZoomFullPage.Text := 'Full Page';
  self.ItemMenuZoomPageWidth.Image := DEXiWin.Properties.Resources.PrevZoomPageWidth;
  self.ItemMenuZoomPageWidth.Name := 'ItemMenuZoomPageWidth';
  self.ItemMenuZoomPageWidth.Size := new System.Drawing.Size(171, 22);
  self.ItemMenuZoomPageWidth.Text := 'Page Width';
  self.toolStripSeparator1.Name := 'toolStripSeparator1';
  self.toolStripSeparator1.Size := new System.Drawing.Size(168, 6);
  self.ItemMenuZoom500.Name := 'ItemMenuZoom500';
  self.ItemMenuZoom500.Size := new System.Drawing.Size(171, 22);
  self.ItemMenuZoom500.Text := '500%';
  self.ItemMenuZoom200.Name := 'ItemMenuZoom200';
  self.ItemMenuZoom200.Size := new System.Drawing.Size(171, 22);
  self.ItemMenuZoom200.Text := '200%';
  self.ItemMenuZoom150.Name := 'ItemMenuZoom150';
  self.ItemMenuZoom150.Size := new System.Drawing.Size(171, 22);
  self.ItemMenuZoom150.Text := '150%';
  self.ItemMenuZoom100.Name := 'ItemMenuZoom100';
  self.ItemMenuZoom100.Size := new System.Drawing.Size(171, 22);
  self.ItemMenuZoom100.Text := '100%';
  self.ItemMenuZoom75.Name := 'ItemMenuZoom75';
  self.ItemMenuZoom75.Size := new System.Drawing.Size(171, 22);
  self.ItemMenuZoom75.Text := '75%';
  self.ItemMenuZoom50.Name := 'ItemMenuZoom50';
  self.ItemMenuZoom50.Size := new System.Drawing.Size(171, 22);
  self.ItemMenuZoom50.Text := '50%';
  self.ItemMenuZoom25.Name := 'ItemMenuZoom25';
  self.ItemMenuZoom25.Size := new System.Drawing.Size(171, 22);
  self.ItemMenuZoom25.Text := '25%';
  self.ItemMenuZoom10.Name := 'ItemMenuZoom10';
  self.ItemMenuZoom10.Size := new System.Drawing.Size(171, 22);
  self.ItemMenuZoom10.Text := '10%';
  self.CtrlPanel.Controls.Add(self.TabFormat);
  self.CtrlPanel.Dock := System.Windows.Forms.DockStyle.Right;
  self.CtrlPanel.Location := new System.Drawing.Point(1078, 49);
  self.CtrlPanel.Name := 'CtrlPanel';
  self.CtrlPanel.Size := new System.Drawing.Size(208, 717);
  self.CtrlPanel.TabIndex := 4;
  self.TabFormat.Controls.Add(self.TabTree);
  self.TabFormat.Controls.Add(self.TabNode);
  self.TabFormat.Dock := System.Windows.Forms.DockStyle.Fill;
  self.TabFormat.Location := new System.Drawing.Point(0, 0);
  self.TabFormat.Name := 'TabFormat';
  self.TabFormat.SelectedIndex := 0;
  self.TabFormat.Size := new System.Drawing.Size(208, 717);
  self.TabFormat.TabIndex := 0;
  self.TabTree.Controls.Add(self.GrpPrune);
  self.TabTree.Controls.Add(self.BtnBackgroundColor);
  self.TabTree.Controls.Add(self.GrpPlacement);
  self.TabTree.Controls.Add(self.GrpSeparation);
  self.TabTree.Controls.Add(self.GrpBorders);
  self.TabTree.Controls.Add(self.GrpStretch);
  self.TabTree.Location := new System.Drawing.Point(4, 22);
  self.TabTree.Name := 'TabTree';
  self.TabTree.Padding := new System.Windows.Forms.Padding(3);
  self.TabTree.Size := new System.Drawing.Size(200, 691);
  self.TabTree.TabIndex := 0;
  self.TabTree.Text := 'Tree';
  self.TabTree.UseVisualStyleBackColor := true;
  self.GrpPrune.Controls.Add(self.BtnExpand);
  self.GrpPrune.Controls.Add(self.BtnCollapse);
  self.GrpPrune.Dock := System.Windows.Forms.DockStyle.Top;
  self.GrpPrune.Location := new System.Drawing.Point(3, 365);
  self.GrpPrune.Name := 'GrpPrune';
  self.GrpPrune.Size := new System.Drawing.Size(194, 54);
  self.GrpPrune.TabIndex := 4;
  self.GrpPrune.TabStop := false;
  self.GrpPrune.Text := 'E&xpand/Collapse selected nodes';
  self.BtnExpand.Location := new System.Drawing.Point(95, 20);
  self.BtnExpand.Name := 'BtnExpand';
  self.BtnExpand.Size := new System.Drawing.Size(75, 23);
  self.BtnExpand.TabIndex := 13;
  self.BtnExpand.Text := 'E&xpand';
  self.BtnExpand.UseVisualStyleBackColor := true;
  self.BtnExpand.Click += new System.EventHandler(self.BtnExpand_Click);
  self.BtnCollapse.Location := new System.Drawing.Point(11, 20);
  self.BtnCollapse.Name := 'BtnCollapse';
  self.BtnCollapse.Size := new System.Drawing.Size(75, 23);
  self.BtnCollapse.TabIndex := 12;
  self.BtnCollapse.Text := '&Collapse';
  self.BtnCollapse.UseVisualStyleBackColor := true;
  self.BtnCollapse.Click += new System.EventHandler(self.BtnCollapse_Click);
  self.BtnBackgroundColor.Anchor := (System.Windows.Forms.AnchorStyles.Top or System.Windows.Forms.AnchorStyles.Left or System.Windows.Forms.AnchorStyles.Right as System.Windows.Forms.AnchorStyles);
  self.BtnBackgroundColor.Location := new System.Drawing.Point(14, 425);
  self.BtnBackgroundColor.Name := 'BtnBackgroundColor';
  self.BtnBackgroundColor.Size := new System.Drawing.Size(159, 23);
  self.BtnBackgroundColor.TabIndex := 14;
  self.BtnBackgroundColor.Text := 'Background color ...';
  self.BtnBackgroundColor.UseVisualStyleBackColor := true;
  self.BtnBackgroundColor.Click += new System.EventHandler(self.BtnBackgroundColor_Click);
  self.GrpPlacement.Controls.Add(self.ChkMirror);
  self.GrpPlacement.Controls.Add(self.ChkAlignParents);
  self.GrpPlacement.Dock := System.Windows.Forms.DockStyle.Top;
  self.GrpPlacement.Location := new System.Drawing.Point(3, 301);
  self.GrpPlacement.Name := 'GrpPlacement';
  self.GrpPlacement.Size := new System.Drawing.Size(194, 64);
  self.GrpPlacement.TabIndex := 3;
  self.GrpPlacement.TabStop := false;
  self.GrpPlacement.Text := 'Pla&cement';
  self.ChkMirror.AutoSize := true;
  self.ChkMirror.Location := new System.Drawing.Point(64, 40);
  self.ChkMirror.Name := 'ChkMirror';
  self.ChkMirror.Size := new System.Drawing.Size(52, 17);
  self.ChkMirror.TabIndex := 11;
  self.ChkMirror.Text := 'Mirror';
  self.ChkMirror.UseVisualStyleBackColor := true;
  self.ChkMirror.CheckStateChanged += new System.EventHandler(self.EditTree_ValueChanged);
  self.ChkAlignParents.AutoSize := true;
  self.ChkAlignParents.Location := new System.Drawing.Point(64, 20);
  self.ChkAlignParents.Name := 'ChkAlignParents';
  self.ChkAlignParents.Size := new System.Drawing.Size(87, 17);
  self.ChkAlignParents.TabIndex := 10;
  self.ChkAlignParents.Text := 'Align parents';
  self.ChkAlignParents.UseVisualStyleBackColor := true;
  self.ChkAlignParents.CheckStateChanged += new System.EventHandler(self.EditTree_ValueChanged);
  self.GrpSeparation.Controls.Add(self.PicSeparation);
  self.GrpSeparation.Controls.Add(self.ChkAlignLevels);
  self.GrpSeparation.Controls.Add(self.EditMinLevelSep);
  self.GrpSeparation.Controls.Add(self.EditLevelSep);
  self.GrpSeparation.Controls.Add(self.EditNodeSep);
  self.GrpSeparation.Controls.Add(self.LblMinLevel);
  self.GrpSeparation.Controls.Add(self.LblLevel);
  self.GrpSeparation.Controls.Add(self.LblNode);
  self.GrpSeparation.Dock := System.Windows.Forms.DockStyle.Top;
  self.GrpSeparation.Location := new System.Drawing.Point(3, 178);
  self.GrpSeparation.Name := 'GrpSeparation';
  self.GrpSeparation.Size := new System.Drawing.Size(194, 123);
  self.GrpSeparation.TabIndex := 2;
  self.GrpSeparation.TabStop := false;
  self.GrpSeparation.Text := 'Se&paration';
  self.PicSeparation.Image := DEXiWin.Properties.Resources.Separation;
  self.PicSeparation.Location := new System.Drawing.Point(120, 20);
  self.PicSeparation.Name := 'PicSeparation';
  self.PicSeparation.Size := new System.Drawing.Size(50, 70);
  self.PicSeparation.SizeMode := System.Windows.Forms.PictureBoxSizeMode.AutoSize;
  self.PicSeparation.TabIndex := 9;
  self.PicSeparation.TabStop := false;
  self.ChkAlignLevels.AutoSize := true;
  self.ChkAlignLevels.Location := new System.Drawing.Point(64, 97);
  self.ChkAlignLevels.Name := 'ChkAlignLevels';
  self.ChkAlignLevels.Size := new System.Drawing.Size(100, 17);
  self.ChkAlignLevels.TabIndex := 9;
  self.ChkAlignLevels.Text := 'Apply Min. level';
  self.ChkAlignLevels.UseVisualStyleBackColor := true;
  self.ChkAlignLevels.CheckStateChanged += new System.EventHandler(self.EditTree_ValueChanged);
  self.EditMinLevelSep.Location := new System.Drawing.Point(64, 70);
  self.EditMinLevelSep.Maximum := new System.Decimal(array of System.Int32([300, 0, 0, 0]));
  self.EditMinLevelSep.Name := 'EditMinLevelSep';
  self.EditMinLevelSep.Size := new System.Drawing.Size(50, 20);
  self.EditMinLevelSep.TabIndex := 8;
  self.EditMinLevelSep.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditMinLevelSep.ValueChanged += new System.EventHandler(self.EditTree_ValueChanged);
  self.EditLevelSep.Location := new System.Drawing.Point(64, 45);
  self.EditLevelSep.Maximum := new System.Decimal(array of System.Int32([300, 0, 0, 0]));
  self.EditLevelSep.Name := 'EditLevelSep';
  self.EditLevelSep.Size := new System.Drawing.Size(50, 20);
  self.EditLevelSep.TabIndex := 7;
  self.EditLevelSep.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditLevelSep.ValueChanged += new System.EventHandler(self.EditTree_ValueChanged);
  self.EditNodeSep.Location := new System.Drawing.Point(64, 20);
  self.EditNodeSep.Maximum := new System.Decimal(array of System.Int32([300, 0, 0, 0]));
  self.EditNodeSep.Name := 'EditNodeSep';
  self.EditNodeSep.Size := new System.Drawing.Size(50, 20);
  self.EditNodeSep.TabIndex := 6;
  self.EditNodeSep.ValueChanged += new System.EventHandler(self.EditTree_ValueChanged);
  self.LblMinLevel.AutoSize := true;
  self.LblMinLevel.Location := new System.Drawing.Point(8, 70);
  self.LblMinLevel.Name := 'LblMinLevel';
  self.LblMinLevel.Size := new System.Drawing.Size(52, 13);
  self.LblMinLevel.TabIndex := 2;
  self.LblMinLevel.Text := '&Min. level';
  self.LblLevel.AutoSize := true;
  self.LblLevel.Location := new System.Drawing.Point(8, 45);
  self.LblLevel.Name := 'LblLevel';
  self.LblLevel.Size := new System.Drawing.Size(33, 13);
  self.LblLevel.TabIndex := 1;
  self.LblLevel.Text := '&Level';
  self.LblNode.AutoSize := true;
  self.LblNode.Location := new System.Drawing.Point(8, 20);
  self.LblNode.Name := 'LblNode';
  self.LblNode.Size := new System.Drawing.Size(33, 13);
  self.LblNode.TabIndex := 0;
  self.LblNode.Text := '&Node';
  self.GrpBorders.Controls.Add(self.EditBorderRight);
  self.GrpBorders.Controls.Add(self.EditBorderBottom);
  self.GrpBorders.Controls.Add(self.EditBorderTop);
  self.GrpBorders.Controls.Add(self.EditBorderLeft);
  self.GrpBorders.Controls.Add(self.PicBorders);
  self.GrpBorders.Dock := System.Windows.Forms.DockStyle.Top;
  self.GrpBorders.Location := new System.Drawing.Point(3, 78);
  self.GrpBorders.Name := 'GrpBorders';
  self.GrpBorders.Size := new System.Drawing.Size(194, 100);
  self.GrpBorders.TabIndex := 1;
  self.GrpBorders.TabStop := false;
  self.GrpBorders.Text := 'Picture &borders';
  self.EditBorderRight.Location := new System.Drawing.Point(120, 45);
  self.EditBorderRight.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditBorderRight.Name := 'EditBorderRight';
  self.EditBorderRight.Size := new System.Drawing.Size(50, 20);
  self.EditBorderRight.TabIndex := 5;
  self.EditBorderRight.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditBorderRight.ValueChanged += new System.EventHandler(self.EditTree_ValueChanged);
  self.EditBorderBottom.Location := new System.Drawing.Point(64, 70);
  self.EditBorderBottom.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditBorderBottom.Name := 'EditBorderBottom';
  self.EditBorderBottom.Size := new System.Drawing.Size(50, 20);
  self.EditBorderBottom.TabIndex := 4;
  self.EditBorderBottom.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditBorderBottom.ValueChanged += new System.EventHandler(self.EditTree_ValueChanged);
  self.EditBorderTop.Location := new System.Drawing.Point(64, 20);
  self.EditBorderTop.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditBorderTop.Name := 'EditBorderTop';
  self.EditBorderTop.Size := new System.Drawing.Size(50, 20);
  self.EditBorderTop.TabIndex := 3;
  self.EditBorderTop.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditBorderTop.ValueChanged += new System.EventHandler(self.EditTree_ValueChanged);
  self.EditBorderLeft.Location := new System.Drawing.Point(8, 45);
  self.EditBorderLeft.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditBorderLeft.Name := 'EditBorderLeft';
  self.EditBorderLeft.Size := new System.Drawing.Size(50, 20);
  self.EditBorderLeft.TabIndex := 2;
  self.EditBorderLeft.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditBorderLeft.ValueChanged += new System.EventHandler(self.EditTree_ValueChanged);
  self.PicBorders.Image := DEXiWin.Properties.Resources.TextBorder;
  self.PicBorders.Location := new System.Drawing.Point(64, 44);
  self.PicBorders.Name := 'PicBorders';
  self.PicBorders.Size := new System.Drawing.Size(50, 22);
  self.PicBorders.SizeMode := System.Windows.Forms.PictureBoxSizeMode.AutoSize;
  self.PicBorders.TabIndex := 0;
  self.PicBorders.TabStop := false;
  self.GrpStretch.Controls.Add(self.PicStretch);
  self.GrpStretch.Controls.Add(self.EditStretchY);
  self.GrpStretch.Controls.Add(self.EditStretchX);
  self.GrpStretch.Dock := System.Windows.Forms.DockStyle.Top;
  self.GrpStretch.Location := new System.Drawing.Point(3, 3);
  self.GrpStretch.Name := 'GrpStretch';
  self.GrpStretch.Size := new System.Drawing.Size(194, 75);
  self.GrpStretch.TabIndex := 0;
  self.GrpStretch.TabStop := false;
  self.GrpStretch.Text := '&Stretch';
  self.PicStretch.Image := DEXiWin.Properties.Resources.Stretch;
  self.PicStretch.Location := new System.Drawing.Point(34, 28);
  self.PicStretch.Name := 'PicStretch';
  self.PicStretch.Size := new System.Drawing.Size(24, 12);
  self.PicStretch.SizeMode := System.Windows.Forms.PictureBoxSizeMode.AutoSize;
  self.PicStretch.TabIndex := 2;
  self.PicStretch.TabStop := false;
  self.EditStretchY.Location := new System.Drawing.Point(8, 45);
  self.EditStretchY.Maximum := new System.Decimal(array of System.Int32([500, 0, 0, 0]));
  self.EditStretchY.Minimum := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditStretchY.Name := 'EditStretchY';
  self.EditStretchY.Size := new System.Drawing.Size(50, 20);
  self.EditStretchY.TabIndex := 1;
  self.EditStretchY.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditStretchY.ValueChanged += new System.EventHandler(self.EditTree_ValueChanged);
  self.EditStretchX.Location := new System.Drawing.Point(64, 20);
  self.EditStretchX.Maximum := new System.Decimal(array of System.Int32([500, 0, 0, 0]));
  self.EditStretchX.Minimum := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditStretchX.Name := 'EditStretchX';
  self.EditStretchX.Size := new System.Drawing.Size(50, 20);
  self.EditStretchX.TabIndex := 0;
  self.EditStretchX.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditStretchX.ValueChanged += new System.EventHandler(self.EditTree_ValueChanged);
  self.TabNode.Controls.Add(self.TabNodeFormat);
  self.TabNode.Controls.Add(self.PanelNodeFormat);
  self.TabNode.Location := new System.Drawing.Point(4, 22);
  self.TabNode.Name := 'TabNode';
  self.TabNode.Padding := new System.Windows.Forms.Padding(3);
  self.TabNode.Size := new System.Drawing.Size(200, 691);
  self.TabNode.TabIndex := 1;
  self.TabNode.Text := 'Nodes';
  self.TabNode.UseVisualStyleBackColor := true;
  self.TabNodeFormat.Controls.Add(self.TabNodeGraphic);
  self.TabNodeFormat.Controls.Add(self.TabNodeText);
  self.TabNodeFormat.Dock := System.Windows.Forms.DockStyle.Fill;
  self.TabNodeFormat.Location := new System.Drawing.Point(3, 86);
  self.TabNodeFormat.Name := 'TabNodeFormat';
  self.TabNodeFormat.SelectedIndex := 0;
  self.TabNodeFormat.Size := new System.Drawing.Size(194, 602);
  self.TabNodeFormat.TabIndex := 3;
  self.TabNodeGraphic.Controls.Add(self.GrpBottomAnchor);
  self.TabNodeGraphic.Controls.Add(self.GrpTopAnchor);
  self.TabNodeGraphic.Controls.Add(self.GrpNodeAlignment);
  self.TabNodeGraphic.Controls.Add(self.GrpNodeGraphic);
  self.TabNodeGraphic.Controls.Add(self.GrpDimensions);
  self.TabNodeGraphic.Location := new System.Drawing.Point(4, 22);
  self.TabNodeGraphic.Name := 'TabNodeGraphic';
  self.TabNodeGraphic.Padding := new System.Windows.Forms.Padding(3);
  self.TabNodeGraphic.Size := new System.Drawing.Size(186, 576);
  self.TabNodeGraphic.TabIndex := 0;
  self.TabNodeGraphic.Text := 'Graphic';
  self.TabNodeGraphic.UseVisualStyleBackColor := true;
  self.GrpBottomAnchor.Controls.Add(self.EditBottomAnchorUnitsVertical);
  self.GrpBottomAnchor.Controls.Add(self.EditBottomAnchorUnitsHorizontal);
  self.GrpBottomAnchor.Controls.Add(self.EditBottomAnchorVertical);
  self.GrpBottomAnchor.Controls.Add(self.EditBottomAnchorHorizontal);
  self.GrpBottomAnchor.Controls.Add(self.label3);
  self.GrpBottomAnchor.Controls.Add(self.label4);
  self.GrpBottomAnchor.Dock := System.Windows.Forms.DockStyle.Top;
  self.GrpBottomAnchor.Location := new System.Drawing.Point(3, 289);
  self.GrpBottomAnchor.Name := 'GrpBottomAnchor';
  self.GrpBottomAnchor.Size := new System.Drawing.Size(180, 73);
  self.GrpBottomAnchor.TabIndex := 50;
  self.GrpBottomAnchor.TabStop := false;
  self.GrpBottomAnchor.Text := '&Bottom anchor';
  self.EditBottomAnchorUnitsVertical.DropDownStyle := System.Windows.Forms.ComboBoxStyle.DropDownList;
  self.EditBottomAnchorUnitsVertical.FormattingEnabled := true;
  self.EditBottomAnchorUnitsVertical.Items.AddRange(array of System.Object(['pix', #37]));
  self.EditBottomAnchorUnitsVertical.Location := new System.Drawing.Point(124, 44);
  self.EditBottomAnchorUnitsVertical.Name := 'EditBottomAnchorUnitsVertical';
  self.EditBottomAnchorUnitsVertical.Size := new System.Drawing.Size(50, 21);
  self.EditBottomAnchorUnitsVertical.TabIndex := 54;
  self.EditBottomAnchorUnitsVertical.SelectedIndexChanged += new System.EventHandler(self.EditFormat_ValueChanged);
  self.EditBottomAnchorUnitsHorizontal.DropDownStyle := System.Windows.Forms.ComboBoxStyle.DropDownList;
  self.EditBottomAnchorUnitsHorizontal.FormattingEnabled := true;
  self.EditBottomAnchorUnitsHorizontal.Items.AddRange(array of System.Object(['pix', #37]));
  self.EditBottomAnchorUnitsHorizontal.Location := new System.Drawing.Point(124, 19);
  self.EditBottomAnchorUnitsHorizontal.Name := 'EditBottomAnchorUnitsHorizontal';
  self.EditBottomAnchorUnitsHorizontal.Size := new System.Drawing.Size(50, 21);
  self.EditBottomAnchorUnitsHorizontal.TabIndex := 52;
  self.EditBottomAnchorUnitsHorizontal.SelectedIndexChanged += new System.EventHandler(self.EditFormat_ValueChanged);
  self.EditBottomAnchorVertical.Location := new System.Drawing.Point(68, 44);
  self.EditBottomAnchorVertical.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditBottomAnchorVertical.Name := 'EditBottomAnchorVertical';
  self.EditBottomAnchorVertical.Size := new System.Drawing.Size(50, 20);
  self.EditBottomAnchorVertical.TabIndex := 53;
  self.EditBottomAnchorVertical.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditBottomAnchorVertical.ValueChanged += new System.EventHandler(self.EditFormat_ValueChanged);
  self.EditBottomAnchorHorizontal.Location := new System.Drawing.Point(68, 19);
  self.EditBottomAnchorHorizontal.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditBottomAnchorHorizontal.Name := 'EditBottomAnchorHorizontal';
  self.EditBottomAnchorHorizontal.Size := new System.Drawing.Size(50, 20);
  self.EditBottomAnchorHorizontal.TabIndex := 51;
  self.EditBottomAnchorHorizontal.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditBottomAnchorHorizontal.ValueChanged += new System.EventHandler(self.EditFormat_ValueChanged);
  self.label3.AutoSize := true;
  self.label3.Location := new System.Drawing.Point(4, 48);
  self.label3.Name := 'label3';
  self.label3.Size := new System.Drawing.Size(42, 13);
  self.label3.TabIndex := 9;
  self.label3.Text := 'Vertical';
  self.label4.AutoSize := true;
  self.label4.Location := new System.Drawing.Point(4, 23);
  self.label4.Name := 'label4';
  self.label4.Size := new System.Drawing.Size(54, 13);
  self.label4.TabIndex := 8;
  self.label4.Text := 'Horizontal';
  self.GrpTopAnchor.Controls.Add(self.EditTopAnchorUnitsVertical);
  self.GrpTopAnchor.Controls.Add(self.EditTopAnchorUnitsHorizontal);
  self.GrpTopAnchor.Controls.Add(self.EditTopAnchorVertical);
  self.GrpTopAnchor.Controls.Add(self.EditTopAnchorHorizontal);
  self.GrpTopAnchor.Controls.Add(self.label1);
  self.GrpTopAnchor.Controls.Add(self.label2);
  self.GrpTopAnchor.Dock := System.Windows.Forms.DockStyle.Top;
  self.GrpTopAnchor.Location := new System.Drawing.Point(3, 216);
  self.GrpTopAnchor.Name := 'GrpTopAnchor';
  self.GrpTopAnchor.Size := new System.Drawing.Size(180, 73);
  self.GrpTopAnchor.TabIndex := 40;
  self.GrpTopAnchor.TabStop := false;
  self.GrpTopAnchor.Text := '&Top anchor';
  self.EditTopAnchorUnitsVertical.DropDownStyle := System.Windows.Forms.ComboBoxStyle.DropDownList;
  self.EditTopAnchorUnitsVertical.FormattingEnabled := true;
  self.EditTopAnchorUnitsVertical.Items.AddRange(array of System.Object(['pix', #37]));
  self.EditTopAnchorUnitsVertical.Location := new System.Drawing.Point(124, 44);
  self.EditTopAnchorUnitsVertical.Name := 'EditTopAnchorUnitsVertical';
  self.EditTopAnchorUnitsVertical.Size := new System.Drawing.Size(50, 21);
  self.EditTopAnchorUnitsVertical.TabIndex := 44;
  self.EditTopAnchorUnitsVertical.SelectedIndexChanged += new System.EventHandler(self.EditFormat_ValueChanged);
  self.EditTopAnchorUnitsHorizontal.DropDownStyle := System.Windows.Forms.ComboBoxStyle.DropDownList;
  self.EditTopAnchorUnitsHorizontal.FormattingEnabled := true;
  self.EditTopAnchorUnitsHorizontal.Items.AddRange(array of System.Object(['pix', #37]));
  self.EditTopAnchorUnitsHorizontal.Location := new System.Drawing.Point(124, 20);
  self.EditTopAnchorUnitsHorizontal.Name := 'EditTopAnchorUnitsHorizontal';
  self.EditTopAnchorUnitsHorizontal.Size := new System.Drawing.Size(50, 21);
  self.EditTopAnchorUnitsHorizontal.TabIndex := 42;
  self.EditTopAnchorUnitsHorizontal.SelectedIndexChanged += new System.EventHandler(self.EditFormat_ValueChanged);
  self.EditTopAnchorVertical.Location := new System.Drawing.Point(68, 44);
  self.EditTopAnchorVertical.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditTopAnchorVertical.Name := 'EditTopAnchorVertical';
  self.EditTopAnchorVertical.Size := new System.Drawing.Size(50, 20);
  self.EditTopAnchorVertical.TabIndex := 43;
  self.EditTopAnchorVertical.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditTopAnchorVertical.ValueChanged += new System.EventHandler(self.EditFormat_ValueChanged);
  self.EditTopAnchorHorizontal.Location := new System.Drawing.Point(68, 20);
  self.EditTopAnchorHorizontal.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditTopAnchorHorizontal.Name := 'EditTopAnchorHorizontal';
  self.EditTopAnchorHorizontal.Size := new System.Drawing.Size(50, 20);
  self.EditTopAnchorHorizontal.TabIndex := 41;
  self.EditTopAnchorHorizontal.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditTopAnchorHorizontal.ValueChanged += new System.EventHandler(self.EditFormat_ValueChanged);
  self.label1.AutoSize := true;
  self.label1.Location := new System.Drawing.Point(4, 48);
  self.label1.Name := 'label1';
  self.label1.Size := new System.Drawing.Size(42, 13);
  self.label1.TabIndex := 9;
  self.label1.Text := 'Vertical';
  self.label2.AutoSize := true;
  self.label2.Location := new System.Drawing.Point(4, 24);
  self.label2.Name := 'label2';
  self.label2.Size := new System.Drawing.Size(54, 13);
  self.label2.TabIndex := 8;
  self.label2.Text := 'Horizontal';
  self.GrpNodeAlignment.Controls.Add(self.RadBottom);
  self.GrpNodeAlignment.Controls.Add(self.RadMiddle);
  self.GrpNodeAlignment.Controls.Add(self.RadTop);
  self.GrpNodeAlignment.Dock := System.Windows.Forms.DockStyle.Top;
  self.GrpNodeAlignment.Location := new System.Drawing.Point(3, 169);
  self.GrpNodeAlignment.Name := 'GrpNodeAlignment';
  self.GrpNodeAlignment.Size := new System.Drawing.Size(180, 47);
  self.GrpNodeAlignment.TabIndex := 30;
  self.GrpNodeAlignment.TabStop := false;
  self.GrpNodeAlignment.Text := 'Node &alignment';
  self.RadBottom.AutoSize := true;
  self.RadBottom.Location := new System.Drawing.Point(105, 20);
  self.RadBottom.Name := 'RadBottom';
  self.RadBottom.Size := new System.Drawing.Size(57, 17);
  self.RadBottom.TabIndex := 33;
  self.RadBottom.TabStop := true;
  self.RadBottom.Text := 'bottom';
  self.RadBottom.UseVisualStyleBackColor := true;
  self.RadBottom.Click += new System.EventHandler(self.EditFormat_ValueChanged);
  self.RadMiddle.AutoSize := true;
  self.RadMiddle.Location := new System.Drawing.Point(51, 20);
  self.RadMiddle.Name := 'RadMiddle';
  self.RadMiddle.Size := new System.Drawing.Size(55, 17);
  self.RadMiddle.TabIndex := 32;
  self.RadMiddle.TabStop := true;
  self.RadMiddle.Text := 'middle';
  self.RadMiddle.UseVisualStyleBackColor := true;
  self.RadMiddle.Click += new System.EventHandler(self.EditFormat_ValueChanged);
  self.RadTop.AutoSize := true;
  self.RadTop.Location := new System.Drawing.Point(10, 20);
  self.RadTop.Name := 'RadTop';
  self.RadTop.Size := new System.Drawing.Size(40, 17);
  self.RadTop.TabIndex := 31;
  self.RadTop.TabStop := true;
  self.RadTop.Text := 'top';
  self.RadTop.UseVisualStyleBackColor := true;
  self.RadTop.Click += new System.EventHandler(self.EditFormat_ValueChanged);
  self.GrpNodeGraphic.Controls.Add(self.BtnShape);
  self.GrpNodeGraphic.Controls.Add(self.PicNode);
  self.GrpNodeGraphic.Dock := System.Windows.Forms.DockStyle.Top;
  self.GrpNodeGraphic.Location := new System.Drawing.Point(3, 88);
  self.GrpNodeGraphic.Name := 'GrpNodeGraphic';
  self.GrpNodeGraphic.Size := new System.Drawing.Size(180, 81);
  self.GrpNodeGraphic.TabIndex := 20;
  self.GrpNodeGraphic.TabStop := false;
  self.GrpNodeGraphic.Text := 'Node &graphic';
  self.BtnShape.Location := new System.Drawing.Point(68, 40);
  self.BtnShape.Name := 'BtnShape';
  self.BtnShape.Size := new System.Drawing.Size(106, 23);
  self.BtnShape.TabIndex := 21;
  self.BtnShape.Text := 'Edit ...';
  self.BtnShape.UseVisualStyleBackColor := true;
  self.BtnShape.Click += new System.EventHandler(self.BtnShape_Click);
  self.PicNode.Location := new System.Drawing.Point(10, 20);
  self.PicNode.Name := 'PicNode';
  self.PicNode.Size := new System.Drawing.Size(52, 52);
  self.PicNode.TabIndex := 0;
  self.PicNode.TabStop := false;
  self.GrpDimensions.Controls.Add(self.EditMaxHeight);
  self.GrpDimensions.Controls.Add(self.EditMinHeight);
  self.GrpDimensions.Controls.Add(self.EditMaxWidth);
  self.GrpDimensions.Controls.Add(self.EditMinWidth);
  self.GrpDimensions.Controls.Add(self.LblDimHeight);
  self.GrpDimensions.Controls.Add(self.LblDimWidth);
  self.GrpDimensions.Controls.Add(self.LblMaxDim);
  self.GrpDimensions.Controls.Add(self.LblMinDim);
  self.GrpDimensions.Dock := System.Windows.Forms.DockStyle.Top;
  self.GrpDimensions.Location := new System.Drawing.Point(3, 3);
  self.GrpDimensions.Name := 'GrpDimensions';
  self.GrpDimensions.Size := new System.Drawing.Size(180, 85);
  self.GrpDimensions.TabIndex := 10;
  self.GrpDimensions.TabStop := false;
  self.GrpDimensions.Text := '&Dimensions';
  self.EditMaxHeight.Location := new System.Drawing.Point(124, 56);
  self.EditMaxHeight.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditMaxHeight.Name := 'EditMaxHeight';
  self.EditMaxHeight.Size := new System.Drawing.Size(50, 20);
  self.EditMaxHeight.TabIndex := 14;
  self.EditMaxHeight.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditMaxHeight.ValueChanged += new System.EventHandler(self.EditFormat_ValueChanged);
  self.EditMinHeight.Location := new System.Drawing.Point(68, 56);
  self.EditMinHeight.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditMinHeight.Minimum := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditMinHeight.Name := 'EditMinHeight';
  self.EditMinHeight.Size := new System.Drawing.Size(50, 20);
  self.EditMinHeight.TabIndex := 13;
  self.EditMinHeight.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditMinHeight.ValueChanged += new System.EventHandler(self.EditFormat_ValueChanged);
  self.EditMaxWidth.Location := new System.Drawing.Point(124, 32);
  self.EditMaxWidth.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditMaxWidth.Name := 'EditMaxWidth';
  self.EditMaxWidth.Size := new System.Drawing.Size(50, 20);
  self.EditMaxWidth.TabIndex := 12;
  self.EditMaxWidth.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditMaxWidth.ValueChanged += new System.EventHandler(self.EditFormat_ValueChanged);
  self.EditMinWidth.Location := new System.Drawing.Point(68, 32);
  self.EditMinWidth.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditMinWidth.Minimum := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditMinWidth.Name := 'EditMinWidth';
  self.EditMinWidth.Size := new System.Drawing.Size(50, 20);
  self.EditMinWidth.TabIndex := 11;
  self.EditMinWidth.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditMinWidth.ValueChanged += new System.EventHandler(self.EditFormat_ValueChanged);
  self.LblDimHeight.AutoSize := true;
  self.LblDimHeight.Location := new System.Drawing.Point(4, 58);
  self.LblDimHeight.Name := 'LblDimHeight';
  self.LblDimHeight.Size := new System.Drawing.Size(38, 13);
  self.LblDimHeight.TabIndex := 3;
  self.LblDimHeight.Text := '&Height';
  self.LblDimWidth.AutoSize := true;
  self.LblDimWidth.Location := new System.Drawing.Point(4, 34);
  self.LblDimWidth.Name := 'LblDimWidth';
  self.LblDimWidth.Size := new System.Drawing.Size(35, 13);
  self.LblDimWidth.TabIndex := 2;
  self.LblDimWidth.Text := '&Width';
  self.LblMaxDim.AutoSize := true;
  self.LblMaxDim.Location := new System.Drawing.Point(110, 14);
  self.LblMaxDim.Name := 'LblMaxDim';
  self.LblMaxDim.Size := new System.Drawing.Size(26, 13);
  self.LblMaxDim.TabIndex := 1;
  self.LblMaxDim.Text := 'max';
  self.LblMinDim.AutoSize := true;
  self.LblMinDim.Location := new System.Drawing.Point(56, 14);
  self.LblMinDim.Name := 'LblMinDim';
  self.LblMinDim.Size := new System.Drawing.Size(23, 13);
  self.LblMinDim.TabIndex := 0;
  self.LblMinDim.Text := 'min';
  self.TabNodeText.Controls.Add(self.BtnFontColor);
  self.TabNodeText.Controls.Add(self.BtnTextFont);
  self.TabNodeText.Controls.Add(self.GrpTextPosition);
  self.TabNodeText.Controls.Add(self.GrpTextFormat);
  self.TabNodeText.Controls.Add(self.GtgpTextBorders);
  self.TabNodeText.Location := new System.Drawing.Point(4, 22);
  self.TabNodeText.Name := 'TabNodeText';
  self.TabNodeText.Padding := new System.Windows.Forms.Padding(3);
  self.TabNodeText.Size := new System.Drawing.Size(186, 576);
  self.TabNodeText.TabIndex := 1;
  self.TabNodeText.Text := 'Text';
  self.TabNodeText.UseVisualStyleBackColor := true;
  self.BtnFontColor.Anchor := (System.Windows.Forms.AnchorStyles.Top or System.Windows.Forms.AnchorStyles.Left or System.Windows.Forms.AnchorStyles.Right as System.Windows.Forms.AnchorStyles);
  self.BtnFontColor.Location := new System.Drawing.Point(7, 319);
  self.BtnFontColor.Name := 'BtnFontColor';
  self.BtnFontColor.Size := new System.Drawing.Size(175, 23);
  self.BtnFontColor.TabIndex := 42;
  self.BtnFontColor.Text := 'Font color ...';
  self.BtnFontColor.UseVisualStyleBackColor := true;
  self.BtnFontColor.Click += new System.EventHandler(self.BtnFontColor_Click);
  self.BtnTextFont.Anchor := (System.Windows.Forms.AnchorStyles.Top or System.Windows.Forms.AnchorStyles.Left or System.Windows.Forms.AnchorStyles.Right as System.Windows.Forms.AnchorStyles);
  self.BtnTextFont.Location := new System.Drawing.Point(6, 290);
  self.BtnTextFont.Name := 'BtnTextFont';
  self.BtnTextFont.Size := new System.Drawing.Size(175, 23);
  self.BtnTextFont.TabIndex := 41;
  self.BtnTextFont.Text := 'Font ...';
  self.BtnTextFont.UseVisualStyleBackColor := true;
  self.BtnTextFont.Click += new System.EventHandler(self.BtnTextFont_Click);
  self.GrpTextPosition.Controls.Add(self.LblMR);
  self.GrpTextPosition.Controls.Add(self.LblBR);
  self.GrpTextPosition.Controls.Add(self.LblTR);
  self.GrpTextPosition.Controls.Add(self.LblMC);
  self.GrpTextPosition.Controls.Add(self.LblBC);
  self.GrpTextPosition.Controls.Add(self.LblTC);
  self.GrpTextPosition.Controls.Add(self.LblML);
  self.GrpTextPosition.Controls.Add(self.LblBL);
  self.GrpTextPosition.Controls.Add(self.LblTL);
  self.GrpTextPosition.Dock := System.Windows.Forms.DockStyle.Top;
  self.GrpTextPosition.Location := new System.Drawing.Point(3, 209);
  self.GrpTextPosition.Name := 'GrpTextPosition';
  self.GrpTextPosition.Size := new System.Drawing.Size(180, 75);
  self.GrpTextPosition.TabIndex := 30;
  self.GrpTextPosition.TabStop := false;
  self.GrpTextPosition.Text := 'P&osition';
  self.LblMR.Location := new System.Drawing.Point(135, 36);
  self.LblMR.Name := 'LblMR';
  self.LblMR.Size := new System.Drawing.Size(35, 13);
  self.LblMR.TabIndex := 5;
  self.LblMR.Tag := #55;
  self.LblMR.Text := 'TEXT';
  self.LblMR.TextAlign := System.Drawing.ContentAlignment.TopCenter;
  self.LblMR.Click += new System.EventHandler(self.LblPos_Click);
  self.LblBR.Location := new System.Drawing.Point(135, 52);
  self.LblBR.Name := 'LblBR';
  self.LblBR.Size := new System.Drawing.Size(35, 13);
  self.LblBR.TabIndex := 8;
  self.LblBR.Tag := #52;
  self.LblBR.Text := 'TEXT';
  self.LblBR.TextAlign := System.Drawing.ContentAlignment.TopCenter;
  self.LblBR.Click += new System.EventHandler(self.LblPos_Click);
  self.LblTR.Location := new System.Drawing.Point(135, 20);
  self.LblTR.Name := 'LblTR';
  self.LblTR.Size := new System.Drawing.Size(35, 13);
  self.LblTR.TabIndex := 2;
  self.LblTR.Tag := #49;
  self.LblTR.Text := 'TEXT';
  self.LblTR.TextAlign := System.Drawing.ContentAlignment.TopCenter;
  self.LblTR.Click += new System.EventHandler(self.LblPos_Click);
  self.LblMC.Location := new System.Drawing.Point(72, 36);
  self.LblMC.Name := 'LblMC';
  self.LblMC.Size := new System.Drawing.Size(35, 13);
  self.LblMC.TabIndex := 4;
  self.LblMC.Tag := #56;
  self.LblMC.Text := 'TEXT';
  self.LblMC.TextAlign := System.Drawing.ContentAlignment.TopCenter;
  self.LblMC.Click += new System.EventHandler(self.LblPos_Click);
  self.LblBC.Location := new System.Drawing.Point(72, 52);
  self.LblBC.Name := 'LblBC';
  self.LblBC.Size := new System.Drawing.Size(35, 13);
  self.LblBC.TabIndex := 7;
  self.LblBC.Tag := #53;
  self.LblBC.Text := 'TEXT';
  self.LblBC.TextAlign := System.Drawing.ContentAlignment.TopCenter;
  self.LblBC.Click += new System.EventHandler(self.LblPos_Click);
  self.LblTC.Location := new System.Drawing.Point(72, 20);
  self.LblTC.Name := 'LblTC';
  self.LblTC.Size := new System.Drawing.Size(35, 13);
  self.LblTC.TabIndex := 1;
  self.LblTC.Tag := #50;
  self.LblTC.Text := 'TEXT';
  self.LblTC.TextAlign := System.Drawing.ContentAlignment.TopCenter;
  self.LblTC.Click += new System.EventHandler(self.LblPos_Click);
  self.LblML.Location := new System.Drawing.Point(10, 36);
  self.LblML.Name := 'LblML';
  self.LblML.Size := new System.Drawing.Size(35, 13);
  self.LblML.TabIndex := 3;
  self.LblML.Tag := #54;
  self.LblML.Text := 'TEXT';
  self.LblML.TextAlign := System.Drawing.ContentAlignment.TopCenter;
  self.LblML.Click += new System.EventHandler(self.LblPos_Click);
  self.LblBL.Location := new System.Drawing.Point(10, 52);
  self.LblBL.Name := 'LblBL';
  self.LblBL.Size := new System.Drawing.Size(35, 13);
  self.LblBL.TabIndex := 6;
  self.LblBL.Tag := #51;
  self.LblBL.Text := 'TEXT';
  self.LblBL.TextAlign := System.Drawing.ContentAlignment.TopCenter;
  self.LblBL.Click += new System.EventHandler(self.LblPos_Click);
  self.LblTL.Location := new System.Drawing.Point(10, 20);
  self.LblTL.Name := 'LblTL';
  self.LblTL.Size := new System.Drawing.Size(35, 13);
  self.LblTL.TabIndex := 0;
  self.LblTL.Tag := #48;
  self.LblTL.Text := 'TEXT';
  self.LblTL.TextAlign := System.Drawing.ContentAlignment.TopCenter;
  self.LblTL.Click += new System.EventHandler(self.LblPos_Click);
  self.GrpTextFormat.Controls.Add(self.LblLineSpace);
  self.GrpTextFormat.Controls.Add(self.LblPercent);
  self.GrpTextFormat.Controls.Add(self.EditLineSpace);
  self.GrpTextFormat.Controls.Add(self.LblCharacters);
  self.GrpTextFormat.Controls.Add(self.EditTrim);
  self.GrpTextFormat.Controls.Add(self.ChkTrim);
  self.GrpTextFormat.Controls.Add(self.ChkClip);
  self.GrpTextFormat.Controls.Add(self.ChkWrap);
  self.GrpTextFormat.Dock := System.Windows.Forms.DockStyle.Top;
  self.GrpTextFormat.Location := new System.Drawing.Point(3, 103);
  self.GrpTextFormat.Name := 'GrpTextFormat';
  self.GrpTextFormat.Size := new System.Drawing.Size(180, 106);
  self.GrpTextFormat.TabIndex := 20;
  self.GrpTextFormat.TabStop := false;
  self.GrpTextFormat.Text := 'For&mat';
  self.LblLineSpace.AutoSize := true;
  self.LblLineSpace.Location := new System.Drawing.Point(4, 80);
  self.LblLineSpace.Name := 'LblLineSpace';
  self.LblLineSpace.Size := new System.Drawing.Size(59, 13);
  self.LblLineSpace.TabIndex := 8;
  self.LblLineSpace.Text := '&Line space';
  self.LblPercent.AutoSize := true;
  self.LblPercent.Location := new System.Drawing.Point(121, 80);
  self.LblPercent.Name := 'LblPercent';
  self.LblPercent.Size := new System.Drawing.Size(15, 13);
  self.LblPercent.TabIndex := 7;
  self.LblPercent.Text := '%';
  self.EditLineSpace.Location := new System.Drawing.Point(64, 76);
  self.EditLineSpace.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditLineSpace.Name := 'EditLineSpace';
  self.EditLineSpace.Size := new System.Drawing.Size(50, 20);
  self.EditLineSpace.TabIndex := 6;
  self.EditLineSpace.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditLineSpace.ValueChanged += new System.EventHandler(self.EditFormat_ValueChanged);
  self.LblCharacters.AutoSize := true;
  self.LblCharacters.Location := new System.Drawing.Point(121, 56);
  self.LblCharacters.Name := 'LblCharacters';
  self.LblCharacters.Size := new System.Drawing.Size(57, 13);
  self.LblCharacters.TabIndex := 5;
  self.LblCharacters.Text := 'characters';
  self.EditTrim.Location := new System.Drawing.Point(64, 52);
  self.EditTrim.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditTrim.Name := 'EditTrim';
  self.EditTrim.Size := new System.Drawing.Size(50, 20);
  self.EditTrim.TabIndex := 4;
  self.EditTrim.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditTrim.ValueChanged += new System.EventHandler(self.EditFormat_ValueChanged);
  self.ChkTrim.AutoSize := true;
  self.ChkTrim.Location := new System.Drawing.Point(6, 54);
  self.ChkTrim.Name := 'ChkTrim';
  self.ChkTrim.Size := new System.Drawing.Size(58, 17);
  self.ChkTrim.TabIndex := 2;
  self.ChkTrim.Text := 'Trim to';
  self.ChkTrim.UseVisualStyleBackColor := true;
  self.ChkTrim.Click += new System.EventHandler(self.EditFormat_ValueChanged);
  self.ChkClip.AutoSize := true;
  self.ChkClip.Location := new System.Drawing.Point(64, 32);
  self.ChkClip.Name := 'ChkClip';
  self.ChkClip.Size := new System.Drawing.Size(43, 17);
  self.ChkClip.TabIndex := 1;
  self.ChkClip.Text := 'Clip';
  self.ChkClip.UseVisualStyleBackColor := true;
  self.ChkClip.Click += new System.EventHandler(self.EditFormat_ValueChanged);
  self.ChkWrap.AutoSize := true;
  self.ChkWrap.Location := new System.Drawing.Point(64, 12);
  self.ChkWrap.Name := 'ChkWrap';
  self.ChkWrap.Size := new System.Drawing.Size(52, 17);
  self.ChkWrap.TabIndex := 0;
  self.ChkWrap.Text := 'Wrap';
  self.ChkWrap.UseVisualStyleBackColor := true;
  self.ChkWrap.Click += new System.EventHandler(self.EditFormat_ValueChanged);
  self.GtgpTextBorders.Controls.Add(self.EditTextBorderRight);
  self.GtgpTextBorders.Controls.Add(self.EditTextBorderBottom);
  self.GtgpTextBorders.Controls.Add(self.EditTextBorderTop);
  self.GtgpTextBorders.Controls.Add(self.EditTextBorderLeft);
  self.GtgpTextBorders.Controls.Add(self.pictureBox1);
  self.GtgpTextBorders.Dock := System.Windows.Forms.DockStyle.Top;
  self.GtgpTextBorders.Location := new System.Drawing.Point(3, 3);
  self.GtgpTextBorders.Name := 'GtgpTextBorders';
  self.GtgpTextBorders.Size := new System.Drawing.Size(180, 100);
  self.GtgpTextBorders.TabIndex := 10;
  self.GtgpTextBorders.TabStop := false;
  self.GtgpTextBorders.Text := 'Text Borders';
  self.EditTextBorderRight.Location := new System.Drawing.Point(120, 45);
  self.EditTextBorderRight.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditTextBorderRight.Name := 'EditTextBorderRight';
  self.EditTextBorderRight.Size := new System.Drawing.Size(50, 20);
  self.EditTextBorderRight.TabIndex := 5;
  self.EditTextBorderRight.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditTextBorderRight.ValueChanged += new System.EventHandler(self.EditFormat_ValueChanged);
  self.EditTextBorderBottom.Location := new System.Drawing.Point(64, 70);
  self.EditTextBorderBottom.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditTextBorderBottom.Name := 'EditTextBorderBottom';
  self.EditTextBorderBottom.Size := new System.Drawing.Size(50, 20);
  self.EditTextBorderBottom.TabIndex := 4;
  self.EditTextBorderBottom.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditTextBorderBottom.ValueChanged += new System.EventHandler(self.EditFormat_ValueChanged);
  self.EditTextBorderTop.Location := new System.Drawing.Point(64, 20);
  self.EditTextBorderTop.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditTextBorderTop.Name := 'EditTextBorderTop';
  self.EditTextBorderTop.Size := new System.Drawing.Size(50, 20);
  self.EditTextBorderTop.TabIndex := 3;
  self.EditTextBorderTop.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditTextBorderTop.ValueChanged += new System.EventHandler(self.EditFormat_ValueChanged);
  self.EditTextBorderLeft.Location := new System.Drawing.Point(8, 45);
  self.EditTextBorderLeft.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditTextBorderLeft.Name := 'EditTextBorderLeft';
  self.EditTextBorderLeft.Size := new System.Drawing.Size(50, 20);
  self.EditTextBorderLeft.TabIndex := 2;
  self.EditTextBorderLeft.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditTextBorderLeft.ValueChanged += new System.EventHandler(self.EditFormat_ValueChanged);
  self.pictureBox1.Image := DEXiWin.Properties.Resources.TextBorder;
  self.pictureBox1.Location := new System.Drawing.Point(64, 44);
  self.pictureBox1.Name := 'pictureBox1';
  self.pictureBox1.Size := new System.Drawing.Size(50, 22);
  self.pictureBox1.SizeMode := System.Windows.Forms.PictureBoxSizeMode.AutoSize;
  self.pictureBox1.TabIndex := 0;
  self.pictureBox1.TabStop := false;
  self.PanelNodeFormat.Controls.Add(self.BtnResetFormat);
  self.PanelNodeFormat.Controls.Add(self.LblNodeFormat);
  self.PanelNodeFormat.Controls.Add(self.EditNodeFormat);
  self.PanelNodeFormat.Dock := System.Windows.Forms.DockStyle.Top;
  self.PanelNodeFormat.Location := new System.Drawing.Point(3, 3);
  self.PanelNodeFormat.Name := 'PanelNodeFormat';
  self.PanelNodeFormat.Size := new System.Drawing.Size(194, 83);
  self.PanelNodeFormat.TabIndex := 0;
  self.BtnResetFormat.Anchor := (System.Windows.Forms.AnchorStyles.Top or System.Windows.Forms.AnchorStyles.Left or System.Windows.Forms.AnchorStyles.Right as System.Windows.Forms.AnchorStyles);
  self.BtnResetFormat.Location := new System.Drawing.Point(10, 49);
  self.BtnResetFormat.Name := 'BtnResetFormat';
  self.BtnResetFormat.Size := new System.Drawing.Size(175, 23);
  self.BtnResetFormat.TabIndex := 2;
  self.BtnResetFormat.Text := 'Reset format';
  self.BtnResetFormat.UseVisualStyleBackColor := true;
  self.BtnResetFormat.Click += new System.EventHandler(self.BtnResetFormat_Click);
  self.LblNodeFormat.AutoSize := true;
  self.LblNodeFormat.Location := new System.Drawing.Point(8, 6);
  self.LblNodeFormat.Name := 'LblNodeFormat';
  self.LblNodeFormat.Size := new System.Drawing.Size(72, 13);
  self.LblNodeFormat.TabIndex := 0;
  self.LblNodeFormat.Text := 'Edit &format of:';
  self.EditNodeFormat.DrawMode := System.Windows.Forms.DrawMode.OwnerDrawFixed;
  self.EditNodeFormat.DropDownStyle := System.Windows.Forms.ComboBoxStyle.DropDownList;
  self.EditNodeFormat.FormattingEnabled := true;
  self.EditNodeFormat.Items.AddRange(array of System.Object(['selected node(s)', 'whole tree', 'aggregate attributes', 'basic attributes', 'discrete inputs', 'continuous inputs', 'link attributes', 'root attributes', 'collapsed nodes']));
  self.EditNodeFormat.Location := new System.Drawing.Point(11, 22);
  self.EditNodeFormat.Name := 'EditNodeFormat';
  self.EditNodeFormat.Size := new System.Drawing.Size(174, 21);
  self.EditNodeFormat.TabIndex := 1;
  self.EditNodeFormat.DrawItem += new System.Windows.Forms.DrawItemEventHandler(self.EditNodeFormat_DrawItem);
  self.EditNodeFormat.SelectedIndexChanged += new System.EventHandler(self.EditNodeFormat_SelectedIndexChanged);
  self.EditNodeFormat.Validating += new System.ComponentModel.CancelEventHandler(self.EditNodeFormat_Validating);
  self.TreePicture.Location := new System.Drawing.Point(0, 0);
  self.TreePicture.Name := 'TreePicture';
  self.TreePicture.Size := new System.Drawing.Size(100, 50);
  self.TreePicture.SizeMode := System.Windows.Forms.PictureBoxSizeMode.StretchImage;
  self.TreePicture.TabIndex := 0;
  self.TreePicture.TabStop := false;
  self.TreePicture.MouseClick += new System.Windows.Forms.MouseEventHandler(self.TreePicture_MouseClick);
  self.DlgColor.AnyColor := true;
  self.TreeMenu.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemPopActualSize, self.ItemPopFullPage, self.ItemPopPageWidth, self.toolStripSeparator2, self.ItemPopCopyMetafile, self.ItemPopCopyBitmap]));
  self.TreeMenu.Name := 'ReportMenu';
  self.TreeMenu.Size := new System.Drawing.Size(163, 120);
  self.ItemPopActualSize.Image := DEXiWin.Properties.Resources.PrevZoom100;
  self.ItemPopActualSize.Name := 'ItemPopActualSize';
  self.ItemPopActualSize.Size := new System.Drawing.Size(162, 22);
  self.ItemPopActualSize.Text := 'Actual Size';
  self.ItemPopActualSize.Click += new System.EventHandler(self.ItemPopActualSize_Click);
  self.ItemPopFullPage.Image := DEXiWin.Properties.Resources.PrevZoomFullPage;
  self.ItemPopFullPage.Name := 'ItemPopFullPage';
  self.ItemPopFullPage.Size := new System.Drawing.Size(162, 22);
  self.ItemPopFullPage.Text := 'Full Page';
  self.ItemPopFullPage.Click += new System.EventHandler(self.ItemPopFullPage_Click);
  self.ItemPopPageWidth.Image := DEXiWin.Properties.Resources.PrevZoomPageWidth;
  self.ItemPopPageWidth.Name := 'ItemPopPageWidth';
  self.ItemPopPageWidth.Size := new System.Drawing.Size(162, 22);
  self.ItemPopPageWidth.Text := 'Page Width';
  self.ItemPopPageWidth.Click += new System.EventHandler(self.ItemPopPageWidth_Click);
  self.toolStripSeparator2.Name := 'toolStripSeparator2';
  self.toolStripSeparator2.Size := new System.Drawing.Size(159, 6);
  self.ItemPopCopyMetafile.Image := (resources.GetObject('ItemPopCopyMetafile.Image') as System.Drawing.Image);
  self.ItemPopCopyMetafile.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemPopCopyMetafile.Name := 'ItemPopCopyMetafile';
  self.ItemPopCopyMetafile.Size := new System.Drawing.Size(162, 22);
  self.ItemPopCopyMetafile.Text := '&Copy as Metafile';
  self.ItemPopCopyMetafile.ToolTipText := 'Copy report page as a Metafile';
  self.ItemPopCopyMetafile.Click += new System.EventHandler(self.ItemMenuCopyMetafile_Click);
  self.ItemPopCopyBitmap.Image := (resources.GetObject('ItemPopCopyBitmap.Image') as System.Drawing.Image);
  self.ItemPopCopyBitmap.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemPopCopyBitmap.Name := 'ItemPopCopyBitmap';
  self.ItemPopCopyBitmap.Size := new System.Drawing.Size(162, 22);
  self.ItemPopCopyBitmap.Text := 'Copy as &Bitmap';
  self.ItemPopCopyBitmap.ToolTipText := 'Copy report page as a Bitmap';
  self.ItemPopCopyBitmap.Click += new System.EventHandler(self.ItemMenuCopyBitmap_Click);
  self.TreePanel.AutoScroll := true;
  self.TreePanel.Controls.Add(self.TreePicture);
  self.TreePanel.Dock := System.Windows.Forms.DockStyle.Fill;
  self.TreePanel.Location := new System.Drawing.Point(0, 49);
  self.TreePanel.Name := 'TreePanel';
  self.TreePanel.Size := new System.Drawing.Size(1078, 717);
  self.TreePanel.TabIndex := 5;
  self.SaveTreeDialog.Filter := 'Metafile|*.emf|Bitmap|*.png';
  self.SaveTreeDialog.Title := 'Save tree graphic as';
  self.AutoScroll := true;
  self.ContextMenuStrip := self.TreeMenu;
  self.Controls.Add(self.TreePanel);
  self.Controls.Add(self.CtrlPanel);
  self.Controls.Add(self.FormTool);
  self.Controls.Add(self.FormMenu);
  self.Name := 'CtrlFormTree';
  self.Size := new System.Drawing.Size(1286, 766);
  self.VisibleChanged += new System.EventHandler(self.CtrlFormTree_VisibleChanged);
  self.Resize += new System.EventHandler(self.CtrlFormTree_Resize);
  self.FormTool.ResumeLayout(false);
  self.FormTool.PerformLayout();
  self.FormMenu.ResumeLayout(false);
  self.FormMenu.PerformLayout();
  self.CtrlPanel.ResumeLayout(false);
  self.TabFormat.ResumeLayout(false);
  self.TabTree.ResumeLayout(false);
  self.GrpPrune.ResumeLayout(false);
  self.GrpPlacement.ResumeLayout(false);
  self.GrpPlacement.PerformLayout();
  self.GrpSeparation.ResumeLayout(false);
  self.GrpSeparation.PerformLayout();
  (self.PicSeparation as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditMinLevelSep as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditLevelSep as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditNodeSep as System.ComponentModel.ISupportInitialize).EndInit();
  self.GrpBorders.ResumeLayout(false);
  self.GrpBorders.PerformLayout();
  (self.EditBorderRight as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditBorderBottom as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditBorderTop as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditBorderLeft as System.ComponentModel.ISupportInitialize).EndInit();
  (self.PicBorders as System.ComponentModel.ISupportInitialize).EndInit();
  self.GrpStretch.ResumeLayout(false);
  self.GrpStretch.PerformLayout();
  (self.PicStretch as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditStretchY as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditStretchX as System.ComponentModel.ISupportInitialize).EndInit();
  self.TabNode.ResumeLayout(false);
  self.TabNodeFormat.ResumeLayout(false);
  self.TabNodeGraphic.ResumeLayout(false);
  self.GrpBottomAnchor.ResumeLayout(false);
  self.GrpBottomAnchor.PerformLayout();
  (self.EditBottomAnchorVertical as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditBottomAnchorHorizontal as System.ComponentModel.ISupportInitialize).EndInit();
  self.GrpTopAnchor.ResumeLayout(false);
  self.GrpTopAnchor.PerformLayout();
  (self.EditTopAnchorVertical as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditTopAnchorHorizontal as System.ComponentModel.ISupportInitialize).EndInit();
  self.GrpNodeAlignment.ResumeLayout(false);
  self.GrpNodeAlignment.PerformLayout();
  self.GrpNodeGraphic.ResumeLayout(false);
  (self.PicNode as System.ComponentModel.ISupportInitialize).EndInit();
  self.GrpDimensions.ResumeLayout(false);
  self.GrpDimensions.PerformLayout();
  (self.EditMaxHeight as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditMinHeight as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditMaxWidth as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditMinWidth as System.ComponentModel.ISupportInitialize).EndInit();
  self.TabNodeText.ResumeLayout(false);
  self.GrpTextPosition.ResumeLayout(false);
  self.GrpTextFormat.ResumeLayout(false);
  self.GrpTextFormat.PerformLayout();
  (self.EditLineSpace as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditTrim as System.ComponentModel.ISupportInitialize).EndInit();
  self.GtgpTextBorders.ResumeLayout(false);
  self.GtgpTextBorders.PerformLayout();
  (self.EditTextBorderRight as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditTextBorderBottom as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditTextBorderTop as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditTextBorderLeft as System.ComponentModel.ISupportInitialize).EndInit();
  (self.pictureBox1 as System.ComponentModel.ISupportInitialize).EndInit();
  self.PanelNodeFormat.ResumeLayout(false);
  self.PanelNodeFormat.PerformLayout();
  (self.TreePicture as System.ComponentModel.ISupportInitialize).EndInit();
  self.TreeMenu.ResumeLayout(false);
  self.TreePanel.ResumeLayout(false);
  self.ResumeLayout(false);
  self.PerformLayout();
end;
{$ENDREGION}

end.