namespace DexiWin;

interface

{$HIDE H7}

uses
  System.Drawing,
  System.Collections,
  System.Windows.Forms,
  System.ComponentModel;

type
  CtrlFormModel = public partial class
  {$REGION Windows Control Designer generated fields}
  private
    ItemPopAttDescr: System.Windows.Forms.ToolStripMenuItem;
    ItemPopSelectScale: System.Windows.Forms.ToolStripMenuItem;
    ItemPopEditScale: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuSelectScale: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuResizeColumns: System.Windows.Forms.ToolStripMenuItem;
    
    toolStripSeparator18: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator17: System.Windows.Forms.ToolStripSeparator;
    ItemMenuViewTree: System.Windows.Forms.ToolStripMenuItem;
    ItemPopEditFunction: System.Windows.Forms.ToolStripMenuItem;
    BtnError: System.Windows.Forms.ToolStripButton;
    toolStripSeparator16: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator15: System.Windows.Forms.ToolStripSeparator;
    
    
    
    BtnEditFunct: System.Windows.Forms.Button;
    BtnSelectScale: System.Windows.Forms.Button;
    BtnEditScale: System.Windows.Forms.Button;
    toolStripSeparator13: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator14: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator11: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator12: System.Windows.Forms.ToolStripSeparator;
    ModelMenu: System.Windows.Forms.ContextMenuStrip;
    
    ItemMenuEditFunction: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuDeleteFunction: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuEditScale: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuDeleteScale: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuReverseScale: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuScale: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuFunction: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator10: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator9: System.Windows.Forms.ToolStripSeparator;
    ItemMenuFindNext: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator8: System.Windows.Forms.ToolStripSeparator;
    ItemMenuSearch: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuPaste: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuCut: System.Windows.Forms.ToolStripMenuItem;
    ItemToolPaste: System.Windows.Forms.ToolStripButton;
    ItemToolCut: System.Windows.Forms.ToolStripButton;
    ItemToolCopy: System.Windows.Forms.ToolStripButton;
    ItemMenuCopy: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator7: System.Windows.Forms.ToolStripSeparator;
    ToolTips: System.Windows.Forms.ToolTip;
    BtnAttDescr: System.Windows.Forms.Button;
    ItemMenuAttDescr: System.Windows.Forms.ToolStripMenuItem;
    ItemToolAttDescr: System.Windows.Forms.ToolStripButton;
    toolStripSeparator6: System.Windows.Forms.ToolStripSeparator;
    ItemMenuViewAttributePanel: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuViewDescription: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuViewScale: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuViewFunction: System.Windows.Forms.ToolStripMenuItem;
    TextDescription: System.Windows.Forms.TextBox;
    TextName: System.Windows.Forms.TextBox;
    LblDescription: System.Windows.Forms.Label;
    LblName: System.Windows.Forms.Label;
    AttPanel: System.Windows.Forms.Panel;
    toolStripSeparator4: System.Windows.Forms.ToolStripSeparator;
    ItemToolModelDescr: System.Windows.Forms.ToolStripButton;
    toolStripSeparator5: System.Windows.Forms.ToolStripSeparator;
    ItemMenuModelDescr: System.Windows.Forms.ToolStripMenuItem;
    ItemToolAddAttribute: System.Windows.Forms.ToolStripButton;
    ItemToolAddChild: System.Windows.Forms.ToolStripButton;
    ItemToolDeleteAttribute: System.Windows.Forms.ToolStripButton;
    ItemToolDuplicateAttribute: System.Windows.Forms.ToolStripButton;
    toolStripSeparator2: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator3: System.Windows.Forms.ToolStripSeparator;
    ItemToolMoveUp: System.Windows.Forms.ToolStripButton;
    ItemToolMoveDown: System.Windows.Forms.ToolStripButton;
    ItemMenuAddChild: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuDeleteAttribute: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuDuplicateAttribute: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuAddAttribute: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuEdit: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator1: System.Windows.Forms.ToolStripSeparator;
    ItemMenuMoveUp: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuMoveDown: System.Windows.Forms.ToolStripMenuItem;
    FunctionText: System.Windows.Forms.RichTextBox;
    LblFunction: System.Windows.Forms.Label;
    ScaleText: System.Windows.Forms.RichTextBox;
    LblScale: System.Windows.Forms.Label;
    ItemToolExpandAll: System.Windows.Forms.ToolStripButton;
    ItemToolExpandOne: System.Windows.Forms.ToolStripButton;
    ItemToolCollapseAll: System.Windows.Forms.ToolStripButton;
    ItemToolCollapseOne: System.Windows.Forms.ToolStripButton;
    ItemMenuView: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuExpandAll: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuExpandOne: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuCollapseAll: System.Windows.Forms.ToolStripMenuItem;
    ItemMenuCollapseOne: System.Windows.Forms.ToolStripMenuItem;
    ItemPopSearch: System.Windows.Forms.ToolStripMenuItem;
    ItemPopFindNext: System.Windows.Forms.ToolStripMenuItem;
    ItemPopCut: System.Windows.Forms.ToolStripMenuItem;
    ItemPopCopy: System.Windows.Forms.ToolStripMenuItem;
    ItemPopPaste: System.Windows.Forms.ToolStripMenuItem;
    ItemPopAddAttribute: System.Windows.Forms.ToolStripMenuItem;
    ItemPopAddChild: System.Windows.Forms.ToolStripMenuItem;
    ItemPopDeleteAttribute: System.Windows.Forms.ToolStripMenuItem;
    ItemPopDuplicateAttribute: System.Windows.Forms.ToolStripMenuItem;
    ItemPopMoveUp: System.Windows.Forms.ToolStripMenuItem;
    ItemPopMoveDown: System.Windows.Forms.ToolStripMenuItem;
    ItemPopDeleteScale: System.Windows.Forms.ToolStripMenuItem;
    ItemPopDeleteFunction: System.Windows.Forms.ToolStripMenuItem;
    ColDescription: BrightIdeasSoftware.OLVColumn;
    ColScale: BrightIdeasSoftware.OLVColumn;
    ColFunction: BrightIdeasSoftware.OLVColumn;
    ColName: BrightIdeasSoftware.OLVColumn;
    ModelSplitter: System.Windows.Forms.Splitter;
    FormSplit: System.Windows.Forms.Splitter;
    TreeViewModel: BrightIdeasSoftware.TreeListView;
    FormMenu: System.Windows.Forms.MenuStrip;
    FormTool: System.Windows.Forms.ToolStrip;
    components: System.ComponentModel.Container := nil;
    method InitializeComponent;
  {$ENDREGION}
  end;

implementation

{$REGION Windows Control Designer generated code}
method CtrlFormModel.InitializeComponent;
begin
  self.components := new System.ComponentModel.Container();
  var resources: System.ComponentModel.ComponentResourceManager := new System.ComponentModel.ComponentResourceManager(typeOf(CtrlFormModel));
  self.FormMenu := new System.Windows.Forms.MenuStrip();
  self.ItemMenuEdit := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator18 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuModelDescr := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuAttDescr := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator8 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuSearch := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuFindNext := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator4 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuCut := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuCopy := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuPaste := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator1 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuAddAttribute := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuAddChild := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuDeleteAttribute := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuDuplicateAttribute := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator9 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuMoveUp := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuMoveDown := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator10 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuScale := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuEditScale := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuSelectScale := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuDeleteScale := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuReverseScale := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuFunction := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuEditFunction := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuDeleteFunction := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuView := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuExpandAll := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuExpandOne := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuCollapseAll := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuCollapseOne := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuResizeColumns := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator6 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuViewAttributePanel := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuViewDescription := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuViewScale := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemMenuViewFunction := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator17 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemMenuViewTree := new System.Windows.Forms.ToolStripMenuItem();
  self.FormTool := new System.Windows.Forms.ToolStrip();
  self.ItemToolModelDescr := new System.Windows.Forms.ToolStripButton();
  self.ItemToolAttDescr := new System.Windows.Forms.ToolStripButton();
  self.toolStripSeparator5 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemToolCut := new System.Windows.Forms.ToolStripButton();
  self.ItemToolCopy := new System.Windows.Forms.ToolStripButton();
  self.ItemToolPaste := new System.Windows.Forms.ToolStripButton();
  self.toolStripSeparator2 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemToolAddAttribute := new System.Windows.Forms.ToolStripButton();
  self.ItemToolAddChild := new System.Windows.Forms.ToolStripButton();
  self.ItemToolDeleteAttribute := new System.Windows.Forms.ToolStripButton();
  self.ItemToolDuplicateAttribute := new System.Windows.Forms.ToolStripButton();
  self.toolStripSeparator3 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemToolMoveDown := new System.Windows.Forms.ToolStripButton();
  self.ItemToolMoveUp := new System.Windows.Forms.ToolStripButton();
  self.toolStripSeparator7 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemToolExpandAll := new System.Windows.Forms.ToolStripButton();
  self.ItemToolExpandOne := new System.Windows.Forms.ToolStripButton();
  self.ItemToolCollapseAll := new System.Windows.Forms.ToolStripButton();
  self.ItemToolCollapseOne := new System.Windows.Forms.ToolStripButton();
  self.BtnError := new System.Windows.Forms.ToolStripButton();
  self.TreeViewModel := new BrightIdeasSoftware.TreeListView();
  self.ColName := (new BrightIdeasSoftware.OLVColumn() as BrightIdeasSoftware.OLVColumn);
  self.ColDescription := (new BrightIdeasSoftware.OLVColumn() as BrightIdeasSoftware.OLVColumn);
  self.ColScale := (new BrightIdeasSoftware.OLVColumn() as BrightIdeasSoftware.OLVColumn);
  self.ColFunction := (new BrightIdeasSoftware.OLVColumn() as BrightIdeasSoftware.OLVColumn);
  self.ModelMenu := new System.Windows.Forms.ContextMenuStrip(self.components);
  self.ItemPopCut := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopCopy := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopPaste := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator11 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopAddAttribute := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopAddChild := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopDeleteAttribute := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopDuplicateAttribute := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator13 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopMoveUp := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopMoveDown := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator14 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopAttDescr := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator15 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopEditScale := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopSelectScale := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopDeleteScale := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator16 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopEditFunction := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopDeleteFunction := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator12 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopSearch := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopFindNext := new System.Windows.Forms.ToolStripMenuItem();
  self.FormSplit := new System.Windows.Forms.Splitter();
  self.AttPanel := new System.Windows.Forms.Panel();
  self.BtnEditFunct := new System.Windows.Forms.Button();
  self.BtnSelectScale := new System.Windows.Forms.Button();
  self.BtnEditScale := new System.Windows.Forms.Button();
  self.BtnAttDescr := new System.Windows.Forms.Button();
  self.FunctionText := new System.Windows.Forms.RichTextBox();
  self.LblFunction := new System.Windows.Forms.Label();
  self.LblScale := new System.Windows.Forms.Label();
  self.ScaleText := new System.Windows.Forms.RichTextBox();
  self.TextDescription := new System.Windows.Forms.TextBox();
  self.TextName := new System.Windows.Forms.TextBox();
  self.LblDescription := new System.Windows.Forms.Label();
  self.LblName := new System.Windows.Forms.Label();
  self.ModelSplitter := new System.Windows.Forms.Splitter();
  self.ToolTips := new System.Windows.Forms.ToolTip(self.components);
  self.FormMenu.SuspendLayout();
  self.FormTool.SuspendLayout();
  (self.TreeViewModel as System.ComponentModel.ISupportInitialize).BeginInit();
  self.ModelMenu.SuspendLayout();
  self.AttPanel.SuspendLayout();
  self.SuspendLayout();
  self.FormMenu.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemMenuEdit, self.ItemMenuView]));
  self.FormMenu.Location := new System.Drawing.Point(0, 0);
  self.FormMenu.Name := 'FormMenu';
  self.FormMenu.Size := new System.Drawing.Size(1332, 24);
  self.FormMenu.TabIndex := 0;
  self.FormMenu.Text := 'menuStrip1';
  self.ItemMenuEdit.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.toolStripSeparator18, self.ItemMenuModelDescr, self.ItemMenuAttDescr, self.toolStripSeparator8, self.ItemMenuSearch, self.ItemMenuFindNext, self.toolStripSeparator4, self.ItemMenuCut, self.ItemMenuCopy, self.ItemMenuPaste, self.toolStripSeparator1, self.ItemMenuAddAttribute, self.ItemMenuAddChild, self.ItemMenuDeleteAttribute, self.ItemMenuDuplicateAttribute, self.toolStripSeparator9, self.ItemMenuMoveUp, self.ItemMenuMoveDown, self.toolStripSeparator10, self.ItemMenuScale, self.ItemMenuFunction]));
  self.ItemMenuEdit.MergeAction := System.Windows.Forms.MergeAction.MatchOnly;
  self.ItemMenuEdit.MergeIndex := 11;
  self.ItemMenuEdit.Name := 'ItemMenuEdit';
  self.ItemMenuEdit.Size := new System.Drawing.Size(39, 20);
  self.ItemMenuEdit.Text := '&Edit';
  self.toolStripSeparator18.Name := 'toolStripSeparator18';
  self.toolStripSeparator18.Size := new System.Drawing.Size(211, 6);
  self.ItemMenuModelDescr.Image := DEXiWin.Properties.Resources.ImgModelDescr;
  self.ItemMenuModelDescr.Name := 'ItemMenuModelDescr';
  self.ItemMenuModelDescr.Size := new System.Drawing.Size(214, 22);
  self.ItemMenuModelDescr.Text := 'Model description...';
  self.ItemMenuModelDescr.ToolTipText := 'Edit model description';
  self.ItemMenuModelDescr.Click += new System.EventHandler(self.ItemMenuModelDescr_Click);
  self.ItemMenuAttDescr.Image := DEXiWin.Properties.Resources.ImgAttributeDescr;
  self.ItemMenuAttDescr.Name := 'ItemMenuAttDescr';
  self.ItemMenuAttDescr.Size := new System.Drawing.Size(214, 22);
  self.ItemMenuAttDescr.Text := 'Attribute description...';
  self.ItemMenuAttDescr.ToolTipText := 'Edit attribute name and description';
  self.ItemMenuAttDescr.Click += new System.EventHandler(self.ItemToolAttDescr_Click);
  self.toolStripSeparator8.Name := 'toolStripSeparator8';
  self.toolStripSeparator8.Size := new System.Drawing.Size(211, 6);
  self.ItemMenuSearch.Image := DEXiWin.Properties.Resources.ImgSearch;
  self.ItemMenuSearch.Name := 'ItemMenuSearch';
  self.ItemMenuSearch.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.F as System.Windows.Forms.Keys);
  self.ItemMenuSearch.Size := new System.Drawing.Size(214, 22);
  self.ItemMenuSearch.Text := '&Search...';
  self.ItemMenuSearch.Click += new System.EventHandler(self.ItemMenuSearch_Click);
  self.ItemMenuFindNext.Image := DEXiWin.Properties.Resources.ImgFindNext;
  self.ItemMenuFindNext.Name := 'ItemMenuFindNext';
  self.ItemMenuFindNext.ShortcutKeys := System.Windows.Forms.Keys.F3;
  self.ItemMenuFindNext.Size := new System.Drawing.Size(214, 22);
  self.ItemMenuFindNext.Text := 'Find next';
  self.ItemMenuFindNext.Click += new System.EventHandler(self.ItemMenuFindNext_Click);
  self.toolStripSeparator4.Name := 'toolStripSeparator4';
  self.toolStripSeparator4.Size := new System.Drawing.Size(211, 6);
  self.ItemMenuCut.Image := (resources.GetObject('ItemMenuCut.Image') as System.Drawing.Image);
  self.ItemMenuCut.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemMenuCut.Name := 'ItemMenuCut';
  self.ItemMenuCut.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.X as System.Windows.Forms.Keys);
  self.ItemMenuCut.Size := new System.Drawing.Size(214, 22);
  self.ItemMenuCut.Text := 'Cu&t';
  self.ItemMenuCut.ToolTipText := 'Cut subtree';
  self.ItemMenuCut.Click += new System.EventHandler(self.ItemToolCut_Click);
  self.ItemMenuCopy.Image := (resources.GetObject('ItemMenuCopy.Image') as System.Drawing.Image);
  self.ItemMenuCopy.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemMenuCopy.Name := 'ItemMenuCopy';
  self.ItemMenuCopy.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.C as System.Windows.Forms.Keys);
  self.ItemMenuCopy.Size := new System.Drawing.Size(214, 22);
  self.ItemMenuCopy.Text := '&Copy';
  self.ItemMenuCopy.ToolTipText := 'Copy attribute and subtree';
  self.ItemMenuCopy.Click += new System.EventHandler(self.ItemToolCopy_Click);
  self.ItemMenuPaste.Image := (resources.GetObject('ItemMenuPaste.Image') as System.Drawing.Image);
  self.ItemMenuPaste.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemMenuPaste.Name := 'ItemMenuPaste';
  self.ItemMenuPaste.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.V as System.Windows.Forms.Keys);
  self.ItemMenuPaste.Size := new System.Drawing.Size(214, 22);
  self.ItemMenuPaste.Text := '&Paste';
  self.ItemMenuPaste.ToolTipText := 'Paste subtree';
  self.ItemMenuPaste.Click += new System.EventHandler(self.ItemToolPaste_Click);
  self.toolStripSeparator1.Name := 'toolStripSeparator1';
  self.toolStripSeparator1.Size := new System.Drawing.Size(211, 6);
  self.ItemMenuAddAttribute.Image := DEXiWin.Properties.Resources.ImgAttributeAddDown;
  self.ItemMenuAddAttribute.Name := 'ItemMenuAddAttribute';
  self.ItemMenuAddAttribute.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Insert as System.Windows.Forms.Keys);
  self.ItemMenuAddAttribute.Size := new System.Drawing.Size(214, 22);
  self.ItemMenuAddAttribute.Text := 'Add &attribute';
  self.ItemMenuAddAttribute.ToolTipText := 'Add attribute at the same level';
  self.ItemMenuAddAttribute.Click += new System.EventHandler(self.ItemToolAddAttribute_Click);
  self.ItemMenuAddChild.Image := DEXiWin.Properties.Resources.ImgAttributeAddRight;
  self.ItemMenuAddChild.Name := 'ItemMenuAddChild';
  self.ItemMenuAddChild.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Shift or System.Windows.Forms.Keys.Insert as System.Windows.Forms.Keys);
  self.ItemMenuAddChild.Size := new System.Drawing.Size(214, 22);
  self.ItemMenuAddChild.Text := 'Add &child';
  self.ItemMenuAddChild.ToolTipText := 'Add child attribute';
  self.ItemMenuAddChild.Click += new System.EventHandler(self.ItemToolAddChild_Click);
  self.ItemMenuDeleteAttribute.Image := DEXiWin.Properties.Resources.ImgAttributeDelete;
  self.ItemMenuDeleteAttribute.Name := 'ItemMenuDeleteAttribute';
  self.ItemMenuDeleteAttribute.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Delete as System.Windows.Forms.Keys);
  self.ItemMenuDeleteAttribute.Size := new System.Drawing.Size(214, 22);
  self.ItemMenuDeleteAttribute.Text := '&Delete attribute';
  self.ItemMenuDeleteAttribute.ToolTipText := 'Delete attribute or subtree';
  self.ItemMenuDeleteAttribute.Click += new System.EventHandler(self.ItemToolDeleteAttribute_Click);
  self.ItemMenuDuplicateAttribute.Image := DEXiWin.Properties.Resources.ImgAttributeDuplicate;
  self.ItemMenuDuplicateAttribute.Name := 'ItemMenuDuplicateAttribute';
  self.ItemMenuDuplicateAttribute.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.D as System.Windows.Forms.Keys);
  self.ItemMenuDuplicateAttribute.Size := new System.Drawing.Size(214, 22);
  self.ItemMenuDuplicateAttribute.Text := 'D&uplicate attribute';
  self.ItemMenuDuplicateAttribute.ToolTipText := 'Duplicate attribute or subtree';
  self.ItemMenuDuplicateAttribute.Click += new System.EventHandler(self.ItemToolDuplicateAttribute_Click);
  self.toolStripSeparator9.Name := 'toolStripSeparator9';
  self.toolStripSeparator9.Size := new System.Drawing.Size(211, 6);
  self.ItemMenuMoveUp.Image := DEXiWin.Properties.Resources.ImgMoveUp;
  self.ItemMenuMoveUp.Name := 'ItemMenuMoveUp';
  self.ItemMenuMoveUp.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Up as System.Windows.Forms.Keys);
  self.ItemMenuMoveUp.Size := new System.Drawing.Size(214, 22);
  self.ItemMenuMoveUp.Text := 'Move up';
  self.ItemMenuMoveUp.ToolTipText := 'Move attribute up';
  self.ItemMenuMoveUp.Click += new System.EventHandler(self.ItemToolMoveUp_Click);
  self.ItemMenuMoveDown.Image := DEXiWin.Properties.Resources.ImgMoveDown;
  self.ItemMenuMoveDown.Name := 'ItemMenuMoveDown';
  self.ItemMenuMoveDown.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Down as System.Windows.Forms.Keys);
  self.ItemMenuMoveDown.Size := new System.Drawing.Size(214, 22);
  self.ItemMenuMoveDown.Text := 'Move down';
  self.ItemMenuMoveDown.ToolTipText := 'Move attribute down';
  self.ItemMenuMoveDown.Click += new System.EventHandler(self.ItemToolMoveDown_Click);
  self.toolStripSeparator10.Name := 'toolStripSeparator10';
  self.toolStripSeparator10.Size := new System.Drawing.Size(211, 6);
  self.ItemMenuScale.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemMenuEditScale, self.ItemMenuSelectScale, self.ItemMenuDeleteScale, self.ItemMenuReverseScale]));
  self.ItemMenuScale.Image := (resources.GetObject('ItemMenuScale.Image') as System.Drawing.Image);
  self.ItemMenuScale.Name := 'ItemMenuScale';
  self.ItemMenuScale.Size := new System.Drawing.Size(214, 22);
  self.ItemMenuScale.Text := '&Scale';
  self.ItemMenuEditScale.Image := DEXiWin.Properties.Resources.ImgScale;
  self.ItemMenuEditScale.Name := 'ItemMenuEditScale';
  self.ItemMenuEditScale.Size := new System.Drawing.Size(143, 22);
  self.ItemMenuEditScale.Text := '&Edit scale...';
  self.ItemMenuEditScale.Click += new System.EventHandler(self.BtnEditScale_Click);
  self.ItemMenuSelectScale.Image := DEXiWin.Properties.Resources.ImgScaleSelect;
  self.ItemMenuSelectScale.Name := 'ItemMenuSelectScale';
  self.ItemMenuSelectScale.Size := new System.Drawing.Size(143, 22);
  self.ItemMenuSelectScale.Text := '&Select scale...';
  self.ItemMenuSelectScale.Click += new System.EventHandler(self.BtnSelectScale_Click);
  self.ItemMenuDeleteScale.Image := DEXiWin.Properties.Resources.ImgScaleDelete;
  self.ItemMenuDeleteScale.Name := 'ItemMenuDeleteScale';
  self.ItemMenuDeleteScale.Size := new System.Drawing.Size(143, 22);
  self.ItemMenuDeleteScale.Text := '&Delete scale';
  self.ItemMenuDeleteScale.Click += new System.EventHandler(self.ItemMenuDeleteScale_Click);
  self.ItemMenuReverseScale.Image := DEXiWin.Properties.Resources.ImgScaleReverse;
  self.ItemMenuReverseScale.Name := 'ItemMenuReverseScale';
  self.ItemMenuReverseScale.Size := new System.Drawing.Size(143, 22);
  self.ItemMenuReverseScale.Text := '&Reverse scale';
  self.ItemMenuReverseScale.Click += new System.EventHandler(self.ItemMenuReverseScale_Click);
  self.ItemMenuFunction.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemMenuEditFunction, self.ItemMenuDeleteFunction]));
  self.ItemMenuFunction.Image := DEXiWin.Properties.Resources.ImgFunction;
  self.ItemMenuFunction.Name := 'ItemMenuFunction';
  self.ItemMenuFunction.Size := new System.Drawing.Size(214, 22);
  self.ItemMenuFunction.Text := '&Function';
  self.ItemMenuEditFunction.Image := DEXiWin.Properties.Resources.ImgFunction;
  self.ItemMenuEditFunction.Name := 'ItemMenuEditFunction';
  self.ItemMenuEditFunction.Size := new System.Drawing.Size(155, 22);
  self.ItemMenuEditFunction.Text := '&Edit function...';
  self.ItemMenuEditFunction.Click += new System.EventHandler(self.ItemMenuEditFunction_Click);
  self.ItemMenuDeleteFunction.Image := DEXiWin.Properties.Resources.ImgFunctionDelete;
  self.ItemMenuDeleteFunction.Name := 'ItemMenuDeleteFunction';
  self.ItemMenuDeleteFunction.Size := new System.Drawing.Size(155, 22);
  self.ItemMenuDeleteFunction.Text := '&Delete function';
  self.ItemMenuDeleteFunction.Click += new System.EventHandler(self.ItemMenuDeleteFunction_Click);
  self.ItemMenuView.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemMenuExpandAll, self.ItemMenuExpandOne, self.ItemMenuCollapseAll, self.ItemMenuCollapseOne, self.ItemMenuResizeColumns, self.toolStripSeparator6, self.ItemMenuViewAttributePanel, self.ItemMenuViewDescription, self.ItemMenuViewScale, self.ItemMenuViewFunction, self.toolStripSeparator17, self.ItemMenuViewTree]));
  self.ItemMenuView.MergeAction := System.Windows.Forms.MergeAction.Insert;
  self.ItemMenuView.MergeIndex := 2;
  self.ItemMenuView.Name := 'ItemMenuView';
  self.ItemMenuView.Size := new System.Drawing.Size(44, 20);
  self.ItemMenuView.Text := '&View';
  self.ItemMenuExpandAll.Image := DEXiWin.Properties.Resources.ImgTreeExpandAll;
  self.ItemMenuExpandAll.Name := 'ItemMenuExpandAll';
  self.ItemMenuExpandAll.Size := new System.Drawing.Size(174, 22);
  self.ItemMenuExpandAll.Text := 'Expand &all';
  self.ItemMenuExpandAll.Click += new System.EventHandler(self.ItemMenuExpandAll_Click);
  self.ItemMenuExpandOne.Image := DEXiWin.Properties.Resources.ImgTreeExpandOne;
  self.ItemMenuExpandOne.Name := 'ItemMenuExpandOne';
  self.ItemMenuExpandOne.Size := new System.Drawing.Size(174, 22);
  self.ItemMenuExpandOne.Text := 'Expand &one level';
  self.ItemMenuExpandOne.Click += new System.EventHandler(self.ItemMenuExpandOne_Click);
  self.ItemMenuCollapseAll.Image := DEXiWin.Properties.Resources.ImgTreeCollapseAll;
  self.ItemMenuCollapseAll.Name := 'ItemMenuCollapseAll';
  self.ItemMenuCollapseAll.Size := new System.Drawing.Size(174, 22);
  self.ItemMenuCollapseAll.Text := '&Collapse all';
  self.ItemMenuCollapseAll.Click += new System.EventHandler(self.ItemMenuCollapseAll_Click);
  self.ItemMenuCollapseOne.Image := DEXiWin.Properties.Resources.ImgTreeCollapseOne;
  self.ItemMenuCollapseOne.Name := 'ItemMenuCollapseOne';
  self.ItemMenuCollapseOne.Size := new System.Drawing.Size(174, 22);
  self.ItemMenuCollapseOne.Text := 'Collapse one le&vel';
  self.ItemMenuCollapseOne.Click += new System.EventHandler(self.ItemMenuCollapseOne_Click);
  self.ItemMenuResizeColumns.Name := 'ItemMenuResizeColumns';
  self.ItemMenuResizeColumns.ShortcutKeyDisplayString := 'F8';
  self.ItemMenuResizeColumns.Size := new System.Drawing.Size(174, 22);
  self.ItemMenuResizeColumns.Text := '&Resize columns';
  self.ItemMenuResizeColumns.ToolTipText := 'Resize columns';
  self.ItemMenuResizeColumns.Click += new System.EventHandler(self.ItemMenuResizeColumns_Click);
  self.toolStripSeparator6.Name := 'toolStripSeparator6';
  self.toolStripSeparator6.Size := new System.Drawing.Size(171, 6);
  self.ItemMenuViewAttributePanel.Name := 'ItemMenuViewAttributePanel';
  self.ItemMenuViewAttributePanel.Size := new System.Drawing.Size(174, 22);
  self.ItemMenuViewAttributePanel.Text := 'Attribute &panel';
  self.ItemMenuViewAttributePanel.Click += new System.EventHandler(self.ItemMenuViewAttributePanel_Click);
  self.ItemMenuViewDescription.Name := 'ItemMenuViewDescription';
  self.ItemMenuViewDescription.Size := new System.Drawing.Size(174, 22);
  self.ItemMenuViewDescription.Text := '&Description';
  self.ItemMenuViewDescription.Click += new System.EventHandler(self.ItemMenuViewDescription_Click);
  self.ItemMenuViewScale.Name := 'ItemMenuViewScale';
  self.ItemMenuViewScale.Size := new System.Drawing.Size(174, 22);
  self.ItemMenuViewScale.Text := '&Scale';
  self.ItemMenuViewScale.Click += new System.EventHandler(self.ItemMenuViewScale_Click);
  self.ItemMenuViewFunction.Name := 'ItemMenuViewFunction';
  self.ItemMenuViewFunction.Size := new System.Drawing.Size(174, 22);
  self.ItemMenuViewFunction.Text := '&Function';
  self.ItemMenuViewFunction.Click += new System.EventHandler(self.ItemMenuViewFunction_Click);
  self.toolStripSeparator17.Name := 'toolStripSeparator17';
  self.toolStripSeparator17.Size := new System.Drawing.Size(171, 6);
  self.ItemMenuViewTree.Image := DEXiWin.Properties.Resources.DirTopDown;
  self.ItemMenuViewTree.Name := 'ItemMenuViewTree';
  self.ItemMenuViewTree.Size := new System.Drawing.Size(174, 22);
  self.ItemMenuViewTree.Text := '&Tree view';
  self.ItemMenuViewTree.Click += new System.EventHandler(self.ItemMenuViewTree_Click);
  self.FormTool.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemToolModelDescr, self.ItemToolAttDescr, self.toolStripSeparator5, self.ItemToolCut, self.ItemToolCopy, self.ItemToolPaste, self.toolStripSeparator2, self.ItemToolAddAttribute, self.ItemToolAddChild, self.ItemToolDeleteAttribute, self.ItemToolDuplicateAttribute, self.toolStripSeparator3, self.ItemToolMoveDown, self.ItemToolMoveUp, self.toolStripSeparator7, self.ItemToolExpandAll, self.ItemToolExpandOne, self.ItemToolCollapseAll, self.ItemToolCollapseOne, self.BtnError]));
  self.FormTool.Location := new System.Drawing.Point(0, 24);
  self.FormTool.Name := 'FormTool';
  self.FormTool.Size := new System.Drawing.Size(1332, 25);
  self.FormTool.TabIndex := 1;
  self.FormTool.Text := 'toolStrip1';
  self.ItemToolModelDescr.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolModelDescr.Image := DEXiWin.Properties.Resources.ImgModelDescr;
  self.ItemToolModelDescr.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolModelDescr.Name := 'ItemToolModelDescr';
  self.ItemToolModelDescr.Size := new System.Drawing.Size(23, 22);
  self.ItemToolModelDescr.Text := 'Model description...';
  self.ItemToolModelDescr.ToolTipText := 'Edit model name and description';
  self.ItemToolModelDescr.Click += new System.EventHandler(self.ItemMenuModelDescr_Click);
  self.ItemToolAttDescr.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolAttDescr.Image := DEXiWin.Properties.Resources.ImgAttributeDescr;
  self.ItemToolAttDescr.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolAttDescr.Name := 'ItemToolAttDescr';
  self.ItemToolAttDescr.Size := new System.Drawing.Size(23, 22);
  self.ItemToolAttDescr.Text := 'Attribute description...';
  self.ItemToolAttDescr.ToolTipText := 'Edit attribute name and description';
  self.ItemToolAttDescr.Click += new System.EventHandler(self.ItemToolAttDescr_Click);
  self.toolStripSeparator5.Name := 'toolStripSeparator5';
  self.toolStripSeparator5.Size := new System.Drawing.Size(6, 25);
  self.ItemToolCut.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolCut.Image := (resources.GetObject('ItemToolCut.Image') as System.Drawing.Image);
  self.ItemToolCut.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolCut.Name := 'ItemToolCut';
  self.ItemToolCut.Size := new System.Drawing.Size(23, 22);
  self.ItemToolCut.Text := 'C&ut';
  self.ItemToolCut.ToolTipText := 'Cut subtree';
  self.ItemToolCut.Click += new System.EventHandler(self.ItemToolCut_Click);
  self.ItemToolCopy.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolCopy.Image := (resources.GetObject('ItemToolCopy.Image') as System.Drawing.Image);
  self.ItemToolCopy.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolCopy.Name := 'ItemToolCopy';
  self.ItemToolCopy.Size := new System.Drawing.Size(23, 22);
  self.ItemToolCopy.Text := '&Copy';
  self.ItemToolCopy.ToolTipText := 'Copy attribute and subtree';
  self.ItemToolCopy.Click += new System.EventHandler(self.ItemToolCopy_Click);
  self.ItemToolPaste.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolPaste.Image := (resources.GetObject('ItemToolPaste.Image') as System.Drawing.Image);
  self.ItemToolPaste.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolPaste.Name := 'ItemToolPaste';
  self.ItemToolPaste.Size := new System.Drawing.Size(23, 22);
  self.ItemToolPaste.Text := '&Paste';
  self.ItemToolPaste.ToolTipText := 'Paste subtree';
  self.ItemToolPaste.Click += new System.EventHandler(self.ItemToolPaste_Click);
  self.toolStripSeparator2.Name := 'toolStripSeparator2';
  self.toolStripSeparator2.Size := new System.Drawing.Size(6, 25);
  self.ItemToolAddAttribute.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolAddAttribute.Image := DEXiWin.Properties.Resources.ImgAttributeAddDown;
  self.ItemToolAddAttribute.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolAddAttribute.Name := 'ItemToolAddAttribute';
  self.ItemToolAddAttribute.Size := new System.Drawing.Size(23, 22);
  self.ItemToolAddAttribute.Text := 'Add attribute';
  self.ItemToolAddAttribute.ToolTipText := 'Add attribute at the same level';
  self.ItemToolAddAttribute.Click += new System.EventHandler(self.ItemToolAddAttribute_Click);
  self.ItemToolAddChild.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolAddChild.Image := DEXiWin.Properties.Resources.ImgAttributeAddRight;
  self.ItemToolAddChild.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolAddChild.Name := 'ItemToolAddChild';
  self.ItemToolAddChild.Size := new System.Drawing.Size(23, 22);
  self.ItemToolAddChild.Text := 'Add child';
  self.ItemToolAddChild.ToolTipText := 'Add child attribute';
  self.ItemToolAddChild.Click += new System.EventHandler(self.ItemToolAddChild_Click);
  self.ItemToolDeleteAttribute.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolDeleteAttribute.Image := DEXiWin.Properties.Resources.ImgAttributeDelete;
  self.ItemToolDeleteAttribute.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolDeleteAttribute.Name := 'ItemToolDeleteAttribute';
  self.ItemToolDeleteAttribute.Size := new System.Drawing.Size(23, 22);
  self.ItemToolDeleteAttribute.Text := 'Delete attribute';
  self.ItemToolDeleteAttribute.ToolTipText := 'Delete attribute or subtree';
  self.ItemToolDeleteAttribute.Click += new System.EventHandler(self.ItemToolDeleteAttribute_Click);
  self.ItemToolDuplicateAttribute.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolDuplicateAttribute.Image := DEXiWin.Properties.Resources.ImgAttributeDuplicate;
  self.ItemToolDuplicateAttribute.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolDuplicateAttribute.Name := 'ItemToolDuplicateAttribute';
  self.ItemToolDuplicateAttribute.Size := new System.Drawing.Size(23, 22);
  self.ItemToolDuplicateAttribute.Text := 'Duplicate attribute';
  self.ItemToolDuplicateAttribute.ToolTipText := 'Duplicate attribute or subtree';
  self.ItemToolDuplicateAttribute.Click += new System.EventHandler(self.ItemToolDuplicateAttribute_Click);
  self.toolStripSeparator3.Name := 'toolStripSeparator3';
  self.toolStripSeparator3.Size := new System.Drawing.Size(6, 25);
  self.ItemToolMoveDown.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolMoveDown.Image := DEXiWin.Properties.Resources.ImgMoveDown;
  self.ItemToolMoveDown.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolMoveDown.Name := 'ItemToolMoveDown';
  self.ItemToolMoveDown.Size := new System.Drawing.Size(23, 22);
  self.ItemToolMoveDown.Text := 'Move down';
  self.ItemToolMoveDown.ToolTipText := 'Move attribute down';
  self.ItemToolMoveDown.Click += new System.EventHandler(self.ItemToolMoveDown_Click);
  self.ItemToolMoveUp.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolMoveUp.Image := DEXiWin.Properties.Resources.ImgMoveUp;
  self.ItemToolMoveUp.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolMoveUp.Name := 'ItemToolMoveUp';
  self.ItemToolMoveUp.Size := new System.Drawing.Size(23, 22);
  self.ItemToolMoveUp.Text := 'Move up';
  self.ItemToolMoveUp.ToolTipText := 'Move attribute up';
  self.ItemToolMoveUp.Click += new System.EventHandler(self.ItemToolMoveUp_Click);
  self.toolStripSeparator7.Name := 'toolStripSeparator7';
  self.toolStripSeparator7.Size := new System.Drawing.Size(6, 25);
  self.ItemToolExpandAll.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolExpandAll.Image := DEXiWin.Properties.Resources.ImgTreeExpandAll;
  self.ItemToolExpandAll.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolExpandAll.Name := 'ItemToolExpandAll';
  self.ItemToolExpandAll.Size := new System.Drawing.Size(23, 22);
  self.ItemToolExpandAll.Text := 'Expand all';
  self.ItemToolExpandAll.Click += new System.EventHandler(self.ItemMenuExpandAll_Click);
  self.ItemToolExpandOne.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolExpandOne.Image := DEXiWin.Properties.Resources.ImgTreeExpandOne;
  self.ItemToolExpandOne.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolExpandOne.Name := 'ItemToolExpandOne';
  self.ItemToolExpandOne.Size := new System.Drawing.Size(23, 22);
  self.ItemToolExpandOne.Text := 'Expand one level';
  self.ItemToolExpandOne.Click += new System.EventHandler(self.ItemMenuExpandOne_Click);
  self.ItemToolCollapseAll.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolCollapseAll.Image := DEXiWin.Properties.Resources.ImgTreeCollapseAll;
  self.ItemToolCollapseAll.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolCollapseAll.Name := 'ItemToolCollapseAll';
  self.ItemToolCollapseAll.Size := new System.Drawing.Size(23, 22);
  self.ItemToolCollapseAll.Text := 'Collapse all';
  self.ItemToolCollapseAll.Click += new System.EventHandler(self.ItemMenuCollapseAll_Click);
  self.ItemToolCollapseOne.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolCollapseOne.Image := DEXiWin.Properties.Resources.ImgTreeCollapseOne;
  self.ItemToolCollapseOne.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolCollapseOne.Name := 'ItemToolCollapseOne';
  self.ItemToolCollapseOne.Size := new System.Drawing.Size(23, 22);
  self.ItemToolCollapseOne.Text := 'Collapse one level';
  self.ItemToolCollapseOne.Click += new System.EventHandler(self.ItemMenuCollapseOne_Click);
  self.BtnError.Alignment := System.Windows.Forms.ToolStripItemAlignment.Right;
  self.BtnError.BackColor := System.Drawing.Color.Red;
  self.BtnError.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Text;
  self.BtnError.ForeColor := System.Drawing.Color.Black;
  self.BtnError.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.BtnError.Name := 'BtnError';
  self.BtnError.Size := new System.Drawing.Size(36, 22);
  self.BtnError.Text := 'Error';
  self.BtnError.Visible := false;
  self.BtnError.Click += new System.EventHandler(self.BtnError_Click);
  self.TreeViewModel.AllColumns.Add(self.ColName);
  self.TreeViewModel.AllColumns.Add(self.ColDescription);
  self.TreeViewModel.AllColumns.Add(self.ColScale);
  self.TreeViewModel.AllColumns.Add(self.ColFunction);
  self.TreeViewModel.AllowColumnReorder := true;
  self.TreeViewModel.AllowDrop := true;
  self.TreeViewModel.CellEditActivation := BrightIdeasSoftware.ObjectListView.CellEditActivateMode.DoubleClick;
  self.TreeViewModel.CellEditUseWholeCell := false;
  self.TreeViewModel.Columns.AddRange(array of System.Windows.Forms.ColumnHeader([self.ColName, self.ColDescription, self.ColScale, self.ColFunction]));
  self.TreeViewModel.ContextMenuStrip := self.ModelMenu;
  self.TreeViewModel.Cursor := System.Windows.Forms.Cursors.Default;
  self.TreeViewModel.Dock := System.Windows.Forms.DockStyle.Left;
  self.TreeViewModel.HasCollapsibleGroups := false;
  self.TreeViewModel.HideSelection := false;
  self.TreeViewModel.IsSimpleDragSource := true;
  self.TreeViewModel.IsSimpleDropSink := true;
  self.TreeViewModel.Location := new System.Drawing.Point(0, 49);
  self.TreeViewModel.MultiSelect := false;
  self.TreeViewModel.Name := 'TreeViewModel';
  self.TreeViewModel.SelectAllOnControlA := false;
  self.TreeViewModel.SelectColumnsOnRightClick := false;
  self.TreeViewModel.SelectColumnsOnRightClickBehaviour := BrightIdeasSoftware.ObjectListView.ColumnSelectBehaviour.None;
  self.TreeViewModel.ShowGroups := false;
  self.TreeViewModel.Size := new System.Drawing.Size(567, 746);
  self.TreeViewModel.TabIndex := 2;
  self.TreeViewModel.UseCompatibleStateImageBehavior := false;
  self.TreeViewModel.View := System.Windows.Forms.View.Details;
  self.TreeViewModel.VirtualMode := true;
  self.TreeViewModel.Collapsing += new System.EventHandler<BrightIdeasSoftware.TreeBranchCollapsingEventArgs>(self.TreeViewModel_Collapsing);
  self.TreeViewModel.Expanded += new System.EventHandler<BrightIdeasSoftware.TreeBranchExpandedEventArgs>(self.TreeViewModel_Expanded);
  self.TreeViewModel.Collapsed += new System.EventHandler<BrightIdeasSoftware.TreeBranchCollapsedEventArgs>(self.TreeViewModel_Collapsed);
  self.TreeViewModel.CellEditFinished += new BrightIdeasSoftware.CellEditEventHandler(self.TreeViewModel_CellEditFinished);
  self.TreeViewModel.CellEditStarting += new BrightIdeasSoftware.CellEditEventHandler(self.TreeViewModel_CellEditStarting);
  self.TreeViewModel.ModelCanDrop += new System.EventHandler<BrightIdeasSoftware.ModelDropEventArgs>(self.TreeViewModel_ModelCanDrop);
  self.TreeViewModel.ModelDropped += new System.EventHandler<BrightIdeasSoftware.ModelDropEventArgs>(self.TreeViewModel_ModelDropped);
  self.TreeViewModel.SelectionChanged += new System.EventHandler(self.TreeViewModel_SelectionChanged);
  self.TreeViewModel.Click += new System.EventHandler(self.TreeViewModel_Click);
  self.TreeViewModel.Enter += new System.EventHandler(self.TreeViewModel_Enter);
  self.ColName.AspectName := 'Name';
  self.ColName.AspectToStringFormat := '';
  self.ColName.CellPadding := new System.Drawing.Rectangle(0, 0, -12, 0);
  self.ColName.Groupable := false;
  self.ColName.MinimumWidth := 100;
  self.ColName.Sortable := false;
  self.ColName.Text := 'Attribute';
  self.ColName.Width := 200;
  self.ColDescription.AspectName := 'Description';
  self.ColDescription.Groupable := false;
  self.ColDescription.MinimumWidth := 100;
  self.ColDescription.Sortable := false;
  self.ColDescription.Text := 'Description';
  self.ColDescription.Width := 200;
  self.ColScale.AspectName := 'ScaleComposite';
  self.ColScale.Groupable := false;
  self.ColScale.IsEditable := false;
  self.ColScale.MinimumWidth := 100;
  self.ColScale.Searchable := false;
  self.ColScale.Sortable := false;
  self.ColScale.Text := 'Scale';
  self.ColScale.Width := 200;
  self.ColFunction.AspectName := 'FunctString';
  self.ColFunction.Groupable := false;
  self.ColFunction.IsEditable := false;
  self.ColFunction.MinimumWidth := 100;
  self.ColFunction.Searchable := false;
  self.ColFunction.Sortable := false;
  self.ColFunction.Text := 'Function';
  self.ColFunction.Width := 200;
  self.ModelMenu.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemPopCut, self.ItemPopCopy, self.ItemPopPaste, self.toolStripSeparator11, self.ItemPopAddAttribute, self.ItemPopAddChild, self.ItemPopDeleteAttribute, self.ItemPopDuplicateAttribute, self.toolStripSeparator13, self.ItemPopMoveUp, self.ItemPopMoveDown, self.toolStripSeparator14, self.ItemPopAttDescr, self.toolStripSeparator15, self.ItemPopEditScale, self.ItemPopSelectScale, self.ItemPopDeleteScale, self.toolStripSeparator16, self.ItemPopEditFunction, self.ItemPopDeleteFunction, self.toolStripSeparator12, self.ItemPopSearch, self.ItemPopFindNext]));
  self.ModelMenu.Name := 'ModelMenu';
  self.ModelMenu.Size := new System.Drawing.Size(193, 414);
  self.ItemPopCut.Image := (resources.GetObject('ItemPopCut.Image') as System.Drawing.Image);
  self.ItemPopCut.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemPopCut.Name := 'ItemPopCut';
  self.ItemPopCut.Size := new System.Drawing.Size(192, 22);
  self.ItemPopCut.Text := 'Cu&t';
  self.ItemPopCut.ToolTipText := 'Cut subtree';
  self.ItemPopCut.Click += new System.EventHandler(self.ItemToolCut_Click);
  self.ItemPopCopy.Image := (resources.GetObject('ItemPopCopy.Image') as System.Drawing.Image);
  self.ItemPopCopy.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemPopCopy.Name := 'ItemPopCopy';
  self.ItemPopCopy.Size := new System.Drawing.Size(192, 22);
  self.ItemPopCopy.Text := '&Copy';
  self.ItemPopCopy.ToolTipText := 'Copy attribute and subtree';
  self.ItemPopCopy.Click += new System.EventHandler(self.ItemToolCopy_Click);
  self.ItemPopPaste.Image := (resources.GetObject('ItemPopPaste.Image') as System.Drawing.Image);
  self.ItemPopPaste.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemPopPaste.Name := 'ItemPopPaste';
  self.ItemPopPaste.Size := new System.Drawing.Size(192, 22);
  self.ItemPopPaste.Text := '&Paste';
  self.ItemPopPaste.ToolTipText := 'Paste subtree';
  self.ItemPopPaste.Click += new System.EventHandler(self.ItemToolPaste_Click);
  self.toolStripSeparator11.Name := 'toolStripSeparator11';
  self.toolStripSeparator11.Size := new System.Drawing.Size(189, 6);
  self.ItemPopAddAttribute.Image := DEXiWin.Properties.Resources.ImgAttributeAddDown;
  self.ItemPopAddAttribute.Name := 'ItemPopAddAttribute';
  self.ItemPopAddAttribute.Size := new System.Drawing.Size(192, 22);
  self.ItemPopAddAttribute.Text := 'Add &attribute';
  self.ItemPopAddAttribute.ToolTipText := 'Add attribute at the same level';
  self.ItemPopAddAttribute.Click += new System.EventHandler(self.ItemToolAddAttribute_Click);
  self.ItemPopAddChild.Image := DEXiWin.Properties.Resources.ImgAttributeAddRight;
  self.ItemPopAddChild.Name := 'ItemPopAddChild';
  self.ItemPopAddChild.Size := new System.Drawing.Size(192, 22);
  self.ItemPopAddChild.Text := 'Add &child';
  self.ItemPopAddChild.ToolTipText := 'Add child attribute';
  self.ItemPopAddChild.Click += new System.EventHandler(self.ItemToolAddChild_Click);
  self.ItemPopDeleteAttribute.Image := DEXiWin.Properties.Resources.ImgAttributeDelete;
  self.ItemPopDeleteAttribute.Name := 'ItemPopDeleteAttribute';
  self.ItemPopDeleteAttribute.Size := new System.Drawing.Size(192, 22);
  self.ItemPopDeleteAttribute.Text := '&Delete attribute';
  self.ItemPopDeleteAttribute.ToolTipText := 'Delete attribute or subtree';
  self.ItemPopDeleteAttribute.Click += new System.EventHandler(self.ItemToolDeleteAttribute_Click);
  self.ItemPopDuplicateAttribute.Image := DEXiWin.Properties.Resources.ImgAttributeDuplicate;
  self.ItemPopDuplicateAttribute.Name := 'ItemPopDuplicateAttribute';
  self.ItemPopDuplicateAttribute.Size := new System.Drawing.Size(192, 22);
  self.ItemPopDuplicateAttribute.Text := 'D&uplicate attribute';
  self.ItemPopDuplicateAttribute.ToolTipText := 'Duplicate attribute or subtree';
  self.ItemPopDuplicateAttribute.Click += new System.EventHandler(self.ItemToolDuplicateAttribute_Click);
  self.toolStripSeparator13.Name := 'toolStripSeparator13';
  self.toolStripSeparator13.Size := new System.Drawing.Size(189, 6);
  self.ItemPopMoveUp.Image := DEXiWin.Properties.Resources.ImgMoveUp;
  self.ItemPopMoveUp.Name := 'ItemPopMoveUp';
  self.ItemPopMoveUp.Size := new System.Drawing.Size(192, 22);
  self.ItemPopMoveUp.Text := 'Move up';
  self.ItemPopMoveUp.ToolTipText := 'Move attribute up';
  self.ItemPopMoveUp.Click += new System.EventHandler(self.ItemToolMoveUp_Click);
  self.ItemPopMoveDown.Image := DEXiWin.Properties.Resources.ImgMoveDown;
  self.ItemPopMoveDown.Name := 'ItemPopMoveDown';
  self.ItemPopMoveDown.Size := new System.Drawing.Size(192, 22);
  self.ItemPopMoveDown.Text := 'Move down';
  self.ItemPopMoveDown.ToolTipText := 'Move attribute down';
  self.ItemPopMoveDown.Click += new System.EventHandler(self.ItemToolMoveDown_Click);
  self.toolStripSeparator14.Name := 'toolStripSeparator14';
  self.toolStripSeparator14.Size := new System.Drawing.Size(189, 6);
  self.ItemPopAttDescr.Image := DEXiWin.Properties.Resources.ImgAttributeDescr;
  self.ItemPopAttDescr.Name := 'ItemPopAttDescr';
  self.ItemPopAttDescr.Size := new System.Drawing.Size(192, 22);
  self.ItemPopAttDescr.Text := 'Attribute description...';
  self.ItemPopAttDescr.ToolTipText := 'Edit attribute name and description';
  self.toolStripSeparator15.Name := 'toolStripSeparator15';
  self.toolStripSeparator15.Size := new System.Drawing.Size(189, 6);
  self.ItemPopEditScale.Image := DEXiWin.Properties.Resources.ImgScale;
  self.ItemPopEditScale.Name := 'ItemPopEditScale';
  self.ItemPopEditScale.Size := new System.Drawing.Size(192, 22);
  self.ItemPopEditScale.Text := '&Edit scale...';
  self.ItemPopEditScale.Click += new System.EventHandler(self.BtnEditScale_Click);
  self.ItemPopSelectScale.Image := DEXiWin.Properties.Resources.ImgScaleSelect;
  self.ItemPopSelectScale.Name := 'ItemPopSelectScale';
  self.ItemPopSelectScale.Size := new System.Drawing.Size(192, 22);
  self.ItemPopSelectScale.Text := '&Select scale...';
  self.ItemPopSelectScale.Click += new System.EventHandler(self.BtnSelectScale_Click);
  self.ItemPopDeleteScale.Image := DEXiWin.Properties.Resources.ImgScaleDelete;
  self.ItemPopDeleteScale.Name := 'ItemPopDeleteScale';
  self.ItemPopDeleteScale.Size := new System.Drawing.Size(192, 22);
  self.ItemPopDeleteScale.Text := '&Delete scale';
  self.ItemPopDeleteScale.Click += new System.EventHandler(self.ItemMenuDeleteScale_Click);
  self.toolStripSeparator16.Name := 'toolStripSeparator16';
  self.toolStripSeparator16.Size := new System.Drawing.Size(189, 6);
  self.ItemPopEditFunction.Image := DEXiWin.Properties.Resources.ImgFunction;
  self.ItemPopEditFunction.Name := 'ItemPopEditFunction';
  self.ItemPopEditFunction.Size := new System.Drawing.Size(192, 22);
  self.ItemPopEditFunction.Text := '&Edit function...';
  self.ItemPopEditFunction.Click += new System.EventHandler(self.ItemMenuEditFunction_Click);
  self.ItemPopDeleteFunction.Image := DEXiWin.Properties.Resources.ImgFunctionDelete;
  self.ItemPopDeleteFunction.Name := 'ItemPopDeleteFunction';
  self.ItemPopDeleteFunction.Size := new System.Drawing.Size(192, 22);
  self.ItemPopDeleteFunction.Text := '&Delete function';
  self.ItemPopDeleteFunction.Click += new System.EventHandler(self.ItemMenuDeleteFunction_Click);
  self.toolStripSeparator12.Name := 'toolStripSeparator12';
  self.toolStripSeparator12.Size := new System.Drawing.Size(189, 6);
  self.ItemPopSearch.Image := DEXiWin.Properties.Resources.ImgSearch;
  self.ItemPopSearch.Name := 'ItemPopSearch';
  self.ItemPopSearch.Size := new System.Drawing.Size(192, 22);
  self.ItemPopSearch.Text := '&Search...';
  self.ItemPopSearch.Click += new System.EventHandler(self.ItemMenuSearch_Click);
  self.ItemPopFindNext.Image := DEXiWin.Properties.Resources.ImgFindNext;
  self.ItemPopFindNext.Name := 'ItemPopFindNext';
  self.ItemPopFindNext.Size := new System.Drawing.Size(192, 22);
  self.ItemPopFindNext.Text := 'Find next';
  self.ItemPopFindNext.Click += new System.EventHandler(self.ItemMenuFindNext_Click);
  self.FormSplit.Location := new System.Drawing.Point(567, 49);
  self.FormSplit.Name := 'FormSplit';
  self.FormSplit.Size := new System.Drawing.Size(3, 746);
  self.FormSplit.TabIndex := 3;
  self.FormSplit.TabStop := false;
  self.FormSplit.DoubleClick += new System.EventHandler(self.FormSplit_DoubleClick);
  self.AttPanel.Controls.Add(self.BtnEditFunct);
  self.AttPanel.Controls.Add(self.BtnSelectScale);
  self.AttPanel.Controls.Add(self.BtnEditScale);
  self.AttPanel.Controls.Add(self.BtnAttDescr);
  self.AttPanel.Controls.Add(self.FunctionText);
  self.AttPanel.Controls.Add(self.LblFunction);
  self.AttPanel.Controls.Add(self.LblScale);
  self.AttPanel.Controls.Add(self.ScaleText);
  self.AttPanel.Controls.Add(self.TextDescription);
  self.AttPanel.Controls.Add(self.TextName);
  self.AttPanel.Controls.Add(self.LblDescription);
  self.AttPanel.Controls.Add(self.LblName);
  self.AttPanel.Controls.Add(self.ModelSplitter);
  self.AttPanel.Dock := System.Windows.Forms.DockStyle.Fill;
  self.AttPanel.Location := new System.Drawing.Point(570, 49);
  self.AttPanel.Name := 'AttPanel';
  self.AttPanel.Size := new System.Drawing.Size(762, 746);
  self.AttPanel.TabIndex := 4;
  self.BtnEditFunct.Anchor := (System.Windows.Forms.AnchorStyles.Top or System.Windows.Forms.AnchorStyles.Right as System.Windows.Forms.AnchorStyles);
  self.BtnEditFunct.Image := DEXiWin.Properties.Resources.ImgFunction;
  self.BtnEditFunct.Location := new System.Drawing.Point(720, 216);
  self.BtnEditFunct.Name := 'BtnEditFunct';
  self.BtnEditFunct.Size := new System.Drawing.Size(24, 24);
  self.BtnEditFunct.TabIndex := 11;
  self.ToolTips.SetToolTip(self.BtnEditFunct, 'Edit function');
  self.BtnEditFunct.UseVisualStyleBackColor := true;
  self.BtnEditFunct.Click += new System.EventHandler(self.ItemMenuEditFunction_Click);
  self.BtnSelectScale.Anchor := (System.Windows.Forms.AnchorStyles.Top or System.Windows.Forms.AnchorStyles.Right as System.Windows.Forms.AnchorStyles);
  self.BtnSelectScale.Image := DEXiWin.Properties.Resources.ImgScaleSelect;
  self.BtnSelectScale.Location := new System.Drawing.Point(693, 156);
  self.BtnSelectScale.Name := 'BtnSelectScale';
  self.BtnSelectScale.Size := new System.Drawing.Size(24, 24);
  self.BtnSelectScale.TabIndex := 8;
  self.ToolTips.SetToolTip(self.BtnSelectScale, 'Select scale');
  self.BtnSelectScale.UseVisualStyleBackColor := true;
  self.BtnSelectScale.Click += new System.EventHandler(self.BtnSelectScale_Click);
  self.BtnEditScale.Anchor := (System.Windows.Forms.AnchorStyles.Top or System.Windows.Forms.AnchorStyles.Right as System.Windows.Forms.AnchorStyles);
  self.BtnEditScale.Image := DEXiWin.Properties.Resources.ImgScale;
  self.BtnEditScale.Location := new System.Drawing.Point(720, 156);
  self.BtnEditScale.Name := 'BtnEditScale';
  self.BtnEditScale.Size := new System.Drawing.Size(24, 24);
  self.BtnEditScale.TabIndex := 9;
  self.ToolTips.SetToolTip(self.BtnEditScale, 'Edit scale');
  self.BtnEditScale.UseVisualStyleBackColor := true;
  self.BtnEditScale.Click += new System.EventHandler(self.BtnEditScale_Click);
  self.BtnAttDescr.Anchor := (System.Windows.Forms.AnchorStyles.Top or System.Windows.Forms.AnchorStyles.Right as System.Windows.Forms.AnchorStyles);
  self.BtnAttDescr.Image := DEXiWin.Properties.Resources.ImgAttributeDescr;
  self.BtnAttDescr.Location := new System.Drawing.Point(720, 36);
  self.BtnAttDescr.Name := 'BtnAttDescr';
  self.BtnAttDescr.Size := new System.Drawing.Size(24, 24);
  self.BtnAttDescr.TabIndex := 5;
  self.ToolTips.SetToolTip(self.BtnAttDescr, 'Edit attribute name and description');
  self.BtnAttDescr.UseVisualStyleBackColor := true;
  self.BtnAttDescr.Click += new System.EventHandler(self.ItemToolAttDescr_Click);
  self.FunctionText.BackColor := System.Drawing.SystemColors.Window;
  self.FunctionText.BorderStyle := System.Windows.Forms.BorderStyle.FixedSingle;
  self.FunctionText.Location := new System.Drawing.Point(16, 218);
  self.FunctionText.Multiline := false;
  self.FunctionText.Name := 'FunctionText';
  self.FunctionText.ReadOnly := true;
  self.FunctionText.Size := new System.Drawing.Size(599, 20);
  self.FunctionText.TabIndex := 10;
  self.FunctionText.TabStop := false;
  self.FunctionText.Text := '';
  self.FunctionText.WordWrap := false;
  self.LblFunction.AutoSize := true;
  self.LblFunction.Location := new System.Drawing.Point(14, 200);
  self.LblFunction.Name := 'LblFunction';
  self.LblFunction.Size := new System.Drawing.Size(48, 13);
  self.LblFunction.TabIndex := 9;
  self.LblFunction.Text := 'Function';
  self.LblScale.AutoSize := true;
  self.LblScale.Location := new System.Drawing.Point(14, 140);
  self.LblScale.Name := 'LblScale';
  self.LblScale.Size := new System.Drawing.Size(34, 13);
  self.LblScale.TabIndex := 7;
  self.LblScale.Text := 'Scale';
  self.ScaleText.BackColor := System.Drawing.SystemColors.Window;
  self.ScaleText.BorderStyle := System.Windows.Forms.BorderStyle.FixedSingle;
  self.ScaleText.Location := new System.Drawing.Point(16, 158);
  self.ScaleText.Multiline := false;
  self.ScaleText.Name := 'ScaleText';
  self.ScaleText.ReadOnly := true;
  self.ScaleText.Size := new System.Drawing.Size(572, 20);
  self.ScaleText.TabIndex := 7;
  self.ScaleText.TabStop := false;
  self.ScaleText.Text := '';
  self.ScaleText.WordWrap := false;
  self.TextDescription.Location := new System.Drawing.Point(16, 98);
  self.TextDescription.Name := 'TextDescription';
  self.TextDescription.Size := new System.Drawing.Size(629, 20);
  self.TextDescription.TabIndex := 6;
  self.TextDescription.TextChanged += new System.EventHandler(self.TextDescription_TextChanged);
  self.TextDescription.Enter += new System.EventHandler(self.TreeViewModel_Enter);
  self.TextDescription.Leave += new System.EventHandler(self.Text_Leave);
  self.TextName.Location := new System.Drawing.Point(16, 38);
  self.TextName.Name := 'TextName';
  self.TextName.Size := new System.Drawing.Size(599, 20);
  self.TextName.TabIndex := 4;
  self.TextName.TextChanged += new System.EventHandler(self.TextName_TextChanged);
  self.TextName.Enter += new System.EventHandler(self.TreeViewModel_Enter);
  self.TextName.Leave += new System.EventHandler(self.Text_Leave);
  self.LblDescription.AutoSize := true;
  self.LblDescription.Location := new System.Drawing.Point(14, 80);
  self.LblDescription.Name := 'LblDescription';
  self.LblDescription.Size := new System.Drawing.Size(100, 13);
  self.LblDescription.TabIndex := 5;
  self.LblDescription.Text := 'Attribute &description';
  self.LblName.AutoSize := true;
  self.LblName.Location := new System.Drawing.Point(14, 20);
  self.LblName.Name := 'LblName';
  self.LblName.Size := new System.Drawing.Size(75, 13);
  self.LblName.TabIndex := 3;
  self.LblName.Text := 'Attribute &name';
  self.ModelSplitter.Cursor := System.Windows.Forms.Cursors.HSplit;
  self.ModelSplitter.Dock := System.Windows.Forms.DockStyle.Top;
  self.ModelSplitter.Location := new System.Drawing.Point(0, 0);
  self.ModelSplitter.Name := 'ModelSplitter';
  self.ModelSplitter.Size := new System.Drawing.Size(762, 3);
  self.ModelSplitter.TabIndex := 1;
  self.ModelSplitter.TabStop := false;
  self.Controls.Add(self.AttPanel);
  self.Controls.Add(self.FormSplit);
  self.Controls.Add(self.TreeViewModel);
  self.Controls.Add(self.FormTool);
  self.Controls.Add(self.FormMenu);
  self.Name := 'CtrlFormModel';
  self.Size := new System.Drawing.Size(1332, 795);
  self.FormMenu.ResumeLayout(false);
  self.FormMenu.PerformLayout();
  self.FormTool.ResumeLayout(false);
  self.FormTool.PerformLayout();
  (self.TreeViewModel as System.ComponentModel.ISupportInitialize).EndInit();
  self.ModelMenu.ResumeLayout(false);
  self.AttPanel.ResumeLayout(false);
  self.AttPanel.PerformLayout();
  self.ResumeLayout(false);
  self.PerformLayout();
end;

{$ENDREGION}

end.