namespace DexiWin;

interface

{$HIDE H7}

uses
  System.Windows.Forms,
  System.Drawing;

type
  MainForm = partial class
  {$REGION Windows Form Designer generated code}
  private
    ItemAppSettings: System.Windows.Forms.ToolStripMenuItem;
    ItemAppFileClose: System.Windows.Forms.ToolStripMenuItem;
    ItemAppWindowFontSize: System.Windows.Forms.ToolStripMenuItem;
    ItemAppWindowFontResize: System.Windows.Forms.ToolStripMenuItem;
    ItemAppWindowFontEnlarge: System.Windows.Forms.ToolStripMenuItem;
    ItemAppWindowFontShrink: System.Windows.Forms.ToolStripMenuItem;
    
    ItemAppHelpSystem: System.Windows.Forms.ToolStripMenuItem;
    ItemToolUndo: System.Windows.Forms.ToolStripButton;
    ItemToolRedo: System.Windows.Forms.ToolStripButton;
    toolStripSeparator2: System.Windows.Forms.ToolStripSeparator;
    
    ItemAppExportModel: System.Windows.Forms.ToolStripMenuItem;
    ItemAppImport: System.Windows.Forms.ToolStripMenuItem;
    ItemAppImportFunct: System.Windows.Forms.ToolStripMenuItem;
    ItemAppImportAlt: System.Windows.Forms.ToolStripMenuItem;
    ItemAppExportTree: System.Windows.Forms.ToolStripMenuItem;
    ItemAppExportFunct: System.Windows.Forms.ToolStripMenuItem;
    ItemAppExportAlt: System.Windows.Forms.ToolStripMenuItem;
    ItemAppExport: System.Windows.Forms.ToolStripMenuItem;
    ValueImages: System.Windows.Forms.ImageList;
    ScaleImages: System.Windows.Forms.ImageList;
    OpenModelDialog: System.Windows.Forms.OpenFileDialog;
    TreeImages: System.Windows.Forms.ImageList;
    toolStripSeparator6: System.Windows.Forms.ToolStripSeparator;
    MainImages: System.Windows.Forms.ImageList;
    AppTool: System.Windows.Forms.ToolStrip;
    ItemToolNew: System.Windows.Forms.ToolStripButton;
    ItemToolOpen: System.Windows.Forms.ToolStripButton;
    ItemToolSave: System.Windows.Forms.ToolStripButton;
    toolStripSeparator: System.Windows.Forms.ToolStripSeparator;
    ItemToolHelp: System.Windows.Forms.ToolStripButton;
    ItemAppWindowResizeForms: System.Windows.Forms.ToolStripMenuItem;
    SeparatorWindow: System.Windows.Forms.ToolStripSeparator;
    ItemAppWindowMinimize: System.Windows.Forms.ToolStripMenuItem;
    ItemAppWindowMaximize: System.Windows.Forms.ToolStripMenuItem;
    ItemAppWindowNormal: System.Windows.Forms.ToolStripMenuItem;
    ItemAppWindowCascade: System.Windows.Forms.ToolStripMenuItem;
    ItemAppWindowTileHorizontally: System.Windows.Forms.ToolStripMenuItem;
    ItemAppWindowTileVertically: System.Windows.Forms.ToolStripMenuItem;
    ItemAppWindowArrange: System.Windows.Forms.ToolStripMenuItem;
    ItemAppHelpHelp: System.Windows.Forms.ToolStripMenuItem;
    ItemAppHelpAbout: System.Windows.Forms.ToolStripMenuItem;
    ItemAppFile: System.Windows.Forms.ToolStripMenuItem;
    ItemAppFileNew: System.Windows.Forms.ToolStripMenuItem;
    ItemAppFileOpen: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator0: System.Windows.Forms.ToolStripSeparator;
    ItemAppFileSave: System.Windows.Forms.ToolStripMenuItem;
    ItemAppFileSaveAs: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator1: System.Windows.Forms.ToolStripSeparator;
    ItemAppFileExit: System.Windows.Forms.ToolStripMenuItem;
    ItemAppEdit: System.Windows.Forms.ToolStripMenuItem;
    ItemAppEditUndo: System.Windows.Forms.ToolStripMenuItem;
    ItemAppEditRedo: System.Windows.Forms.ToolStripMenuItem;
    ItemAppWindow: System.Windows.Forms.ToolStripMenuItem;
    ItemAppHelp: System.Windows.Forms.ToolStripMenuItem;
    AppMenu: System.Windows.Forms.MenuStrip;
    components: System.ComponentModel.Container := nil;
    method InitializeComponent;
  {$ENDREGION}
  end;

implementation

{$REGION Windows Form Designer generated code}
method MainForm.InitializeComponent;
begin
  self.components := new System.ComponentModel.Container();
  var resources: System.ComponentModel.ComponentResourceManager := new System.ComponentModel.ComponentResourceManager(typeOf(MainForm));
  self.AppMenu := new System.Windows.Forms.MenuStrip();
  self.ItemAppFile := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppFileNew := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppFileOpen := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppFileClose := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator0 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemAppFileSave := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppFileSaveAs := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppImport := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppImportFunct := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppImportAlt := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppExport := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppExportModel := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppExportTree := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppExportFunct := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppExportAlt := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator2 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemAppSettings := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator1 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemAppFileExit := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppEdit := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppEditUndo := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppEditRedo := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppWindow := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppWindowCascade := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppWindowTileHorizontally := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppWindowTileVertically := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppWindowArrange := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppWindowResizeForms := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppWindowMinimize := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppWindowMaximize := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppWindowNormal := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppWindowFontSize := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppWindowFontResize := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppWindowFontEnlarge := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppWindowFontShrink := new System.Windows.Forms.ToolStripMenuItem();
  self.SeparatorWindow := new System.Windows.Forms.ToolStripSeparator();
  self.ItemAppHelp := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppHelpHelp := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppHelpSystem := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAppHelpAbout := new System.Windows.Forms.ToolStripMenuItem();
  self.AppTool := new System.Windows.Forms.ToolStrip();
  self.ItemToolNew := new System.Windows.Forms.ToolStripButton();
  self.ItemToolOpen := new System.Windows.Forms.ToolStripButton();
  self.ItemToolSave := new System.Windows.Forms.ToolStripButton();
  self.toolStripSeparator := new System.Windows.Forms.ToolStripSeparator();
  self.ItemToolHelp := new System.Windows.Forms.ToolStripButton();
  self.ItemToolUndo := new System.Windows.Forms.ToolStripButton();
  self.ItemToolRedo := new System.Windows.Forms.ToolStripButton();
  self.toolStripSeparator6 := new System.Windows.Forms.ToolStripSeparator();
  self.OpenModelDialog := new System.Windows.Forms.OpenFileDialog();
  self.MainImages := new System.Windows.Forms.ImageList(self.components);
  self.TreeImages := new System.Windows.Forms.ImageList(self.components);
  self.ScaleImages := new System.Windows.Forms.ImageList(self.components);
  self.ValueImages := new System.Windows.Forms.ImageList(self.components);
  self.AppMenu.SuspendLayout();
  self.AppTool.SuspendLayout();
  self.SuspendLayout();
  self.AppMenu.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemAppFile, self.ItemAppEdit, self.ItemAppWindow, self.ItemAppHelp]));
  self.AppMenu.Location := new System.Drawing.Point(0, 0);
  self.AppMenu.MdiWindowListItem := self.ItemAppWindow;
  self.AppMenu.Name := 'AppMenu';
  self.AppMenu.Size := new System.Drawing.Size(1268, 24);
  self.AppMenu.TabIndex := 2;
  self.AppMenu.Text := 'File';
  self.ItemAppFile.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemAppFileNew, self.ItemAppFileOpen, self.ItemAppFileClose, self.toolStripSeparator0, self.ItemAppFileSave, self.ItemAppFileSaveAs, self.ItemAppImport, self.ItemAppExport, self.toolStripSeparator2, self.ItemAppSettings, self.toolStripSeparator1, self.ItemAppFileExit]));
  self.ItemAppFile.MergeIndex := 1;
  self.ItemAppFile.Name := 'ItemAppFile';
  self.ItemAppFile.Size := new System.Drawing.Size(37, 20);
  self.ItemAppFile.Text := '&File';
  self.ItemAppFileNew.Image := (resources.GetObject('ItemAppFileNew.Image') as System.Drawing.Image);
  self.ItemAppFileNew.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemAppFileNew.MergeIndex := 1;
  self.ItemAppFileNew.Name := 'ItemAppFileNew';
  self.ItemAppFileNew.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.N as System.Windows.Forms.Keys);
  self.ItemAppFileNew.Size := new System.Drawing.Size(180, 22);
  self.ItemAppFileNew.Text := '&New';
  self.ItemAppFileNew.Click += new System.EventHandler(self.ItemAppFileNew_Click);
  self.ItemAppFileOpen.Image := (resources.GetObject('ItemAppFileOpen.Image') as System.Drawing.Image);
  self.ItemAppFileOpen.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemAppFileOpen.MergeIndex := 2;
  self.ItemAppFileOpen.Name := 'ItemAppFileOpen';
  self.ItemAppFileOpen.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.O as System.Windows.Forms.Keys);
  self.ItemAppFileOpen.Size := new System.Drawing.Size(180, 22);
  self.ItemAppFileOpen.Text := '&Open';
  self.ItemAppFileOpen.Click += new System.EventHandler(self.ItemAppFileOpen_Click);
  self.ItemAppFileClose.Name := 'ItemAppFileClose';
  self.ItemAppFileClose.Size := new System.Drawing.Size(180, 22);
  self.ItemAppFileClose.Text := 'Close';
  self.ItemAppFileClose.Click += new System.EventHandler(self.ItemAppFileClose_Click);
  self.toolStripSeparator0.Name := 'toolStripSeparator0';
  self.toolStripSeparator0.Size := new System.Drawing.Size(177, 6);
  self.ItemAppFileSave.Image := (resources.GetObject('ItemAppFileSave.Image') as System.Drawing.Image);
  self.ItemAppFileSave.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemAppFileSave.MergeIndex := 10;
  self.ItemAppFileSave.Name := 'ItemAppFileSave';
  self.ItemAppFileSave.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.S as System.Windows.Forms.Keys);
  self.ItemAppFileSave.Size := new System.Drawing.Size(180, 22);
  self.ItemAppFileSave.Text := '&Save';
  self.ItemAppFileSave.Click += new System.EventHandler(self.ItemAppFileSave_Click);
  self.ItemAppFileSaveAs.MergeIndex := 11;
  self.ItemAppFileSaveAs.Name := 'ItemAppFileSaveAs';
  self.ItemAppFileSaveAs.Size := new System.Drawing.Size(180, 22);
  self.ItemAppFileSaveAs.Text := 'Save &as...';
  self.ItemAppFileSaveAs.Click += new System.EventHandler(self.ItemAppFileSaveAs_Click);
  self.ItemAppImport.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemAppImportFunct, self.ItemAppImportAlt]));
  self.ItemAppImport.MergeIndex := 15;
  self.ItemAppImport.Name := 'ItemAppImport';
  self.ItemAppImport.Size := new System.Drawing.Size(180, 22);
  self.ItemAppImport.Text := '&Import...';
  self.ItemAppImportFunct.Name := 'ItemAppImportFunct';
  self.ItemAppImportFunct.Size := new System.Drawing.Size(182, 22);
  self.ItemAppImportFunct.Text := 'Import &function...';
  self.ItemAppImportFunct.Click += new System.EventHandler(self.ItemAppImportFunct_Click);
  self.ItemAppImportAlt.Name := 'ItemAppImportAlt';
  self.ItemAppImportAlt.Size := new System.Drawing.Size(182, 22);
  self.ItemAppImportAlt.Text := 'Import &alternatives...';
  self.ItemAppImportAlt.Click += new System.EventHandler(self.ItemAppImportAlt_Click);
  self.ItemAppExport.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemAppExportModel, self.ItemAppExportTree, self.ItemAppExportFunct, self.ItemAppExportAlt]));
  self.ItemAppExport.MergeIndex := 16;
  self.ItemAppExport.Name := 'ItemAppExport';
  self.ItemAppExport.Size := new System.Drawing.Size(180, 22);
  self.ItemAppExport.Text := '&Export...';
  self.ItemAppExportModel.Name := 'ItemAppExportModel';
  self.ItemAppExportModel.Size := new System.Drawing.Size(180, 22);
  self.ItemAppExportModel.Text := 'Export &model...';
  self.ItemAppExportModel.Click += new System.EventHandler(self.ItemAppExportModel_Click);
  self.ItemAppExportTree.Name := 'ItemAppExportTree';
  self.ItemAppExportTree.Size := new System.Drawing.Size(180, 22);
  self.ItemAppExportTree.Text := 'Export &tree...';
  self.ItemAppExportTree.Click += new System.EventHandler(self.ItemAppExportTree_Click);
  self.ItemAppExportFunct.Name := 'ItemAppExportFunct';
  self.ItemAppExportFunct.Size := new System.Drawing.Size(180, 22);
  self.ItemAppExportFunct.Text := 'Export &function...';
  self.ItemAppExportFunct.Click += new System.EventHandler(self.ItemAppExportFunct_Click);
  self.ItemAppExportAlt.Name := 'ItemAppExportAlt';
  self.ItemAppExportAlt.Size := new System.Drawing.Size(180, 22);
  self.ItemAppExportAlt.Text := 'Export &alternatives...';
  self.ItemAppExportAlt.Click += new System.EventHandler(self.ItemAppExportAlt_Click);
  self.toolStripSeparator2.Name := 'toolStripSeparator2';
  self.toolStripSeparator2.Size := new System.Drawing.Size(177, 6);
  self.ItemAppSettings.MergeIndex := 30;
  self.ItemAppSettings.Name := 'ItemAppSettings';
  self.ItemAppSettings.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.T as System.Windows.Forms.Keys);
  self.ItemAppSettings.Size := new System.Drawing.Size(180, 22);
  self.ItemAppSettings.Text := 'Se&ttings...';
  self.ItemAppSettings.Click += new System.EventHandler(self.ItemAppSettings_Click);
  self.toolStripSeparator1.Name := 'toolStripSeparator1';
  self.toolStripSeparator1.Size := new System.Drawing.Size(177, 6);
  self.ItemAppFileExit.MergeIndex := 40;
  self.ItemAppFileExit.Name := 'ItemAppFileExit';
  self.ItemAppFileExit.Size := new System.Drawing.Size(180, 22);
  self.ItemAppFileExit.Text := 'E&xit';
  self.ItemAppFileExit.Click += new System.EventHandler(self.ItemAppFileExit_Click);
  self.ItemAppEdit.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemAppEditUndo, self.ItemAppEditRedo]));
  self.ItemAppEdit.MergeIndex := 11;
  self.ItemAppEdit.Name := 'ItemAppEdit';
  self.ItemAppEdit.Size := new System.Drawing.Size(39, 20);
  self.ItemAppEdit.Text := '&Edit';
  self.ItemAppEditUndo.Enabled := false;
  self.ItemAppEditUndo.Image := DEXiWin.Properties.Resources.ImgUndo;
  self.ItemAppEditUndo.MergeIndex := 1;
  self.ItemAppEditUndo.Name := 'ItemAppEditUndo';
  self.ItemAppEditUndo.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Z as System.Windows.Forms.Keys);
  self.ItemAppEditUndo.Size := new System.Drawing.Size(180, 22);
  self.ItemAppEditUndo.Text := '&Undo';
  self.ItemAppEditRedo.Enabled := false;
  self.ItemAppEditRedo.Image := DEXiWin.Properties.Resources.ImgRedo;
  self.ItemAppEditRedo.MergeIndex := 2;
  self.ItemAppEditRedo.Name := 'ItemAppEditRedo';
  self.ItemAppEditRedo.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Y as System.Windows.Forms.Keys);
  self.ItemAppEditRedo.Size := new System.Drawing.Size(180, 22);
  self.ItemAppEditRedo.Text := '&Redo';
  self.ItemAppWindow.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemAppWindowCascade, self.ItemAppWindowTileHorizontally, self.ItemAppWindowTileVertically, self.ItemAppWindowArrange, self.ItemAppWindowResizeForms, self.ItemAppWindowFontSize, self.SeparatorWindow]));
  self.ItemAppWindow.MergeIndex := 21;
  self.ItemAppWindow.Name := 'ItemAppWindow';
  self.ItemAppWindow.Size := new System.Drawing.Size(63, 20);
  self.ItemAppWindow.Text := '&Window';
  self.ItemAppWindowCascade.Name := 'ItemAppWindowCascade';
  self.ItemAppWindowCascade.Size := new System.Drawing.Size(180, 22);
  self.ItemAppWindowCascade.Text := '&Cascade';
  self.ItemAppWindowCascade.Click += new System.EventHandler(self.ItemAppWindowCascade_Click);
  self.ItemAppWindowTileHorizontally.Name := 'ItemAppWindowTileHorizontally';
  self.ItemAppWindowTileHorizontally.Size := new System.Drawing.Size(180, 22);
  self.ItemAppWindowTileHorizontally.Text := 'Tile &horizontally';
  self.ItemAppWindowTileHorizontally.Click += new System.EventHandler(self.ItemAppWindowTileHorizontally_Click);
  self.ItemAppWindowTileVertically.Name := 'ItemAppWindowTileVertically';
  self.ItemAppWindowTileVertically.Size := new System.Drawing.Size(180, 22);
  self.ItemAppWindowTileVertically.Text := 'Tile &vertically';
  self.ItemAppWindowTileVertically.Click += new System.EventHandler(self.ItemAppWindowTileVertically_Click);
  self.ItemAppWindowArrange.Name := 'ItemAppWindowArrange';
  self.ItemAppWindowArrange.Size := new System.Drawing.Size(180, 22);
  self.ItemAppWindowArrange.Text := '&Arrange icons';
  self.ItemAppWindowArrange.Click += new System.EventHandler(self.ItemAppWindowArrange_Click);
  self.ItemAppWindowResizeForms.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemAppWindowMinimize, self.ItemAppWindowMaximize, self.ItemAppWindowNormal]));
  self.ItemAppWindowResizeForms.Name := 'ItemAppWindowResizeForms';
  self.ItemAppWindowResizeForms.Size := new System.Drawing.Size(180, 22);
  self.ItemAppWindowResizeForms.Text := '&Resize forms';
  self.ItemAppWindowMinimize.Name := 'ItemAppWindowMinimize';
  self.ItemAppWindowMinimize.Size := new System.Drawing.Size(180, 22);
  self.ItemAppWindowMinimize.Text := '&Minimize';
  self.ItemAppWindowMinimize.Click += new System.EventHandler(self.ItemAppWindowMinimize_Click);
  self.ItemAppWindowMaximize.Name := 'ItemAppWindowMaximize';
  self.ItemAppWindowMaximize.Size := new System.Drawing.Size(180, 22);
  self.ItemAppWindowMaximize.Text := 'Ma&ximize';
  self.ItemAppWindowMaximize.Click += new System.EventHandler(self.ItemAppWindowMaximize_Click);
  self.ItemAppWindowNormal.Name := 'ItemAppWindowNormal';
  self.ItemAppWindowNormal.Size := new System.Drawing.Size(180, 22);
  self.ItemAppWindowNormal.Text := '&Normal size';
  self.ItemAppWindowNormal.Click += new System.EventHandler(self.ItemAppWindowNormal_Click);
  self.ItemAppWindowFontSize.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemAppWindowFontResize, self.ItemAppWindowFontEnlarge, self.ItemAppWindowFontShrink]));
  self.ItemAppWindowFontSize.Name := 'ItemAppWindowFontSize';
  self.ItemAppWindowFontSize.Size := new System.Drawing.Size(180, 22);
  self.ItemAppWindowFontSize.Text := '&Font size';
  self.ItemAppWindowFontResize.Name := 'ItemAppWindowFontResize';
  self.ItemAppWindowFontResize.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Shift or System.Windows.Forms.Keys.F9 as System.Windows.Forms.Keys);
  self.ItemAppWindowFontResize.Size := new System.Drawing.Size(191, 22);
  self.ItemAppWindowFontResize.Text := '&Reset';
  self.ItemAppWindowFontResize.Click += new System.EventHandler(self.ItemAppWindowFontResize_Click);
  self.ItemAppWindowFontEnlarge.Name := 'ItemAppWindowFontEnlarge';
  self.ItemAppWindowFontEnlarge.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Shift or System.Windows.Forms.Keys.F8 as System.Windows.Forms.Keys);
  self.ItemAppWindowFontEnlarge.Size := new System.Drawing.Size(191, 22);
  self.ItemAppWindowFontEnlarge.Text := '&Enlarge';
  self.ItemAppWindowFontEnlarge.Click += new System.EventHandler(self.ItemAppWindowFontEnlarge_Click);
  self.ItemAppWindowFontShrink.Name := 'ItemAppWindowFontShrink';
  self.ItemAppWindowFontShrink.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Shift or System.Windows.Forms.Keys.F7 as System.Windows.Forms.Keys);
  self.ItemAppWindowFontShrink.Size := new System.Drawing.Size(191, 22);
  self.ItemAppWindowFontShrink.Text := '&Shrink';
  self.ItemAppWindowFontShrink.Click += new System.EventHandler(self.ItemAppWindowFontShrink_Click);
  self.SeparatorWindow.Name := 'SeparatorWindow';
  self.SeparatorWindow.Size := new System.Drawing.Size(177, 6);
  self.ItemAppHelp.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemAppHelpHelp, self.ItemAppHelpSystem, self.ItemAppHelpAbout]));
  self.ItemAppHelp.MergeIndex := 31;
  self.ItemAppHelp.Name := 'ItemAppHelp';
  self.ItemAppHelp.Size := new System.Drawing.Size(44, 20);
  self.ItemAppHelp.Text := '&Help';
  self.ItemAppHelpHelp.Image := (resources.GetObject('ItemAppHelpHelp.Image') as System.Drawing.Image);
  self.ItemAppHelpHelp.Name := 'ItemAppHelpHelp';
  self.ItemAppHelpHelp.Size := new System.Drawing.Size(216, 22);
  self.ItemAppHelpHelp.Text := '&Help';
  self.ItemAppHelpHelp.Click += new System.EventHandler(self.ItemAppHelpHelp_Click);
  self.ItemAppHelpSystem.Name := 'ItemAppHelpSystem';
  self.ItemAppHelpSystem.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Alt or System.Windows.Forms.Keys.Shift or System.Windows.Forms.Keys.S as System.Windows.Forms.Keys);
  self.ItemAppHelpSystem.Size := new System.Drawing.Size(216, 22);
  self.ItemAppHelpSystem.Text := 'System...';
  self.ItemAppHelpSystem.ToolTipText := 'System data';
  self.ItemAppHelpSystem.Click += new System.EventHandler(self.ItemAppHelpSystem_Click);
  self.ItemAppHelpAbout.Image := DEXiWin.Properties.Resources.ImgDexiWin;
  self.ItemAppHelpAbout.Name := 'ItemAppHelpAbout';
  self.ItemAppHelpAbout.Size := new System.Drawing.Size(216, 22);
  self.ItemAppHelpAbout.Text := '&About...';
  self.ItemAppHelpAbout.Click += new System.EventHandler(self.ItemAppHelpAbout_Click);
  self.AppTool.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemToolNew, self.ItemToolOpen, self.ItemToolSave, self.toolStripSeparator, self.ItemToolHelp, self.ItemToolUndo, self.ItemToolRedo, self.toolStripSeparator6]));
  self.AppTool.Location := new System.Drawing.Point(0, 24);
  self.AppTool.Name := 'AppTool';
  self.AppTool.Size := new System.Drawing.Size(1268, 25);
  self.AppTool.TabIndex := 4;
  self.AppTool.Text := 'AppToolbar';
  self.ItemToolNew.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolNew.Image := (resources.GetObject('ItemToolNew.Image') as System.Drawing.Image);
  self.ItemToolNew.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolNew.Name := 'ItemToolNew';
  self.ItemToolNew.Size := new System.Drawing.Size(23, 22);
  self.ItemToolNew.Text := '&New';
  self.ItemToolNew.Click += new System.EventHandler(self.ItemAppFileNew_Click);
  self.ItemToolOpen.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolOpen.Image := (resources.GetObject('ItemToolOpen.Image') as System.Drawing.Image);
  self.ItemToolOpen.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolOpen.Name := 'ItemToolOpen';
  self.ItemToolOpen.Size := new System.Drawing.Size(23, 22);
  self.ItemToolOpen.Text := '&Open';
  self.ItemToolOpen.Click += new System.EventHandler(self.ItemAppFileOpen_Click);
  self.ItemToolSave.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolSave.Image := (resources.GetObject('ItemToolSave.Image') as System.Drawing.Image);
  self.ItemToolSave.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolSave.Name := 'ItemToolSave';
  self.ItemToolSave.Size := new System.Drawing.Size(23, 22);
  self.ItemToolSave.Text := '&Save';
  self.ItemToolSave.Click += new System.EventHandler(self.ItemAppFileSave_Click);
  self.toolStripSeparator.Name := 'toolStripSeparator';
  self.toolStripSeparator.Size := new System.Drawing.Size(6, 25);
  self.ItemToolHelp.Alignment := System.Windows.Forms.ToolStripItemAlignment.Right;
  self.ItemToolHelp.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolHelp.Image := (resources.GetObject('ItemToolHelp.Image') as System.Drawing.Image);
  self.ItemToolHelp.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolHelp.MergeIndex := 99;
  self.ItemToolHelp.Name := 'ItemToolHelp';
  self.ItemToolHelp.Size := new System.Drawing.Size(23, 22);
  self.ItemToolHelp.Text := 'He&lp';
  self.ItemToolHelp.Click += new System.EventHandler(self.ItemAppHelpHelp_Click);
  self.ItemToolUndo.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolUndo.Image := DEXiWin.Properties.Resources.ImgUndo;
  self.ItemToolUndo.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolUndo.Name := 'ItemToolUndo';
  self.ItemToolUndo.Size := new System.Drawing.Size(23, 22);
  self.ItemToolUndo.Text := 'Undo';
  self.ItemToolUndo.Click += new System.EventHandler(self.ItemToolUndo_Click);
  self.ItemToolRedo.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolRedo.Image := DEXiWin.Properties.Resources.ImgRedo;
  self.ItemToolRedo.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolRedo.Name := 'ItemToolRedo';
  self.ItemToolRedo.Size := new System.Drawing.Size(23, 22);
  self.ItemToolRedo.Text := 'Redo';
  self.ItemToolRedo.Click += new System.EventHandler(self.ItemToolRedo_Click);
  self.toolStripSeparator6.Name := 'toolStripSeparator6';
  self.toolStripSeparator6.Size := new System.Drawing.Size(6, 25);
  self.OpenModelDialog.DefaultExt := 'dxi';
  self.OpenModelDialog.Filter := 'DEXi Model|*.dxi';
  self.OpenModelDialog.ReadOnlyChecked := true;
  self.OpenModelDialog.Title := 'Open DEXi Model';
  self.MainImages.ImageStream := (resources.GetObject('MainImages.ImageStream') as System.Windows.Forms.ImageListStreamer);
  self.MainImages.TransparentColor := System.Drawing.Color.Transparent;
  self.MainImages.Images.SetKeyName(0, 'ImgModel');
  self.MainImages.Images.SetKeyName(1, 'ImgModelTransparent');
  self.MainImages.Images.SetKeyName(2, 'ImgAlternatives');
  self.MainImages.Images.SetKeyName(3, 'ImgReport');
  self.MainImages.Images.SetKeyName(4, 'ImgEvaluation');
  self.MainImages.Images.SetKeyName(5, 'ImgTree');
  self.MainImages.Images.SetKeyName(6, 'ImgChart');
  self.TreeImages.ImageStream := (resources.GetObject('TreeImages.ImageStream') as System.Windows.Forms.ImageListStreamer);
  self.TreeImages.TransparentColor := System.Drawing.Color.Transparent;
  self.TreeImages.Images.SetKeyName(0, 'ImgAttTermUnDef');
  self.TreeImages.Images.SetKeyName(1, 'ImgAttTermDiscr');
  self.TreeImages.Images.SetKeyName(2, 'ImgAttTermCont');
  self.TreeImages.Images.SetKeyName(3, 'ImgAttTermLink');
  self.TreeImages.Images.SetKeyName(4, 'ImgAttAggUndef');
  self.TreeImages.Images.SetKeyName(5, 'ImgAttAggUndefOK');
  self.TreeImages.Images.SetKeyName(6, 'ImgAttAggUndefIncomplete');
  self.TreeImages.Images.SetKeyName(7, 'ImgAttAggDefUndet');
  self.TreeImages.Images.SetKeyName(8, 'ImgAttAggDefDet');
  self.ScaleImages.ImageStream := (resources.GetObject('ScaleImages.ImageStream') as System.Windows.Forms.ImageListStreamer);
  self.ScaleImages.TransparentColor := System.Drawing.Color.Transparent;
  self.ScaleImages.Images.SetKeyName(0, 'ImgScaleContinuous');
  self.ScaleImages.Images.SetKeyName(1, 'ImgScaleDiscrete');
  self.ValueImages.ImageStream := (resources.GetObject('ValueImages.ImageStream') as System.Windows.Forms.ImageListStreamer);
  self.ValueImages.TransparentColor := System.Drawing.Color.Transparent;
  self.ValueImages.Images.SetKeyName(0, 'ImgValue');
  self.ValueImages.Images.SetKeyName(1, 'ImgValueGood');
  self.ValueImages.Images.SetKeyName(2, 'ImgValueBad');
  self.AutoScaleDimensions := new System.Drawing.SizeF(6.0, 13.0);
  self.AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font;
  self.ClientSize := new System.Drawing.Size(1268, 695);
  self.Controls.Add(self.AppTool);
  self.Controls.Add(self.AppMenu);
  self.Icon := (resources.GetObject('$this.Icon') as System.Drawing.Icon);
  self.IsMdiContainer := true;
  self.Name := 'MainForm';
  self.Text := 'MainForm';
  self.Activated += new System.EventHandler(self.MainForm_Activated);
  self.Load += new System.EventHandler(self.MainForm_Load);
  self.MdiChildActivate += new System.EventHandler(self.MainForm_MdiChildActivate);
  self.AppMenu.ResumeLayout(false);
  self.AppMenu.PerformLayout();
  self.AppTool.ResumeLayout(false);
  self.AppTool.PerformLayout();
  self.ResumeLayout(false);
  self.PerformLayout();
end;
{$ENDREGION}

end.