namespace DexiWin;

interface

{$HIDE H7}

uses
  System.Drawing,
  System.Collections,
  System.Windows.Forms,
  System.ComponentModel;

type
  FormFunctEditTabular = partial class
  {$REGION Windows Form Designer generated fields}
  private
    ItemToolSymmetricity: System.Windows.Forms.ToolStripButton;
    ItemPopSymmetrcity: System.Windows.Forms.ToolStripMenuItem;
    ItemPopResetColumns: System.Windows.Forms.ToolStripMenuItem;
    ItemPopResizeColumns: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator6: System.Windows.Forms.ToolStripSeparator;
    
    BtnUndo: System.Windows.Forms.ToolStripButton;
    BtnRedo: System.Windows.Forms.ToolStripButton;
    SepUndoRedo: System.Windows.Forms.ToolStripSeparator;
    ItemToolChart: System.Windows.Forms.ToolStripButton;
    ItemToolShowFunction: System.Windows.Forms.ToolStripButton;
    ItemToolWeights: System.Windows.Forms.ToolStripButton;
    ItemPopDeleteRule: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator3: System.Windows.Forms.ToolStripSeparator;
    ItemToolPasteFunct: System.Windows.Forms.ToolStripButton;
    ItemToolCopyFunct: System.Windows.Forms.ToolStripButton;
    ItemPopEnter: System.Windows.Forms.ToolStripMenuItem;
    ItemPopEnterTable: System.Windows.Forms.ToolStripMenuItem;
    ItemPopEnterSingle: System.Windows.Forms.ToolStripMenuItem;
    ItemAutoUseDominance: System.Windows.Forms.ToolStripMenuItem;
    ItemAutoUseWeights: System.Windows.Forms.ToolStripMenuItem;
    ItemToolAutoSettings: System.Windows.Forms.ToolStripSplitButton;
    AutoImages: System.Windows.Forms.ImageList;
    ItemToolEditRule: System.Windows.Forms.ToolStripButton;
    toolStripSeparator4: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator2: System.Windows.Forms.ToolStripSeparator;
    ItemPopRuleStatus: System.Windows.Forms.ToolStripMenuItem;
    ItemPopUndefinedValue: System.Windows.Forms.ToolStripMenuItem;
    FunctMenu: System.Windows.Forms.ContextMenuStrip;
    ItemToolDeleteRule: System.Windows.Forms.ToolStripButton;
    ItemToolRuleDescr: System.Windows.Forms.ToolStripButton;
    ColStatus: BrightIdeasSoftware.OLVColumn;
    RuleImages: System.Windows.Forms.ImageList;
    HeaderFormat: BrightIdeasSoftware.HeaderFormatStyle;
    LblStatus: System.Windows.Forms.Label;
    TablePannel: System.Windows.Forms.Panel;
    ViewFunct: BrightIdeasSoftware.ObjectListView;
    ColNumber: BrightIdeasSoftware.OLVColumn;
    ItemToolFunctDescr: System.Windows.Forms.ToolStripButton;
    ButtonPanel: System.Windows.Forms.Panel;
    FormTool: System.Windows.Forms.ToolStrip;
    toolStripSeparator5: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator1: System.Windows.Forms.ToolStripSeparator;
    BtnCancel: System.Windows.Forms.Button;
    BtnOK: System.Windows.Forms.Button;
    var components: System.ComponentModel.Container := nil;
    method InitializeComponent;
  {$ENDREGION}
  end;

implementation

{$REGION Windows Form Designer generated code}
method FormFunctEditTabular.InitializeComponent;
begin
  self.components := new System.ComponentModel.Container();
  var resources: System.ComponentModel.ComponentResourceManager := new System.ComponentModel.ComponentResourceManager(typeOf(FormFunctEditTabular));
  var headerStateStyle1: BrightIdeasSoftware.HeaderStateStyle := new BrightIdeasSoftware.HeaderStateStyle();
  var headerStateStyle2: BrightIdeasSoftware.HeaderStateStyle := new BrightIdeasSoftware.HeaderStateStyle();
  var headerStateStyle3: BrightIdeasSoftware.HeaderStateStyle := new BrightIdeasSoftware.HeaderStateStyle();
  self.FormTool := new System.Windows.Forms.ToolStrip();
  self.ItemToolFunctDescr := new System.Windows.Forms.ToolStripButton();
  self.ItemToolRuleDescr := new System.Windows.Forms.ToolStripButton();
  self.toolStripSeparator3 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemToolEditRule := new System.Windows.Forms.ToolStripButton();
  self.ItemToolDeleteRule := new System.Windows.Forms.ToolStripButton();
  self.toolStripSeparator5 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemToolAutoSettings := new System.Windows.Forms.ToolStripSplitButton();
  self.ItemAutoUseDominance := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAutoUseWeights := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator1 := new System.Windows.Forms.ToolStripSeparator();
  self.BtnUndo := new System.Windows.Forms.ToolStripButton();
  self.BtnRedo := new System.Windows.Forms.ToolStripButton();
  self.SepUndoRedo := new System.Windows.Forms.ToolStripSeparator();
  self.ItemToolShowFunction := new System.Windows.Forms.ToolStripButton();
  self.ItemToolChart := new System.Windows.Forms.ToolStripButton();
  self.ItemToolWeights := new System.Windows.Forms.ToolStripButton();
  self.ItemToolSymmetricity := new System.Windows.Forms.ToolStripButton();
  self.ItemToolCopyFunct := new System.Windows.Forms.ToolStripButton();
  self.ItemToolPasteFunct := new System.Windows.Forms.ToolStripButton();
  self.ButtonPanel := new System.Windows.Forms.Panel();
  self.LblStatus := new System.Windows.Forms.Label();
  self.BtnCancel := new System.Windows.Forms.Button();
  self.BtnOK := new System.Windows.Forms.Button();
  self.TablePannel := new System.Windows.Forms.Panel();
  self.ViewFunct := new BrightIdeasSoftware.ObjectListView();
  self.ColNumber := (new BrightIdeasSoftware.OLVColumn() as BrightIdeasSoftware.OLVColumn);
  self.ColStatus := (new BrightIdeasSoftware.OLVColumn() as BrightIdeasSoftware.OLVColumn);
  self.RuleImages := new System.Windows.Forms.ImageList(self.components);
  self.FunctMenu := new System.Windows.Forms.ContextMenuStrip(self.components);
  self.toolStripSeparator4 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopUndefinedValue := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopDeleteRule := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator2 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopRuleStatus := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopEnter := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopEnterTable := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopEnterSingle := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopSymmetrcity := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator6 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopResizeColumns := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopResetColumns := new System.Windows.Forms.ToolStripMenuItem();
  self.HeaderFormat := new BrightIdeasSoftware.HeaderFormatStyle();
  self.AutoImages := new System.Windows.Forms.ImageList(self.components);
  self.FormTool.SuspendLayout();
  self.ButtonPanel.SuspendLayout();
  self.TablePannel.SuspendLayout();
  (self.ViewFunct as System.ComponentModel.ISupportInitialize).BeginInit();
  self.FunctMenu.SuspendLayout();
  self.SuspendLayout();
  self.FormTool.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemToolFunctDescr, self.ItemToolRuleDescr, self.toolStripSeparator3, self.ItemToolEditRule, self.ItemToolDeleteRule, self.toolStripSeparator5, self.ItemToolAutoSettings, self.toolStripSeparator1, self.BtnUndo, self.BtnRedo, self.SepUndoRedo, self.ItemToolShowFunction, self.ItemToolChart, self.ItemToolWeights, self.ItemToolSymmetricity, self.ItemToolCopyFunct, self.ItemToolPasteFunct]));
  self.FormTool.Location := new System.Drawing.Point(0, 0);
  self.FormTool.Name := 'FormTool';
  self.FormTool.Size := new System.Drawing.Size(729, 25);
  self.FormTool.TabIndex := 13;
  self.FormTool.Text := 'toolStrip1';
  self.ItemToolFunctDescr.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolFunctDescr.Image := DEXiWin.Properties.Resources.ImgFunctionDescr;
  self.ItemToolFunctDescr.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolFunctDescr.Name := 'ItemToolFunctDescr';
  self.ItemToolFunctDescr.Size := new System.Drawing.Size(23, 22);
  self.ItemToolFunctDescr.Text := 'Function description...';
  self.ItemToolFunctDescr.ToolTipText := 'Edit function name and description';
  self.ItemToolFunctDescr.Click += new System.EventHandler(self.ItemToolFunctDescr_Click);
  self.ItemToolRuleDescr.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolRuleDescr.Image := DEXiWin.Properties.Resources.ImgRuleDescr;
  self.ItemToolRuleDescr.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolRuleDescr.Name := 'ItemToolRuleDescr';
  self.ItemToolRuleDescr.Size := new System.Drawing.Size(23, 22);
  self.ItemToolRuleDescr.Text := 'Rule description...';
  self.ItemToolRuleDescr.ToolTipText := 'Edit rule description';
  self.toolStripSeparator3.Name := 'toolStripSeparator3';
  self.toolStripSeparator3.Size := new System.Drawing.Size(6, 25);
  self.ItemToolEditRule.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolEditRule.Image := DEXiWin.Properties.Resources.ImgRuleEdit;
  self.ItemToolEditRule.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolEditRule.Name := 'ItemToolEditRule';
  self.ItemToolEditRule.Size := new System.Drawing.Size(23, 22);
  self.ItemToolEditRule.Text := 'Edit rule value';
  self.ItemToolEditRule.ToolTipText := 'Edit selected rule value (F2)';
  self.ItemToolEditRule.Click += new System.EventHandler(self.ItemToolEditRule_Click);
  self.ItemToolDeleteRule.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolDeleteRule.Image := DEXiWin.Properties.Resources.ImgRuleDelete;
  self.ItemToolDeleteRule.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolDeleteRule.Name := 'ItemToolDeleteRule';
  self.ItemToolDeleteRule.Size := new System.Drawing.Size(23, 22);
  self.ItemToolDeleteRule.Text := 'Delete rule value';
  self.ItemToolDeleteRule.ToolTipText := 'Delete selected rule value (Del)';
  self.ItemToolDeleteRule.Click += new System.EventHandler(self.ItemToolDeleteRule_Click);
  self.toolStripSeparator5.Name := 'toolStripSeparator5';
  self.toolStripSeparator5.Size := new System.Drawing.Size(6, 25);
  self.ItemToolAutoSettings.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolAutoSettings.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemAutoUseDominance, self.ItemAutoUseWeights]));
  self.ItemToolAutoSettings.Image := DEXiWin.Properties.Resources.ImgAuto;
  self.ItemToolAutoSettings.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolAutoSettings.Name := 'ItemToolAutoSettings';
  self.ItemToolAutoSettings.Size := new System.Drawing.Size(32, 22);
  self.ItemToolAutoSettings.Text := 'Automatic value setup';
  self.ItemToolAutoSettings.ToolTipText := 'Choose method(s) for automatic setup of non-entered rule values';
  self.ItemAutoUseDominance.Name := 'ItemAutoUseDominance';
  self.ItemAutoUseDominance.Size := new System.Drawing.Size(229, 22);
  self.ItemAutoUseDominance.Text := 'Use &dominance (scale orders)';
  self.ItemAutoUseDominance.ToolTipText := 'Use the principle of dominance for automatic value setup';
  self.ItemAutoUseDominance.Click += new System.EventHandler(self.ItemAutoUseDominance_Click);
  self.ItemAutoUseWeights.Name := 'ItemAutoUseWeights';
  self.ItemAutoUseWeights.Size := new System.Drawing.Size(229, 22);
  self.ItemAutoUseWeights.Text := 'Use &weights';
  self.ItemAutoUseWeights.ToolTipText := 'Use attribute weights for automatic value setup';
  self.ItemAutoUseWeights.Click += new System.EventHandler(self.ItemAutoUseWeights_Click);
  self.toolStripSeparator1.Name := 'toolStripSeparator1';
  self.toolStripSeparator1.Size := new System.Drawing.Size(6, 25);
  self.BtnUndo.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.BtnUndo.Image := DEXiWin.Properties.Resources.ImgUndo;
  self.BtnUndo.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.BtnUndo.Name := 'BtnUndo';
  self.BtnUndo.Size := new System.Drawing.Size(23, 22);
  self.BtnUndo.Text := 'Undo';
  self.BtnUndo.Click += new System.EventHandler(self.BtnUndo_Click);
  self.BtnRedo.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.BtnRedo.Image := DEXiWin.Properties.Resources.ImgRedo;
  self.BtnRedo.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.BtnRedo.Name := 'BtnRedo';
  self.BtnRedo.Size := new System.Drawing.Size(23, 22);
  self.BtnRedo.Text := 'Redo';
  self.BtnRedo.Click += new System.EventHandler(self.BtnRedo_Click);
  self.SepUndoRedo.Name := 'SepUndoRedo';
  self.SepUndoRedo.Size := new System.Drawing.Size(6, 25);
  self.ItemToolShowFunction.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolShowFunction.Image := DEXiWin.Properties.Resources.ImgReport;
  self.ItemToolShowFunction.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolShowFunction.Name := 'ItemToolShowFunction';
  self.ItemToolShowFunction.Size := new System.Drawing.Size(23, 22);
  self.ItemToolShowFunction.Text := 'Show function';
  self.ItemToolShowFunction.Click += new System.EventHandler(self.ItemToolShowFunction_Click);
  self.ItemToolChart.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolChart.Image := DEXiWin.Properties.Resources.ImgFunction3D;
  self.ItemToolChart.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolChart.Name := 'ItemToolChart';
  self.ItemToolChart.Size := new System.Drawing.Size(23, 22);
  self.ItemToolChart.Text := 'Chart';
  self.ItemToolChart.ToolTipText := 'Chart';
  self.ItemToolChart.Click += new System.EventHandler(self.ItemToolsChart_Click);
  self.ItemToolWeights.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolWeights.Image := DEXiWin.Properties.Resources.ImgWeights;
  self.ItemToolWeights.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolWeights.Name := 'ItemToolWeights';
  self.ItemToolWeights.Size := new System.Drawing.Size(23, 22);
  self.ItemToolWeights.Text := 'toolStripButton1';
  self.ItemToolWeights.ToolTipText := 'Edit Weights';
  self.ItemToolWeights.Click += new System.EventHandler(self.ItemToolWeights_Click);
  self.ItemToolSymmetricity.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolSymmetricity.Image := DEXiWin.Properties.Resources.ImgSymmetricity;
  self.ItemToolSymmetricity.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolSymmetricity.Name := 'ItemToolSymmetricity';
  self.ItemToolSymmetricity.Size := new System.Drawing.Size(23, 22);
  self.ItemToolSymmetricity.Text := 'Symmetricity';
  self.ItemToolSymmetricity.Click += new System.EventHandler(self.ItemToolSymmetricity_Click);
  self.ItemToolCopyFunct.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolCopyFunct.Image := (resources.GetObject('ItemToolCopyFunct.Image') as System.Drawing.Image);
  self.ItemToolCopyFunct.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolCopyFunct.Name := 'ItemToolCopyFunct';
  self.ItemToolCopyFunct.Size := new System.Drawing.Size(23, 22);
  self.ItemToolCopyFunct.Text := '&Copy';
  self.ItemToolCopyFunct.ToolTipText := 'Copy function';
  self.ItemToolCopyFunct.Click += new System.EventHandler(self.ItemToolCopyFunct_Click);
  self.ItemToolPasteFunct.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolPasteFunct.Image := (resources.GetObject('ItemToolPasteFunct.Image') as System.Drawing.Image);
  self.ItemToolPasteFunct.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolPasteFunct.Name := 'ItemToolPasteFunct';
  self.ItemToolPasteFunct.Size := new System.Drawing.Size(23, 22);
  self.ItemToolPasteFunct.Text := '&Paste';
  self.ItemToolPasteFunct.ToolTipText := 'Paste function';
  self.ItemToolPasteFunct.Click += new System.EventHandler(self.ItemToolPasteFunct_Click);
  self.ButtonPanel.Controls.Add(self.LblStatus);
  self.ButtonPanel.Controls.Add(self.BtnCancel);
  self.ButtonPanel.Controls.Add(self.BtnOK);
  self.ButtonPanel.Dock := System.Windows.Forms.DockStyle.Bottom;
  self.ButtonPanel.Location := new System.Drawing.Point(0, 369);
  self.ButtonPanel.Name := 'ButtonPanel';
  self.ButtonPanel.Size := new System.Drawing.Size(729, 62);
  self.ButtonPanel.TabIndex := 15;
  self.LblStatus.BorderStyle := System.Windows.Forms.BorderStyle.Fixed3D;
  self.LblStatus.Dock := System.Windows.Forms.DockStyle.Top;
  self.LblStatus.Location := new System.Drawing.Point(0, 0);
  self.LblStatus.Name := 'LblStatus';
  self.LblStatus.Size := new System.Drawing.Size(729, 15);
  self.LblStatus.TabIndex := 12;
  self.LblStatus.Text := 'Status';
  self.BtnCancel.Anchor := (System.Windows.Forms.AnchorStyles.Bottom or System.Windows.Forms.AnchorStyles.Left as System.Windows.Forms.AnchorStyles);
  self.BtnCancel.DialogResult := System.Windows.Forms.DialogResult.Cancel;
  self.BtnCancel.Location := new System.Drawing.Point(94, 27);
  self.BtnCancel.Name := 'BtnCancel';
  self.BtnCancel.Size := new System.Drawing.Size(75, 23);
  self.BtnCancel.TabIndex := 10;
  self.BtnCancel.Text := '&Cancel';
  self.BtnCancel.UseVisualStyleBackColor := true;
  self.BtnOK.Anchor := (System.Windows.Forms.AnchorStyles.Bottom or System.Windows.Forms.AnchorStyles.Left as System.Windows.Forms.AnchorStyles);
  self.BtnOK.DialogResult := System.Windows.Forms.DialogResult.OK;
  self.BtnOK.Location := new System.Drawing.Point(12, 27);
  self.BtnOK.Name := 'BtnOK';
  self.BtnOK.Size := new System.Drawing.Size(75, 23);
  self.BtnOK.TabIndex := 9;
  self.BtnOK.Text := '&OK';
  self.BtnOK.UseVisualStyleBackColor := true;
  self.TablePannel.Controls.Add(self.ViewFunct);
  self.TablePannel.Dock := System.Windows.Forms.DockStyle.Fill;
  self.TablePannel.Location := new System.Drawing.Point(0, 25);
  self.TablePannel.Name := 'TablePannel';
  self.TablePannel.Size := new System.Drawing.Size(729, 344);
  self.TablePannel.TabIndex := 16;
  self.ViewFunct.AllColumns.Add(self.ColNumber);
  self.ViewFunct.AllColumns.Add(self.ColStatus);
  self.ViewFunct.AllowColumnReorder := true;
  self.ViewFunct.CellEditUseWholeCell := false;
  self.ViewFunct.Columns.AddRange(array of System.Windows.Forms.ColumnHeader([self.ColNumber, self.ColStatus]));
  self.ViewFunct.Cursor := System.Windows.Forms.Cursors.Default;
  self.ViewFunct.Dock := System.Windows.Forms.DockStyle.Fill;
  self.ViewFunct.HasCollapsibleGroups := false;
  self.ViewFunct.HideSelection := false;
  self.ViewFunct.IsSearchOnSortColumn := false;
  self.ViewFunct.Location := new System.Drawing.Point(0, 0);
  self.ViewFunct.MultiSelect := false;
  self.ViewFunct.Name := 'ViewFunct';
  self.ViewFunct.SelectAllOnControlA := false;
  self.ViewFunct.SelectColumnsMenuStaysOpen := false;
  self.ViewFunct.SelectColumnsOnRightClick := false;
  self.ViewFunct.SelectColumnsOnRightClickBehaviour := BrightIdeasSoftware.ObjectListView.ColumnSelectBehaviour.None;
  self.ViewFunct.ShowGroups := false;
  self.ViewFunct.ShowImagesOnSubItems := true;
  self.ViewFunct.Size := new System.Drawing.Size(729, 344);
  self.ViewFunct.SmallImageList := self.RuleImages;
  self.ViewFunct.Sorting := System.Windows.Forms.SortOrder.Ascending;
  self.ViewFunct.TabIndex := 15;
  self.ViewFunct.TintSortColumn := true;
  self.ViewFunct.UseCellFormatEvents := true;
  self.ViewFunct.UseCompatibleStateImageBehavior := false;
  self.ViewFunct.UseFilterIndicator := true;
  self.ViewFunct.UseFiltering := true;
  self.ViewFunct.View := System.Windows.Forms.View.Details;
  self.ViewFunct.CellEditFinished += new BrightIdeasSoftware.CellEditEventHandler(self.ViewFunct_CellEditFinished);
  self.ViewFunct.CellEditFinishing += new BrightIdeasSoftware.CellEditEventHandler(self.ViewFunct_CellEditFinishing);
  self.ViewFunct.CellEditStarting += new BrightIdeasSoftware.CellEditEventHandler(self.ViewFunct_CellEditStarting);
  self.ViewFunct.FormatCell += new System.EventHandler<BrightIdeasSoftware.FormatCellEventArgs>(self.ViewFunct_FormatCell);
  self.ViewFunct.SelectionChanged += new System.EventHandler(self.ViewFunct_SelectionChanged);
  self.ViewFunct.SelectedIndexChanged += new System.EventHandler(self.ViewFunct_SelectedIndexChanged);
  self.ViewFunct.KeyDown += new System.Windows.Forms.KeyEventHandler(self.ViewFunct_KeyDown);
  self.ViewFunct.KeyPress += new System.Windows.Forms.KeyPressEventHandler(self.ViewFunct_KeyPress);
  self.ViewFunct.MouseClick += new System.Windows.Forms.MouseEventHandler(self.ViewFunct_MouseClick);
  self.ViewFunct.MouseDoubleClick += new System.Windows.Forms.MouseEventHandler(self.ViewFunct_MouseDoubleClick);
  self.ColNumber.AspectName := 'Number';
  self.ColNumber.Groupable := false;
  self.ColNumber.Hideable := false;
  self.ColNumber.IsEditable := false;
  self.ColNumber.MaximumWidth := 60;
  self.ColNumber.MinimumWidth := 20;
  self.ColNumber.Searchable := false;
  self.ColNumber.Text := '';
  self.ColNumber.TextAlign := System.Windows.Forms.HorizontalAlignment.Right;
  self.ColNumber.ToolTipText := 'Rule number';
  self.ColNumber.UseFiltering := false;
  self.ColNumber.Width := 30;
  self.ColStatus.AspectName := 'Entered';
  self.ColStatus.Groupable := false;
  self.ColStatus.Hideable := false;
  self.ColStatus.IsEditable := false;
  self.ColStatus.MaximumWidth := 32;
  self.ColStatus.MinimumWidth := 32;
  self.ColStatus.Searchable := false;
  self.ColStatus.Sortable := false;
  self.ColStatus.Text := 'Stat';
  self.ColStatus.ToolTipText := 'Status';
  self.ColStatus.UseFiltering := false;
  self.ColStatus.Width := 32;
  self.RuleImages.ImageStream := (resources.GetObject('RuleImages.ImageStream') as System.Windows.Forms.ImageListStreamer);
  self.RuleImages.TransparentColor := System.Drawing.Color.Transparent;
  self.RuleImages.Images.SetKeyName(0, 'ImgRuleEntered');
  self.RuleImages.Images.SetKeyName(1, 'ImgRuleEnteredInconsist');
  self.RuleImages.Images.SetKeyName(2, 'ImgRuleInconsist');
  self.FunctMenu.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.toolStripSeparator4, self.ItemPopUndefinedValue, self.ItemPopDeleteRule, self.toolStripSeparator2, self.ItemPopRuleStatus, self.ItemPopEnter, self.ItemPopSymmetrcity, self.toolStripSeparator6, self.ItemPopResizeColumns, self.ItemPopResetColumns]));
  self.FunctMenu.Name := 'FunctMenu';
  self.FunctMenu.Size := new System.Drawing.Size(186, 176);
  self.toolStripSeparator4.Name := 'toolStripSeparator4';
  self.toolStripSeparator4.Size := new System.Drawing.Size(182, 6);
  self.ItemPopUndefinedValue.Name := 'ItemPopUndefinedValue';
  self.ItemPopUndefinedValue.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Delete as System.Windows.Forms.Keys);
  self.ItemPopUndefinedValue.Size := new System.Drawing.Size(185, 22);
  self.ItemPopUndefinedValue.Tag := '-1';
  self.ItemPopUndefinedValue.Text := 'Undefined';
  self.ItemPopUndefinedValue.ToolTipText := 'Declare rule value as undefined';
  self.ItemPopUndefinedValue.Click += new System.EventHandler(self.ItemPopUndefinedValue_Click);
  self.ItemPopDeleteRule.Image := DEXiWin.Properties.Resources.ImgRuleDelete;
  self.ItemPopDeleteRule.Name := 'ItemPopDeleteRule';
  self.ItemPopDeleteRule.ShortcutKeys := System.Windows.Forms.Keys.Delete;
  self.ItemPopDeleteRule.Size := new System.Drawing.Size(185, 22);
  self.ItemPopDeleteRule.Text := '&Delete rule value';
  self.ItemPopDeleteRule.Click += new System.EventHandler(self.ItemToolDeleteRule_Click);
  self.toolStripSeparator2.Name := 'toolStripSeparator2';
  self.toolStripSeparator2.Size := new System.Drawing.Size(182, 6);
  self.ItemPopRuleStatus.Name := 'ItemPopRuleStatus';
  self.ItemPopRuleStatus.Size := new System.Drawing.Size(185, 22);
  self.ItemPopRuleStatus.Text := 'Rule status...';
  self.ItemPopRuleStatus.Click += new System.EventHandler(self.ItemPopRuleStatus_Click);
  self.ItemPopEnter.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemPopEnterTable, self.ItemPopEnterSingle]));
  self.ItemPopEnter.Name := 'ItemPopEnter';
  self.ItemPopEnter.Size := new System.Drawing.Size(185, 22);
  self.ItemPopEnter.Text := 'Enter rule &values';
  self.ItemPopEnterTable.Name := 'ItemPopEnterTable';
  self.ItemPopEnterTable.Size := new System.Drawing.Size(287, 22);
  self.ItemPopEnterTable.Text := '&Whole table';
  self.ItemPopEnterTable.Click += new System.EventHandler(self.ItemPopEnterTable_Click);
  self.ItemPopEnterSingle.Name := 'ItemPopEnterSingle';
  self.ItemPopEnterSingle.Size := new System.Drawing.Size(287, 22);
  self.ItemPopEnterSingle.Text := 'Rules having single (non-interval) values';
  self.ItemPopEnterSingle.Click += new System.EventHandler(self.ItemPopEnterSingle_Click);
  self.ItemPopSymmetrcity.Image := DEXiWin.Properties.Resources.ImgSymmetricity;
  self.ItemPopSymmetrcity.Name := 'ItemPopSymmetrcity';
  self.ItemPopSymmetrcity.Size := new System.Drawing.Size(185, 22);
  self.ItemPopSymmetrcity.Text := 'Symmetricity...';
  self.toolStripSeparator6.Name := 'toolStripSeparator6';
  self.toolStripSeparator6.Size := new System.Drawing.Size(182, 6);
  self.ItemPopResizeColumns.Name := 'ItemPopResizeColumns';
  self.ItemPopResizeColumns.ShortcutKeys := System.Windows.Forms.Keys.F8;
  self.ItemPopResizeColumns.Size := new System.Drawing.Size(185, 22);
  self.ItemPopResizeColumns.Text := 'Re&size columns';
  self.ItemPopResizeColumns.ToolTipText := 'Resize columns';
  self.ItemPopResizeColumns.Click += new System.EventHandler(self.ItemPopResizeColumns_Click);
  self.ItemPopResetColumns.Name := 'ItemPopResetColumns';
  self.ItemPopResetColumns.ShortcutKeys := System.Windows.Forms.Keys.F9;
  self.ItemPopResetColumns.Size := new System.Drawing.Size(185, 22);
  self.ItemPopResetColumns.Text := 'Reset columns';
  self.ItemPopResetColumns.ToolTipText := 'Reset table columns';
  self.ItemPopResetColumns.Click += new System.EventHandler(self.ItemPopResetColumns_Click);
  self.HeaderFormat.Hot := headerStateStyle1;
  self.HeaderFormat.Normal := headerStateStyle2;
  self.HeaderFormat.Pressed := headerStateStyle3;
  self.AutoImages.ImageStream := (resources.GetObject('AutoImages.ImageStream') as System.Windows.Forms.ImageListStreamer);
  self.AutoImages.TransparentColor := System.Drawing.Color.Transparent;
  self.AutoImages.Images.SetKeyName(0, 'ImgAutoNone');
  self.AutoImages.Images.SetKeyName(1, 'ImgAutoDominance');
  self.AutoImages.Images.SetKeyName(2, 'ImgAutoWeights');
  self.AutoImages.Images.SetKeyName(3, 'ImgAutoAll');
  self.AutoScaleDimensions := new System.Drawing.SizeF(6.0, 13.0);
  self.AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font;
  self.ClientSize := new System.Drawing.Size(729, 431);
  self.Controls.Add(self.TablePannel);
  self.Controls.Add(self.ButtonPanel);
  self.Controls.Add(self.FormTool);
  self.Name := 'FormFunctEditTabular';
  self.ShowIcon := false;
  self.ShowInTaskbar := false;
  self.StartPosition := System.Windows.Forms.FormStartPosition.CenterParent;
  self.Text := 'Edit function of "{0}"';
  self.FormTool.ResumeLayout(false);
  self.FormTool.PerformLayout();
  self.ButtonPanel.ResumeLayout(false);
  self.TablePannel.ResumeLayout(false);
  (self.ViewFunct as System.ComponentModel.ISupportInitialize).EndInit();
  self.FunctMenu.ResumeLayout(false);
  self.ResumeLayout(false);
  self.PerformLayout();
end;
{$ENDREGION}

end.