namespace DexiWin;

interface

{$HIDE H7}

uses
  System.Drawing,
  System.Collections,
  System.Windows.Forms,
  System.ComponentModel;

type
  FormReportManager = partial class
  {$REGION Windows Form Designer generated fields}
  private
    ItemToolAddStat: System.Windows.Forms.ToolStripMenuItem;
    ItemPopShow: System.Windows.Forms.ToolStripMenuItem;
    
    ItemAddFnc: System.Windows.Forms.ToolStripMenuItem;
    ItemToolAddScales: System.Windows.Forms.ToolStripMenuItem;
    ItemToolAddAttDescr: System.Windows.Forms.ToolStripMenuItem;
    ItemPopDuplicate: System.Windows.Forms.ToolStripMenuItem;
    ItemPopDelete: System.Windows.Forms.ToolStripMenuItem;
    
    toolStripSeparator1: System.Windows.Forms.ToolStripSeparator;
    ItemPopUnSelectAll: System.Windows.Forms.ToolStripMenuItem;
    ItemPopSelectAll: System.Windows.Forms.ToolStripMenuItem;
    ItemPopMoveDown: System.Windows.Forms.ToolStripMenuItem;
    ItemPopMoveUp: System.Windows.Forms.ToolStripMenuItem;
    ItemPopSettings: System.Windows.Forms.ToolStripMenuItem;
    RptManagerMenu: System.Windows.Forms.ContextMenuStrip;
    PageElements: System.Windows.Forms.TabPage;
    ItemToolAddAlt: System.Windows.Forms.ToolStripMenuItem;
    CtrlFormat: DexiWin.CtrlRptFormat;
    TabsReports: System.Windows.Forms.TabControl;
    
    PageFormat: System.Windows.Forms.TabPage;
    ItemToolAddModel: System.Windows.Forms.ToolStripMenuItem;
    ItemToolAddAttInfo: System.Windows.Forms.ToolStripMenuItem;
    ItemToolAddAttTree: System.Windows.Forms.ToolStripMenuItem;
    ItemToolAddFncSum: System.Windows.Forms.ToolStripMenuItem;
    ItemToolAddWeights: System.Windows.Forms.ToolStripMenuItem;
    ItemToolAddEval: System.Windows.Forms.ToolStripMenuItem;
    ItemToolAdd: System.Windows.Forms.ToolStripDropDownButton;
    ImgToolUnSelectAll: System.Windows.Forms.ToolStripButton;
    ItemToolSelectAll: System.Windows.Forms.ToolStripButton;
    ItemToolShow: System.Windows.Forms.ToolStripMenuItem;
    ItemToolCopy: System.Windows.Forms.ToolStripMenuItem;
    ItemToolCopyNewTab: System.Windows.Forms.ToolStripMenuItem;
    ItemToolMove: System.Windows.Forms.ToolStripMenuItem;
    ItemToolMoveNewTab: System.Windows.Forms.ToolStripMenuItem;
    ItemToolDuplicate: System.Windows.Forms.ToolStripButton;
    ItemToolDelete: System.Windows.Forms.ToolStripButton;
    ItemToolOpen: System.Windows.Forms.ToolStripDropDownButton;
    ItemToolMoveDown: System.Windows.Forms.ToolStripButton;
    ItemToolMoveUp: System.Windows.Forms.ToolStripButton;
    ItemToolSettings: System.Windows.Forms.ToolStripButton;
    ColReport: BrightIdeasSoftware.OLVColumn;
    ViewReports: BrightIdeasSoftware.ObjectListView;
    
    
    
    AutoImages: System.Windows.Forms.ImageList;
    toolStripSeparator4: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator2: System.Windows.Forms.ToolStripSeparator;
    
    HeaderFormat: BrightIdeasSoftware.HeaderFormatStyle;
    TablePannel: System.Windows.Forms.Panel;
    ButtonPanel: System.Windows.Forms.Panel;
    FormTool: System.Windows.Forms.ToolStrip;
    BtnOK: System.Windows.Forms.Button;
    var components: System.ComponentModel.Container := nil;
    method InitializeComponent;
  {$ENDREGION}
  end;

implementation

{$REGION Windows Form Designer generated code}
method FormReportManager.InitializeComponent;
begin
  self.components := new System.ComponentModel.Container();
  var resources: System.ComponentModel.ComponentResourceManager := new System.ComponentModel.ComponentResourceManager(typeOf(FormReportManager));
  var headerStateStyle1: BrightIdeasSoftware.HeaderStateStyle := new BrightIdeasSoftware.HeaderStateStyle();
  var headerStateStyle2: BrightIdeasSoftware.HeaderStateStyle := new BrightIdeasSoftware.HeaderStateStyle();
  var headerStateStyle3: BrightIdeasSoftware.HeaderStateStyle := new BrightIdeasSoftware.HeaderStateStyle();
  self.FormTool := new System.Windows.Forms.ToolStrip();
  self.ItemToolSettings := new System.Windows.Forms.ToolStripButton();
  self.ItemToolAdd := new System.Windows.Forms.ToolStripDropDownButton();
  self.ItemToolAddModel := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolAddAttInfo := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolAddAttTree := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolAddAttDescr := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolAddScales := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemAddFnc := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolAddFncSum := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolAddWeights := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolAddAlt := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolAddEval := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolDelete := new System.Windows.Forms.ToolStripButton();
  self.ItemToolDuplicate := new System.Windows.Forms.ToolStripButton();
  self.ItemToolOpen := new System.Windows.Forms.ToolStripDropDownButton();
  self.ItemToolShow := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolCopy := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolCopyNewTab := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolMove := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolMoveNewTab := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemToolMoveDown := new System.Windows.Forms.ToolStripButton();
  self.ItemToolMoveUp := new System.Windows.Forms.ToolStripButton();
  self.ItemToolSelectAll := new System.Windows.Forms.ToolStripButton();
  self.ImgToolUnSelectAll := new System.Windows.Forms.ToolStripButton();
  self.ButtonPanel := new System.Windows.Forms.Panel();
  self.BtnOK := new System.Windows.Forms.Button();
  self.TablePannel := new System.Windows.Forms.Panel();
  self.TabsReports := new System.Windows.Forms.TabControl();
  self.PageElements := new System.Windows.Forms.TabPage();
  self.ViewReports := new BrightIdeasSoftware.ObjectListView();
  self.ColReport := (new BrightIdeasSoftware.OLVColumn() as BrightIdeasSoftware.OLVColumn);
  self.RptManagerMenu := new System.Windows.Forms.ContextMenuStrip(self.components);
  self.ItemPopSettings := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopShow := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator4 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopDelete := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopDuplicate := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator2 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopMoveUp := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopMoveDown := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator1 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopSelectAll := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopUnSelectAll := new System.Windows.Forms.ToolStripMenuItem();
  self.PageFormat := new System.Windows.Forms.TabPage();
  self.CtrlFormat := new DexiWin.CtrlRptFormat();
  self.HeaderFormat := new BrightIdeasSoftware.HeaderFormatStyle();
  self.AutoImages := new System.Windows.Forms.ImageList(self.components);
  self.ItemToolAddStat := new System.Windows.Forms.ToolStripMenuItem();
  self.FormTool.SuspendLayout();
  self.ButtonPanel.SuspendLayout();
  self.TablePannel.SuspendLayout();
  self.TabsReports.SuspendLayout();
  self.PageElements.SuspendLayout();
  (self.ViewReports as System.ComponentModel.ISupportInitialize).BeginInit();
  self.RptManagerMenu.SuspendLayout();
  self.PageFormat.SuspendLayout();
  self.SuspendLayout();
  self.FormTool.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemToolSettings, self.ItemToolAdd, self.ItemToolDelete, self.ItemToolDuplicate, self.ItemToolOpen, self.ItemToolMoveDown, self.ItemToolMoveUp, self.ItemToolSelectAll, self.ImgToolUnSelectAll]));
  self.FormTool.Location := new System.Drawing.Point(0, 0);
  self.FormTool.Name := 'FormTool';
  self.FormTool.Size := new System.Drawing.Size(729, 25);
  self.FormTool.TabIndex := 13;
  self.ItemToolSettings.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolSettings.Image := (resources.GetObject('ItemToolSettings.Image') as System.Drawing.Image);
  self.ItemToolSettings.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolSettings.Name := 'ItemToolSettings';
  self.ItemToolSettings.Size := new System.Drawing.Size(23, 22);
  self.ItemToolSettings.Text := 'Report parameters';
  self.ItemToolSettings.Click += new System.EventHandler(self.ItemToolSettings_Click);
  self.ItemToolAdd.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolAdd.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemToolAddModel, self.ItemToolAddStat, self.ItemToolAddAttInfo, self.ItemToolAddAttTree, self.ItemToolAddAttDescr, self.ItemToolAddScales, self.ItemAddFnc, self.ItemToolAddFncSum, self.ItemToolAddWeights, self.ItemToolAddAlt, self.ItemToolAddEval]));
  self.ItemToolAdd.Image := (resources.GetObject('ItemToolAdd.Image') as System.Drawing.Image);
  self.ItemToolAdd.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolAdd.Name := 'ItemToolAdd';
  self.ItemToolAdd.Size := new System.Drawing.Size(29, 22);
  self.ItemToolAdd.Text := 'Add report element';
  self.ItemToolAddModel.Name := 'ItemToolAddModel';
  self.ItemToolAddModel.Size := new System.Drawing.Size(200, 22);
  self.ItemToolAddModel.Text := '&Model description';
  self.ItemToolAddModel.ToolTipText := 'Model name and description';
  self.ItemToolAddModel.Click += new System.EventHandler(self.ItemToolAddModel_Click);
  self.ItemToolAddAttInfo.Name := 'ItemToolAddAttInfo';
  self.ItemToolAddAttInfo.Size := new System.Drawing.Size(200, 22);
  self.ItemToolAddAttInfo.Text := 'Attribute &information';
  self.ItemToolAddAttInfo.ToolTipText := 'Traverse the model and display: attribute name, description, scale and function (selectable)';
  self.ItemToolAddAttInfo.Click += new System.EventHandler(self.ItemToolAddAttInfo_Click);
  self.ItemToolAddAttTree.Name := 'ItemToolAddAttTree';
  self.ItemToolAddAttTree.Size := new System.Drawing.Size(200, 22);
  self.ItemToolAddAttTree.Text := 'Attribute &tree';
  self.ItemToolAddAttTree.ToolTipText := 'Show model structure together with: attribute description, scale, function summary (selectable)';
  self.ItemToolAddAttTree.Click += new System.EventHandler(self.ItemToolAddAttTree_Click);
  self.ItemToolAddAttDescr.AccessibleRole := System.Windows.Forms.AccessibleRole.PageTabList;
  self.ItemToolAddAttDescr.Name := 'ItemToolAddAttDescr';
  self.ItemToolAddAttDescr.Size := new System.Drawing.Size(200, 22);
  self.ItemToolAddAttDescr.Text := '    Attribute &descriptions';
  self.ItemToolAddAttDescr.ToolTipText := 'Show model structure together with attribute descriptions';
  self.ItemToolAddAttDescr.Click += new System.EventHandler(self.ItemToolAddAttDescr_Click);
  self.ItemToolAddScales.Name := 'ItemToolAddScales';
  self.ItemToolAddScales.Size := new System.Drawing.Size(200, 22);
  self.ItemToolAddScales.Text := '    &Scales';
  self.ItemToolAddScales.ToolTipText := 'Show model structure together with scales';
  self.ItemToolAddScales.Click += new System.EventHandler(self.ItemToolAddScales_Click);
  self.ItemAddFnc.Name := 'ItemAddFnc';
  self.ItemAddFnc.Size := new System.Drawing.Size(200, 22);
  self.ItemAddFnc.Text := '    &Function summary';
  self.ItemAddFnc.ToolTipText := 'Show model structure together with function summaries';
  self.ItemAddFnc.Click += new System.EventHandler(self.ItemToolAddFncSum_Click);
  self.ItemToolAddFncSum.Name := 'ItemToolAddFncSum';
  self.ItemToolAddFncSum.Size := new System.Drawing.Size(200, 22);
  self.ItemToolAddFncSum.Text := 'F&unction information';
  self.ItemToolAddFncSum.ToolTipText := 'Show model structure together with function information';
  self.ItemToolAddFncSum.Click += new System.EventHandler(self.ItemToolAddFnc_Click);
  self.ItemToolAddWeights.Name := 'ItemToolAddWeights';
  self.ItemToolAddWeights.Size := new System.Drawing.Size(200, 22);
  self.ItemToolAddWeights.Text := '&Weights tree';
  self.ItemToolAddWeights.ToolTipText := 'Show model structure together with attribute weights';
  self.ItemToolAddWeights.Click += new System.EventHandler(self.ItemToolAddWeights_Click);
  self.ItemToolAddAlt.Name := 'ItemToolAddAlt';
  self.ItemToolAddAlt.Size := new System.Drawing.Size(200, 22);
  self.ItemToolAddAlt.Text := '&Alternatives';
  self.ItemToolAddAlt.ToolTipText := "Show alternatives' descriptions (input data))";
  self.ItemToolAddAlt.Click += new System.EventHandler(self.ItemToolAddAlt_Click);
  self.ItemToolAddEval.Name := 'ItemToolAddEval';
  self.ItemToolAddEval.Size := new System.Drawing.Size(200, 22);
  self.ItemToolAddEval.Text := '&Evaluation results';
  self.ItemToolAddEval.ToolTipText := 'Show model structure together evaluation results';
  self.ItemToolAddEval.Click += new System.EventHandler(self.ItemToolAddEval_Click);
  self.ItemToolDelete.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolDelete.Image := (resources.GetObject('ItemToolDelete.Image') as System.Drawing.Image);
  self.ItemToolDelete.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolDelete.Name := 'ItemToolDelete';
  self.ItemToolDelete.Size := new System.Drawing.Size(23, 22);
  self.ItemToolDelete.Text := 'Delete report element';
  self.ItemToolDelete.Click += new System.EventHandler(self.ItemToolDelete_Click);
  self.ItemToolDuplicate.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolDuplicate.Image := (resources.GetObject('ItemToolDuplicate.Image') as System.Drawing.Image);
  self.ItemToolDuplicate.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolDuplicate.Name := 'ItemToolDuplicate';
  self.ItemToolDuplicate.Size := new System.Drawing.Size(23, 22);
  self.ItemToolDuplicate.Text := 'Duplicate report element';
  self.ItemToolDuplicate.Click += new System.EventHandler(self.ItemToolDuplicate_Click);
  self.ItemToolOpen.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolOpen.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemToolShow, self.ItemToolCopy, self.ItemToolMove]));
  self.ItemToolOpen.Image := (resources.GetObject('ItemToolOpen.Image') as System.Drawing.Image);
  self.ItemToolOpen.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolOpen.Name := 'ItemToolOpen';
  self.ItemToolOpen.Size := new System.Drawing.Size(29, 22);
  self.ItemToolOpen.Text := 'Open, copy or move report element';
  self.ItemToolShow.Image := DEXiWin.Properties.Resources.PrevWindow;
  self.ItemToolShow.Name := 'ItemToolShow';
  self.ItemToolShow.Size := new System.Drawing.Size(170, 22);
  self.ItemToolShow.Text := 'Show in a &window';
  self.ItemToolShow.Click += new System.EventHandler(self.ItemToolShow_Click);
  self.ItemToolCopy.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemToolCopyNewTab]));
  self.ItemToolCopy.Name := 'ItemToolCopy';
  self.ItemToolCopy.Size := new System.Drawing.Size(170, 22);
  self.ItemToolCopy.Text := '&Copy to';
  self.ItemToolCopyNewTab.Name := 'ItemToolCopyNewTab';
  self.ItemToolCopyNewTab.Size := new System.Drawing.Size(118, 22);
  self.ItemToolCopyNewTab.Text := '&New tab';
  self.ItemToolCopyNewTab.Click += new System.EventHandler(self.ItemToolCopyNewTab_Click);
  self.ItemToolMove.DropDownItems.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemToolMoveNewTab]));
  self.ItemToolMove.Name := 'ItemToolMove';
  self.ItemToolMove.Size := new System.Drawing.Size(170, 22);
  self.ItemToolMove.Text := '&Move to';
  self.ItemToolMoveNewTab.Name := 'ItemToolMoveNewTab';
  self.ItemToolMoveNewTab.Size := new System.Drawing.Size(118, 22);
  self.ItemToolMoveNewTab.Text := '&New tab';
  self.ItemToolMoveNewTab.Click += new System.EventHandler(self.ItemToolMoveNewTab_Click);
  self.ItemToolMoveDown.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolMoveDown.Image := (resources.GetObject('ItemToolMoveDown.Image') as System.Drawing.Image);
  self.ItemToolMoveDown.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolMoveDown.Name := 'ItemToolMoveDown';
  self.ItemToolMoveDown.Size := new System.Drawing.Size(23, 22);
  self.ItemToolMoveDown.Text := 'Move down';
  self.ItemToolMoveDown.ToolTipText := 'Move report down';
  self.ItemToolMoveDown.Click += new System.EventHandler(self.ItemToolMoveDown_Click);
  self.ItemToolMoveUp.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolMoveUp.Image := (resources.GetObject('ItemToolMoveUp.Image') as System.Drawing.Image);
  self.ItemToolMoveUp.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolMoveUp.Name := 'ItemToolMoveUp';
  self.ItemToolMoveUp.Size := new System.Drawing.Size(23, 22);
  self.ItemToolMoveUp.Text := 'Move up';
  self.ItemToolMoveUp.ToolTipText := 'Move report up';
  self.ItemToolMoveUp.Click += new System.EventHandler(self.ItemToolMoveUp_Click);
  self.ItemToolSelectAll.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolSelectAll.Image := (resources.GetObject('ItemToolSelectAll.Image') as System.Drawing.Image);
  self.ItemToolSelectAll.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolSelectAll.Name := 'ItemToolSelectAll';
  self.ItemToolSelectAll.Size := new System.Drawing.Size(23, 22);
  self.ItemToolSelectAll.Text := 'Select all report elements';
  self.ItemToolSelectAll.Click += new System.EventHandler(self.ItemToolSelectAll_Click);
  self.ImgToolUnSelectAll.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ImgToolUnSelectAll.Image := (resources.GetObject('ImgToolUnSelectAll.Image') as System.Drawing.Image);
  self.ImgToolUnSelectAll.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ImgToolUnSelectAll.Name := 'ImgToolUnSelectAll';
  self.ImgToolUnSelectAll.Size := new System.Drawing.Size(23, 22);
  self.ImgToolUnSelectAll.Text := 'Unselect all report elements';
  self.ImgToolUnSelectAll.Click += new System.EventHandler(self.ImgToolUnSelectAll_Click);
  self.ButtonPanel.Controls.Add(self.BtnOK);
  self.ButtonPanel.Dock := System.Windows.Forms.DockStyle.Bottom;
  self.ButtonPanel.Location := new System.Drawing.Point(0, 530);
  self.ButtonPanel.Name := 'ButtonPanel';
  self.ButtonPanel.Size := new System.Drawing.Size(729, 45);
  self.ButtonPanel.TabIndex := 15;
  self.BtnOK.Anchor := (System.Windows.Forms.AnchorStyles.Bottom or System.Windows.Forms.AnchorStyles.Left as System.Windows.Forms.AnchorStyles);
  self.BtnOK.DialogResult := System.Windows.Forms.DialogResult.OK;
  self.BtnOK.Location := new System.Drawing.Point(12, 10);
  self.BtnOK.Name := 'BtnOK';
  self.BtnOK.Size := new System.Drawing.Size(75, 23);
  self.BtnOK.TabIndex := 9;
  self.BtnOK.Text := '&Close';
  self.BtnOK.UseVisualStyleBackColor := true;
  self.TablePannel.Controls.Add(self.TabsReports);
  self.TablePannel.Dock := System.Windows.Forms.DockStyle.Fill;
  self.TablePannel.Location := new System.Drawing.Point(0, 25);
  self.TablePannel.Name := 'TablePannel';
  self.TablePannel.Size := new System.Drawing.Size(729, 505);
  self.TablePannel.TabIndex := 16;
  self.TabsReports.Controls.Add(self.PageElements);
  self.TabsReports.Controls.Add(self.PageFormat);
  self.TabsReports.Dock := System.Windows.Forms.DockStyle.Fill;
  self.TabsReports.Location := new System.Drawing.Point(0, 0);
  self.TabsReports.Name := 'TabsReports';
  self.TabsReports.SelectedIndex := 0;
  self.TabsReports.Size := new System.Drawing.Size(729, 505);
  self.TabsReports.TabIndex := 16;
  self.PageElements.Controls.Add(self.ViewReports);
  self.PageElements.Location := new System.Drawing.Point(4, 22);
  self.PageElements.Name := 'PageElements';
  self.PageElements.Padding := new System.Windows.Forms.Padding(3);
  self.PageElements.Size := new System.Drawing.Size(721, 479);
  self.PageElements.TabIndex := 0;
  self.PageElements.Text := 'Elements';
  self.PageElements.UseVisualStyleBackColor := true;
  self.ViewReports.AllColumns.Add(self.ColReport);
  self.ViewReports.CellEditActivation := BrightIdeasSoftware.ObjectListView.CellEditActivateMode.F2Only;
  self.ViewReports.CellEditUseWholeCell := false;
  self.ViewReports.CheckBoxes := true;
  self.ViewReports.Columns.AddRange(array of System.Windows.Forms.ColumnHeader([self.ColReport]));
  self.ViewReports.ContextMenuStrip := self.RptManagerMenu;
  self.ViewReports.Cursor := System.Windows.Forms.Cursors.Default;
  self.ViewReports.Dock := System.Windows.Forms.DockStyle.Fill;
  self.ViewReports.HasCollapsibleGroups := false;
  self.ViewReports.HeaderStyle := System.Windows.Forms.ColumnHeaderStyle.None;
  self.ViewReports.HideSelection := false;
  self.ViewReports.IsSearchOnSortColumn := false;
  self.ViewReports.Location := new System.Drawing.Point(3, 3);
  self.ViewReports.MultiSelect := false;
  self.ViewReports.Name := 'ViewReports';
  self.ViewReports.SelectAllOnControlA := false;
  self.ViewReports.SelectColumnsMenuStaysOpen := false;
  self.ViewReports.SelectColumnsOnRightClick := false;
  self.ViewReports.SelectColumnsOnRightClickBehaviour := BrightIdeasSoftware.ObjectListView.ColumnSelectBehaviour.None;
  self.ViewReports.ShowGroups := false;
  self.ViewReports.Size := new System.Drawing.Size(715, 473);
  self.ViewReports.TabIndex := 15;
  self.ViewReports.UseCompatibleStateImageBehavior := false;
  self.ViewReports.View := System.Windows.Forms.View.Details;
  self.ViewReports.SelectionChanged += new System.EventHandler(self.ViewReports_SelectionChanged);
  self.ViewReports.KeyDown += new System.Windows.Forms.KeyEventHandler(self.ViewReports_KeyDown);
  self.ViewReports.MouseDoubleClick += new System.Windows.Forms.MouseEventHandler(self.ViewReports_MouseDoubleClick);
  self.ColReport.AspectName := 'Title';
  self.ColReport.FillsFreeSpace := true;
  self.ColReport.Groupable := false;
  self.ColReport.Hideable := false;
  self.ColReport.MinimumWidth := 20;
  self.ColReport.Searchable := false;
  self.ColReport.Sortable := false;
  self.ColReport.Text := '';
  self.ColReport.ToolTipText := 'Report';
  self.ColReport.UseFiltering := false;
  self.ColReport.Width := 30;
  self.RptManagerMenu.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemPopSettings, self.ItemPopShow, self.toolStripSeparator4, self.ItemPopDelete, self.ItemPopDuplicate, self.toolStripSeparator2, self.ItemPopMoveUp, self.ItemPopMoveDown, self.toolStripSeparator1, self.ItemPopSelectAll, self.ItemPopUnSelectAll]));
  self.RptManagerMenu.Name := 'FunctMenu';
  self.RptManagerMenu.Size := new System.Drawing.Size(246, 198);
  self.ItemPopSettings.Image := DEXiWin.Properties.Resources.ImgSettings;
  self.ItemPopSettings.Name := 'ItemPopSettings';
  self.ItemPopSettings.Size := new System.Drawing.Size(245, 22);
  self.ItemPopSettings.Text := 'Report parameters';
  self.ItemPopSettings.Click += new System.EventHandler(self.ItemToolSettings_Click);
  self.ItemPopShow.Image := DEXiWin.Properties.Resources.PrevWindow;
  self.ItemPopShow.Name := 'ItemPopShow';
  self.ItemPopShow.Size := new System.Drawing.Size(245, 22);
  self.ItemPopShow.Text := 'Show in a &window';
  self.ItemPopShow.Click += new System.EventHandler(self.ItemToolShow_Click);
  self.toolStripSeparator4.Name := 'toolStripSeparator4';
  self.toolStripSeparator4.Size := new System.Drawing.Size(242, 6);
  self.ItemPopDelete.Image := DEXiWin.Properties.Resources.ImgReportDelete;
  self.ItemPopDelete.Name := 'ItemPopDelete';
  self.ItemPopDelete.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Delete as System.Windows.Forms.Keys);
  self.ItemPopDelete.Size := new System.Drawing.Size(245, 22);
  self.ItemPopDelete.Text := 'Delete report element';
  self.ItemPopDelete.Click += new System.EventHandler(self.ItemToolDelete_Click);
  self.ItemPopDuplicate.Image := DEXiWin.Properties.Resources.ImgReportDuplicate;
  self.ItemPopDuplicate.Name := 'ItemPopDuplicate';
  self.ItemPopDuplicate.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.D2 as System.Windows.Forms.Keys);
  self.ItemPopDuplicate.Size := new System.Drawing.Size(245, 22);
  self.ItemPopDuplicate.Text := 'Duplicate report element';
  self.ItemPopDuplicate.Click += new System.EventHandler(self.ItemToolDuplicate_Click);
  self.toolStripSeparator2.Name := 'toolStripSeparator2';
  self.toolStripSeparator2.Size := new System.Drawing.Size(242, 6);
  self.ItemPopMoveUp.Image := DEXiWin.Properties.Resources.ImgMoveUp;
  self.ItemPopMoveUp.Name := 'ItemPopMoveUp';
  self.ItemPopMoveUp.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Up as System.Windows.Forms.Keys);
  self.ItemPopMoveUp.Size := new System.Drawing.Size(245, 22);
  self.ItemPopMoveUp.Text := 'Move up';
  self.ItemPopMoveUp.ToolTipText := 'Move attribute up';
  self.ItemPopMoveUp.Click += new System.EventHandler(self.ItemToolMoveUp_Click);
  self.ItemPopMoveDown.Image := DEXiWin.Properties.Resources.ImgMoveDown;
  self.ItemPopMoveDown.Name := 'ItemPopMoveDown';
  self.ItemPopMoveDown.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Down as System.Windows.Forms.Keys);
  self.ItemPopMoveDown.Size := new System.Drawing.Size(245, 22);
  self.ItemPopMoveDown.Text := 'Move down';
  self.ItemPopMoveDown.ToolTipText := 'Move attribute down';
  self.ItemPopMoveDown.Click += new System.EventHandler(self.ItemToolMoveDown_Click);
  self.toolStripSeparator1.Name := 'toolStripSeparator1';
  self.toolStripSeparator1.Size := new System.Drawing.Size(242, 6);
  self.ItemPopSelectAll.Image := DEXiWin.Properties.Resources.ImgCheck;
  self.ItemPopSelectAll.Name := 'ItemPopSelectAll';
  self.ItemPopSelectAll.Size := new System.Drawing.Size(245, 22);
  self.ItemPopSelectAll.Text := 'Select &all';
  self.ItemPopSelectAll.Click += new System.EventHandler(self.ItemToolSelectAll_Click);
  self.ItemPopUnSelectAll.Image := DEXiWin.Properties.Resources.ImgClear;
  self.ItemPopUnSelectAll.Name := 'ItemPopUnSelectAll';
  self.ItemPopUnSelectAll.Size := new System.Drawing.Size(245, 22);
  self.ItemPopUnSelectAll.Text := '&Unselect all';
  self.ItemPopUnSelectAll.Click += new System.EventHandler(self.ImgToolUnSelectAll_Click);
  self.PageFormat.Controls.Add(self.CtrlFormat);
  self.PageFormat.Location := new System.Drawing.Point(4, 22);
  self.PageFormat.Name := 'PageFormat';
  self.PageFormat.Padding := new System.Windows.Forms.Padding(3);
  self.PageFormat.Size := new System.Drawing.Size(721, 479);
  self.PageFormat.TabIndex := 1;
  self.PageFormat.Text := 'Format';
  self.PageFormat.UseVisualStyleBackColor := true;
  self.CtrlFormat.CanEditTitle := true;
  self.CtrlFormat.Dock := System.Windows.Forms.DockStyle.Fill;
  self.CtrlFormat.Location := new System.Drawing.Point(3, 3);
  self.CtrlFormat.Name := 'CtrlFormat';
  self.CtrlFormat.Size := new System.Drawing.Size(715, 473);
  self.CtrlFormat.TabIndex := 0;
  self.HeaderFormat.Hot := headerStateStyle1;
  self.HeaderFormat.Normal := headerStateStyle2;
  self.HeaderFormat.Pressed := headerStateStyle3;
  self.AutoImages.ImageStream := (resources.GetObject('AutoImages.ImageStream') as System.Windows.Forms.ImageListStreamer);
  self.AutoImages.TransparentColor := System.Drawing.Color.Transparent;
  self.AutoImages.Images.SetKeyName(0, 'ImgAutoNone');
  self.AutoImages.Images.SetKeyName(1, 'ImgAutoDominance');
  self.AutoImages.Images.SetKeyName(2, 'ImgAutoWeights');
  self.AutoImages.Images.SetKeyName(3, 'ImgAutoAll');
  self.ItemToolAddStat.Name := 'ItemToolAddStat';
  self.ItemToolAddStat.Size := new System.Drawing.Size(200, 22);
  self.ItemToolAddStat.Text := 'Model statistics';
  self.ItemToolAddStat.ToolTipText := 'Model statistics';
  self.ItemToolAddStat.Click += new System.EventHandler(self.ItemToolAddStat_Click);
  self.AutoScaleDimensions := new System.Drawing.SizeF(6.0, 13.0);
  self.AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font;
  self.ClientSize := new System.Drawing.Size(729, 575);
  self.Controls.Add(self.TablePannel);
  self.Controls.Add(self.ButtonPanel);
  self.Controls.Add(self.FormTool);
  self.Name := 'FormReportManager';
  self.ShowIcon := false;
  self.ShowInTaskbar := false;
  self.StartPosition := System.Windows.Forms.FormStartPosition.CenterParent;
  self.Text := 'Report manager';
  self.Activated += new System.EventHandler(self.FormReportManager_Activated);
  self.FormTool.ResumeLayout(false);
  self.FormTool.PerformLayout();
  self.ButtonPanel.ResumeLayout(false);
  self.TablePannel.ResumeLayout(false);
  self.TabsReports.ResumeLayout(false);
  self.PageElements.ResumeLayout(false);
  (self.ViewReports as System.ComponentModel.ISupportInitialize).EndInit();
  self.RptManagerMenu.ResumeLayout(false);
  self.PageFormat.ResumeLayout(false);
  self.ResumeLayout(false);
  self.PerformLayout();
end;
{$ENDREGION}

end.