namespace DexiWin;

interface

{$HIDE H7}

uses
  System.Drawing,
  System.Collections,
  System.Windows.Forms,
  System.ComponentModel;

type
  FormShapeEdit = partial class
  {$REGION Windows Form Designer generated fields}
  private
    EditNodeFillStyle: System.Windows.Forms.ComboBox;
    groupBox1: System.Windows.Forms.GroupBox;
    BtnLineColor: System.Windows.Forms.Button;
    LblLineWidth: System.Windows.Forms.Label;
    EditLineWidth: System.Windows.Forms.NumericUpDown;
    EditLineStyle: System.Windows.Forms.ComboBox;
    LblLinStyle: System.Windows.Forms.Label;
    BtnNodeLineColor: System.Windows.Forms.Button;
    LblNodeLineWidth: System.Windows.Forms.Label;
    EditNodeLineWidth: System.Windows.Forms.NumericUpDown;
    EditNodeLineStyle: System.Windows.Forms.ComboBox;
    LblNodeLineStyle: System.Windows.Forms.Label;
    BtnHatchColor: System.Windows.Forms.Button;
    GrpRounded: System.Windows.Forms.GroupBox;
    EditRoundEdgeUnitsVertical: System.Windows.Forms.ComboBox;
    EditRoundEdgeUnitsHorizontal: System.Windows.Forms.ComboBox;
    EditRoundEdgeVertical: System.Windows.Forms.NumericUpDown;
    EditRoundEdgeHorizontal: System.Windows.Forms.NumericUpDown;
    LblEdgeVertical: System.Windows.Forms.Label;
    LblEdgeHorizontal: System.Windows.Forms.Label;
    GrpShape: System.Windows.Forms.GroupBox;
    RadRounded: System.Windows.Forms.RadioButton;
    RadEllipse: System.Windows.Forms.RadioButton;
    RadRectangle: System.Windows.Forms.RadioButton;
    PicNode: System.Windows.Forms.PictureBox;
    BtnCancel: System.Windows.Forms.Button;
    BtnOK: System.Windows.Forms.Button;
    GrpFill: System.Windows.Forms.GroupBox;
    BtnFillColor: System.Windows.Forms.Button;
    LblFillStyle: System.Windows.Forms.Label;
    DlgColor: System.Windows.Forms.ColorDialog;
    GrpLine: System.Windows.Forms.GroupBox;
    var components: System.ComponentModel.Container := nil;
    method InitializeComponent;
  {$ENDREGION}
  end;

implementation

{$REGION Windows Form Designer generated code}
method FormShapeEdit.InitializeComponent;
begin
  self.GrpLine := new System.Windows.Forms.GroupBox();
  self.BtnNodeLineColor := new System.Windows.Forms.Button();
  self.LblNodeLineWidth := new System.Windows.Forms.Label();
  self.EditNodeLineWidth := new System.Windows.Forms.NumericUpDown();
  self.EditNodeLineStyle := new System.Windows.Forms.ComboBox();
  self.LblNodeLineStyle := new System.Windows.Forms.Label();
  self.DlgColor := new System.Windows.Forms.ColorDialog();
  self.GrpFill := new System.Windows.Forms.GroupBox();
  self.BtnHatchColor := new System.Windows.Forms.Button();
  self.BtnFillColor := new System.Windows.Forms.Button();
  self.EditNodeFillStyle := new System.Windows.Forms.ComboBox();
  self.LblFillStyle := new System.Windows.Forms.Label();
  self.PicNode := new System.Windows.Forms.PictureBox();
  self.BtnCancel := new System.Windows.Forms.Button();
  self.BtnOK := new System.Windows.Forms.Button();
  self.GrpShape := new System.Windows.Forms.GroupBox();
  self.RadRounded := new System.Windows.Forms.RadioButton();
  self.RadEllipse := new System.Windows.Forms.RadioButton();
  self.RadRectangle := new System.Windows.Forms.RadioButton();
  self.GrpRounded := new System.Windows.Forms.GroupBox();
  self.EditRoundEdgeUnitsVertical := new System.Windows.Forms.ComboBox();
  self.EditRoundEdgeUnitsHorizontal := new System.Windows.Forms.ComboBox();
  self.EditRoundEdgeVertical := new System.Windows.Forms.NumericUpDown();
  self.EditRoundEdgeHorizontal := new System.Windows.Forms.NumericUpDown();
  self.LblEdgeVertical := new System.Windows.Forms.Label();
  self.LblEdgeHorizontal := new System.Windows.Forms.Label();
  self.groupBox1 := new System.Windows.Forms.GroupBox();
  self.BtnLineColor := new System.Windows.Forms.Button();
  self.LblLineWidth := new System.Windows.Forms.Label();
  self.EditLineWidth := new System.Windows.Forms.NumericUpDown();
  self.EditLineStyle := new System.Windows.Forms.ComboBox();
  self.LblLinStyle := new System.Windows.Forms.Label();
  self.GrpLine.SuspendLayout();
  (self.EditNodeLineWidth as System.ComponentModel.ISupportInitialize).BeginInit();
  self.GrpFill.SuspendLayout();
  (self.PicNode as System.ComponentModel.ISupportInitialize).BeginInit();
  self.GrpShape.SuspendLayout();
  self.GrpRounded.SuspendLayout();
  (self.EditRoundEdgeVertical as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.EditRoundEdgeHorizontal as System.ComponentModel.ISupportInitialize).BeginInit();
  self.groupBox1.SuspendLayout();
  (self.EditLineWidth as System.ComponentModel.ISupportInitialize).BeginInit();
  self.SuspendLayout();
  self.GrpLine.Controls.Add(self.BtnNodeLineColor);
  self.GrpLine.Controls.Add(self.LblNodeLineWidth);
  self.GrpLine.Controls.Add(self.EditNodeLineWidth);
  self.GrpLine.Controls.Add(self.EditNodeLineStyle);
  self.GrpLine.Controls.Add(self.LblNodeLineStyle);
  self.GrpLine.Location := new System.Drawing.Point(12, 241);
  self.GrpLine.Name := 'GrpLine';
  self.GrpLine.Size := new System.Drawing.Size(168, 114);
  self.GrpLine.TabIndex := 2;
  self.GrpLine.TabStop := false;
  self.GrpLine.Text := 'Border &line';
  self.BtnNodeLineColor.Location := new System.Drawing.Point(8, 80);
  self.BtnNodeLineColor.Name := 'BtnNodeLineColor';
  self.BtnNodeLineColor.Size := new System.Drawing.Size(148, 23);
  self.BtnNodeLineColor.TabIndex := 4;
  self.BtnNodeLineColor.Text := 'Color ...';
  self.BtnNodeLineColor.UseVisualStyleBackColor := true;
  self.BtnNodeLineColor.Click += new System.EventHandler(self.BtnNodeLineColor_Click);
  self.LblNodeLineWidth.AutoSize := true;
  self.LblNodeLineWidth.Location := new System.Drawing.Point(8, 54);
  self.LblNodeLineWidth.Name := 'LblNodeLineWidth';
  self.LblNodeLineWidth.Size := new System.Drawing.Size(55, 13);
  self.LblNodeLineWidth.TabIndex := 2;
  self.LblNodeLineWidth.Text := 'Line &width';
  self.EditNodeLineWidth.Location := new System.Drawing.Point(106, 50);
  self.EditNodeLineWidth.Maximum := new System.Decimal(array of System.Int32([20, 0, 0, 0]));
  self.EditNodeLineWidth.Name := 'EditNodeLineWidth';
  self.EditNodeLineWidth.Size := new System.Drawing.Size(50, 20);
  self.EditNodeLineWidth.TabIndex := 3;
  self.EditNodeLineWidth.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditNodeLineWidth.ValueChanged += new System.EventHandler(self.Edit_ValueChanged);
  self.EditNodeLineStyle.DropDownStyle := System.Windows.Forms.ComboBoxStyle.DropDownList;
  self.EditNodeLineStyle.FormattingEnabled := true;
  self.EditNodeLineStyle.Items.AddRange(array of System.Object(['Solid', 'Dash', 'Dot', 'DashDot', 'DashDotDot']));
  self.EditNodeLineStyle.Location := new System.Drawing.Point(50, 20);
  self.EditNodeLineStyle.Name := 'EditNodeLineStyle';
  self.EditNodeLineStyle.Size := new System.Drawing.Size(106, 21);
  self.EditNodeLineStyle.TabIndex := 1;
  self.EditNodeLineStyle.SelectedIndexChanged += new System.EventHandler(self.Edit_ValueChanged);
  self.LblNodeLineStyle.AutoSize := true;
  self.LblNodeLineStyle.Location := new System.Drawing.Point(8, 24);
  self.LblNodeLineStyle.Name := 'LblNodeLineStyle';
  self.LblNodeLineStyle.Size := new System.Drawing.Size(30, 13);
  self.LblNodeLineStyle.TabIndex := 0;
  self.LblNodeLineStyle.Text := '&Style';
  self.GrpFill.Controls.Add(self.BtnHatchColor);
  self.GrpFill.Controls.Add(self.BtnFillColor);
  self.GrpFill.Controls.Add(self.EditNodeFillStyle);
  self.GrpFill.Controls.Add(self.LblFillStyle);
  self.GrpFill.Location := new System.Drawing.Point(12, 361);
  self.GrpFill.Name := 'GrpFill';
  self.GrpFill.Size := new System.Drawing.Size(168, 111);
  self.GrpFill.TabIndex := 3;
  self.GrpFill.TabStop := false;
  self.GrpFill.Text := '&Fill';
  self.BtnHatchColor.Location := new System.Drawing.Point(11, 79);
  self.BtnHatchColor.Name := 'BtnHatchColor';
  self.BtnHatchColor.Size := new System.Drawing.Size(145, 23);
  self.BtnHatchColor.TabIndex := 3;
  self.BtnHatchColor.Text := 'Hatch pattern color ...';
  self.BtnHatchColor.UseVisualStyleBackColor := true;
  self.BtnHatchColor.Click += new System.EventHandler(self.BtnHatchColor_Click);
  self.BtnFillColor.Location := new System.Drawing.Point(10, 50);
  self.BtnFillColor.Name := 'BtnFillColor';
  self.BtnFillColor.Size := new System.Drawing.Size(146, 23);
  self.BtnFillColor.TabIndex := 2;
  self.BtnFillColor.Text := 'Color ...';
  self.BtnFillColor.UseVisualStyleBackColor := true;
  self.BtnFillColor.Click += new System.EventHandler(self.BtnFillColor_Click);
  self.EditNodeFillStyle.DropDownStyle := System.Windows.Forms.ComboBoxStyle.DropDownList;
  self.EditNodeFillStyle.FormattingEnabled := true;
  self.EditNodeFillStyle.Items.AddRange(array of System.Object(['Solid', 'Horizontal', 'Vertical', 'ForwardDiagonal', 'BackwardDiagonal', 'Cross', 'DiagonalCross']));
  self.EditNodeFillStyle.Location := new System.Drawing.Point(50, 20);
  self.EditNodeFillStyle.Name := 'EditNodeFillStyle';
  self.EditNodeFillStyle.Size := new System.Drawing.Size(106, 21);
  self.EditNodeFillStyle.TabIndex := 1;
  self.EditNodeFillStyle.SelectedIndexChanged += new System.EventHandler(self.Edit_ValueChanged);
  self.LblFillStyle.AutoSize := true;
  self.LblFillStyle.Location := new System.Drawing.Point(8, 24);
  self.LblFillStyle.Name := 'LblFillStyle';
  self.LblFillStyle.Size := new System.Drawing.Size(30, 13);
  self.LblFillStyle.TabIndex := 0;
  self.LblFillStyle.Text := '&Style';
  self.PicNode.Location := new System.Drawing.Point(191, 62);
  self.PicNode.Name := 'PicNode';
  self.PicNode.Size := new System.Drawing.Size(180, 169);
  self.PicNode.TabIndex := 17;
  self.PicNode.TabStop := false;
  self.BtnCancel.CausesValidation := false;
  self.BtnCancel.DialogResult := System.Windows.Forms.DialogResult.Cancel;
  self.BtnCancel.Location := new System.Drawing.Point(290, 440);
  self.BtnCancel.Name := 'BtnCancel';
  self.BtnCancel.Size := new System.Drawing.Size(75, 23);
  self.BtnCancel.TabIndex := 16;
  self.BtnCancel.Text := '&Cancel';
  self.BtnCancel.UseVisualStyleBackColor := true;
  self.BtnOK.DialogResult := System.Windows.Forms.DialogResult.OK;
  self.BtnOK.Location := new System.Drawing.Point(198, 440);
  self.BtnOK.Name := 'BtnOK';
  self.BtnOK.Size := new System.Drawing.Size(75, 23);
  self.BtnOK.TabIndex := 15;
  self.BtnOK.Text := '&OK';
  self.BtnOK.UseVisualStyleBackColor := true;
  self.GrpShape.Controls.Add(self.RadRounded);
  self.GrpShape.Controls.Add(self.RadEllipse);
  self.GrpShape.Controls.Add(self.RadRectangle);
  self.GrpShape.Location := new System.Drawing.Point(12, 136);
  self.GrpShape.Name := 'GrpShape';
  self.GrpShape.Size := new System.Drawing.Size(168, 99);
  self.GrpShape.TabIndex := 1;
  self.GrpShape.TabStop := false;
  self.GrpShape.Text := 'S&hape';
  self.RadRounded.AutoSize := true;
  self.RadRounded.Location := new System.Drawing.Point(8, 72);
  self.RadRounded.Name := 'RadRounded';
  self.RadRounded.Size := new System.Drawing.Size(69, 17);
  self.RadRounded.TabIndex := 2;
  self.RadRounded.TabStop := true;
  self.RadRounded.Text := 'Rounded';
  self.RadRounded.UseVisualStyleBackColor := true;
  self.RadRounded.Click += new System.EventHandler(self.Edit_ValueChanged);
  self.RadEllipse.AutoSize := true;
  self.RadEllipse.Location := new System.Drawing.Point(8, 46);
  self.RadEllipse.Name := 'RadEllipse';
  self.RadEllipse.Size := new System.Drawing.Size(55, 17);
  self.RadEllipse.TabIndex := 1;
  self.RadEllipse.TabStop := true;
  self.RadEllipse.Text := 'Ellipse';
  self.RadEllipse.UseVisualStyleBackColor := true;
  self.RadEllipse.Click += new System.EventHandler(self.Edit_ValueChanged);
  self.RadRectangle.AutoSize := true;
  self.RadRectangle.Location := new System.Drawing.Point(8, 20);
  self.RadRectangle.Name := 'RadRectangle';
  self.RadRectangle.Size := new System.Drawing.Size(74, 17);
  self.RadRectangle.TabIndex := 0;
  self.RadRectangle.TabStop := true;
  self.RadRectangle.Text := 'Rectangle';
  self.RadRectangle.UseVisualStyleBackColor := true;
  self.RadRectangle.Click += new System.EventHandler(self.Edit_ValueChanged);
  self.GrpRounded.Controls.Add(self.EditRoundEdgeUnitsVertical);
  self.GrpRounded.Controls.Add(self.EditRoundEdgeUnitsHorizontal);
  self.GrpRounded.Controls.Add(self.EditRoundEdgeVertical);
  self.GrpRounded.Controls.Add(self.EditRoundEdgeHorizontal);
  self.GrpRounded.Controls.Add(self.LblEdgeVertical);
  self.GrpRounded.Controls.Add(self.LblEdgeHorizontal);
  self.GrpRounded.Location := new System.Drawing.Point(191, 241);
  self.GrpRounded.Name := 'GrpRounded';
  self.GrpRounded.Size := new System.Drawing.Size(180, 73);
  self.GrpRounded.TabIndex := 4;
  self.GrpRounded.TabStop := false;
  self.GrpRounded.Text := 'Rounded edges';
  self.EditRoundEdgeUnitsVertical.DropDownStyle := System.Windows.Forms.ComboBoxStyle.DropDownList;
  self.EditRoundEdgeUnitsVertical.FormattingEnabled := true;
  self.EditRoundEdgeUnitsVertical.Items.AddRange(array of System.Object(['pix', #37]));
  self.EditRoundEdgeUnitsVertical.Location := new System.Drawing.Point(124, 44);
  self.EditRoundEdgeUnitsVertical.Name := 'EditRoundEdgeUnitsVertical';
  self.EditRoundEdgeUnitsVertical.Size := new System.Drawing.Size(50, 21);
  self.EditRoundEdgeUnitsVertical.TabIndex := 5;
  self.EditRoundEdgeUnitsVertical.SelectedIndexChanged += new System.EventHandler(self.Edit_ValueChanged);
  self.EditRoundEdgeUnitsHorizontal.DropDownStyle := System.Windows.Forms.ComboBoxStyle.DropDownList;
  self.EditRoundEdgeUnitsHorizontal.FormattingEnabled := true;
  self.EditRoundEdgeUnitsHorizontal.Items.AddRange(array of System.Object(['pix', #37]));
  self.EditRoundEdgeUnitsHorizontal.Location := new System.Drawing.Point(124, 20);
  self.EditRoundEdgeUnitsHorizontal.Name := 'EditRoundEdgeUnitsHorizontal';
  self.EditRoundEdgeUnitsHorizontal.Size := new System.Drawing.Size(50, 21);
  self.EditRoundEdgeUnitsHorizontal.TabIndex := 2;
  self.EditRoundEdgeUnitsHorizontal.SelectedIndexChanged += new System.EventHandler(self.Edit_ValueChanged);
  self.EditRoundEdgeVertical.Location := new System.Drawing.Point(68, 44);
  self.EditRoundEdgeVertical.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditRoundEdgeVertical.Name := 'EditRoundEdgeVertical';
  self.EditRoundEdgeVertical.Size := new System.Drawing.Size(50, 20);
  self.EditRoundEdgeVertical.TabIndex := 4;
  self.EditRoundEdgeVertical.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditRoundEdgeHorizontal.Location := new System.Drawing.Point(68, 20);
  self.EditRoundEdgeHorizontal.Maximum := new System.Decimal(array of System.Int32([200, 0, 0, 0]));
  self.EditRoundEdgeHorizontal.Name := 'EditRoundEdgeHorizontal';
  self.EditRoundEdgeHorizontal.Size := new System.Drawing.Size(50, 20);
  self.EditRoundEdgeHorizontal.TabIndex := 1;
  self.EditRoundEdgeHorizontal.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditRoundEdgeHorizontal.ValueChanged += new System.EventHandler(self.Edit_ValueChanged);
  self.LblEdgeVertical.AutoSize := true;
  self.LblEdgeVertical.Location := new System.Drawing.Point(4, 48);
  self.LblEdgeVertical.Name := 'LblEdgeVertical';
  self.LblEdgeVertical.Size := new System.Drawing.Size(42, 13);
  self.LblEdgeVertical.TabIndex := 3;
  self.LblEdgeVertical.Text := 'Vertical';
  self.LblEdgeHorizontal.AutoSize := true;
  self.LblEdgeHorizontal.Location := new System.Drawing.Point(4, 24);
  self.LblEdgeHorizontal.Name := 'LblEdgeHorizontal';
  self.LblEdgeHorizontal.Size := new System.Drawing.Size(54, 13);
  self.LblEdgeHorizontal.TabIndex := 8;
  self.LblEdgeHorizontal.Text := 'Horizontal';
  self.groupBox1.Controls.Add(self.BtnLineColor);
  self.groupBox1.Controls.Add(self.LblLineWidth);
  self.groupBox1.Controls.Add(self.EditLineWidth);
  self.groupBox1.Controls.Add(self.EditLineStyle);
  self.groupBox1.Controls.Add(self.LblLinStyle);
  self.groupBox1.Location := new System.Drawing.Point(12, 12);
  self.groupBox1.Name := 'groupBox1';
  self.groupBox1.Size := new System.Drawing.Size(168, 118);
  self.groupBox1.TabIndex := 0;
  self.groupBox1.TabStop := false;
  self.groupBox1.Text := '&Line';
  self.BtnLineColor.Location := new System.Drawing.Point(8, 80);
  self.BtnLineColor.Name := 'BtnLineColor';
  self.BtnLineColor.Size := new System.Drawing.Size(148, 23);
  self.BtnLineColor.TabIndex := 4;
  self.BtnLineColor.Text := 'Color ...';
  self.BtnLineColor.UseVisualStyleBackColor := true;
  self.BtnLineColor.Click += new System.EventHandler(self.BtnLineColor_Click);
  self.LblLineWidth.AutoSize := true;
  self.LblLineWidth.Location := new System.Drawing.Point(8, 54);
  self.LblLineWidth.Name := 'LblLineWidth';
  self.LblLineWidth.Size := new System.Drawing.Size(55, 13);
  self.LblLineWidth.TabIndex := 2;
  self.LblLineWidth.Text := 'Line &width';
  self.EditLineWidth.Location := new System.Drawing.Point(106, 50);
  self.EditLineWidth.Maximum := new System.Decimal(array of System.Int32([20, 0, 0, 0]));
  self.EditLineWidth.Name := 'EditLineWidth';
  self.EditLineWidth.Size := new System.Drawing.Size(50, 20);
  self.EditLineWidth.TabIndex := 3;
  self.EditLineWidth.Value := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.EditLineWidth.ValueChanged += new System.EventHandler(self.Edit_ValueChanged);
  self.EditLineStyle.DropDownStyle := System.Windows.Forms.ComboBoxStyle.DropDownList;
  self.EditLineStyle.FormattingEnabled := true;
  self.EditLineStyle.Items.AddRange(array of System.Object(['Solid', 'Dash', 'Dot', 'DashDot', 'DashDotDot']));
  self.EditLineStyle.Location := new System.Drawing.Point(50, 20);
  self.EditLineStyle.Name := 'EditLineStyle';
  self.EditLineStyle.Size := new System.Drawing.Size(106, 21);
  self.EditLineStyle.TabIndex := 1;
  self.EditLineStyle.SelectedIndexChanged += new System.EventHandler(self.Edit_ValueChanged);
  self.LblLinStyle.AutoSize := true;
  self.LblLinStyle.Location := new System.Drawing.Point(8, 24);
  self.LblLinStyle.Name := 'LblLinStyle';
  self.LblLinStyle.Size := new System.Drawing.Size(30, 13);
  self.LblLinStyle.TabIndex := 0;
  self.LblLinStyle.Text := '&Style';
  self.AutoScaleDimensions := new System.Drawing.SizeF(6.0, 13.0);
  self.AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font;
  self.ClientSize := new System.Drawing.Size(389, 481);
  self.Controls.Add(self.groupBox1);
  self.Controls.Add(self.GrpRounded);
  self.Controls.Add(self.GrpShape);
  self.Controls.Add(self.PicNode);
  self.Controls.Add(self.BtnCancel);
  self.Controls.Add(self.BtnOK);
  self.Controls.Add(self.GrpFill);
  self.Controls.Add(self.GrpLine);
  self.Name := 'FormShapeEdit';
  self.ShowIcon := false;
  self.ShowInTaskbar := false;
  self.StartPosition := System.Windows.Forms.FormStartPosition.CenterParent;
  self.Text := 'Edit graphic of {0}';
  self.GrpLine.ResumeLayout(false);
  self.GrpLine.PerformLayout();
  (self.EditNodeLineWidth as System.ComponentModel.ISupportInitialize).EndInit();
  self.GrpFill.ResumeLayout(false);
  self.GrpFill.PerformLayout();
  (self.PicNode as System.ComponentModel.ISupportInitialize).EndInit();
  self.GrpShape.ResumeLayout(false);
  self.GrpShape.PerformLayout();
  self.GrpRounded.ResumeLayout(false);
  self.GrpRounded.PerformLayout();
  (self.EditRoundEdgeVertical as System.ComponentModel.ISupportInitialize).EndInit();
  (self.EditRoundEdgeHorizontal as System.ComponentModel.ISupportInitialize).EndInit();
  self.groupBox1.ResumeLayout(false);
  self.groupBox1.PerformLayout();
  (self.EditLineWidth as System.ComponentModel.ISupportInitialize).EndInit();
  self.ResumeLayout(false);
end;
{$ENDREGION}

end.