namespace DexiWin;

interface

{$HIDE H7}

uses
  System.Drawing,
  System.Collections,
  System.Windows.Forms,
  System.ComponentModel;

type
  FormReportParameters = partial class
  {$REGION Windows Form Designer generated fields}
  private
    ChkFunctMarginals: System.Windows.Forms.CheckBox;
    ChkFunctNumericValues: System.Windows.Forms.CheckBox;
    
    PanelCompare: System.Windows.Forms.Panel;
    
    CompareGroup: System.Windows.Forms.GroupBox;
    ChkDeepCompare: System.Windows.Forms.CheckBox;
    PanelEvaluation: System.Windows.Forms.Panel;
    LblMaxColumns: System.Windows.Forms.Label;
    NumColumns: System.Windows.Forms.NumericUpDown;
    GrpEval: System.Windows.Forms.GroupBox;
    PanelElements: System.Windows.Forms.Panel;
    GrpElements: System.Windows.Forms.GroupBox;
    LblMessage: System.Windows.Forms.Label;
    PanelMessage: System.Windows.Forms.Panel;
    ColGenAttribute: BrightIdeasSoftware.OLVColumn;
    GenAttList: BrightIdeasSoftware.TreeListView;
    NumGenMaxShow: System.Windows.Forms.NumericUpDown;
    LblGenMaxShow: System.Windows.Forms.Label;
    NumGenMaxGenerate: System.Windows.Forms.NumericUpDown;
    LblGenMaxGenerate: System.Windows.Forms.Label;
    PanelGenCtrl2: System.Windows.Forms.Panel;
    GrpGenLimit: System.Windows.Forms.GroupBox;
    GrpGenChanging: System.Windows.Forms.GroupBox;
    ChkGenUnidirectional: System.Windows.Forms.CheckBox;
    NumGenMaxSteps: System.Windows.Forms.NumericUpDown;
    LblGenMaxSteps: System.Windows.Forms.Label;
    LblGenExplain: System.Windows.Forms.Label;
    RadGenDegrade: System.Windows.Forms.RadioButton;
    RadGenImprov: System.Windows.Forms.RadioButton;
    LblGenTry: System.Windows.Forms.Label;
    PageGenerator: System.Windows.Forms.TabPage;
    PanelGenControl: System.Windows.Forms.Panel;
    TextGenValue: System.Windows.Forms.RichTextBox;
    LblGenValue: System.Windows.Forms.Label;
    EditGenAlternative: System.Windows.Forms.ComboBox;
    EditGoalAttribute: System.Windows.Forms.ComboBox;
    LblGenAlternative: System.Windows.Forms.Label;
    LblGoalAttribute: System.Windows.Forms.Label;
    ChkFunctWeights: System.Windows.Forms.CheckBox;
    NumPlusSteps: System.Windows.Forms.NumericUpDown;
    LblPlusSteps: System.Windows.Forms.Label;
    NumMinusSteps: System.Windows.Forms.NumericUpDown;
    LblMinusSteps: System.Windows.Forms.Label;
    PanelPlusMinus: System.Windows.Forms.Panel;
    GrpPlusMinus: System.Windows.Forms.GroupBox;
    PanelWeights: System.Windows.Forms.Panel;
    GrpWeights: System.Windows.Forms.GroupBox;
    ChkWeiGlobalNormalized: System.Windows.Forms.CheckBox;
    ChkWeiLocalNormalized: System.Windows.Forms.CheckBox;
    ChkWeiGlobal: System.Windows.Forms.CheckBox;
    ChkWeiLocal: System.Windows.Forms.CheckBox;
    ChkAttFunct: System.Windows.Forms.CheckBox;
    ChkAttScale: System.Windows.Forms.CheckBox;
    ChkAttDescription: System.Windows.Forms.CheckBox;
    ChkAttName: System.Windows.Forms.CheckBox;
    ChkFunctStatus: System.Windows.Forms.CheckBox;
    ChkFunctEntered: System.Windows.Forms.CheckBox;
    ChkFunctNormWeight: System.Windows.Forms.CheckBox;
    ChkFunctNumbers: System.Windows.Forms.CheckBox;
    EditFunctRepresentation: System.Windows.Forms.ComboBox;
    PanelFunctions: System.Windows.Forms.Panel;
    GrpFunction: System.Windows.Forms.GroupBox;
    LblFunctRepresentation: System.Windows.Forms.Label;
    PanelMainAlternative: System.Windows.Forms.Panel;
    EditMainAlternative: System.Windows.Forms.ComboBox;
    LblMainAlternative: System.Windows.Forms.Label;
    EditRootAttribute: System.Windows.Forms.ComboBox;
    LblRootAttribute: System.Windows.Forms.Label;
    PanelRootAttribute: System.Windows.Forms.Panel;
    AttList: BrightIdeasSoftware.TreeListView;
    ColAttribute: BrightIdeasSoftware.OLVColumn;
    PanelAttCtrl: System.Windows.Forms.Panel;
    BtnUncheckAllAtt: System.Windows.Forms.Button;
    BtnCheckAllAtt: System.Windows.Forms.Button;
    ChkSelectAllAtt: System.Windows.Forms.CheckBox;
    PageAttributes: System.Windows.Forms.TabPage;
    ColAlternative: BrightIdeasSoftware.OLVColumn;
    AltList: BrightIdeasSoftware.ObjectListView;
    PageAlternatives: System.Windows.Forms.TabPage;
    PanelAltCtrl: System.Windows.Forms.Panel;
    BtnUncheckAllAlt: System.Windows.Forms.Button;
    BtnCheckAllAlt: System.Windows.Forms.Button;
    ChkSelectAllAlt: System.Windows.Forms.CheckBox;
    CtrlFormat: DexiWin.CtrlRptFormat;
    PageParameters: System.Windows.Forms.TabPage;
    PageFormat: System.Windows.Forms.TabPage;
    PanelCtrl: System.Windows.Forms.Panel;
    BtnCancel: System.Windows.Forms.Button;
    BtnOK: System.Windows.Forms.Button;
    TabsReport: System.Windows.Forms.TabControl;
    var components: System.ComponentModel.Container := nil;
    method InitializeComponent;
  {$ENDREGION}
  end;

implementation

{$REGION Windows Form Designer generated code}
method FormReportParameters.InitializeComponent;
begin
  self.components := new System.ComponentModel.Container();
  self.TabsReport := new System.Windows.Forms.TabControl();
  self.PageParameters := new System.Windows.Forms.TabPage();
  self.PanelMessage := new System.Windows.Forms.Panel();
  self.LblMessage := new System.Windows.Forms.Label();
  self.PanelCompare := new System.Windows.Forms.Panel();
  self.CompareGroup := new System.Windows.Forms.GroupBox();
  self.ChkDeepCompare := new System.Windows.Forms.CheckBox();
  self.PanelPlusMinus := new System.Windows.Forms.Panel();
  self.GrpPlusMinus := new System.Windows.Forms.GroupBox();
  self.NumPlusSteps := new System.Windows.Forms.NumericUpDown();
  self.LblPlusSteps := new System.Windows.Forms.Label();
  self.NumMinusSteps := new System.Windows.Forms.NumericUpDown();
  self.LblMinusSteps := new System.Windows.Forms.Label();
  self.PanelWeights := new System.Windows.Forms.Panel();
  self.GrpWeights := new System.Windows.Forms.GroupBox();
  self.ChkWeiGlobalNormalized := new System.Windows.Forms.CheckBox();
  self.ChkWeiLocalNormalized := new System.Windows.Forms.CheckBox();
  self.ChkWeiGlobal := new System.Windows.Forms.CheckBox();
  self.ChkWeiLocal := new System.Windows.Forms.CheckBox();
  self.PanelFunctions := new System.Windows.Forms.Panel();
  self.GrpFunction := new System.Windows.Forms.GroupBox();
  self.ChkFunctMarginals := new System.Windows.Forms.CheckBox();
  self.ChkFunctNumericValues := new System.Windows.Forms.CheckBox();
  self.ChkFunctStatus := new System.Windows.Forms.CheckBox();
  self.ChkFunctEntered := new System.Windows.Forms.CheckBox();
  self.ChkFunctNormWeight := new System.Windows.Forms.CheckBox();
  self.ChkFunctWeights := new System.Windows.Forms.CheckBox();
  self.ChkFunctNumbers := new System.Windows.Forms.CheckBox();
  self.EditFunctRepresentation := new System.Windows.Forms.ComboBox();
  self.LblFunctRepresentation := new System.Windows.Forms.Label();
  self.PanelEvaluation := new System.Windows.Forms.Panel();
  self.GrpEval := new System.Windows.Forms.GroupBox();
  self.LblMaxColumns := new System.Windows.Forms.Label();
  self.NumColumns := new System.Windows.Forms.NumericUpDown();
  self.PanelElements := new System.Windows.Forms.Panel();
  self.GrpElements := new System.Windows.Forms.GroupBox();
  self.ChkAttFunct := new System.Windows.Forms.CheckBox();
  self.ChkAttScale := new System.Windows.Forms.CheckBox();
  self.ChkAttDescription := new System.Windows.Forms.CheckBox();
  self.ChkAttName := new System.Windows.Forms.CheckBox();
  self.PanelMainAlternative := new System.Windows.Forms.Panel();
  self.EditMainAlternative := new System.Windows.Forms.ComboBox();
  self.LblMainAlternative := new System.Windows.Forms.Label();
  self.PanelRootAttribute := new System.Windows.Forms.Panel();
  self.EditRootAttribute := new System.Windows.Forms.ComboBox();
  self.LblRootAttribute := new System.Windows.Forms.Label();
  self.PageGenerator := new System.Windows.Forms.TabPage();
  self.GenAttList := new BrightIdeasSoftware.TreeListView();
  self.ColGenAttribute := (new BrightIdeasSoftware.OLVColumn() as BrightIdeasSoftware.OLVColumn);
  self.PanelGenCtrl2 := new System.Windows.Forms.Panel();
  self.GrpGenLimit := new System.Windows.Forms.GroupBox();
  self.NumGenMaxShow := new System.Windows.Forms.NumericUpDown();
  self.LblGenMaxShow := new System.Windows.Forms.Label();
  self.NumGenMaxGenerate := new System.Windows.Forms.NumericUpDown();
  self.LblGenMaxGenerate := new System.Windows.Forms.Label();
  self.GrpGenChanging := new System.Windows.Forms.GroupBox();
  self.ChkGenUnidirectional := new System.Windows.Forms.CheckBox();
  self.NumGenMaxSteps := new System.Windows.Forms.NumericUpDown();
  self.LblGenMaxSteps := new System.Windows.Forms.Label();
  self.PanelGenControl := new System.Windows.Forms.Panel();
  self.LblGenExplain := new System.Windows.Forms.Label();
  self.RadGenDegrade := new System.Windows.Forms.RadioButton();
  self.RadGenImprov := new System.Windows.Forms.RadioButton();
  self.LblGenTry := new System.Windows.Forms.Label();
  self.TextGenValue := new System.Windows.Forms.RichTextBox();
  self.LblGenValue := new System.Windows.Forms.Label();
  self.EditGenAlternative := new System.Windows.Forms.ComboBox();
  self.EditGoalAttribute := new System.Windows.Forms.ComboBox();
  self.LblGenAlternative := new System.Windows.Forms.Label();
  self.LblGoalAttribute := new System.Windows.Forms.Label();
  self.PageAttributes := new System.Windows.Forms.TabPage();
  self.AttList := new BrightIdeasSoftware.TreeListView();
  self.ColAttribute := (new BrightIdeasSoftware.OLVColumn() as BrightIdeasSoftware.OLVColumn);
  self.PanelAttCtrl := new System.Windows.Forms.Panel();
  self.BtnUncheckAllAtt := new System.Windows.Forms.Button();
  self.BtnCheckAllAtt := new System.Windows.Forms.Button();
  self.ChkSelectAllAtt := new System.Windows.Forms.CheckBox();
  self.PageAlternatives := new System.Windows.Forms.TabPage();
  self.AltList := new BrightIdeasSoftware.ObjectListView();
  self.ColAlternative := (new BrightIdeasSoftware.OLVColumn() as BrightIdeasSoftware.OLVColumn);
  self.PanelAltCtrl := new System.Windows.Forms.Panel();
  self.BtnUncheckAllAlt := new System.Windows.Forms.Button();
  self.BtnCheckAllAlt := new System.Windows.Forms.Button();
  self.ChkSelectAllAlt := new System.Windows.Forms.CheckBox();
  self.PageFormat := new System.Windows.Forms.TabPage();
  self.CtrlFormat := new DexiWin.CtrlRptFormat();
  self.PanelCtrl := new System.Windows.Forms.Panel();
  self.BtnCancel := new System.Windows.Forms.Button();
  self.BtnOK := new System.Windows.Forms.Button();
  self.TabsReport.SuspendLayout();
  self.PageParameters.SuspendLayout();
  self.PanelMessage.SuspendLayout();
  self.PanelCompare.SuspendLayout();
  self.CompareGroup.SuspendLayout();
  self.PanelPlusMinus.SuspendLayout();
  self.GrpPlusMinus.SuspendLayout();
  (self.NumPlusSteps as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.NumMinusSteps as System.ComponentModel.ISupportInitialize).BeginInit();
  self.PanelWeights.SuspendLayout();
  self.GrpWeights.SuspendLayout();
  self.PanelFunctions.SuspendLayout();
  self.GrpFunction.SuspendLayout();
  self.PanelEvaluation.SuspendLayout();
  self.GrpEval.SuspendLayout();
  (self.NumColumns as System.ComponentModel.ISupportInitialize).BeginInit();
  self.PanelElements.SuspendLayout();
  self.GrpElements.SuspendLayout();
  self.PanelMainAlternative.SuspendLayout();
  self.PanelRootAttribute.SuspendLayout();
  self.PageGenerator.SuspendLayout();
  (self.GenAttList as System.ComponentModel.ISupportInitialize).BeginInit();
  self.PanelGenCtrl2.SuspendLayout();
  self.GrpGenLimit.SuspendLayout();
  (self.NumGenMaxShow as System.ComponentModel.ISupportInitialize).BeginInit();
  (self.NumGenMaxGenerate as System.ComponentModel.ISupportInitialize).BeginInit();
  self.GrpGenChanging.SuspendLayout();
  (self.NumGenMaxSteps as System.ComponentModel.ISupportInitialize).BeginInit();
  self.PanelGenControl.SuspendLayout();
  self.PageAttributes.SuspendLayout();
  (self.AttList as System.ComponentModel.ISupportInitialize).BeginInit();
  self.PanelAttCtrl.SuspendLayout();
  self.PageAlternatives.SuspendLayout();
  (self.AltList as System.ComponentModel.ISupportInitialize).BeginInit();
  self.PanelAltCtrl.SuspendLayout();
  self.PageFormat.SuspendLayout();
  self.PanelCtrl.SuspendLayout();
  self.SuspendLayout();
  self.TabsReport.Controls.Add(self.PageParameters);
  self.TabsReport.Controls.Add(self.PageGenerator);
  self.TabsReport.Controls.Add(self.PageAttributes);
  self.TabsReport.Controls.Add(self.PageAlternatives);
  self.TabsReport.Controls.Add(self.PageFormat);
  self.TabsReport.Dock := System.Windows.Forms.DockStyle.Fill;
  self.TabsReport.Location := new System.Drawing.Point(0, 0);
  self.TabsReport.Name := 'TabsReport';
  self.TabsReport.SelectedIndex := 0;
  self.TabsReport.Size := new System.Drawing.Size(540, 501);
  self.TabsReport.TabIndex := 3;
  self.PageParameters.AutoScroll := true;
  self.PageParameters.Controls.Add(self.PanelMessage);
  self.PageParameters.Controls.Add(self.PanelCompare);
  self.PageParameters.Controls.Add(self.PanelPlusMinus);
  self.PageParameters.Controls.Add(self.PanelWeights);
  self.PageParameters.Controls.Add(self.PanelFunctions);
  self.PageParameters.Controls.Add(self.PanelEvaluation);
  self.PageParameters.Controls.Add(self.PanelElements);
  self.PageParameters.Controls.Add(self.PanelMainAlternative);
  self.PageParameters.Controls.Add(self.PanelRootAttribute);
  self.PageParameters.Location := new System.Drawing.Point(4, 22);
  self.PageParameters.Name := 'PageParameters';
  self.PageParameters.Padding := new System.Windows.Forms.Padding(3);
  self.PageParameters.Size := new System.Drawing.Size(532, 475);
  self.PageParameters.TabIndex := 0;
  self.PageParameters.Text := 'Parameters';
  self.PageParameters.UseVisualStyleBackColor := true;
  self.PanelMessage.Controls.Add(self.LblMessage);
  self.PanelMessage.Dock := System.Windows.Forms.DockStyle.Top;
  self.PanelMessage.Location := new System.Drawing.Point(3, 715);
  self.PanelMessage.Name := 'PanelMessage';
  self.PanelMessage.Size := new System.Drawing.Size(509, 34);
  self.PanelMessage.TabIndex := 80;
  self.LblMessage.AutoSize := true;
  self.LblMessage.Location := new System.Drawing.Point(12, 7);
  self.LblMessage.Name := 'LblMessage';
  self.LblMessage.Size := new System.Drawing.Size(10, 13);
  self.LblMessage.TabIndex := 0;
  self.LblMessage.Text := ' ';
  self.PanelCompare.Controls.Add(self.CompareGroup);
  self.PanelCompare.Dock := System.Windows.Forms.DockStyle.Top;
  self.PanelCompare.Location := new System.Drawing.Point(3, 663);
  self.PanelCompare.Name := 'PanelCompare';
  self.PanelCompare.Size := new System.Drawing.Size(509, 52);
  self.PanelCompare.TabIndex := 81;
  self.CompareGroup.Anchor := (System.Windows.Forms.AnchorStyles.Top or System.Windows.Forms.AnchorStyles.Left or System.Windows.Forms.AnchorStyles.Right as System.Windows.Forms.AnchorStyles);
  self.CompareGroup.Controls.Add(self.ChkDeepCompare);
  self.CompareGroup.Location := new System.Drawing.Point(3, 6);
  self.CompareGroup.Name := 'CompareGroup';
  self.CompareGroup.Size := new System.Drawing.Size(501, 44);
  self.CompareGroup.TabIndex := 60;
  self.CompareGroup.TabStop := false;
  self.CompareGroup.Text := '&Compare alternatives';
  self.ChkDeepCompare.AutoSize := true;
  self.ChkDeepCompare.Location := new System.Drawing.Point(97, 20);
  self.ChkDeepCompare.Name := 'ChkDeepCompare';
  self.ChkDeepCompare.Size := new System.Drawing.Size(157, 17);
  self.ChkDeepCompare.TabIndex := 19;
  self.ChkDeepCompare.Text := 'Show &comparison operators';
  self.ChkDeepCompare.UseVisualStyleBackColor := true;
  self.ChkDeepCompare.CheckedChanged += new System.EventHandler(self.ChkDeepCompare_CheckedChanged);
  self.PanelPlusMinus.Controls.Add(self.GrpPlusMinus);
  self.PanelPlusMinus.Dock := System.Windows.Forms.DockStyle.Top;
  self.PanelPlusMinus.Location := new System.Drawing.Point(3, 577);
  self.PanelPlusMinus.Name := 'PanelPlusMinus';
  self.PanelPlusMinus.Size := new System.Drawing.Size(509, 86);
  self.PanelPlusMinus.TabIndex := 70;
  self.GrpPlusMinus.Anchor := (System.Windows.Forms.AnchorStyles.Top or System.Windows.Forms.AnchorStyles.Left or System.Windows.Forms.AnchorStyles.Right as System.Windows.Forms.AnchorStyles);
  self.GrpPlusMinus.Controls.Add(self.NumPlusSteps);
  self.GrpPlusMinus.Controls.Add(self.LblPlusSteps);
  self.GrpPlusMinus.Controls.Add(self.NumMinusSteps);
  self.GrpPlusMinus.Controls.Add(self.LblMinusSteps);
  self.GrpPlusMinus.Location := new System.Drawing.Point(3, 6);
  self.GrpPlusMinus.Name := 'GrpPlusMinus';
  self.GrpPlusMinus.Size := new System.Drawing.Size(501, 74);
  self.GrpPlusMinus.TabIndex := 70;
  self.GrpPlusMinus.TabStop := false;
  self.GrpPlusMinus.Text := 'Plus/Minus analysis';
  self.NumPlusSteps.Location := new System.Drawing.Point(97, 46);
  self.NumPlusSteps.Maximum := new System.Decimal(array of System.Int32([10, 0, 0, 0]));
  self.NumPlusSteps.Minimum := new System.Decimal(array of System.Int32([1, 0, 0, -2147483648]));
  self.NumPlusSteps.Name := 'NumPlusSteps';
  self.NumPlusSteps.Size := new System.Drawing.Size(68, 20);
  self.NumPlusSteps.TabIndex := 27;
  self.NumPlusSteps.TextAlign := System.Windows.Forms.HorizontalAlignment.Right;
  self.NumPlusSteps.Value := new System.Decimal(array of System.Int32([10, 0, 0, 0]));
  self.NumPlusSteps.ValueChanged += new System.EventHandler(self.NumPlusSteps_ValueChanged);
  self.LblPlusSteps.AutoSize := true;
  self.LblPlusSteps.Location := new System.Drawing.Point(10, 50);
  self.LblPlusSteps.Name := 'LblPlusSteps';
  self.LblPlusSteps.Size := new System.Drawing.Size(55, 13);
  self.LblPlusSteps.TabIndex := 26;
  self.LblPlusSteps.Text := '&Plus steps';
  self.NumMinusSteps.Location := new System.Drawing.Point(97, 21);
  self.NumMinusSteps.Maximum := new System.Decimal(array of System.Int32([10, 0, 0, 0]));
  self.NumMinusSteps.Minimum := new System.Decimal(array of System.Int32([1, 0, 0, -2147483648]));
  self.NumMinusSteps.Name := 'NumMinusSteps';
  self.NumMinusSteps.Size := new System.Drawing.Size(68, 20);
  self.NumMinusSteps.TabIndex := 25;
  self.NumMinusSteps.TextAlign := System.Windows.Forms.HorizontalAlignment.Right;
  self.NumMinusSteps.Value := new System.Decimal(array of System.Int32([10, 0, 0, 0]));
  self.NumMinusSteps.ValueChanged += new System.EventHandler(self.NumMinusSteps_ValueChanged);
  self.LblMinusSteps.AutoSize := true;
  self.LblMinusSteps.Location := new System.Drawing.Point(9, 25);
  self.LblMinusSteps.Name := 'LblMinusSteps';
  self.LblMinusSteps.Size := new System.Drawing.Size(63, 13);
  self.LblMinusSteps.TabIndex := 24;
  self.LblMinusSteps.Text := '&Minus steps';
  self.PanelWeights.Controls.Add(self.GrpWeights);
  self.PanelWeights.Dock := System.Windows.Forms.DockStyle.Top;
  self.PanelWeights.Location := new System.Drawing.Point(3, 466);
  self.PanelWeights.Name := 'PanelWeights';
  self.PanelWeights.Size := new System.Drawing.Size(509, 111);
  self.PanelWeights.TabIndex := 60;
  self.GrpWeights.Anchor := (System.Windows.Forms.AnchorStyles.Top or System.Windows.Forms.AnchorStyles.Left or System.Windows.Forms.AnchorStyles.Right as System.Windows.Forms.AnchorStyles);
  self.GrpWeights.Controls.Add(self.ChkWeiGlobalNormalized);
  self.GrpWeights.Controls.Add(self.ChkWeiLocalNormalized);
  self.GrpWeights.Controls.Add(self.ChkWeiGlobal);
  self.GrpWeights.Controls.Add(self.ChkWeiLocal);
  self.GrpWeights.Location := new System.Drawing.Point(3, 6);
  self.GrpWeights.Name := 'GrpWeights';
  self.GrpWeights.Size := new System.Drawing.Size(501, 102);
  self.GrpWeights.TabIndex := 60;
  self.GrpWeights.TabStop := false;
  self.GrpWeights.Text := 'Displaying &weights';
  self.ChkWeiGlobalNormalized.AutoSize := true;
  self.ChkWeiGlobalNormalized.Location := new System.Drawing.Point(97, 80);
  self.ChkWeiGlobalNormalized.Name := 'ChkWeiGlobalNormalized';
  self.ChkWeiGlobalNormalized.Size := new System.Drawing.Size(109, 17);
  self.ChkWeiGlobalNormalized.TabIndex := 22;
  self.ChkWeiGlobalNormalized.Text := 'Global normali&zed';
  self.ChkWeiGlobalNormalized.UseVisualStyleBackColor := true;
  self.ChkWeiGlobalNormalized.CheckedChanged += new System.EventHandler(self.ChkWeiGlobalNormalized_CheckedChanged);
  self.ChkWeiLocalNormalized.AutoSize := true;
  self.ChkWeiLocalNormalized.Location := new System.Drawing.Point(97, 60);
  self.ChkWeiLocalNormalized.Name := 'ChkWeiLocalNormalized';
  self.ChkWeiLocalNormalized.Size := new System.Drawing.Size(105, 17);
  self.ChkWeiLocalNormalized.TabIndex := 21;
  self.ChkWeiLocalNormalized.Text := 'Local &normalized';
  self.ChkWeiLocalNormalized.UseVisualStyleBackColor := true;
  self.ChkWeiLocalNormalized.CheckedChanged += new System.EventHandler(self.ChkWeiLocalNormalized_CheckedChanged);
  self.ChkWeiGlobal.AutoSize := true;
  self.ChkWeiGlobal.Location := new System.Drawing.Point(97, 40);
  self.ChkWeiGlobal.Name := 'ChkWeiGlobal';
  self.ChkWeiGlobal.Size := new System.Drawing.Size(56, 17);
  self.ChkWeiGlobal.TabIndex := 20;
  self.ChkWeiGlobal.Text := '&Global';
  self.ChkWeiGlobal.UseVisualStyleBackColor := true;
  self.ChkWeiGlobal.CheckedChanged += new System.EventHandler(self.ChkWeiGlobal_CheckedChanged);
  self.ChkWeiLocal.AutoSize := true;
  self.ChkWeiLocal.Location := new System.Drawing.Point(97, 20);
  self.ChkWeiLocal.Name := 'ChkWeiLocal';
  self.ChkWeiLocal.Size := new System.Drawing.Size(52, 17);
  self.ChkWeiLocal.TabIndex := 19;
  self.ChkWeiLocal.Text := '&Local';
  self.ChkWeiLocal.UseVisualStyleBackColor := true;
  self.ChkWeiLocal.CheckedChanged += new System.EventHandler(self.ChkWeiLocal_CheckedChanged);
  self.PanelFunctions.Controls.Add(self.GrpFunction);
  self.PanelFunctions.Dock := System.Windows.Forms.DockStyle.Top;
  self.PanelFunctions.Location := new System.Drawing.Point(3, 266);
  self.PanelFunctions.Name := 'PanelFunctions';
  self.PanelFunctions.Size := new System.Drawing.Size(509, 200);
  self.PanelFunctions.TabIndex := 50;
  self.GrpFunction.Anchor := (System.Windows.Forms.AnchorStyles.Top or System.Windows.Forms.AnchorStyles.Left or System.Windows.Forms.AnchorStyles.Right as System.Windows.Forms.AnchorStyles);
  self.GrpFunction.Controls.Add(self.ChkFunctMarginals);
  self.GrpFunction.Controls.Add(self.ChkFunctNumericValues);
  self.GrpFunction.Controls.Add(self.ChkFunctStatus);
  self.GrpFunction.Controls.Add(self.ChkFunctEntered);
  self.GrpFunction.Controls.Add(self.ChkFunctNormWeight);
  self.GrpFunction.Controls.Add(self.ChkFunctWeights);
  self.GrpFunction.Controls.Add(self.ChkFunctNumbers);
  self.GrpFunction.Controls.Add(self.EditFunctRepresentation);
  self.GrpFunction.Controls.Add(self.LblFunctRepresentation);
  self.GrpFunction.Location := new System.Drawing.Point(3, 6);
  self.GrpFunction.Name := 'GrpFunction';
  self.GrpFunction.Size := new System.Drawing.Size(501, 192);
  self.GrpFunction.TabIndex := 50;
  self.GrpFunction.TabStop := false;
  self.GrpFunction.Text := 'Displaying aggregation functions';
  self.ChkFunctMarginals.AutoSize := true;
  self.ChkFunctMarginals.Location := new System.Drawing.Point(97, 171);
  self.ChkFunctMarginals.Name := 'ChkFunctMarginals';
  self.ChkFunctMarginals.Size := new System.Drawing.Size(129, 17);
  self.ChkFunctMarginals.TabIndex := 14;
  self.ChkFunctMarginals.Text := 'Show marginal values';
  self.ChkFunctMarginals.UseVisualStyleBackColor := true;
  self.ChkFunctMarginals.CheckedChanged += new System.EventHandler(self.ChkFunctMarginals_CheckedChanged);
  self.ChkFunctNumericValues.AutoSize := true;
  self.ChkFunctNumericValues.Location := new System.Drawing.Point(97, 150);
  self.ChkFunctNumericValues.Name := 'ChkFunctNumericValues';
  self.ChkFunctNumericValues.Size := new System.Drawing.Size(255, 17);
  self.ChkFunctNumericValues.TabIndex := 13;
  self.ChkFunctNumericValues.Text := 'Show numeric evaluations (with Elementary only)';
  self.ChkFunctNumericValues.UseVisualStyleBackColor := true;
  self.ChkFunctNumericValues.CheckedChanged += new System.EventHandler(self.ChkFunctNumeric_CheckedChanged);
  self.ChkFunctStatus.AutoSize := true;
  self.ChkFunctStatus.Location := new System.Drawing.Point(97, 130);
  self.ChkFunctStatus.Name := 'ChkFunctStatus';
  self.ChkFunctStatus.Size := new System.Drawing.Size(125, 17);
  self.ChkFunctStatus.TabIndex := 12;
  self.ChkFunctStatus.Text := 'Show function s&tatus';
  self.ChkFunctStatus.UseVisualStyleBackColor := true;
  self.ChkFunctStatus.CheckedChanged += new System.EventHandler(self.ChkFunctStatus_CheckedChanged);
  self.ChkFunctEntered.AutoSize := true;
  self.ChkFunctEntered.Location := new System.Drawing.Point(97, 110);
  self.ChkFunctEntered.Name := 'ChkFunctEntered';
  self.ChkFunctEntered.Size := new System.Drawing.Size(182, 17);
  self.ChkFunctEntered.TabIndex := 11;
  self.ChkFunctEntered.Text := 'Consider only &entered rules/items';
  self.ChkFunctEntered.UseVisualStyleBackColor := true;
  self.ChkFunctEntered.CheckedChanged += new System.EventHandler(self.ChkFunctEntered_CheckedChanged);
  self.ChkFunctNormWeight.AutoSize := true;
  self.ChkFunctNormWeight.Location := new System.Drawing.Point(97, 90);
  self.ChkFunctNormWeight.Name := 'ChkFunctNormWeight';
  self.ChkFunctNormWeight.Size := new System.Drawing.Size(137, 17);
  self.ChkFunctNormWeight.TabIndex := 10;
  self.ChkFunctNormWeight.Text := 'Use &normalized weights';
  self.ChkFunctNormWeight.UseVisualStyleBackColor := true;
  self.ChkFunctNormWeight.CheckedChanged += new System.EventHandler(self.ChkFunctNormWeight_CheckedChanged);
  self.ChkFunctWeights.AutoSize := true;
  self.ChkFunctWeights.Location := new System.Drawing.Point(97, 70);
  self.ChkFunctWeights.Name := 'ChkFunctWeights';
  self.ChkFunctWeights.Size := new System.Drawing.Size(92, 17);
  self.ChkFunctWeights.TabIndex := 9;
  self.ChkFunctWeights.Text := 'Show &weights';
  self.ChkFunctWeights.UseVisualStyleBackColor := true;
  self.ChkFunctWeights.CheckedChanged += new System.EventHandler(self.ChkFunctWeights_CheckedChanged);
  self.ChkFunctNumbers.AutoSize := true;
  self.ChkFunctNumbers.Location := new System.Drawing.Point(97, 50);
  self.ChkFunctNumbers.Name := 'ChkFunctNumbers';
  self.ChkFunctNumbers.Size := new System.Drawing.Size(116, 17);
  self.ChkFunctNumbers.TabIndex := 8;
  self.ChkFunctNumbers.Text := 'Show rule &numbers';
  self.ChkFunctNumbers.UseVisualStyleBackColor := true;
  self.ChkFunctNumbers.CheckedChanged += new System.EventHandler(self.ChkFunctNumbers_CheckedChanged);
  self.EditFunctRepresentation.DropDownStyle := System.Windows.Forms.ComboBoxStyle.DropDownList;
  self.EditFunctRepresentation.FormattingEnabled := true;
  self.EditFunctRepresentation.Location := new System.Drawing.Point(97, 21);
  self.EditFunctRepresentation.Name := 'EditFunctRepresentation';
  self.EditFunctRepresentation.Size := new System.Drawing.Size(181, 21);
  self.EditFunctRepresentation.TabIndex := 7;
  self.EditFunctRepresentation.SelectedIndexChanged += new System.EventHandler(self.EditFunctRepresentation_SelectedIndexChanged);
  self.LblFunctRepresentation.AutoSize := true;
  self.LblFunctRepresentation.Location := new System.Drawing.Point(9, 25);
  self.LblFunctRepresentation.Name := 'LblFunctRepresentation';
  self.LblFunctRepresentation.Size := new System.Drawing.Size(79, 13);
  self.LblFunctRepresentation.TabIndex := 6;
  self.LblFunctRepresentation.Text := '&Representation';
  self.PanelEvaluation.Controls.Add(self.GrpEval);
  self.PanelEvaluation.Dock := System.Windows.Forms.DockStyle.Top;
  self.PanelEvaluation.Location := new System.Drawing.Point(3, 204);
  self.PanelEvaluation.Name := 'PanelEvaluation';
  self.PanelEvaluation.Size := new System.Drawing.Size(509, 62);
  self.PanelEvaluation.TabIndex := 40;
  self.GrpEval.Anchor := (System.Windows.Forms.AnchorStyles.Top or System.Windows.Forms.AnchorStyles.Left or System.Windows.Forms.AnchorStyles.Right as System.Windows.Forms.AnchorStyles);
  self.GrpEval.Controls.Add(self.LblMaxColumns);
  self.GrpEval.Controls.Add(self.NumColumns);
  self.GrpEval.Location := new System.Drawing.Point(0, 6);
  self.GrpEval.Name := 'GrpEval';
  self.GrpEval.Size := new System.Drawing.Size(506, 51);
  self.GrpEval.TabIndex := 40;
  self.GrpEval.TabStop := false;
  self.GrpEval.Text := 'Displaying evaluation results';
  self.LblMaxColumns.AutoSize := true;
  self.LblMaxColumns.Location := new System.Drawing.Point(9, 25);
  self.LblMaxColumns.Name := 'LblMaxColumns';
  self.LblMaxColumns.Size := new System.Drawing.Size(122, 13);
  self.LblMaxColumns.TabIndex := 34;
  self.LblMaxColumns.Text := 'Max. number of &columns';
  self.NumColumns.Location := new System.Drawing.Point(150, 21);
  self.NumColumns.Minimum := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.NumColumns.Name := 'NumColumns';
  self.NumColumns.Size := new System.Drawing.Size(68, 20);
  self.NumColumns.TabIndex := 33;
  self.NumColumns.TextAlign := System.Windows.Forms.HorizontalAlignment.Right;
  self.NumColumns.Value := new System.Decimal(array of System.Int32([10, 0, 0, 0]));
  self.NumColumns.ValueChanged += new System.EventHandler(self.NumColumns_ValueChanged);
  self.PanelElements.Controls.Add(self.GrpElements);
  self.PanelElements.Dock := System.Windows.Forms.DockStyle.Top;
  self.PanelElements.Location := new System.Drawing.Point(3, 93);
  self.PanelElements.Name := 'PanelElements';
  self.PanelElements.Size := new System.Drawing.Size(509, 111);
  self.PanelElements.TabIndex := 30;
  self.GrpElements.Anchor := (System.Windows.Forms.AnchorStyles.Top or System.Windows.Forms.AnchorStyles.Left or System.Windows.Forms.AnchorStyles.Right as System.Windows.Forms.AnchorStyles);
  self.GrpElements.Controls.Add(self.ChkAttFunct);
  self.GrpElements.Controls.Add(self.ChkAttScale);
  self.GrpElements.Controls.Add(self.ChkAttDescription);
  self.GrpElements.Controls.Add(self.ChkAttName);
  self.GrpElements.Location := new System.Drawing.Point(3, 6);
  self.GrpElements.Name := 'GrpElements';
  self.GrpElements.Size := new System.Drawing.Size(501, 102);
  self.GrpElements.TabIndex := 30;
  self.GrpElements.TabStop := false;
  self.ChkAttFunct.AutoSize := true;
  self.ChkAttFunct.Location := new System.Drawing.Point(97, 80);
  self.ChkAttFunct.Name := 'ChkAttFunct';
  self.ChkAttFunct.Size := new System.Drawing.Size(67, 17);
  self.ChkAttFunct.TabIndex := 17;
  self.ChkAttFunct.Text := 'Function';
  self.ChkAttFunct.UseVisualStyleBackColor := true;
  self.ChkAttFunct.CheckedChanged += new System.EventHandler(self.ChkAttFunct_CheckedChanged);
  self.ChkAttScale.AutoSize := true;
  self.ChkAttScale.Location := new System.Drawing.Point(97, 60);
  self.ChkAttScale.Name := 'ChkAttScale';
  self.ChkAttScale.Size := new System.Drawing.Size(53, 17);
  self.ChkAttScale.TabIndex := 16;
  self.ChkAttScale.Text := '&Scale';
  self.ChkAttScale.UseVisualStyleBackColor := true;
  self.ChkAttScale.CheckedChanged += new System.EventHandler(self.ChkAttScale_CheckedChanged);
  self.ChkAttDescription.AutoSize := true;
  self.ChkAttDescription.Location := new System.Drawing.Point(97, 40);
  self.ChkAttDescription.Name := 'ChkAttDescription';
  self.ChkAttDescription.Size := new System.Drawing.Size(119, 17);
  self.ChkAttDescription.TabIndex := 15;
  self.ChkAttDescription.Text := 'Attribute &description';
  self.ChkAttDescription.UseVisualStyleBackColor := true;
  self.ChkAttDescription.CheckedChanged += new System.EventHandler(self.ChkAttDescription_CheckedChanged);
  self.ChkAttName.AutoSize := true;
  self.ChkAttName.Location := new System.Drawing.Point(97, 20);
  self.ChkAttName.Name := 'ChkAttName';
  self.ChkAttName.Size := new System.Drawing.Size(94, 17);
  self.ChkAttName.TabIndex := 14;
  self.ChkAttName.Text := 'Attribute &name';
  self.ChkAttName.UseVisualStyleBackColor := true;
  self.ChkAttName.CheckedChanged += new System.EventHandler(self.ChkAttName_CheckedChanged);
  self.PanelMainAlternative.Controls.Add(self.EditMainAlternative);
  self.PanelMainAlternative.Controls.Add(self.LblMainAlternative);
  self.PanelMainAlternative.Dock := System.Windows.Forms.DockStyle.Top;
  self.PanelMainAlternative.Location := new System.Drawing.Point(3, 48);
  self.PanelMainAlternative.Name := 'PanelMainAlternative';
  self.PanelMainAlternative.Size := new System.Drawing.Size(509, 45);
  self.PanelMainAlternative.TabIndex := 20;
  self.EditMainAlternative.Anchor := (System.Windows.Forms.AnchorStyles.Top or System.Windows.Forms.AnchorStyles.Left or System.Windows.Forms.AnchorStyles.Right as System.Windows.Forms.AnchorStyles);
  self.EditMainAlternative.DropDownStyle := System.Windows.Forms.ComboBoxStyle.DropDownList;
  self.EditMainAlternative.FormattingEnabled := true;
  self.EditMainAlternative.Location := new System.Drawing.Point(100, 12);
  self.EditMainAlternative.Name := 'EditMainAlternative';
  self.EditMainAlternative.Size := new System.Drawing.Size(404, 21);
  self.EditMainAlternative.TabIndex := 4;
  self.EditMainAlternative.SelectedIndexChanged += new System.EventHandler(self.EditMainAlternative_SelectedIndexChanged);
  self.LblMainAlternative.AutoSize := true;
  self.LblMainAlternative.Location := new System.Drawing.Point(12, 16);
  self.LblMainAlternative.Name := 'LblMainAlternative';
  self.LblMainAlternative.Size := new System.Drawing.Size(82, 13);
  self.LblMainAlternative.TabIndex := 3;
  self.LblMainAlternative.Text := 'Main &alternative';
  self.PanelRootAttribute.Controls.Add(self.EditRootAttribute);
  self.PanelRootAttribute.Controls.Add(self.LblRootAttribute);
  self.PanelRootAttribute.Dock := System.Windows.Forms.DockStyle.Top;
  self.PanelRootAttribute.Location := new System.Drawing.Point(3, 3);
  self.PanelRootAttribute.Name := 'PanelRootAttribute';
  self.PanelRootAttribute.Size := new System.Drawing.Size(509, 45);
  self.PanelRootAttribute.TabIndex := 10;
  self.EditRootAttribute.Anchor := (System.Windows.Forms.AnchorStyles.Top or System.Windows.Forms.AnchorStyles.Left or System.Windows.Forms.AnchorStyles.Right as System.Windows.Forms.AnchorStyles);
  self.EditRootAttribute.DropDownStyle := System.Windows.Forms.ComboBoxStyle.DropDownList;
  self.EditRootAttribute.FormattingEnabled := true;
  self.EditRootAttribute.Location := new System.Drawing.Point(100, 12);
  self.EditRootAttribute.Name := 'EditRootAttribute';
  self.EditRootAttribute.Size := new System.Drawing.Size(404, 21);
  self.EditRootAttribute.TabIndex := 2;
  self.EditRootAttribute.SelectedIndexChanged += new System.EventHandler(self.EditRootAttribute_SelectedIndexChanged);
  self.LblRootAttribute.AutoSize := true;
  self.LblRootAttribute.Location := new System.Drawing.Point(12, 16);
  self.LblRootAttribute.Name := 'LblRootAttribute';
  self.LblRootAttribute.Size := new System.Drawing.Size(71, 13);
  self.LblRootAttribute.TabIndex := 1;
  self.LblRootAttribute.Text := '&Root attribute';
  self.PageGenerator.Controls.Add(self.GenAttList);
  self.PageGenerator.Controls.Add(self.PanelGenCtrl2);
  self.PageGenerator.Controls.Add(self.PanelGenControl);
  self.PageGenerator.Location := new System.Drawing.Point(4, 22);
  self.PageGenerator.Name := 'PageGenerator';
  self.PageGenerator.Padding := new System.Windows.Forms.Padding(3);
  self.PageGenerator.Size := new System.Drawing.Size(532, 697);
  self.PageGenerator.TabIndex := 5;
  self.PageGenerator.Text := 'Parameters';
  self.PageGenerator.UseVisualStyleBackColor := true;
  self.GenAttList.AllColumns.Add(self.ColGenAttribute);
  self.GenAttList.CellEditUseWholeCell := false;
  self.GenAttList.CheckBoxes := true;
  self.GenAttList.Columns.AddRange(array of System.Windows.Forms.ColumnHeader([self.ColGenAttribute]));
  self.GenAttList.Dock := System.Windows.Forms.DockStyle.Fill;
  self.GenAttList.HeaderStyle := System.Windows.Forms.ColumnHeaderStyle.None;
  self.GenAttList.HideSelection := false;
  self.GenAttList.Location := new System.Drawing.Point(3, 165);
  self.GenAttList.MultiSelect := false;
  self.GenAttList.Name := 'GenAttList';
  self.GenAttList.ShowGroups := false;
  self.GenAttList.ShowImagesOnSubItems := true;
  self.GenAttList.ShowItemToolTips := true;
  self.GenAttList.Size := new System.Drawing.Size(526, 391);
  self.GenAttList.TabIndex := 20;
  self.GenAttList.UseCompatibleStateImageBehavior := false;
  self.GenAttList.View := System.Windows.Forms.View.Details;
  self.GenAttList.VirtualMode := true;
  self.GenAttList.ItemChecked += new System.Windows.Forms.ItemCheckedEventHandler(self.GenAttList_ItemChecked);
  self.ColGenAttribute.AspectName := 'Name';
  self.ColGenAttribute.FillsFreeSpace := true;
  self.ColGenAttribute.Groupable := false;
  self.ColGenAttribute.Hideable := false;
  self.ColGenAttribute.IsEditable := false;
  self.ColGenAttribute.Searchable := false;
  self.ColGenAttribute.Sortable := false;
  self.ColGenAttribute.UseFiltering := false;
  self.PanelGenCtrl2.Controls.Add(self.GrpGenLimit);
  self.PanelGenCtrl2.Controls.Add(self.GrpGenChanging);
  self.PanelGenCtrl2.Dock := System.Windows.Forms.DockStyle.Bottom;
  self.PanelGenCtrl2.Location := new System.Drawing.Point(3, 556);
  self.PanelGenCtrl2.Name := 'PanelGenCtrl2';
  self.PanelGenCtrl2.Size := new System.Drawing.Size(526, 138);
  self.PanelGenCtrl2.TabIndex := 30;
  self.GrpGenLimit.Anchor := (System.Windows.Forms.AnchorStyles.Top or System.Windows.Forms.AnchorStyles.Left or System.Windows.Forms.AnchorStyles.Right as System.Windows.Forms.AnchorStyles);
  self.GrpGenLimit.Controls.Add(self.NumGenMaxShow);
  self.GrpGenLimit.Controls.Add(self.LblGenMaxShow);
  self.GrpGenLimit.Controls.Add(self.NumGenMaxGenerate);
  self.GrpGenLimit.Controls.Add(self.LblGenMaxGenerate);
  self.GrpGenLimit.Location := new System.Drawing.Point(3, 60);
  self.GrpGenLimit.Name := 'GrpGenLimit';
  self.GrpGenLimit.Size := new System.Drawing.Size(518, 72);
  self.GrpGenLimit.TabIndex := 50;
  self.GrpGenLimit.TabStop := false;
  self.GrpGenLimit.Text := 'Limit the number of solutions';
  self.NumGenMaxShow.Location := new System.Drawing.Point(97, 46);
  self.NumGenMaxShow.Minimum := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.NumGenMaxShow.Name := 'NumGenMaxShow';
  self.NumGenMaxShow.Size := new System.Drawing.Size(68, 20);
  self.NumGenMaxShow.TabIndex := 27;
  self.NumGenMaxShow.TextAlign := System.Windows.Forms.HorizontalAlignment.Right;
  self.NumGenMaxShow.Value := new System.Decimal(array of System.Int32([10, 0, 0, 0]));
  self.NumGenMaxShow.ValueChanged += new System.EventHandler(self.NumGenMaxShow_ValueChanged);
  self.LblGenMaxShow.AutoSize := true;
  self.LblGenMaxShow.Location := new System.Drawing.Point(9, 50);
  self.LblGenMaxShow.Name := 'LblGenMaxShow';
  self.LblGenMaxShow.Size := new System.Drawing.Size(58, 13);
  self.LblGenMaxShow.TabIndex := 26;
  self.LblGenMaxShow.Text := '&Max. show';
  self.NumGenMaxGenerate.Location := new System.Drawing.Point(97, 21);
  self.NumGenMaxGenerate.Maximum := new System.Decimal(array of System.Int32([10000, 0, 0, 0]));
  self.NumGenMaxGenerate.Minimum := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.NumGenMaxGenerate.Name := 'NumGenMaxGenerate';
  self.NumGenMaxGenerate.Size := new System.Drawing.Size(68, 20);
  self.NumGenMaxGenerate.TabIndex := 25;
  self.NumGenMaxGenerate.TextAlign := System.Windows.Forms.HorizontalAlignment.Right;
  self.NumGenMaxGenerate.Value := new System.Decimal(array of System.Int32([10, 0, 0, 0]));
  self.NumGenMaxGenerate.ValueChanged += new System.EventHandler(self.NumGenMaxGenerate_ValueChanged);
  self.LblGenMaxGenerate.AutoSize := true;
  self.LblGenMaxGenerate.Location := new System.Drawing.Point(9, 25);
  self.LblGenMaxGenerate.Name := 'LblGenMaxGenerate';
  self.LblGenMaxGenerate.Size := new System.Drawing.Size(75, 13);
  self.LblGenMaxGenerate.TabIndex := 24;
  self.LblGenMaxGenerate.Text := '&Max. generate';
  self.GrpGenChanging.Anchor := (System.Windows.Forms.AnchorStyles.Top or System.Windows.Forms.AnchorStyles.Left or System.Windows.Forms.AnchorStyles.Right as System.Windows.Forms.AnchorStyles);
  self.GrpGenChanging.Controls.Add(self.ChkGenUnidirectional);
  self.GrpGenChanging.Controls.Add(self.NumGenMaxSteps);
  self.GrpGenChanging.Controls.Add(self.LblGenMaxSteps);
  self.GrpGenChanging.Location := new System.Drawing.Point(3, 6);
  self.GrpGenChanging.Name := 'GrpGenChanging';
  self.GrpGenChanging.Size := new System.Drawing.Size(518, 48);
  self.GrpGenChanging.TabIndex := 40;
  self.GrpGenChanging.TabStop := false;
  self.GrpGenChanging.Text := 'Changing attribute values';
  self.ChkGenUnidirectional.AutoSize := true;
  self.ChkGenUnidirectional.Location := new System.Drawing.Point(187, 23);
  self.ChkGenUnidirectional.Name := 'ChkGenUnidirectional';
  self.ChkGenUnidirectional.Size := new System.Drawing.Size(90, 17);
  self.ChkGenUnidirectional.TabIndex := 26;
  self.ChkGenUnidirectional.Text := '&Unidirectional';
  self.ChkGenUnidirectional.UseVisualStyleBackColor := true;
  self.NumGenMaxSteps.Location := new System.Drawing.Point(97, 21);
  self.NumGenMaxSteps.Maximum := new System.Decimal(array of System.Int32([10, 0, 0, 0]));
  self.NumGenMaxSteps.Minimum := new System.Decimal(array of System.Int32([1, 0, 0, 0]));
  self.NumGenMaxSteps.Name := 'NumGenMaxSteps';
  self.NumGenMaxSteps.Size := new System.Drawing.Size(68, 20);
  self.NumGenMaxSteps.TabIndex := 25;
  self.NumGenMaxSteps.TextAlign := System.Windows.Forms.HorizontalAlignment.Right;
  self.NumGenMaxSteps.Value := new System.Decimal(array of System.Int32([10, 0, 0, 0]));
  self.NumGenMaxSteps.ValueChanged += new System.EventHandler(self.NumGenMaxSteps_ValueChanged);
  self.LblGenMaxSteps.AutoSize := true;
  self.LblGenMaxSteps.Location := new System.Drawing.Point(9, 25);
  self.LblGenMaxSteps.Name := 'LblGenMaxSteps';
  self.LblGenMaxSteps.Size := new System.Drawing.Size(58, 13);
  self.LblGenMaxSteps.TabIndex := 24;
  self.LblGenMaxSteps.Text := '&Max. steps';
  self.PanelGenControl.Controls.Add(self.LblGenExplain);
  self.PanelGenControl.Controls.Add(self.RadGenDegrade);
  self.PanelGenControl.Controls.Add(self.RadGenImprov);
  self.PanelGenControl.Controls.Add(self.LblGenTry);
  self.PanelGenControl.Controls.Add(self.TextGenValue);
  self.PanelGenControl.Controls.Add(self.LblGenValue);
  self.PanelGenControl.Controls.Add(self.EditGenAlternative);
  self.PanelGenControl.Controls.Add(self.EditGoalAttribute);
  self.PanelGenControl.Controls.Add(self.LblGenAlternative);
  self.PanelGenControl.Controls.Add(self.LblGoalAttribute);
  self.PanelGenControl.Dock := System.Windows.Forms.DockStyle.Top;
  self.PanelGenControl.Location := new System.Drawing.Point(3, 3);
  self.PanelGenControl.Name := 'PanelGenControl';
  self.PanelGenControl.Size := new System.Drawing.Size(526, 162);
  self.PanelGenControl.TabIndex := 10;
  self.LblGenExplain.AutoSize := true;
  self.LblGenExplain.Location := new System.Drawing.Point(12, 140);
  self.LblGenExplain.Name := 'LblGenExplain';
  self.LblGenExplain.Size := new System.Drawing.Size(258, 13);
  self.LblGenExplain.TabIndex := 10;
  self.LblGenExplain.Text := 'the current value by modifying the selected attributes:';
  self.RadGenDegrade.AutoSize := true;
  self.RadGenDegrade.Location := new System.Drawing.Point(190, 110);
  self.RadGenDegrade.Name := 'RadGenDegrade';
  self.RadGenDegrade.Size := new System.Drawing.Size(64, 17);
  self.RadGenDegrade.TabIndex := 9;
  self.RadGenDegrade.TabStop := true;
  self.RadGenDegrade.Text := 'de&grade';
  self.RadGenDegrade.UseVisualStyleBackColor := true;
  self.RadGenDegrade.CheckedChanged += new System.EventHandler(self.RadGenDegrade_CheckedChanged);
  self.RadGenImprov.AutoSize := true;
  self.RadGenImprov.Location := new System.Drawing.Point(100, 110);
  self.RadGenImprov.Name := 'RadGenImprov';
  self.RadGenImprov.Size := new System.Drawing.Size(62, 17);
  self.RadGenImprov.TabIndex := 8;
  self.RadGenImprov.TabStop := true;
  self.RadGenImprov.Text := '&improve';
  self.RadGenImprov.UseVisualStyleBackColor := true;
  self.RadGenImprov.CheckedChanged += new System.EventHandler(self.RadGenImprov_CheckedChanged);
  self.LblGenTry.AutoSize := true;
  self.LblGenTry.Location := new System.Drawing.Point(12, 112);
  self.LblGenTry.Name := 'LblGenTry';
  self.LblGenTry.Size := new System.Drawing.Size(34, 13);
  self.LblGenTry.TabIndex := 7;
  self.LblGenTry.Text := 'Try to';
  self.TextGenValue.Anchor := (System.Windows.Forms.AnchorStyles.Top or System.Windows.Forms.AnchorStyles.Left or System.Windows.Forms.AnchorStyles.Right as System.Windows.Forms.AnchorStyles);
  self.TextGenValue.BackColor := System.Drawing.Color.White;
  self.TextGenValue.Location := new System.Drawing.Point(100, 75);
  self.TextGenValue.Multiline := false;
  self.TextGenValue.Name := 'TextGenValue';
  self.TextGenValue.ReadOnly := true;
  self.TextGenValue.Size := new System.Drawing.Size(421, 23);
  self.TextGenValue.TabIndex := 6;
  self.TextGenValue.Text := '';
  self.LblGenValue.AutoSize := true;
  self.LblGenValue.Location := new System.Drawing.Point(12, 80);
  self.LblGenValue.Name := 'LblGenValue';
  self.LblGenValue.Size := new System.Drawing.Size(70, 13);
  self.LblGenValue.TabIndex := 5;
  self.LblGenValue.Text := 'Current value';
  self.EditGenAlternative.Anchor := (System.Windows.Forms.AnchorStyles.Top or System.Windows.Forms.AnchorStyles.Left or System.Windows.Forms.AnchorStyles.Right as System.Windows.Forms.AnchorStyles);
  self.EditGenAlternative.DropDownStyle := System.Windows.Forms.ComboBoxStyle.DropDownList;
  self.EditGenAlternative.FormattingEnabled := true;
  self.EditGenAlternative.Location := new System.Drawing.Point(100, 44);
  self.EditGenAlternative.Name := 'EditGenAlternative';
  self.EditGenAlternative.Size := new System.Drawing.Size(421, 21);
  self.EditGenAlternative.TabIndex := 4;
  self.EditGenAlternative.SelectedIndexChanged += new System.EventHandler(self.EditGenAlternative_SelectedIndexChanged);
  self.EditGoalAttribute.Anchor := (System.Windows.Forms.AnchorStyles.Top or System.Windows.Forms.AnchorStyles.Left or System.Windows.Forms.AnchorStyles.Right as System.Windows.Forms.AnchorStyles);
  self.EditGoalAttribute.DropDownStyle := System.Windows.Forms.ComboBoxStyle.DropDownList;
  self.EditGoalAttribute.FormattingEnabled := true;
  self.EditGoalAttribute.Location := new System.Drawing.Point(100, 12);
  self.EditGoalAttribute.Name := 'EditGoalAttribute';
  self.EditGoalAttribute.Size := new System.Drawing.Size(421, 21);
  self.EditGoalAttribute.TabIndex := 2;
  self.EditGoalAttribute.SelectedIndexChanged += new System.EventHandler(self.EditGoalAttribute_SelectedIndexChanged);
  self.LblGenAlternative.AutoSize := true;
  self.LblGenAlternative.Location := new System.Drawing.Point(12, 48);
  self.LblGenAlternative.Name := 'LblGenAlternative';
  self.LblGenAlternative.Size := new System.Drawing.Size(57, 13);
  self.LblGenAlternative.TabIndex := 3;
  self.LblGenAlternative.Text := '&Alternative';
  self.LblGoalAttribute.AutoSize := true;
  self.LblGoalAttribute.Location := new System.Drawing.Point(12, 16);
  self.LblGoalAttribute.Name := 'LblGoalAttribute';
  self.LblGoalAttribute.Size := new System.Drawing.Size(70, 13);
  self.LblGoalAttribute.TabIndex := 1;
  self.LblGoalAttribute.Text := '&Goal attribute';
  self.PageAttributes.Controls.Add(self.AttList);
  self.PageAttributes.Controls.Add(self.PanelAttCtrl);
  self.PageAttributes.Location := new System.Drawing.Point(4, 22);
  self.PageAttributes.Name := 'PageAttributes';
  self.PageAttributes.Padding := new System.Windows.Forms.Padding(3);
  self.PageAttributes.Size := new System.Drawing.Size(532, 697);
  self.PageAttributes.TabIndex := 4;
  self.PageAttributes.Text := 'Attributes';
  self.PageAttributes.UseVisualStyleBackColor := true;
  self.AttList.AllColumns.Add(self.ColAttribute);
  self.AttList.CellEditUseWholeCell := false;
  self.AttList.CheckBoxes := true;
  self.AttList.Columns.AddRange(array of System.Windows.Forms.ColumnHeader([self.ColAttribute]));
  self.AttList.Dock := System.Windows.Forms.DockStyle.Fill;
  self.AttList.HeaderStyle := System.Windows.Forms.ColumnHeaderStyle.None;
  self.AttList.HideSelection := false;
  self.AttList.Location := new System.Drawing.Point(3, 51);
  self.AttList.MultiSelect := false;
  self.AttList.Name := 'AttList';
  self.AttList.ShowGroups := false;
  self.AttList.ShowImagesOnSubItems := true;
  self.AttList.ShowItemToolTips := true;
  self.AttList.Size := new System.Drawing.Size(526, 643);
  self.AttList.TabIndex := 10;
  self.AttList.UseCompatibleStateImageBehavior := false;
  self.AttList.View := System.Windows.Forms.View.Details;
  self.AttList.VirtualMode := true;
  self.AttList.CellToolTipShowing += new System.EventHandler<BrightIdeasSoftware.ToolTipShowingEventArgs>(self.AttList_CellToolTipShowing);
  self.AttList.ItemChecked += new System.Windows.Forms.ItemCheckedEventHandler(self.AttList_ItemChecked);
  self.ColAttribute.AspectName := 'Name';
  self.ColAttribute.FillsFreeSpace := true;
  self.ColAttribute.Groupable := false;
  self.ColAttribute.Hideable := false;
  self.ColAttribute.IsEditable := false;
  self.ColAttribute.Searchable := false;
  self.ColAttribute.Sortable := false;
  self.ColAttribute.UseFiltering := false;
  self.PanelAttCtrl.Controls.Add(self.BtnUncheckAllAtt);
  self.PanelAttCtrl.Controls.Add(self.BtnCheckAllAtt);
  self.PanelAttCtrl.Controls.Add(self.ChkSelectAllAtt);
  self.PanelAttCtrl.Dock := System.Windows.Forms.DockStyle.Top;
  self.PanelAttCtrl.Location := new System.Drawing.Point(3, 3);
  self.PanelAttCtrl.Name := 'PanelAttCtrl';
  self.PanelAttCtrl.Size := new System.Drawing.Size(526, 48);
  self.PanelAttCtrl.TabIndex := 1;
  self.BtnUncheckAllAtt.Location := new System.Drawing.Point(256, 13);
  self.BtnUncheckAllAtt.Name := 'BtnUncheckAllAtt';
  self.BtnUncheckAllAtt.Size := new System.Drawing.Size(82, 23);
  self.BtnUncheckAllAtt.TabIndex := 2;
  self.BtnUncheckAllAtt.Text := 'Uncheck all';
  self.BtnUncheckAllAtt.UseVisualStyleBackColor := true;
  self.BtnUncheckAllAtt.Click += new System.EventHandler(self.BtnUncheckAllAtt_Click);
  self.BtnCheckAllAtt.Location := new System.Drawing.Point(156, 13);
  self.BtnCheckAllAtt.Name := 'BtnCheckAllAtt';
  self.BtnCheckAllAtt.Size := new System.Drawing.Size(82, 23);
  self.BtnCheckAllAtt.TabIndex := 1;
  self.BtnCheckAllAtt.Text := 'Check all';
  self.BtnCheckAllAtt.UseVisualStyleBackColor := true;
  self.BtnCheckAllAtt.Click += new System.EventHandler(self.BtnCheckAllAtt_Click);
  self.ChkSelectAllAtt.AutoSize := true;
  self.ChkSelectAllAtt.Location := new System.Drawing.Point(12, 16);
  self.ChkSelectAllAtt.Name := 'ChkSelectAllAtt';
  self.ChkSelectAllAtt.Size := new System.Drawing.Size(115, 17);
  self.ChkSelectAllAtt.TabIndex := 0;
  self.ChkSelectAllAtt.Text := 'Select &all attributes';
  self.ChkSelectAllAtt.UseVisualStyleBackColor := true;
  self.ChkSelectAllAtt.CheckedChanged += new System.EventHandler(self.ChkSelectAllAtt_CheckedChanged);
  self.PageAlternatives.Controls.Add(self.AltList);
  self.PageAlternatives.Controls.Add(self.PanelAltCtrl);
  self.PageAlternatives.Location := new System.Drawing.Point(4, 22);
  self.PageAlternatives.Name := 'PageAlternatives';
  self.PageAlternatives.Padding := new System.Windows.Forms.Padding(3);
  self.PageAlternatives.Size := new System.Drawing.Size(532, 697);
  self.PageAlternatives.TabIndex := 2;
  self.PageAlternatives.Text := 'Alternatives';
  self.PageAlternatives.UseVisualStyleBackColor := true;
  self.AltList.AllColumns.Add(self.ColAlternative);
  self.AltList.CellEditUseWholeCell := false;
  self.AltList.CheckBoxes := true;
  self.AltList.Columns.AddRange(array of System.Windows.Forms.ColumnHeader([self.ColAlternative]));
  self.AltList.Cursor := System.Windows.Forms.Cursors.Default;
  self.AltList.Dock := System.Windows.Forms.DockStyle.Fill;
  self.AltList.FullRowSelect := true;
  self.AltList.HeaderStyle := System.Windows.Forms.ColumnHeaderStyle.None;
  self.AltList.HideSelection := false;
  self.AltList.Location := new System.Drawing.Point(3, 51);
  self.AltList.Name := 'AltList';
  self.AltList.ShowGroups := false;
  self.AltList.ShowItemToolTips := true;
  self.AltList.Size := new System.Drawing.Size(526, 643);
  self.AltList.TabIndex := 10;
  self.AltList.UseCompatibleStateImageBehavior := false;
  self.AltList.View := System.Windows.Forms.View.Details;
  self.AltList.CellToolTipShowing += new System.EventHandler<BrightIdeasSoftware.ToolTipShowingEventArgs>(self.AltList_CellToolTipShowing);
  self.AltList.ItemChecked += new System.Windows.Forms.ItemCheckedEventHandler(self.AltList_ItemChecked);
  self.ColAlternative.AspectName := 'Name';
  self.ColAlternative.CellEditUseWholeCell := true;
  self.ColAlternative.MaximumWidth := 100;
  self.ColAlternative.ToolTipText := 'Description';
  self.PanelAltCtrl.Controls.Add(self.BtnUncheckAllAlt);
  self.PanelAltCtrl.Controls.Add(self.BtnCheckAllAlt);
  self.PanelAltCtrl.Controls.Add(self.ChkSelectAllAlt);
  self.PanelAltCtrl.Dock := System.Windows.Forms.DockStyle.Top;
  self.PanelAltCtrl.Location := new System.Drawing.Point(3, 3);
  self.PanelAltCtrl.Name := 'PanelAltCtrl';
  self.PanelAltCtrl.Size := new System.Drawing.Size(526, 48);
  self.PanelAltCtrl.TabIndex := 1;
  self.BtnUncheckAllAlt.Location := new System.Drawing.Point(256, 13);
  self.BtnUncheckAllAlt.Name := 'BtnUncheckAllAlt';
  self.BtnUncheckAllAlt.Size := new System.Drawing.Size(82, 23);
  self.BtnUncheckAllAlt.TabIndex := 2;
  self.BtnUncheckAllAlt.Text := 'Uncheck all';
  self.BtnUncheckAllAlt.UseVisualStyleBackColor := true;
  self.BtnUncheckAllAlt.Click += new System.EventHandler(self.BtnUncheckAllAlt_Click);
  self.BtnCheckAllAlt.Location := new System.Drawing.Point(156, 13);
  self.BtnCheckAllAlt.Name := 'BtnCheckAllAlt';
  self.BtnCheckAllAlt.Size := new System.Drawing.Size(82, 23);
  self.BtnCheckAllAlt.TabIndex := 1;
  self.BtnCheckAllAlt.Text := 'Check all';
  self.BtnCheckAllAlt.UseVisualStyleBackColor := true;
  self.BtnCheckAllAlt.Click += new System.EventHandler(self.BtnCheckAllAlt_Click);
  self.ChkSelectAllAlt.AutoSize := true;
  self.ChkSelectAllAlt.Location := new System.Drawing.Point(12, 16);
  self.ChkSelectAllAlt.Name := 'ChkSelectAllAlt';
  self.ChkSelectAllAlt.Size := new System.Drawing.Size(126, 17);
  self.ChkSelectAllAlt.TabIndex := 0;
  self.ChkSelectAllAlt.Text := 'Select &all alternatives';
  self.ChkSelectAllAlt.UseVisualStyleBackColor := true;
  self.ChkSelectAllAlt.CheckedChanged += new System.EventHandler(self.ChkSelectAllAlt_CheckedChanged);
  self.PageFormat.Controls.Add(self.CtrlFormat);
  self.PageFormat.Location := new System.Drawing.Point(4, 22);
  self.PageFormat.Name := 'PageFormat';
  self.PageFormat.Padding := new System.Windows.Forms.Padding(3);
  self.PageFormat.Size := new System.Drawing.Size(532, 697);
  self.PageFormat.TabIndex := 1;
  self.PageFormat.Text := 'Format';
  self.PageFormat.UseVisualStyleBackColor := true;
  self.CtrlFormat.CanEditTitle := true;
  self.CtrlFormat.Dock := System.Windows.Forms.DockStyle.Fill;
  self.CtrlFormat.Location := new System.Drawing.Point(3, 3);
  self.CtrlFormat.Name := 'CtrlFormat';
  self.CtrlFormat.Size := new System.Drawing.Size(526, 691);
  self.CtrlFormat.TabIndex := 0;
  self.PanelCtrl.Controls.Add(self.BtnCancel);
  self.PanelCtrl.Controls.Add(self.BtnOK);
  self.PanelCtrl.Dock := System.Windows.Forms.DockStyle.Bottom;
  self.PanelCtrl.Location := new System.Drawing.Point(0, 501);
  self.PanelCtrl.Name := 'PanelCtrl';
  self.PanelCtrl.Size := new System.Drawing.Size(540, 49);
  self.PanelCtrl.TabIndex := 1;
  self.BtnCancel.Anchor := (System.Windows.Forms.AnchorStyles.Bottom or System.Windows.Forms.AnchorStyles.Left as System.Windows.Forms.AnchorStyles);
  self.BtnCancel.CausesValidation := false;
  self.BtnCancel.DialogResult := System.Windows.Forms.DialogResult.Cancel;
  self.BtnCancel.Location := new System.Drawing.Point(101, 14);
  self.BtnCancel.Name := 'BtnCancel';
  self.BtnCancel.Size := new System.Drawing.Size(75, 23);
  self.BtnCancel.TabIndex := 101;
  self.BtnCancel.Text := '&Cancel';
  self.BtnCancel.UseVisualStyleBackColor := true;
  self.BtnOK.Anchor := (System.Windows.Forms.AnchorStyles.Bottom or System.Windows.Forms.AnchorStyles.Left as System.Windows.Forms.AnchorStyles);
  self.BtnOK.DialogResult := System.Windows.Forms.DialogResult.OK;
  self.BtnOK.Location := new System.Drawing.Point(20, 14);
  self.BtnOK.Name := 'BtnOK';
  self.BtnOK.Size := new System.Drawing.Size(75, 23);
  self.BtnOK.TabIndex := 100;
  self.BtnOK.Text := '&OK';
  self.BtnOK.UseVisualStyleBackColor := true;
  self.AutoScaleDimensions := new System.Drawing.SizeF(6.0, 13.0);
  self.AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font;
  self.ClientSize := new System.Drawing.Size(540, 550);
  self.Controls.Add(self.TabsReport);
  self.Controls.Add(self.PanelCtrl);
  self.MinimumSize := new System.Drawing.Size(400, 500);
  self.Name := 'FormReportParameters';
  self.ShowIcon := false;
  self.ShowInTaskbar := false;
  self.StartPosition := System.Windows.Forms.FormStartPosition.CenterParent;
  self.Text := 'Report parameters: {0}';
  self.TabsReport.ResumeLayout(false);
  self.PageParameters.ResumeLayout(false);
  self.PanelMessage.ResumeLayout(false);
  self.PanelMessage.PerformLayout();
  self.PanelCompare.ResumeLayout(false);
  self.CompareGroup.ResumeLayout(false);
  self.CompareGroup.PerformLayout();
  self.PanelPlusMinus.ResumeLayout(false);
  self.GrpPlusMinus.ResumeLayout(false);
  self.GrpPlusMinus.PerformLayout();
  (self.NumPlusSteps as System.ComponentModel.ISupportInitialize).EndInit();
  (self.NumMinusSteps as System.ComponentModel.ISupportInitialize).EndInit();
  self.PanelWeights.ResumeLayout(false);
  self.GrpWeights.ResumeLayout(false);
  self.GrpWeights.PerformLayout();
  self.PanelFunctions.ResumeLayout(false);
  self.GrpFunction.ResumeLayout(false);
  self.GrpFunction.PerformLayout();
  self.PanelEvaluation.ResumeLayout(false);
  self.GrpEval.ResumeLayout(false);
  self.GrpEval.PerformLayout();
  (self.NumColumns as System.ComponentModel.ISupportInitialize).EndInit();
  self.PanelElements.ResumeLayout(false);
  self.GrpElements.ResumeLayout(false);
  self.GrpElements.PerformLayout();
  self.PanelMainAlternative.ResumeLayout(false);
  self.PanelMainAlternative.PerformLayout();
  self.PanelRootAttribute.ResumeLayout(false);
  self.PanelRootAttribute.PerformLayout();
  self.PageGenerator.ResumeLayout(false);
  (self.GenAttList as System.ComponentModel.ISupportInitialize).EndInit();
  self.PanelGenCtrl2.ResumeLayout(false);
  self.GrpGenLimit.ResumeLayout(false);
  self.GrpGenLimit.PerformLayout();
  (self.NumGenMaxShow as System.ComponentModel.ISupportInitialize).EndInit();
  (self.NumGenMaxGenerate as System.ComponentModel.ISupportInitialize).EndInit();
  self.GrpGenChanging.ResumeLayout(false);
  self.GrpGenChanging.PerformLayout();
  (self.NumGenMaxSteps as System.ComponentModel.ISupportInitialize).EndInit();
  self.PanelGenControl.ResumeLayout(false);
  self.PanelGenControl.PerformLayout();
  self.PageAttributes.ResumeLayout(false);
  (self.AttList as System.ComponentModel.ISupportInitialize).EndInit();
  self.PanelAttCtrl.ResumeLayout(false);
  self.PanelAttCtrl.PerformLayout();
  self.PageAlternatives.ResumeLayout(false);
  (self.AltList as System.ComponentModel.ISupportInitialize).EndInit();
  self.PanelAltCtrl.ResumeLayout(false);
  self.PanelAltCtrl.PerformLayout();
  self.PageFormat.ResumeLayout(false);
  self.PanelCtrl.ResumeLayout(false);
  self.ResumeLayout(false);
end;

{$ENDREGION}

end.