namespace DexiWin;

interface

{$HIDE H7}

uses
  System.Drawing,
  System.Collections,
  System.Windows.Forms,
  System.ComponentModel;

type
  FormScaleEditDiscrete = partial class
  {$REGION Windows Form Designer generated fields}
  private
    TablePanel: System.Windows.Forms.Panel;
    ItemPopSetGood: System.Windows.Forms.ToolStripMenuItem;
    ItemPopSetBad: System.Windows.Forms.ToolStripMenuItem;
    ItemPopSetNeutral: System.Windows.Forms.ToolStripMenuItem;
    ItemPopAddValueDown: System.Windows.Forms.ToolStripMenuItem;
    ItemPopAddValueUp: System.Windows.Forms.ToolStripMenuItem;
    ItemPopDeleteValue: System.Windows.Forms.ToolStripMenuItem;
    ItemPopDuplicateValue: System.Windows.Forms.ToolStripMenuItem;
    ItemPopValueDescr: System.Windows.Forms.ToolStripMenuItem;
    ItemPopScaleDescr: System.Windows.Forms.ToolStripMenuItem;
    ValueMenu: System.Windows.Forms.ContextMenuStrip;
    toolStripSeparator11: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator13: System.Windows.Forms.ToolStripSeparator;
    ItemPopMoveUp: System.Windows.Forms.ToolStripMenuItem;
    ItemPopMoveDown: System.Windows.Forms.ToolStripMenuItem;
    toolStripSeparator14: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator15: System.Windows.Forms.ToolStripSeparator;
    ItemToolSetNeutral: System.Windows.Forms.ToolStripButton;
    ColValue: BrightIdeasSoftware.OLVColumn;
    ColDescription: BrightIdeasSoftware.OLVColumn;
    ViewValues: BrightIdeasSoftware.ObjectListView;
    ItemToolOrder: System.Windows.Forms.ToolStripComboBox;
    ItemToolType: System.Windows.Forms.ToolStripComboBox;
    ItemToolSetBad: System.Windows.Forms.ToolStripButton;
    ItemToolSetGood: System.Windows.Forms.ToolStripButton;
    toolStripSeparator1: System.Windows.Forms.ToolStripSeparator;
    ItemToolDeleteValue: System.Windows.Forms.ToolStripButton;
    ItemToolDuplicateValue: System.Windows.Forms.ToolStripButton;
    ItemToolAddValueUp: System.Windows.Forms.ToolStripButton;
    ItemToolAddValueDown: System.Windows.Forms.ToolStripButton;
    ItemToolValueDescr: System.Windows.Forms.ToolStripButton;
    ItemToolScaleDescr: System.Windows.Forms.ToolStripButton;
    ButtonPanel: System.Windows.Forms.Panel;
    FormTool: System.Windows.Forms.ToolStrip;
    toolStripSeparator5: System.Windows.Forms.ToolStripSeparator;
    toolStripSeparator3: System.Windows.Forms.ToolStripSeparator;
    ItemToolMoveDown: System.Windows.Forms.ToolStripButton;
    ItemToolMoveUp: System.Windows.Forms.ToolStripButton;
    toolStripSeparator7: System.Windows.Forms.ToolStripSeparator;
    BtnCancel: System.Windows.Forms.Button;
    BtnOK: System.Windows.Forms.Button;
    var components: System.ComponentModel.Container := nil;
    method InitializeComponent;
  {$ENDREGION}
  end;

implementation

{$REGION Windows Form Designer generated code}
method FormScaleEditDiscrete.InitializeComponent;
begin
  self.components := new System.ComponentModel.Container();
  self.FormTool := new System.Windows.Forms.ToolStrip();
  self.ItemToolScaleDescr := new System.Windows.Forms.ToolStripButton();
  self.ItemToolValueDescr := new System.Windows.Forms.ToolStripButton();
  self.toolStripSeparator5 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemToolOrder := new System.Windows.Forms.ToolStripComboBox();
  self.ItemToolType := new System.Windows.Forms.ToolStripComboBox();
  self.toolStripSeparator1 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemToolAddValueDown := new System.Windows.Forms.ToolStripButton();
  self.ItemToolAddValueUp := new System.Windows.Forms.ToolStripButton();
  self.ItemToolDeleteValue := new System.Windows.Forms.ToolStripButton();
  self.ItemToolDuplicateValue := new System.Windows.Forms.ToolStripButton();
  self.toolStripSeparator3 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemToolMoveDown := new System.Windows.Forms.ToolStripButton();
  self.ItemToolMoveUp := new System.Windows.Forms.ToolStripButton();
  self.toolStripSeparator7 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemToolSetBad := new System.Windows.Forms.ToolStripButton();
  self.ItemToolSetNeutral := new System.Windows.Forms.ToolStripButton();
  self.ItemToolSetGood := new System.Windows.Forms.ToolStripButton();
  self.ValueMenu := new System.Windows.Forms.ContextMenuStrip(self.components);
  self.ItemPopScaleDescr := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopValueDescr := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator11 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopAddValueDown := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopAddValueUp := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopDeleteValue := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopDuplicateValue := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator13 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopMoveUp := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopMoveDown := new System.Windows.Forms.ToolStripMenuItem();
  self.toolStripSeparator14 := new System.Windows.Forms.ToolStripSeparator();
  self.toolStripSeparator15 := new System.Windows.Forms.ToolStripSeparator();
  self.ItemPopSetBad := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopSetNeutral := new System.Windows.Forms.ToolStripMenuItem();
  self.ItemPopSetGood := new System.Windows.Forms.ToolStripMenuItem();
  self.ButtonPanel := new System.Windows.Forms.Panel();
  self.BtnCancel := new System.Windows.Forms.Button();
  self.BtnOK := new System.Windows.Forms.Button();
  self.TablePanel := new System.Windows.Forms.Panel();
  self.ViewValues := new BrightIdeasSoftware.ObjectListView();
  self.ColValue := (new BrightIdeasSoftware.OLVColumn() as BrightIdeasSoftware.OLVColumn);
  self.ColDescription := (new BrightIdeasSoftware.OLVColumn() as BrightIdeasSoftware.OLVColumn);
  self.FormTool.SuspendLayout();
  self.ValueMenu.SuspendLayout();
  self.ButtonPanel.SuspendLayout();
  self.TablePanel.SuspendLayout();
  (self.ViewValues as System.ComponentModel.ISupportInitialize).BeginInit();
  self.SuspendLayout();
  self.FormTool.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemToolScaleDescr, self.ItemToolValueDescr, self.toolStripSeparator5, self.ItemToolOrder, self.ItemToolType, self.toolStripSeparator1, self.ItemToolAddValueDown, self.ItemToolAddValueUp, self.ItemToolDeleteValue, self.ItemToolDuplicateValue, self.toolStripSeparator3, self.ItemToolMoveDown, self.ItemToolMoveUp, self.toolStripSeparator7, self.ItemToolSetBad, self.ItemToolSetNeutral, self.ItemToolSetGood]));
  self.FormTool.Location := new System.Drawing.Point(0, 0);
  self.FormTool.Name := 'FormTool';
  self.FormTool.Size := new System.Drawing.Size(676, 25);
  self.FormTool.TabIndex := 9;
  self.FormTool.Text := 'toolStrip1';
  self.ItemToolScaleDescr.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolScaleDescr.Image := DEXiWin.Properties.Resources.ImgScaleDescr;
  self.ItemToolScaleDescr.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolScaleDescr.Name := 'ItemToolScaleDescr';
  self.ItemToolScaleDescr.Size := new System.Drawing.Size(23, 22);
  self.ItemToolScaleDescr.Text := 'Scale description...';
  self.ItemToolScaleDescr.ToolTipText := 'Edit scale name and description';
  self.ItemToolScaleDescr.Click += new System.EventHandler(self.ItemToolScaleDescr_Click);
  self.ItemToolValueDescr.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolValueDescr.Image := DEXiWin.Properties.Resources.ImgValueDescr;
  self.ItemToolValueDescr.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolValueDescr.Name := 'ItemToolValueDescr';
  self.ItemToolValueDescr.Size := new System.Drawing.Size(23, 22);
  self.ItemToolValueDescr.Text := 'Value description...';
  self.ItemToolValueDescr.ToolTipText := 'Edit value name and description';
  self.ItemToolValueDescr.Click += new System.EventHandler(self.ItemToolValueDescr_Click);
  self.toolStripSeparator5.Name := 'toolStripSeparator5';
  self.toolStripSeparator5.Size := new System.Drawing.Size(6, 25);
  self.ItemToolOrder.DropDownStyle := System.Windows.Forms.ComboBoxStyle.DropDownList;
  self.ItemToolOrder.Items.AddRange(array of System.Object(['ascending', 'descending', 'unordered']));
  self.ItemToolOrder.Name := 'ItemToolOrder';
  self.ItemToolOrder.Size := new System.Drawing.Size(121, 25);
  self.ItemToolOrder.ToolTipText := 'Scale order';
  self.ItemToolOrder.SelectedIndexChanged += new System.EventHandler(self.ItemToolOrder_SelectedIndexChanged);
  self.ItemToolType.DropDownStyle := System.Windows.Forms.ComboBoxStyle.DropDownList;
  self.ItemToolType.Items.AddRange(array of System.Object(['interval', 'categorical']));
  self.ItemToolType.Name := 'ItemToolType';
  self.ItemToolType.Size := new System.Drawing.Size(121, 25);
  self.ItemToolType.ToolTipText := 'Scale type';
  self.ItemToolType.SelectedIndexChanged += new System.EventHandler(self.ItemToolType_SelectedIndexChanged);
  self.toolStripSeparator1.Name := 'toolStripSeparator1';
  self.toolStripSeparator1.Size := new System.Drawing.Size(6, 25);
  self.ItemToolAddValueDown.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolAddValueDown.Image := DEXiWin.Properties.Resources.ImgValueAddDown;
  self.ItemToolAddValueDown.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolAddValueDown.Name := 'ItemToolAddValueDown';
  self.ItemToolAddValueDown.Size := new System.Drawing.Size(23, 22);
  self.ItemToolAddValueDown.Text := 'Add value';
  self.ItemToolAddValueDown.ToolTipText := 'Add or insert value below the current one';
  self.ItemToolAddValueDown.Click += new System.EventHandler(self.ItemToolAddValueDown_Click);
  self.ItemToolAddValueUp.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolAddValueUp.Image := DEXiWin.Properties.Resources.ImgValueAddUp;
  self.ItemToolAddValueUp.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolAddValueUp.Name := 'ItemToolAddValueUp';
  self.ItemToolAddValueUp.Size := new System.Drawing.Size(23, 22);
  self.ItemToolAddValueUp.Text := 'Add value';
  self.ItemToolAddValueUp.ToolTipText := 'Add or insert value above the current one';
  self.ItemToolAddValueUp.Click += new System.EventHandler(self.ItemToolAddValueUp_Click);
  self.ItemToolDeleteValue.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolDeleteValue.Image := DEXiWin.Properties.Resources.ImgValueDelete;
  self.ItemToolDeleteValue.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolDeleteValue.Name := 'ItemToolDeleteValue';
  self.ItemToolDeleteValue.Size := new System.Drawing.Size(23, 22);
  self.ItemToolDeleteValue.Text := 'Delete value';
  self.ItemToolDeleteValue.ToolTipText := 'Delete selected value';
  self.ItemToolDeleteValue.Click += new System.EventHandler(self.ItemToolDeleteValue_Click);
  self.ItemToolDuplicateValue.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolDuplicateValue.Image := DEXiWin.Properties.Resources.ImgValueDuplicate;
  self.ItemToolDuplicateValue.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolDuplicateValue.Name := 'ItemToolDuplicateValue';
  self.ItemToolDuplicateValue.Size := new System.Drawing.Size(23, 22);
  self.ItemToolDuplicateValue.Text := 'Duplicate value';
  self.ItemToolDuplicateValue.ToolTipText := 'Duplicate selected value';
  self.ItemToolDuplicateValue.Click += new System.EventHandler(self.ItemToolDuplicateValue_Click);
  self.toolStripSeparator3.Name := 'toolStripSeparator3';
  self.toolStripSeparator3.Size := new System.Drawing.Size(6, 25);
  self.ItemToolMoveDown.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolMoveDown.Image := DEXiWin.Properties.Resources.ImgMoveDown;
  self.ItemToolMoveDown.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolMoveDown.Name := 'ItemToolMoveDown';
  self.ItemToolMoveDown.Size := new System.Drawing.Size(23, 22);
  self.ItemToolMoveDown.Text := 'Move down';
  self.ItemToolMoveDown.ToolTipText := 'Move value down';
  self.ItemToolMoveDown.Click += new System.EventHandler(self.ItemToolMoveDown_Click);
  self.ItemToolMoveUp.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolMoveUp.Image := DEXiWin.Properties.Resources.ImgMoveUp;
  self.ItemToolMoveUp.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolMoveUp.Name := 'ItemToolMoveUp';
  self.ItemToolMoveUp.Size := new System.Drawing.Size(23, 22);
  self.ItemToolMoveUp.Text := 'Move up';
  self.ItemToolMoveUp.ToolTipText := 'Move value up';
  self.ItemToolMoveUp.Click += new System.EventHandler(self.ItemToolMoveUp_Click);
  self.toolStripSeparator7.Name := 'toolStripSeparator7';
  self.toolStripSeparator7.Size := new System.Drawing.Size(6, 25);
  self.ItemToolSetBad.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolSetBad.Image := DEXiWin.Properties.Resources.ImgValueBad;
  self.ItemToolSetBad.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolSetBad.Name := 'ItemToolSetBad';
  self.ItemToolSetBad.Size := new System.Drawing.Size(23, 22);
  self.ItemToolSetBad.Text := 'Set bad category';
  self.ItemToolSetBad.Click += new System.EventHandler(self.ItemToolSetBad_Click);
  self.ItemToolSetNeutral.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolSetNeutral.Image := DEXiWin.Properties.Resources.ImgValue;
  self.ItemToolSetNeutral.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolSetNeutral.Name := 'ItemToolSetNeutral';
  self.ItemToolSetNeutral.Size := new System.Drawing.Size(23, 22);
  self.ItemToolSetNeutral.Text := 'Set neutral category';
  self.ItemToolSetNeutral.Click += new System.EventHandler(self.ItemToolSetNeutral_Click);
  self.ItemToolSetGood.DisplayStyle := System.Windows.Forms.ToolStripItemDisplayStyle.Image;
  self.ItemToolSetGood.Image := DEXiWin.Properties.Resources.ImgValueGood;
  self.ItemToolSetGood.ImageTransparentColor := System.Drawing.Color.Magenta;
  self.ItemToolSetGood.Name := 'ItemToolSetGood';
  self.ItemToolSetGood.Size := new System.Drawing.Size(23, 22);
  self.ItemToolSetGood.Text := 'Set good category';
  self.ItemToolSetGood.Click += new System.EventHandler(self.ItemToolSetGood_Click);
  self.ValueMenu.Items.AddRange(array of System.Windows.Forms.ToolStripItem([self.ItemPopScaleDescr, self.ItemPopValueDescr, self.toolStripSeparator11, self.ItemPopAddValueDown, self.ItemPopAddValueUp, self.ItemPopDeleteValue, self.ItemPopDuplicateValue, self.toolStripSeparator13, self.ItemPopMoveUp, self.ItemPopMoveDown, self.toolStripSeparator14, self.toolStripSeparator15, self.ItemPopSetBad, self.ItemPopSetNeutral, self.ItemPopSetGood]));
  self.ValueMenu.Name := 'ModelMenu';
  self.ValueMenu.Size := new System.Drawing.Size(226, 270);
  self.ItemPopScaleDescr.Image := DEXiWin.Properties.Resources.ImgScaleDescr;
  self.ItemPopScaleDescr.Name := 'ItemPopScaleDescr';
  self.ItemPopScaleDescr.Size := new System.Drawing.Size(225, 22);
  self.ItemPopScaleDescr.Text := 'Scale description...';
  self.ItemPopScaleDescr.ToolTipText := 'Edit scale name and description';
  self.ItemPopScaleDescr.Click += new System.EventHandler(self.ItemToolScaleDescr_Click);
  self.ItemPopValueDescr.Image := DEXiWin.Properties.Resources.ImgValueDescr;
  self.ItemPopValueDescr.Name := 'ItemPopValueDescr';
  self.ItemPopValueDescr.Size := new System.Drawing.Size(225, 22);
  self.ItemPopValueDescr.Text := 'Value description...';
  self.ItemPopValueDescr.ToolTipText := 'Edit value name and description';
  self.ItemPopValueDescr.Click += new System.EventHandler(self.ItemToolValueDescr_Click);
  self.toolStripSeparator11.Name := 'toolStripSeparator11';
  self.toolStripSeparator11.Size := new System.Drawing.Size(222, 6);
  self.ItemPopAddValueDown.Image := DEXiWin.Properties.Resources.ImgValueAddDown;
  self.ItemPopAddValueDown.Name := 'ItemPopAddValueDown';
  self.ItemPopAddValueDown.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Insert as System.Windows.Forms.Keys);
  self.ItemPopAddValueDown.Size := new System.Drawing.Size(225, 22);
  self.ItemPopAddValueDown.Text := 'Add &value down';
  self.ItemPopAddValueDown.ToolTipText := 'Add or insert value below the current one';
  self.ItemPopAddValueDown.Click += new System.EventHandler(self.ItemToolAddValueDown_Click);
  self.ItemPopAddValueUp.Image := DEXiWin.Properties.Resources.ImgValueAddUp;
  self.ItemPopAddValueUp.Name := 'ItemPopAddValueUp';
  self.ItemPopAddValueUp.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Shift or System.Windows.Forms.Keys.Insert as System.Windows.Forms.Keys);
  self.ItemPopAddValueUp.Size := new System.Drawing.Size(225, 22);
  self.ItemPopAddValueUp.Text := 'Add value &up';
  self.ItemPopAddValueUp.ToolTipText := 'Add or insert value above the current one';
  self.ItemPopAddValueUp.Click += new System.EventHandler(self.ItemToolAddValueUp_Click);
  self.ItemPopDeleteValue.Image := DEXiWin.Properties.Resources.ImgValueDelete;
  self.ItemPopDeleteValue.Name := 'ItemPopDeleteValue';
  self.ItemPopDeleteValue.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Delete as System.Windows.Forms.Keys);
  self.ItemPopDeleteValue.Size := new System.Drawing.Size(225, 22);
  self.ItemPopDeleteValue.Text := '&Delete value';
  self.ItemPopDeleteValue.ToolTipText := 'Delete value';
  self.ItemPopDeleteValue.Click += new System.EventHandler(self.ItemToolDeleteValue_Click);
  self.ItemPopDuplicateValue.Image := DEXiWin.Properties.Resources.ImgValueDuplicate;
  self.ItemPopDuplicateValue.Name := 'ItemPopDuplicateValue';
  self.ItemPopDuplicateValue.Size := new System.Drawing.Size(225, 22);
  self.ItemPopDuplicateValue.Text := 'Du&plicate value';
  self.ItemPopDuplicateValue.ToolTipText := 'Duplicate value';
  self.ItemPopDuplicateValue.Click += new System.EventHandler(self.ItemToolDuplicateValue_Click);
  self.toolStripSeparator13.Name := 'toolStripSeparator13';
  self.toolStripSeparator13.Size := new System.Drawing.Size(222, 6);
  self.ItemPopMoveUp.Image := DEXiWin.Properties.Resources.ImgMoveUp;
  self.ItemPopMoveUp.Name := 'ItemPopMoveUp';
  self.ItemPopMoveUp.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Up as System.Windows.Forms.Keys);
  self.ItemPopMoveUp.Size := new System.Drawing.Size(225, 22);
  self.ItemPopMoveUp.Text := 'Move up';
  self.ItemPopMoveUp.ToolTipText := 'Move value up';
  self.ItemPopMoveUp.Click += new System.EventHandler(self.ItemToolMoveUp_Click);
  self.ItemPopMoveDown.Image := DEXiWin.Properties.Resources.ImgMoveDown;
  self.ItemPopMoveDown.Name := 'ItemPopMoveDown';
  self.ItemPopMoveDown.ShortcutKeys := (System.Windows.Forms.Keys.Control or System.Windows.Forms.Keys.Down as System.Windows.Forms.Keys);
  self.ItemPopMoveDown.Size := new System.Drawing.Size(225, 22);
  self.ItemPopMoveDown.Text := 'Move down';
  self.ItemPopMoveDown.ToolTipText := 'Move value down';
  self.ItemPopMoveDown.Click += new System.EventHandler(self.ItemToolMoveDown_Click);
  self.toolStripSeparator14.Name := 'toolStripSeparator14';
  self.toolStripSeparator14.Size := new System.Drawing.Size(222, 6);
  self.toolStripSeparator15.Name := 'toolStripSeparator15';
  self.toolStripSeparator15.Size := new System.Drawing.Size(222, 6);
  self.ItemPopSetBad.Image := DEXiWin.Properties.Resources.ImgValueBad;
  self.ItemPopSetBad.Name := 'ItemPopSetBad';
  self.ItemPopSetBad.Size := new System.Drawing.Size(225, 22);
  self.ItemPopSetBad.Text := 'Set &bad category';
  self.ItemPopSetBad.ToolTipText := 'Set bad category';
  self.ItemPopSetBad.Click += new System.EventHandler(self.ItemToolSetBad_Click);
  self.ItemPopSetNeutral.Image := DEXiWin.Properties.Resources.ImgValue;
  self.ItemPopSetNeutral.Name := 'ItemPopSetNeutral';
  self.ItemPopSetNeutral.Size := new System.Drawing.Size(225, 22);
  self.ItemPopSetNeutral.Text := 'Set &neutral category';
  self.ItemPopSetNeutral.ToolTipText := 'Set neutral category';
  self.ItemPopSetNeutral.Click += new System.EventHandler(self.ItemToolSetNeutral_Click);
  self.ItemPopSetGood.Image := DEXiWin.Properties.Resources.ImgValueGood;
  self.ItemPopSetGood.Name := 'ItemPopSetGood';
  self.ItemPopSetGood.Size := new System.Drawing.Size(225, 22);
  self.ItemPopSetGood.Text := 'Set &good category';
  self.ItemPopSetGood.ToolTipText := 'Set good category';
  self.ItemPopSetGood.Click += new System.EventHandler(self.ItemToolSetGood_Click);
  self.ButtonPanel.Controls.Add(self.BtnCancel);
  self.ButtonPanel.Controls.Add(self.BtnOK);
  self.ButtonPanel.Dock := System.Windows.Forms.DockStyle.Bottom;
  self.ButtonPanel.Location := new System.Drawing.Point(0, 390);
  self.ButtonPanel.Name := 'ButtonPanel';
  self.ButtonPanel.Size := new System.Drawing.Size(676, 49);
  self.ButtonPanel.TabIndex := 12;
  self.BtnCancel.Anchor := (System.Windows.Forms.AnchorStyles.Bottom or System.Windows.Forms.AnchorStyles.Left as System.Windows.Forms.AnchorStyles);
  self.BtnCancel.DialogResult := System.Windows.Forms.DialogResult.Cancel;
  self.BtnCancel.Location := new System.Drawing.Point(94, 14);
  self.BtnCancel.Name := 'BtnCancel';
  self.BtnCancel.Size := new System.Drawing.Size(75, 23);
  self.BtnCancel.TabIndex := 10;
  self.BtnCancel.Text := '&Cancel';
  self.BtnCancel.UseVisualStyleBackColor := true;
  self.BtnOK.Anchor := (System.Windows.Forms.AnchorStyles.Bottom or System.Windows.Forms.AnchorStyles.Left as System.Windows.Forms.AnchorStyles);
  self.BtnOK.DialogResult := System.Windows.Forms.DialogResult.OK;
  self.BtnOK.Location := new System.Drawing.Point(12, 14);
  self.BtnOK.Name := 'BtnOK';
  self.BtnOK.Size := new System.Drawing.Size(75, 23);
  self.BtnOK.TabIndex := 9;
  self.BtnOK.Text := '&OK';
  self.BtnOK.UseVisualStyleBackColor := true;
  self.TablePanel.Controls.Add(self.ViewValues);
  self.TablePanel.Dock := System.Windows.Forms.DockStyle.Fill;
  self.TablePanel.Location := new System.Drawing.Point(0, 25);
  self.TablePanel.Name := 'TablePanel';
  self.TablePanel.Size := new System.Drawing.Size(676, 365);
  self.TablePanel.TabIndex := 13;
  self.ViewValues.AllColumns.Add(self.ColValue);
  self.ViewValues.AllColumns.Add(self.ColDescription);
  self.ViewValues.CellEditUseWholeCell := false;
  self.ViewValues.Columns.AddRange(array of System.Windows.Forms.ColumnHeader([self.ColValue, self.ColDescription]));
  self.ViewValues.ContextMenuStrip := self.ValueMenu;
  self.ViewValues.Cursor := System.Windows.Forms.Cursors.Default;
  self.ViewValues.Dock := System.Windows.Forms.DockStyle.Fill;
  self.ViewValues.HideSelection := false;
  self.ViewValues.Location := new System.Drawing.Point(0, 0);
  self.ViewValues.MultiSelect := false;
  self.ViewValues.Name := 'ViewValues';
  self.ViewValues.SelectAllOnControlA := false;
  self.ViewValues.SelectColumnsMenuStaysOpen := false;
  self.ViewValues.SelectColumnsOnRightClick := false;
  self.ViewValues.SelectColumnsOnRightClickBehaviour := BrightIdeasSoftware.ObjectListView.ColumnSelectBehaviour.None;
  self.ViewValues.Size := new System.Drawing.Size(676, 365);
  self.ViewValues.TabIndex := 12;
  self.ViewValues.UseCellFormatEvents := true;
  self.ViewValues.UseCompatibleStateImageBehavior := false;
  self.ViewValues.View := System.Windows.Forms.View.Details;
  self.ViewValues.FormatCell += new System.EventHandler<BrightIdeasSoftware.FormatCellEventArgs>(self.ViewValues_FormatCell);
  self.ViewValues.SelectionChanged += new System.EventHandler(self.ViewValues_SelectionChanged);
  self.ViewValues.KeyDown += new System.Windows.Forms.KeyEventHandler(self.ViewValues_KeyDown);
  self.ViewValues.MouseClick += new System.Windows.Forms.MouseEventHandler(self.ViewValues_MouseClick);
  self.ViewValues.MouseDoubleClick += new System.Windows.Forms.MouseEventHandler(self.ViewValues_MouseDoubleClick);
  self.ColValue.AspectName := 'Name';
  self.ColValue.Groupable := false;
  self.ColValue.Hideable := false;
  self.ColValue.MinimumWidth := 100;
  self.ColValue.Searchable := false;
  self.ColValue.Sortable := false;
  self.ColValue.Text := 'Value';
  self.ColValue.Width := 200;
  self.ColDescription.AspectName := 'Description';
  self.ColDescription.Groupable := false;
  self.ColDescription.Hideable := false;
  self.ColDescription.MinimumWidth := 100;
  self.ColDescription.Searchable := false;
  self.ColDescription.Sortable := false;
  self.ColDescription.Text := 'Description';
  self.ColDescription.Width := 400;
  self.AutoScaleDimensions := new System.Drawing.SizeF(6.0, 13.0);
  self.AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font;
  self.ClientSize := new System.Drawing.Size(676, 439);
  self.Controls.Add(self.TablePanel);
  self.Controls.Add(self.ButtonPanel);
  self.Controls.Add(self.FormTool);
  self.Name := 'FormScaleEditDiscrete';
  self.ShowIcon := false;
  self.ShowInTaskbar := false;
  self.StartPosition := System.Windows.Forms.FormStartPosition.CenterParent;
  self.Text := 'Edit scale of "{0}"';
  self.FormTool.ResumeLayout(false);
  self.FormTool.PerformLayout();
  self.ValueMenu.ResumeLayout(false);
  self.ButtonPanel.ResumeLayout(false);
  self.TablePanel.ResumeLayout(false);
  (self.ViewValues as System.ComponentModel.ISupportInitialize).EndInit();
  self.ResumeLayout(false);
  self.PerformLayout();
end;

{$ENDREGION}

end.