namespace DexiWin;

interface

{$HIDE H7}

uses
  System.Drawing,
  System.Collections,
  System.Windows.Forms,
  System.ComponentModel;

type
  FormWeights = partial class
  {$REGION Windows Form Designer generated fields}
  private
    BarRendererActual: BrightIdeasSoftware.BarRenderer;
    BarRendererRequired: BrightIdeasSoftware.BarRenderer;
    ColReqChart: BrightIdeasSoftware.OLVColumn;
    ColActChart: BrightIdeasSoftware.OLVColumn;
    ViewWeights: BrightIdeasSoftware.ObjectListView;
    ColAttribute: BrightIdeasSoftware.OLVColumn;
    ColRequired: BrightIdeasSoftware.OLVColumn;
    ColActual: BrightIdeasSoftware.OLVColumn;
    GrpRounding: System.Windows.Forms.GroupBox;
    RBtnUp: System.Windows.Forms.RadioButton;
    RBtnNone: System.Windows.Forms.RadioButton;
    RBtnDown: System.Windows.Forms.RadioButton;
    GrpNormalize: System.Windows.Forms.GroupBox;
    BtnMax100: System.Windows.Forms.Button;
    BtnSum100: System.Windows.Forms.Button;
    BtnApply: System.Windows.Forms.Button;
    BtnCancel: System.Windows.Forms.Button;
    BtnOK: System.Windows.Forms.Button;
    PanelCtrl: System.Windows.Forms.Panel;
    PanelWeights: System.Windows.Forms.Panel;
    var components: System.ComponentModel.Container := nil;
    method InitializeComponent;
  {$ENDREGION}
  end;

implementation

{$REGION Windows Form Designer generated code}
method FormWeights.InitializeComponent;
begin
  self.PanelCtrl := new System.Windows.Forms.Panel();
  self.GrpRounding := new System.Windows.Forms.GroupBox();
  self.RBtnUp := new System.Windows.Forms.RadioButton();
  self.RBtnNone := new System.Windows.Forms.RadioButton();
  self.RBtnDown := new System.Windows.Forms.RadioButton();
  self.GrpNormalize := new System.Windows.Forms.GroupBox();
  self.BtnMax100 := new System.Windows.Forms.Button();
  self.BtnSum100 := new System.Windows.Forms.Button();
  self.BtnApply := new System.Windows.Forms.Button();
  self.BtnCancel := new System.Windows.Forms.Button();
  self.BtnOK := new System.Windows.Forms.Button();
  self.PanelWeights := new System.Windows.Forms.Panel();
  self.ViewWeights := new BrightIdeasSoftware.ObjectListView();
  self.ColAttribute := (new BrightIdeasSoftware.OLVColumn() as BrightIdeasSoftware.OLVColumn);
  self.ColRequired := (new BrightIdeasSoftware.OLVColumn() as BrightIdeasSoftware.OLVColumn);
  self.ColReqChart := (new BrightIdeasSoftware.OLVColumn() as BrightIdeasSoftware.OLVColumn);
  self.BarRendererRequired := new BrightIdeasSoftware.BarRenderer();
  self.ColActual := (new BrightIdeasSoftware.OLVColumn() as BrightIdeasSoftware.OLVColumn);
  self.ColActChart := (new BrightIdeasSoftware.OLVColumn() as BrightIdeasSoftware.OLVColumn);
  self.BarRendererActual := new BrightIdeasSoftware.BarRenderer();
  self.PanelCtrl.SuspendLayout();
  self.GrpRounding.SuspendLayout();
  self.GrpNormalize.SuspendLayout();
  self.PanelWeights.SuspendLayout();
  (self.ViewWeights as System.ComponentModel.ISupportInitialize).BeginInit();
  self.SuspendLayout();
  self.PanelCtrl.Controls.Add(self.GrpRounding);
  self.PanelCtrl.Controls.Add(self.GrpNormalize);
  self.PanelCtrl.Controls.Add(self.BtnApply);
  self.PanelCtrl.Controls.Add(self.BtnCancel);
  self.PanelCtrl.Controls.Add(self.BtnOK);
  self.PanelCtrl.Dock := System.Windows.Forms.DockStyle.Bottom;
  self.PanelCtrl.Location := new System.Drawing.Point(0, 145);
  self.PanelCtrl.Name := 'PanelCtrl';
  self.PanelCtrl.Size := new System.Drawing.Size(566, 108);
  self.PanelCtrl.TabIndex := 0;
  self.GrpRounding.Anchor := (System.Windows.Forms.AnchorStyles.Bottom or System.Windows.Forms.AnchorStyles.Left as System.Windows.Forms.AnchorStyles);
  self.GrpRounding.Controls.Add(self.RBtnUp);
  self.GrpRounding.Controls.Add(self.RBtnNone);
  self.GrpRounding.Controls.Add(self.RBtnDown);
  self.GrpRounding.Location := new System.Drawing.Point(190, 11);
  self.GrpRounding.Name := 'GrpRounding';
  self.GrpRounding.Size := new System.Drawing.Size(157, 56);
  self.GrpRounding.TabIndex := 3;
  self.GrpRounding.TabStop := false;
  self.GrpRounding.Text := 'Rounding';
  self.RBtnUp.AutoSize := true;
  self.RBtnUp.Location := new System.Drawing.Point(107, 22);
  self.RBtnUp.Name := 'RBtnUp';
  self.RBtnUp.Size := new System.Drawing.Size(37, 17);
  self.RBtnUp.TabIndex := 6;
  self.RBtnUp.TabStop := true;
  self.RBtnUp.Text := 'up';
  self.RBtnUp.UseVisualStyleBackColor := true;
  self.RBtnNone.AutoSize := true;
  self.RBtnNone.Location := new System.Drawing.Point(64, 22);
  self.RBtnNone.Name := 'RBtnNone';
  self.RBtnNone.Size := new System.Drawing.Size(37, 17);
  self.RBtnNone.TabIndex := 5;
  self.RBtnNone.TabStop := true;
  self.RBtnNone.Text := 'no';
  self.RBtnNone.UseVisualStyleBackColor := true;
  self.RBtnDown.AutoSize := true;
  self.RBtnDown.Location := new System.Drawing.Point(7, 22);
  self.RBtnDown.Name := 'RBtnDown';
  self.RBtnDown.Size := new System.Drawing.Size(51, 17);
  self.RBtnDown.TabIndex := 4;
  self.RBtnDown.TabStop := true;
  self.RBtnDown.Text := 'down';
  self.RBtnDown.UseVisualStyleBackColor := true;
  self.GrpNormalize.Anchor := (System.Windows.Forms.AnchorStyles.Bottom or System.Windows.Forms.AnchorStyles.Left as System.Windows.Forms.AnchorStyles);
  self.GrpNormalize.Controls.Add(self.BtnMax100);
  self.GrpNormalize.Controls.Add(self.BtnSum100);
  self.GrpNormalize.Location := new System.Drawing.Point(12, 11);
  self.GrpNormalize.Name := 'GrpNormalize';
  self.GrpNormalize.Size := new System.Drawing.Size(172, 56);
  self.GrpNormalize.TabIndex := 1;
  self.GrpNormalize.TabStop := false;
  self.GrpNormalize.Text := 'Normalize';
  self.BtnMax100.Location := new System.Drawing.Point(89, 19);
  self.BtnMax100.Name := 'BtnMax100';
  self.BtnMax100.Size := new System.Drawing.Size(75, 23);
  self.BtnMax100.TabIndex := 2;
  self.BtnMax100.Text := '&Max 100';
  self.BtnMax100.UseVisualStyleBackColor := true;
  self.BtnMax100.Click += new System.EventHandler(self.BtnMax100_Click);
  self.BtnSum100.Location := new System.Drawing.Point(6, 19);
  self.BtnSum100.Name := 'BtnSum100';
  self.BtnSum100.Size := new System.Drawing.Size(75, 23);
  self.BtnSum100.TabIndex := 1;
  self.BtnSum100.Text := '&Sum 100';
  self.BtnSum100.UseVisualStyleBackColor := true;
  self.BtnSum100.Click += new System.EventHandler(self.BtnSum100_Click);
  self.BtnApply.Anchor := (System.Windows.Forms.AnchorStyles.Bottom or System.Windows.Forms.AnchorStyles.Left as System.Windows.Forms.AnchorStyles);
  self.BtnApply.Location := new System.Drawing.Point(101, 73);
  self.BtnApply.Name := 'BtnApply';
  self.BtnApply.Size := new System.Drawing.Size(75, 23);
  self.BtnApply.TabIndex := 8;
  self.BtnApply.Text := '&Apply';
  self.BtnApply.UseVisualStyleBackColor := true;
  self.BtnApply.Click += new System.EventHandler(self.BtnApply_Click);
  self.BtnCancel.Anchor := (System.Windows.Forms.AnchorStyles.Bottom or System.Windows.Forms.AnchorStyles.Left as System.Windows.Forms.AnchorStyles);
  self.BtnCancel.CausesValidation := false;
  self.BtnCancel.DialogResult := System.Windows.Forms.DialogResult.Cancel;
  self.BtnCancel.Location := new System.Drawing.Point(190, 73);
  self.BtnCancel.Name := 'BtnCancel';
  self.BtnCancel.Size := new System.Drawing.Size(75, 23);
  self.BtnCancel.TabIndex := 9;
  self.BtnCancel.Text := '&Cancel';
  self.BtnCancel.UseVisualStyleBackColor := true;
  self.BtnOK.Anchor := (System.Windows.Forms.AnchorStyles.Bottom or System.Windows.Forms.AnchorStyles.Left as System.Windows.Forms.AnchorStyles);
  self.BtnOK.DialogResult := System.Windows.Forms.DialogResult.OK;
  self.BtnOK.Location := new System.Drawing.Point(20, 73);
  self.BtnOK.Name := 'BtnOK';
  self.BtnOK.Size := new System.Drawing.Size(75, 23);
  self.BtnOK.TabIndex := 7;
  self.BtnOK.Text := '&OK';
  self.BtnOK.UseVisualStyleBackColor := true;
  self.BtnOK.Click += new System.EventHandler(self.BtnOK_Click);
  self.PanelWeights.AutoScroll := true;
  self.PanelWeights.Controls.Add(self.ViewWeights);
  self.PanelWeights.Dock := System.Windows.Forms.DockStyle.Fill;
  self.PanelWeights.Location := new System.Drawing.Point(0, 0);
  self.PanelWeights.Name := 'PanelWeights';
  self.PanelWeights.Size := new System.Drawing.Size(566, 145);
  self.PanelWeights.TabIndex := 1;
  self.ViewWeights.AllColumns.Add(self.ColAttribute);
  self.ViewWeights.AllColumns.Add(self.ColRequired);
  self.ViewWeights.AllColumns.Add(self.ColReqChart);
  self.ViewWeights.AllColumns.Add(self.ColActual);
  self.ViewWeights.AllColumns.Add(self.ColActChart);
  self.ViewWeights.AllowColumnReorder := true;
  self.ViewWeights.CellEditActivation := BrightIdeasSoftware.ObjectListView.CellEditActivateMode.DoubleClick;
  self.ViewWeights.CellEditUseWholeCell := false;
  self.ViewWeights.Columns.AddRange(array of System.Windows.Forms.ColumnHeader([self.ColAttribute, self.ColRequired, self.ColReqChart, self.ColActual, self.ColActChart]));
  self.ViewWeights.Cursor := System.Windows.Forms.Cursors.Default;
  self.ViewWeights.Dock := System.Windows.Forms.DockStyle.Fill;
  self.ViewWeights.HideSelection := false;
  self.ViewWeights.IsSearchOnSortColumn := false;
  self.ViewWeights.Location := new System.Drawing.Point(0, 0);
  self.ViewWeights.MultiSelect := false;
  self.ViewWeights.Name := 'ViewWeights';
  self.ViewWeights.Size := new System.Drawing.Size(566, 145);
  self.ViewWeights.TabIndex := 0;
  self.ViewWeights.UseCellFormatEvents := true;
  self.ViewWeights.UseCompatibleStateImageBehavior := false;
  self.ViewWeights.View := System.Windows.Forms.View.Details;
  self.ViewWeights.CellEditFinished += new BrightIdeasSoftware.CellEditEventHandler(self.ViewWeights_CellEditFinished);
  self.ViewWeights.CellEditStarting += new BrightIdeasSoftware.CellEditEventHandler(self.ViewWeights_CellEditStarting);
  self.ViewWeights.FormatCell += new System.EventHandler<BrightIdeasSoftware.FormatCellEventArgs>(self.ViewWeights_FormatCell);
  self.ViewWeights.SelectionChanged += new System.EventHandler(self.ViewWeights_SelectionChanged);
  self.ViewWeights.KeyDown += new System.Windows.Forms.KeyEventHandler(self.ViewWeights_KeyDown);
  self.ViewWeights.MouseClick += new System.Windows.Forms.MouseEventHandler(self.ViewWeights_MouseClick);
  self.ColAttribute.AspectName := 'Name';
  self.ColAttribute.Groupable := false;
  self.ColAttribute.Hideable := false;
  self.ColAttribute.IsEditable := false;
  self.ColAttribute.MinimumWidth := 150;
  self.ColAttribute.Searchable := false;
  self.ColAttribute.Sortable := false;
  self.ColAttribute.Text := 'Attribute';
  self.ColAttribute.UseFiltering := false;
  self.ColAttribute.Width := 150;
  self.ColAttribute.WordWrap := true;
  self.ColRequired.AspectName := 'Required';
  self.ColRequired.Groupable := false;
  self.ColRequired.Hideable := false;
  self.ColRequired.MaximumWidth := 100;
  self.ColRequired.MinimumWidth := 100;
  self.ColRequired.Sortable := false;
  self.ColRequired.Text := 'Required Weight';
  self.ColRequired.TextAlign := System.Windows.Forms.HorizontalAlignment.Right;
  self.ColRequired.UseFiltering := false;
  self.ColRequired.Width := 100;
  self.ColReqChart.AspectName := 'Required';
  self.ColReqChart.Groupable := false;
  self.ColReqChart.IsEditable := false;
  self.ColReqChart.MinimumWidth := 100;
  self.ColReqChart.Renderer := self.BarRendererRequired;
  self.ColReqChart.Searchable := false;
  self.ColReqChart.Sortable := false;
  self.ColReqChart.Text := 'Required';
  self.ColReqChart.UseFiltering := false;
  self.ColReqChart.Width := 100;
  self.BarRendererRequired.GradientEndColor := System.Drawing.Color.Blue;
  self.BarRendererRequired.MaximumWidth := 300;
  self.BarRendererRequired.UseStandardBar := false;
  self.ColActual.AspectName := 'Actual';
  self.ColActual.Groupable := false;
  self.ColActual.Hideable := false;
  self.ColActual.IsEditable := false;
  self.ColActual.MaximumWidth := 100;
  self.ColActual.MinimumWidth := 80;
  self.ColActual.Sortable := false;
  self.ColActual.Text := 'Actual Weight';
  self.ColActual.TextAlign := System.Windows.Forms.HorizontalAlignment.Right;
  self.ColActual.UseFiltering := false;
  self.ColActual.Width := 80;
  self.ColActChart.AspectName := 'Actual';
  self.ColActChart.Groupable := false;
  self.ColActChart.IsEditable := false;
  self.ColActChart.MinimumWidth := 100;
  self.ColActChart.Renderer := self.BarRendererActual;
  self.ColActChart.Sortable := false;
  self.ColActChart.Text := 'Actual';
  self.ColActChart.UseFiltering := false;
  self.ColActChart.Width := 100;
  self.BarRendererActual.FillColor := System.Drawing.Color.Blue;
  self.BarRendererActual.GradientEndColor := System.Drawing.Color.Blue;
  self.BarRendererActual.MaximumWidth := 300;
  self.BarRendererActual.UseStandardBar := false;
  self.AutoScaleDimensions := new System.Drawing.SizeF(6.0, 13.0);
  self.AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font;
  self.ClientSize := new System.Drawing.Size(566, 253);
  self.Controls.Add(self.PanelWeights);
  self.Controls.Add(self.PanelCtrl);
  self.Name := 'FormWeights';
  self.ShowIcon := false;
  self.ShowInTaskbar := false;
  self.Text := 'Weights: {0}';
  self.Shown += new System.EventHandler(self.FormWeights_Shown);
  self.PanelCtrl.ResumeLayout(false);
  self.GrpRounding.ResumeLayout(false);
  self.GrpRounding.PerformLayout();
  self.GrpNormalize.ResumeLayout(false);
  self.PanelWeights.ResumeLayout(false);
  (self.ViewWeights as System.ComponentModel.ISupportInitialize).EndInit();
  self.ResumeLayout(false);
end;
{$ENDREGION}

end.