namespace DexiWin;

interface

{$HIDE H7}

uses
  System.Drawing,
  System.Collections,
  System.Windows.Forms,
  System.ComponentModel;

type
  FormSystem = partial class
  {$REGION Windows Form Designer generated fields}
  private
    BtnShow: System.Windows.Forms.Button;
    PanelExe: System.Windows.Forms.Panel;
    GrpBuildInfo: System.Windows.Forms.GroupBox;
    LblPathValue: System.Windows.Forms.Label;
    LblConfValue: System.Windows.Forms.Label;
    LblBuildValue: System.Windows.Forms.Label;
    LblAppValue: System.Windows.Forms.Label;
    
    LblConfiguration: System.Windows.Forms.Label;
    LblBuild: System.Windows.Forms.Label;
    LblApplication: System.Windows.Forms.Label;
    GrpUndoRedo: System.Windows.Forms.GroupBox;
    LblNumRedo: System.Windows.Forms.Label;
    LblNumUndo: System.Windows.Forms.Label;
    LblRedo: System.Windows.Forms.Label;
    LblUndo: System.Windows.Forms.Label;
    BtnClose: System.Windows.Forms.Button;
    BtnCollect: System.Windows.Forms.Button;
    GrpObjects: System.Windows.Forms.GroupBox;
    LblNumFinalized: System.Windows.Forms.Label;
    LblNumCreated: System.Windows.Forms.Label;
    LblNumActive: System.Windows.Forms.Label;
    LblFinalized: System.Windows.Forms.Label;
    LblCreated: System.Windows.Forms.Label;
    LblActive: System.Windows.Forms.Label;
    var components: System.ComponentModel.Container := nil;
    method InitializeComponent;
  {$ENDREGION}
  end;

implementation

{$REGION Windows Form Designer generated code}
method FormSystem.InitializeComponent;
begin
  self.GrpObjects := new System.Windows.Forms.GroupBox();
  self.BtnShow := new System.Windows.Forms.Button();
  self.BtnCollect := new System.Windows.Forms.Button();
  self.LblNumFinalized := new System.Windows.Forms.Label();
  self.LblNumCreated := new System.Windows.Forms.Label();
  self.LblNumActive := new System.Windows.Forms.Label();
  self.LblFinalized := new System.Windows.Forms.Label();
  self.LblCreated := new System.Windows.Forms.Label();
  self.LblActive := new System.Windows.Forms.Label();
  self.BtnClose := new System.Windows.Forms.Button();
  self.GrpUndoRedo := new System.Windows.Forms.GroupBox();
  self.LblNumRedo := new System.Windows.Forms.Label();
  self.LblNumUndo := new System.Windows.Forms.Label();
  self.LblRedo := new System.Windows.Forms.Label();
  self.LblUndo := new System.Windows.Forms.Label();
  self.GrpBuildInfo := new System.Windows.Forms.GroupBox();
  self.LblConfValue := new System.Windows.Forms.Label();
  self.LblBuildValue := new System.Windows.Forms.Label();
  self.LblAppValue := new System.Windows.Forms.Label();
  self.LblConfiguration := new System.Windows.Forms.Label();
  self.LblBuild := new System.Windows.Forms.Label();
  self.LblApplication := new System.Windows.Forms.Label();
  self.PanelExe := new System.Windows.Forms.Panel();
  self.LblPathValue := new System.Windows.Forms.Label();
  self.GrpObjects.SuspendLayout();
  self.GrpUndoRedo.SuspendLayout();
  self.GrpBuildInfo.SuspendLayout();
  self.PanelExe.SuspendLayout();
  self.SuspendLayout();
  self.GrpObjects.Controls.Add(self.BtnShow);
  self.GrpObjects.Controls.Add(self.BtnCollect);
  self.GrpObjects.Controls.Add(self.LblNumFinalized);
  self.GrpObjects.Controls.Add(self.LblNumCreated);
  self.GrpObjects.Controls.Add(self.LblNumActive);
  self.GrpObjects.Controls.Add(self.LblFinalized);
  self.GrpObjects.Controls.Add(self.LblCreated);
  self.GrpObjects.Controls.Add(self.LblActive);
  self.GrpObjects.Dock := System.Windows.Forms.DockStyle.Top;
  self.GrpObjects.Location := new System.Drawing.Point(0, 27);
  self.GrpObjects.Name := 'GrpObjects';
  self.GrpObjects.Size := new System.Drawing.Size(329, 84);
  self.GrpObjects.TabIndex := 0;
  self.GrpObjects.TabStop := false;
  self.GrpObjects.Text := '&Objects';
  self.BtnShow.Location := new System.Drawing.Point(242, 50);
  self.BtnShow.Name := 'BtnShow';
  self.BtnShow.Size := new System.Drawing.Size(75, 23);
  self.BtnShow.TabIndex := 7;
  self.BtnShow.Text := 'Show active';
  self.BtnShow.UseVisualStyleBackColor := true;
  self.BtnShow.Click += new System.EventHandler(self.BtnShow_Click);
  self.BtnCollect.Location := new System.Drawing.Point(242, 20);
  self.BtnCollect.Name := 'BtnCollect';
  self.BtnCollect.Size := new System.Drawing.Size(75, 23);
  self.BtnCollect.TabIndex := 6;
  self.BtnCollect.Text := 'Collect';
  self.BtnCollect.UseVisualStyleBackColor := true;
  self.BtnCollect.Click += new System.EventHandler(self.BtnCollect_Click);
  self.LblNumFinalized.BackColor := System.Drawing.SystemColors.Control;
  self.LblNumFinalized.Location := new System.Drawing.Point(78, 60);
  self.LblNumFinalized.Name := 'LblNumFinalized';
  self.LblNumFinalized.Size := new System.Drawing.Size(72, 18);
  self.LblNumFinalized.TabIndex := 5;
  self.LblNumFinalized.Text := 'finalized';
  self.LblNumFinalized.TextAlign := System.Drawing.ContentAlignment.TopRight;
  self.LblNumCreated.BackColor := System.Drawing.SystemColors.Control;
  self.LblNumCreated.Location := new System.Drawing.Point(78, 40);
  self.LblNumCreated.Name := 'LblNumCreated';
  self.LblNumCreated.Size := new System.Drawing.Size(72, 20);
  self.LblNumCreated.TabIndex := 4;
  self.LblNumCreated.Text := 'created';
  self.LblNumCreated.TextAlign := System.Drawing.ContentAlignment.TopRight;
  self.LblNumActive.BackColor := System.Drawing.SystemColors.Control;
  self.LblNumActive.Location := new System.Drawing.Point(78, 20);
  self.LblNumActive.Name := 'LblNumActive';
  self.LblNumActive.Size := new System.Drawing.Size(72, 20);
  self.LblNumActive.TabIndex := 3;
  self.LblNumActive.Text := 'active';
  self.LblNumActive.TextAlign := System.Drawing.ContentAlignment.TopRight;
  self.LblFinalized.AutoSize := true;
  self.LblFinalized.Location := new System.Drawing.Point(13, 60);
  self.LblFinalized.Name := 'LblFinalized';
  self.LblFinalized.Size := new System.Drawing.Size(51, 13);
  self.LblFinalized.TabIndex := 2;
  self.LblFinalized.Text := 'Finalized:';
  self.LblCreated.AutoSize := true;
  self.LblCreated.Location := new System.Drawing.Point(13, 40);
  self.LblCreated.Name := 'LblCreated';
  self.LblCreated.Size := new System.Drawing.Size(47, 13);
  self.LblCreated.TabIndex := 1;
  self.LblCreated.Text := 'Created:';
  self.LblActive.AutoSize := true;
  self.LblActive.Location := new System.Drawing.Point(13, 20);
  self.LblActive.Name := 'LblActive';
  self.LblActive.Size := new System.Drawing.Size(40, 13);
  self.LblActive.TabIndex := 0;
  self.LblActive.Text := 'Active:';
  self.BtnClose.Anchor := (System.Windows.Forms.AnchorStyles.Bottom or System.Windows.Forms.AnchorStyles.Left as System.Windows.Forms.AnchorStyles);
  self.BtnClose.DialogResult := System.Windows.Forms.DialogResult.OK;
  self.BtnClose.Location := new System.Drawing.Point(13, 266);
  self.BtnClose.Name := 'BtnClose';
  self.BtnClose.Size := new System.Drawing.Size(75, 23);
  self.BtnClose.TabIndex := 1;
  self.BtnClose.Text := 'Close';
  self.BtnClose.UseVisualStyleBackColor := true;
  self.GrpUndoRedo.Controls.Add(self.LblNumRedo);
  self.GrpUndoRedo.Controls.Add(self.LblNumUndo);
  self.GrpUndoRedo.Controls.Add(self.LblRedo);
  self.GrpUndoRedo.Controls.Add(self.LblUndo);
  self.GrpUndoRedo.Dock := System.Windows.Forms.DockStyle.Top;
  self.GrpUndoRedo.Location := new System.Drawing.Point(0, 111);
  self.GrpUndoRedo.Name := 'GrpUndoRedo';
  self.GrpUndoRedo.Size := new System.Drawing.Size(329, 66);
  self.GrpUndoRedo.TabIndex := 2;
  self.GrpUndoRedo.TabStop := false;
  self.GrpUndoRedo.Text := '&UndoRedo';
  self.LblNumRedo.BackColor := System.Drawing.SystemColors.Control;
  self.LblNumRedo.Location := new System.Drawing.Point(78, 40);
  self.LblNumRedo.Name := 'LblNumRedo';
  self.LblNumRedo.Size := new System.Drawing.Size(72, 20);
  self.LblNumRedo.TabIndex := 8;
  self.LblNumRedo.Text := 'redo';
  self.LblNumRedo.TextAlign := System.Drawing.ContentAlignment.TopRight;
  self.LblNumUndo.BackColor := System.Drawing.SystemColors.Control;
  self.LblNumUndo.Location := new System.Drawing.Point(78, 20);
  self.LblNumUndo.Name := 'LblNumUndo';
  self.LblNumUndo.Size := new System.Drawing.Size(72, 20);
  self.LblNumUndo.TabIndex := 7;
  self.LblNumUndo.Text := 'undo';
  self.LblNumUndo.TextAlign := System.Drawing.ContentAlignment.TopRight;
  self.LblRedo.AutoSize := true;
  self.LblRedo.Location := new System.Drawing.Point(13, 40);
  self.LblRedo.Name := 'LblRedo';
  self.LblRedo.Size := new System.Drawing.Size(65, 13);
  self.LblRedo.TabIndex := 6;
  self.LblRedo.Text := 'Redo stack:';
  self.LblUndo.AutoSize := true;
  self.LblUndo.Location := new System.Drawing.Point(13, 20);
  self.LblUndo.Name := 'LblUndo';
  self.LblUndo.Size := new System.Drawing.Size(65, 13);
  self.LblUndo.TabIndex := 5;
  self.LblUndo.Text := 'Undo stack:';
  self.GrpBuildInfo.Controls.Add(self.LblConfValue);
  self.GrpBuildInfo.Controls.Add(self.LblBuildValue);
  self.GrpBuildInfo.Controls.Add(self.LblAppValue);
  self.GrpBuildInfo.Controls.Add(self.LblConfiguration);
  self.GrpBuildInfo.Controls.Add(self.LblBuild);
  self.GrpBuildInfo.Controls.Add(self.LblApplication);
  self.GrpBuildInfo.Dock := System.Windows.Forms.DockStyle.Top;
  self.GrpBuildInfo.Location := new System.Drawing.Point(0, 177);
  self.GrpBuildInfo.Name := 'GrpBuildInfo';
  self.GrpBuildInfo.Size := new System.Drawing.Size(329, 83);
  self.GrpBuildInfo.TabIndex := 4;
  self.GrpBuildInfo.TabStop := false;
  self.GrpBuildInfo.Text := 'Build info';
  self.LblConfValue.BackColor := System.Drawing.SystemColors.Control;
  self.LblConfValue.Location := new System.Drawing.Point(88, 60);
  self.LblConfValue.Name := 'LblConfValue';
  self.LblConfValue.Size := new System.Drawing.Size(62, 20);
  self.LblConfValue.TabIndex := 11;
  self.LblConfValue.Text := 'conf';
  self.LblConfValue.TextAlign := System.Drawing.ContentAlignment.TopRight;
  self.LblBuildValue.BackColor := System.Drawing.SystemColors.Control;
  self.LblBuildValue.Location := new System.Drawing.Point(78, 40);
  self.LblBuildValue.Name := 'LblBuildValue';
  self.LblBuildValue.Size := new System.Drawing.Size(72, 20);
  self.LblBuildValue.TabIndex := 10;
  self.LblBuildValue.Text := 'build';
  self.LblBuildValue.TextAlign := System.Drawing.ContentAlignment.TopRight;
  self.LblAppValue.BackColor := System.Drawing.SystemColors.Control;
  self.LblAppValue.Location := new System.Drawing.Point(78, 20);
  self.LblAppValue.Name := 'LblAppValue';
  self.LblAppValue.Size := new System.Drawing.Size(72, 20);
  self.LblAppValue.TabIndex := 9;
  self.LblAppValue.Text := 'app';
  self.LblAppValue.TextAlign := System.Drawing.ContentAlignment.TopRight;
  self.LblConfiguration.AutoSize := true;
  self.LblConfiguration.Location := new System.Drawing.Point(13, 60);
  self.LblConfiguration.Name := 'LblConfiguration';
  self.LblConfiguration.Size := new System.Drawing.Size(72, 13);
  self.LblConfiguration.TabIndex := 2;
  self.LblConfiguration.Text := 'Configuration:';
  self.LblBuild.AutoSize := true;
  self.LblBuild.Location := new System.Drawing.Point(13, 40);
  self.LblBuild.Name := 'LblBuild';
  self.LblBuild.Size := new System.Drawing.Size(70, 13);
  self.LblBuild.TabIndex := 1;
  self.LblBuild.Text := 'Build version:';
  self.LblApplication.AutoSize := true;
  self.LblApplication.Location := new System.Drawing.Point(13, 20);
  self.LblApplication.Name := 'LblApplication';
  self.LblApplication.Size := new System.Drawing.Size(62, 13);
  self.LblApplication.TabIndex := 0;
  self.LblApplication.Text := 'Application:';
  self.PanelExe.BackColor := System.Drawing.SystemColors.AppWorkspace;
  self.PanelExe.Controls.Add(self.LblPathValue);
  self.PanelExe.Dock := System.Windows.Forms.DockStyle.Top;
  self.PanelExe.Location := new System.Drawing.Point(0, 0);
  self.PanelExe.Name := 'PanelExe';
  self.PanelExe.Size := new System.Drawing.Size(329, 27);
  self.PanelExe.TabIndex := 14;
  self.LblPathValue.BackColor := System.Drawing.SystemColors.AppWorkspace;
  self.LblPathValue.Location := new System.Drawing.Point(6, 4);
  self.LblPathValue.Name := 'LblPathValue';
  self.LblPathValue.Size := new System.Drawing.Size(317, 19);
  self.LblPathValue.TabIndex := 14;
  self.LblPathValue.Text := 'path';
  self.LblPathValue.TextAlign := System.Drawing.ContentAlignment.MiddleLeft;
  self.AutoScaleDimensions := new System.Drawing.SizeF(6.0, 13.0);
  self.AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font;
  self.ClientSize := new System.Drawing.Size(329, 301);
  self.Controls.Add(self.GrpBuildInfo);
  self.Controls.Add(self.GrpUndoRedo);
  self.Controls.Add(self.BtnClose);
  self.Controls.Add(self.GrpObjects);
  self.Controls.Add(self.PanelExe);
  self.Name := 'FormSystem';
  self.ShowIcon := false;
  self.ShowInTaskbar := false;
  self.StartPosition := System.Windows.Forms.FormStartPosition.CenterParent;
  self.Text := 'System Status';
  self.Shown += new System.EventHandler(self.FormSystem_Shown);
  self.GrpObjects.ResumeLayout(false);
  self.GrpObjects.PerformLayout();
  self.GrpUndoRedo.ResumeLayout(false);
  self.GrpUndoRedo.PerformLayout();
  self.GrpBuildInfo.ResumeLayout(false);
  self.GrpBuildInfo.PerformLayout();
  self.PanelExe.ResumeLayout(false);
  self.ResumeLayout(false);
end;
{$ENDREGION}

end.