//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}
{$HIDE H11}

namespace DEXiWin.Properties;

uses
    System;
    
type
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [System.CodeDom.Compiler.GeneratedCodeAttribute('System.Resources.Tools.StronglyTypedResourceBuilder', '16.0.0.0')]
    [System.Diagnostics.DebuggerNonUserCodeAttribute]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
    Resources = public class
    private 
    
        class var resourceMan: System.Resources.ResourceManager;
        class var resourceCulture: System.Globalization.CultureInfo;
        
        class method get_ResourceManager: System.Resources.ResourceManager;
        begin
            if System.Object.ReferenceEquals(resourceMan, nil) then begin
                var temp: System.Resources.ResourceManager := new System.Resources.ResourceManager('DEXiWin.Properties.Resources', typeOf(Resources).Assembly);
                resourceMan := temp;
            end;
            exit resourceMan;
        end;
        
        class method get_Culture: System.Globalization.CultureInfo;
        begin
            exit resourceCulture;
        end;
        
        class method set_Culture(value: System.Globalization.CultureInfo);
        begin
            resourceCulture := value;
        end;
        
        class method get_AlgAlign: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('AlgAlign', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_AlgDistribute: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('AlgDistribute', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_AlgQP: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('AlgQP', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_AlgWalker: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('AlgWalker', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_DirBottomUp: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('DirBottomUp', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_DirLeftRight: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('DirLeftRight', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_DirRightLeft: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('DirRightLeft', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_DirTopDown: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('DirTopDown', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgAlternativeAddLeft: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgAlternativeAddLeft', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgAlternativeAddRight: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgAlternativeAddRight', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgAlternativeDelete: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgAlternativeDelete', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgAlternativeDescr: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgAlternativeDescr', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgAlternativeDuplicate: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgAlternativeDuplicate', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgAttributeAddDown: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgAttributeAddDown', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgAttributeAddRight: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgAttributeAddRight', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgAttributeDelete: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgAttributeDelete', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgAttributeDescr: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgAttributeDescr', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgAttributeDuplicate: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgAttributeDuplicate', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgAuto: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgAuto', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgBoundAdd: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgBoundAdd', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgBoundDelete: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgBoundDelete', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgBoundEdit: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgBoundEdit', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgCheck: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgCheck', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgClear: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgClear', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgCompare: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgCompare', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgDexiWin: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgDexiWin', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgEdit: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgEdit', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgEvaluationQQ: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgEvaluationQQ', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgFindNext: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgFindNext', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgFirstChart: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgFirstChart', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgFunction: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgFunction', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgFunction3D: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgFunction3D', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgFunctionDelete: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgFunctionDelete', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgFunctionDescr: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgFunctionDescr', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgGenerate: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgGenerate', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgModel: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgModel', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgModelDescr: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgModelDescr', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgMoveDown: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgMoveDown', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgMoveLeft: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgMoveLeft', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgMoveRight: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgMoveRight', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgMoveUp: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgMoveUp', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgPlusMinus: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgPlusMinus', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgRedo: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgRedo', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgReport: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgReport', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgReportAdd: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgReportAdd', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgReportCopyOrMove: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgReportCopyOrMove', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgReportDelete: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgReportDelete', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgReportDuplicate: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgReportDuplicate', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgRule: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgRule', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgRuleDelete: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgRuleDelete', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgRuleDescr: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgRuleDescr', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgRuleEdit: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgRuleEdit', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgScale: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgScale', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgScaleContinuous: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgScaleContinuous', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgScaleDelete: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgScaleDelete', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgScaleDescr: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgScaleDescr', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgScaleDiscrete: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgScaleDiscrete', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgScaleReverse: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgScaleReverse', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgScaleSelect: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgScaleSelect', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgSearch: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgSearch', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgSelExpl: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgSelExpl', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgSettings: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgSettings', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgSymmetricity: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgSymmetricity', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgTreeCollapseAll: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgTreeCollapseAll', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgTreeCollapseOne: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgTreeCollapseOne', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgTreeExpandAll: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgTreeExpandAll', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgTreeExpandOne: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgTreeExpandOne', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgUndo: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgUndo', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgValue: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgValue', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgValueAddDown: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgValueAddDown', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgValueAddUp: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgValueAddUp', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgValueBad: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgValueBad', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgValueDelete: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgValueDelete', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgValueDescr: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgValueDescr', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgValueDuplicate: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgValueDuplicate', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgValueEdit: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgValueEdit', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgValueEditMulti: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgValueEditMulti', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgValueGood: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgValueGood', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgVertReset: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgVertReset', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_ImgWeights: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('ImgWeights', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_PrevBrowse: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('PrevBrowse', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_PrevCancel: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('PrevCancel', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_PrevCopy: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('PrevCopy', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_PrevCopyBitmap: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('PrevCopyBitmap', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_PrevCopyMetafile: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('PrevCopyMetafile', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_PrevFirst: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('PrevFirst', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_PrevLast: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('PrevLast', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_PrevNext: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('PrevNext', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_PrevPageSetup: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('PrevPageSetup', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_PrevPrev: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('PrevPrev', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_PrevPrint: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('PrevPrint', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_PrevSave: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('PrevSave', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_PrevTwoPages: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('PrevTwoPages', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_PrevWindow: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('PrevWindow', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_PrevZoom: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('PrevZoom', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_PrevZoom100: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('PrevZoom100', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_PrevZoomFullPage: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('PrevZoomFullPage', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_PrevZoomPageWidth: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('PrevZoomPageWidth', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_Separation: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('Separation', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_Stretch: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('Stretch', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
        class method get_TextBorder: System.Drawing.Bitmap;
        begin
            var obj: System.Object := ResourceManager.GetObject('TextBorder', resourceCulture);
            exit (obj as System.Drawing.Bitmap);
        end;
        
    assembly 
    
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute('Microsoft.Performance', 'CA1811:AvoidUncalledPrivateCode')]
        constructor;
        begin
        end;
        
    public 
    
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        class property ResourceManager: System.Resources.ResourceManager read get_ResourceManager;
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        class property Culture: System.Globalization.CultureInfo read get_Culture write set_Culture;
        class property AlgAlign: System.Drawing.Bitmap read get_AlgAlign;
        class property AlgDistribute: System.Drawing.Bitmap read get_AlgDistribute;
        class property AlgQP: System.Drawing.Bitmap read get_AlgQP;
        class property AlgWalker: System.Drawing.Bitmap read get_AlgWalker;
        class property DirBottomUp: System.Drawing.Bitmap read get_DirBottomUp;
        class property DirLeftRight: System.Drawing.Bitmap read get_DirLeftRight;
        class property DirRightLeft: System.Drawing.Bitmap read get_DirRightLeft;
        class property DirTopDown: System.Drawing.Bitmap read get_DirTopDown;
        class property ImgAlternativeAddLeft: System.Drawing.Bitmap read get_ImgAlternativeAddLeft;
        class property ImgAlternativeAddRight: System.Drawing.Bitmap read get_ImgAlternativeAddRight;
        class property ImgAlternativeDelete: System.Drawing.Bitmap read get_ImgAlternativeDelete;
        class property ImgAlternativeDescr: System.Drawing.Bitmap read get_ImgAlternativeDescr;
        class property ImgAlternativeDuplicate: System.Drawing.Bitmap read get_ImgAlternativeDuplicate;
        class property ImgAttributeAddDown: System.Drawing.Bitmap read get_ImgAttributeAddDown;
        class property ImgAttributeAddRight: System.Drawing.Bitmap read get_ImgAttributeAddRight;
        class property ImgAttributeDelete: System.Drawing.Bitmap read get_ImgAttributeDelete;
        class property ImgAttributeDescr: System.Drawing.Bitmap read get_ImgAttributeDescr;
        class property ImgAttributeDuplicate: System.Drawing.Bitmap read get_ImgAttributeDuplicate;
        class property ImgAuto: System.Drawing.Bitmap read get_ImgAuto;
        class property ImgBoundAdd: System.Drawing.Bitmap read get_ImgBoundAdd;
        class property ImgBoundDelete: System.Drawing.Bitmap read get_ImgBoundDelete;
        class property ImgBoundEdit: System.Drawing.Bitmap read get_ImgBoundEdit;
        class property ImgCheck: System.Drawing.Bitmap read get_ImgCheck;
        class property ImgClear: System.Drawing.Bitmap read get_ImgClear;
        class property ImgCompare: System.Drawing.Bitmap read get_ImgCompare;
        class property ImgDexiWin: System.Drawing.Bitmap read get_ImgDexiWin;
        class property ImgEdit: System.Drawing.Bitmap read get_ImgEdit;
        class property ImgEvaluationQQ: System.Drawing.Bitmap read get_ImgEvaluationQQ;
        class property ImgFindNext: System.Drawing.Bitmap read get_ImgFindNext;
        class property ImgFirstChart: System.Drawing.Bitmap read get_ImgFirstChart;
        class property ImgFunction: System.Drawing.Bitmap read get_ImgFunction;
        class property ImgFunction3D: System.Drawing.Bitmap read get_ImgFunction3D;
        class property ImgFunctionDelete: System.Drawing.Bitmap read get_ImgFunctionDelete;
        class property ImgFunctionDescr: System.Drawing.Bitmap read get_ImgFunctionDescr;
        class property ImgGenerate: System.Drawing.Bitmap read get_ImgGenerate;
        class property ImgModel: System.Drawing.Bitmap read get_ImgModel;
        class property ImgModelDescr: System.Drawing.Bitmap read get_ImgModelDescr;
        class property ImgMoveDown: System.Drawing.Bitmap read get_ImgMoveDown;
        class property ImgMoveLeft: System.Drawing.Bitmap read get_ImgMoveLeft;
        class property ImgMoveRight: System.Drawing.Bitmap read get_ImgMoveRight;
        class property ImgMoveUp: System.Drawing.Bitmap read get_ImgMoveUp;
        class property ImgPlusMinus: System.Drawing.Bitmap read get_ImgPlusMinus;
        class property ImgRedo: System.Drawing.Bitmap read get_ImgRedo;
        class property ImgReport: System.Drawing.Bitmap read get_ImgReport;
        class property ImgReportAdd: System.Drawing.Bitmap read get_ImgReportAdd;
        class property ImgReportCopyOrMove: System.Drawing.Bitmap read get_ImgReportCopyOrMove;
        class property ImgReportDelete: System.Drawing.Bitmap read get_ImgReportDelete;
        class property ImgReportDuplicate: System.Drawing.Bitmap read get_ImgReportDuplicate;
        class property ImgRule: System.Drawing.Bitmap read get_ImgRule;
        class property ImgRuleDelete: System.Drawing.Bitmap read get_ImgRuleDelete;
        class property ImgRuleDescr: System.Drawing.Bitmap read get_ImgRuleDescr;
        class property ImgRuleEdit: System.Drawing.Bitmap read get_ImgRuleEdit;
        class property ImgScale: System.Drawing.Bitmap read get_ImgScale;
        class property ImgScaleContinuous: System.Drawing.Bitmap read get_ImgScaleContinuous;
        class property ImgScaleDelete: System.Drawing.Bitmap read get_ImgScaleDelete;
        class property ImgScaleDescr: System.Drawing.Bitmap read get_ImgScaleDescr;
        class property ImgScaleDiscrete: System.Drawing.Bitmap read get_ImgScaleDiscrete;
        class property ImgScaleReverse: System.Drawing.Bitmap read get_ImgScaleReverse;
        class property ImgScaleSelect: System.Drawing.Bitmap read get_ImgScaleSelect;
        class property ImgSearch: System.Drawing.Bitmap read get_ImgSearch;
        class property ImgSelExpl: System.Drawing.Bitmap read get_ImgSelExpl;
        class property ImgSettings: System.Drawing.Bitmap read get_ImgSettings;
        class property ImgSymmetricity: System.Drawing.Bitmap read get_ImgSymmetricity;
        class property ImgTreeCollapseAll: System.Drawing.Bitmap read get_ImgTreeCollapseAll;
        class property ImgTreeCollapseOne: System.Drawing.Bitmap read get_ImgTreeCollapseOne;
        class property ImgTreeExpandAll: System.Drawing.Bitmap read get_ImgTreeExpandAll;
        class property ImgTreeExpandOne: System.Drawing.Bitmap read get_ImgTreeExpandOne;
        class property ImgUndo: System.Drawing.Bitmap read get_ImgUndo;
        class property ImgValue: System.Drawing.Bitmap read get_ImgValue;
        class property ImgValueAddDown: System.Drawing.Bitmap read get_ImgValueAddDown;
        class property ImgValueAddUp: System.Drawing.Bitmap read get_ImgValueAddUp;
        class property ImgValueBad: System.Drawing.Bitmap read get_ImgValueBad;
        class property ImgValueDelete: System.Drawing.Bitmap read get_ImgValueDelete;
        class property ImgValueDescr: System.Drawing.Bitmap read get_ImgValueDescr;
        class property ImgValueDuplicate: System.Drawing.Bitmap read get_ImgValueDuplicate;
        class property ImgValueEdit: System.Drawing.Bitmap read get_ImgValueEdit;
        class property ImgValueEditMulti: System.Drawing.Bitmap read get_ImgValueEditMulti;
        class property ImgValueGood: System.Drawing.Bitmap read get_ImgValueGood;
        class property ImgVertReset: System.Drawing.Bitmap read get_ImgVertReset;
        class property ImgWeights: System.Drawing.Bitmap read get_ImgWeights;
        class property PrevBrowse: System.Drawing.Bitmap read get_PrevBrowse;
        class property PrevCancel: System.Drawing.Bitmap read get_PrevCancel;
        class property PrevCopy: System.Drawing.Bitmap read get_PrevCopy;
        class property PrevCopyBitmap: System.Drawing.Bitmap read get_PrevCopyBitmap;
        class property PrevCopyMetafile: System.Drawing.Bitmap read get_PrevCopyMetafile;
        class property PrevFirst: System.Drawing.Bitmap read get_PrevFirst;
        class property PrevLast: System.Drawing.Bitmap read get_PrevLast;
        class property PrevNext: System.Drawing.Bitmap read get_PrevNext;
        class property PrevPageSetup: System.Drawing.Bitmap read get_PrevPageSetup;
        class property PrevPrev: System.Drawing.Bitmap read get_PrevPrev;
        class property PrevPrint: System.Drawing.Bitmap read get_PrevPrint;
        class property PrevSave: System.Drawing.Bitmap read get_PrevSave;
        class property PrevTwoPages: System.Drawing.Bitmap read get_PrevTwoPages;
        class property PrevWindow: System.Drawing.Bitmap read get_PrevWindow;
        class property PrevZoom: System.Drawing.Bitmap read get_PrevZoom;
        class property PrevZoom100: System.Drawing.Bitmap read get_PrevZoom100;
        class property PrevZoomFullPage: System.Drawing.Bitmap read get_PrevZoomFullPage;
        class property PrevZoomPageWidth: System.Drawing.Bitmap read get_PrevZoomPageWidth;
        class property Separation: System.Drawing.Bitmap read get_Separation;
        class property Stretch: System.Drawing.Bitmap read get_Stretch;
        class property TextBorder: System.Drawing.Bitmap read get_TextBorder;
        
    end;
    
end.
